alchemy-fr/Phraseanet

- lib/Alchemy/Phrasea/SearchEngine/Phrasea/PhraseaEngine.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
mixing doctype, fieldname,... gives 0 results
the built query is invalid, ex.
zzz AND recordtype=image IN Title
also fix pb with combination of status bits gives 0 results
> fix PHRAS-354

- lib/classes/API/V1/adapter.php
> fix #PHRAS-388

- www/skins/admin/template-dialogs.js
> fix #PHRAS-359

- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- www/skins/prod/jquery.main-prod.js
> fix #PHRAS-343

- lib/Alchemy/Phrasea/Controller/Prod/Export.php
- lib/classes/ftpclient.php
- templates/web/common/dialog_export.html.twig
> #PHRAS-223

- lib/Alchemy/Phrasea/Controller/Prod/Upload.php
- templates/web/common/menubar.html.twig
- templates/web/prod/upload/upload-flash.html.twig
- templates/web/prod/upload/upload.html.twig
#time 8h
hide "use flash uploader" with ie >= 10
> #PHRAS-356

- lib/Alchemy/Phrasea/Controller/Prod/Records.php
- lib/classes/record/preview.php
- templates/web/prod/index.html.twig
- www/include/jquery.p4.preview.js
> #PHRAS-382 #time 3h

- lib/Alchemy/Phrasea/Border/Manager.php
- lib/Alchemy/Phrasea/Controller/Api/V1.php
- lib/classes/API/V1/adapter.php
- lib/classes/media/subdef.php
- lib/classes/record/adapter.php
WIP #time 5h
fix "substit" flag in subdef.
new api route /embed/substitute
parms :
- databox_id
- record_id
- name
- /file/
more properties returned by api / object "embed" :
- substituted
- created_on
- updated_on
> #PHRAS-325

- lib/Alchemy/Phrasea/Controller/Prod/Lazaret.php
- templates/web/prod/upload/lazaret.html.twig
> fix #PHRAS-370

- www/skins/prod/jquery.main-prod.js
> fix #PHRAS-343 #time 30m

- templates/web/prod/upload/upload.html.twig
#PHRAS-356 #time 8h
tested with ie9, ie10, ie11, chrome, firefox
> fix #PHRAS-356 time 8h

- templates/web/prod/WorkZone/Macros.html.twig
- templates/web/prod/index.html.twig
- www/skins/prod/000000/prodcolor.css
> Modification general layout

- templates/web/prod/upload/upload-flash.html.twig
hide html5 uploader if browser doest not support
> fix #PHRAS-356 time 2h

- lib/Alchemy/Phrasea/Command/Setup/H264MappingGenerator.php
fix https://github.com/alchemy-fr/Phraseanet/issues/1244
> Fix H264MappingGenerator

- lib/Alchemy/Phrasea/Application/Api.php
- lib/Alchemy/Phrasea/Controller/Api/V1.php
- lib/Alchemy/Phrasea/Core/Provider/JsonSchemaServiceProvider.php
- lib/classes/API/V1/adapter.php
- lib/classes/record/adapter.php
- lib/conf.d/json_schema/story.json
- lib/conf.d/json_schema/story_record.json
- tests/Alchemy/Tests/Phrasea/Application/ApiAbstract.php
- tests/Alchemy/Tests/Phrasea/Border/Checker/Sha256Test.php
> [3.8.7][PHRAS-29] Add creation story api route

- lib/classes/recordutils/image.php
#PHRAS-423 #time 6h
restored transparency in stamp
> Stamp transparency

- templates/web/prod/actions/Tools/index.html.twig
> PHRAS-425 (prod/tools broken)

- grammar/query.pp
- lib/Alchemy/Phrasea/Controller/Prod/Query.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/CollectionExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineResult.php
- templates/web/prod/index.html.twig
- www/skins/prod/jquery.main-prod.js
- Handle collection facet
- Back button on facets
> Facets support

- templates/web/prod/index.html.twig
- templates/web/prod/toolbar.html.twig
- www/skins/prod/jquery.main-prod.js
- Allow to set an empty query as default query in user preferences
- Refactor toolbar template to allow overriding, it is needed for any phraseanet plugins that need to add an action button in the toolbar for example.
> [3.9] Some enhancements

- lib/classes/databox.php
- lib/classes/databox/field.php
- lib/classes/patch/390alpha22a.php
- lib/conf.d/bases_structure.xml
- templates/web/admin/fields/templates.html.twig
- tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php
change field.aggregable from bool to int -> allows to set the number of aggregation values
0 = do not compute aggregation
10, 20, 50, 100 = return N values
-1 = return ALL aggregation values
> setting for the number of aggregated values (per field)

- templates/web/prod/index.html.twig
- templates/web/prod/thesaurus.js.twig
- www/skins/prod/000000/prodcolor.css
- www/skins/prod/jquery.main-prod.js
wip, todo:
- tooltip (title=) on text/buttons ?
- triangle at right side of facet to open/close
- hover color
...
> wip : facettes ui

- lib/Alchemy/Phrasea/SearchEngine/Elastic/StringUtils.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
> Use a single transliterator to do ASCII folding

- bin/console
- composer.json
- composer.lock
- grammar/query.pp
- lib/Alchemy/Phrasea/Command/SearchEngine/Debug/QueryParseCommand.php
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryCompiler.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
INA or OREO words do not work in uppercase since they are matched as
`<keyword:"IN">` `<text:"A">` and not `<text:"INA">`.
This PR fixes that by being explicit about space occurences in grammar.
> Parsing of INA/OREO queries

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Controller/Admin/FeedController.php
- lib/Alchemy/Phrasea/Controller/Admin/RootController.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Feeds.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Publications.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Root.php
- lib/classes/databox.php
> admin publication provider

- grammar/query.pp
IN -> DANS
AND -> ET
OU -> OR
EXCEPT -> SAUF
(and all case variants "and", "And", "aNd", ...)
> Mixed case and French operators

- composer.lock
- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Controller/Admin/SearchEngineController.php
- lib/Alchemy/Phrasea/Controller/Admin/SetupController.php
- lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- lib/Alchemy/Phrasea/Controller/Admin/TaskManagerController.php
- lib/Alchemy/Phrasea/Controller/Controller.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/SearchEngine.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Setup.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Subdefs.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/TaskManager.php
- lib/Alchemy/Phrasea/SearchEngine/AbstractConfigurationPanel.php
- lib/Alchemy/Phrasea/SearchEngine/ConfigurationPanelInterface.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ConfigurationPanel.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/TaskManager/Job/Factory.php
- lib/classes/databox/descriptionStructure.php
- tests/Alchemy/Tests/Phrasea/Controller/Admin/SetupTest.php
> Controller as service

- lib/Alchemy/Phrasea/SearchEngine/Phrasea/PhraseaEngineQueryParser.php
> fix #PHRAS-449 (search diacritics via thesaurus)

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/resources/queries.csv
> Fix strict facets regressions and add tests

- lib/Alchemy/Phrasea/Controller/Api/V1.php
- lib/classes/API/V1/adapter.php
PHRAS-29
- fix : title is written into the first "thumbtitle" field
- enhancement : metadata can be set
- enhancement : check the ContentType is application/json
> api story creation

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Helper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Navigator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/TermVisitor.php
Also fixes candidates collected from all string fields
> [WIP] Thesaurus prefixes in field structure

- templates/web/admin/users.html.twig
refs PHRAS-452
Javascript event listeners were far too ofter created and double at each request.
> Issue creating users. Javascript alert

- www/scripts/models/field.js
#PHRAS-435
#time 6h (si, si, pour 1 ligne...)
> fix admin/field creation

- lib/Alchemy/Phrasea/ControllerProvider/Prod/Query.php
- lib/classes/record/preview.php
- templates/web/prod/preview/result_train.html.twig
fix #PHRAS-492 (décalage train des imagettes en preview)
#time 1d
> Thumb train

- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Controller/Api/V1.php
- lib/classes/API/V1/adapter.php
- lib/conf.d/json_schema/story.json
- lib/conf.d/json_schema/story_cover.json
#time 5h
- add route to change cover of a story
- enhance route to create stories (set cover)
- enhance route to add records to a story (change cover)
- refactor code
todo :
- doc
- better dispatch events (many events for one op)
> #PHRAS-488

- www/skins/prod/jquery.main-prod.js
fix sort popup reset in advanced search
#PHRAS-456
#time 2h
> fix sort popup reset in advanced search

- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/TermIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryCompiler.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Filter.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Helper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Navigator.php
> Thesaurus prefixes in field structure (the return)

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
#PHRAS-325
#time 2h
- fix api subdef substitute
- fix api addrecord/nosubdef
> report api substitute / nosubdef

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/ApiExceptionHandlerSubscriber.php
- lib/classes/record/adapter.php
- lib/conf.d/json_schema/story.json
- lib/conf.d/json_schema/story_cover.json
- tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
> report des routes api/story de 3.8

- templates/web/admin/users.html.twig
- fix : last-model-applied filter is kept while changing page in admin/users
#time 20m
> #PHRAS-527

- lib/Alchemy/Phrasea/TaskManager/Editor/RecordMoverEditor.php
- lib/Alchemy/Phrasea/TaskManager/Job/RecordMoverJob.php
- templates/web/admin/task-manager/task-editor/archive.html.twig
- templates/web/admin/task-manager/task-editor/ftp-pull.html.twig
- templates/web/admin/task-manager/task-editor/ftp.html.twig
- templates/web/admin/task-manager/task-editor/record-mover.html.twig
- templates/web/admin/task-manager/task-editor/subdefs.html.twig
- templates/web/admin/task-manager/task-editor/task.html.twig
- templates/web/admin/task-manager/task-editor/write-metadata.html.twig
> Task record mover #PHRAS-517

- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Application/Api.php
- lib/Alchemy/Phrasea/Controller/Admin/SetupController.php
- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Controller/MediaAccessorController.php
- lib/Alchemy/Phrasea/ControllerProvider/MediaAccessor.php
- lib/Alchemy/Phrasea/Core/Configuration/RegistryManipulator.php
- lib/Alchemy/Phrasea/Core/Version.php
- lib/Alchemy/Phrasea/Form/Configuration/GeneralFormType.php
- lib/Alchemy/Phrasea/Model/Entities/Secret.php
- lib/Alchemy/Phrasea/Model/Provider/DefaultSecretProvider.php
- lib/Alchemy/Phrasea/Model/Provider/SecretProvider.php
- lib/Alchemy/Phrasea/Model/Repositories/SecretRepository.php
- lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20150519173347.php
- lib/classes/base.php
- lib/classes/patch/400alpha2a.php
- resources/vagrant/vms/phraseanet-php55-nginx/puphpet/config.yaml
- templates/web/admin/setup.html.twig
> Add media accesor

- lib/Alchemy/Phrasea/Model/Entities/ElasticsearchRecord.php
- lib/Alchemy/Phrasea/Model/RecordInterface.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
- lib/classes/caption/record.php
- lib/classes/record/adapter.php
- templates/web/common/macros.html.twig
> private fields are not displayed on production

- lib/Alchemy/Phrasea/Controller/Admin/UserController.php
- lib/Alchemy/Phrasea/ControllerProvider/Root/Account.php
- lib/Alchemy/Phrasea/Core/Provider/ORMServiceProvider.php
- lib/Alchemy/Phrasea/Model/Repositories/RegistrationRepository.php
> Prevent updateAccount to generate 400 bad request.

- bin/console
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/Model/RecordInterface.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Structure.php
- tests/Alchemy/Tests/Phrasea/ApplicationTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/StructureTest.php
Much more extensive testing is needed.
ping @bburnichon can you review this?
> Refactor merged field structure

- lib/Alchemy/Phrasea/Core/Provider/TasksServiceProvider.php
- lib/Alchemy/Phrasea/TaskManager/Editor/IndexerEditor.php
- lib/Alchemy/Phrasea/TaskManager/Job/IndexerJob.php
- templates/web/admin/task-manager/task-editor/indexer.html.twig
#time 1h
restore deleted indexer task, see
https://github.com/alchemy-fr/Phraseanet/commit/a0815afcd5974f8bc11cdf39ba7a77ecfebf0e83
> RESTORE-INDEXER-TASK

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
populate : candidates are written under the good field
> PHRAS-462 #time 5 h

- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/Search/QueryContextTest.php
Introduced in 40e2df6c3f8653ff482f3cd8165cfbea9461f7e5.
> Fix IN search regression

- lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Thesaurus.php
- lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Xmlhttp.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/CandidateAccepted.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/ConceptDeleted.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/FieldLinked.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/Imported.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/ItemAdded.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/ItemTrashed.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/SynonymLngChanged.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/SynonymParm.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/SynonymPositionChanged.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/ThesaurusEvent.php
- lib/Alchemy/Phrasea/Core/PhraseaEvents.php
- templates/web/thesaurus/new-term.html.twig
- templates/web/thesaurus/properties.html.twig
- templates/web/thesaurus/thesaurus.html.twig
PHRAS-368
thesaurus modification events
cs
> Phras 368 th reindex evt

- lib/classes/ACL.php
- lib/classes/API/V1/adapter.php
List collection rights in /me
PHRAS-590 #time 2h
> Rebase #1394 onto 3.8

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
populate : records are indexed from newer to older (rid desc)
> PHRAS-582 #time 10 m

- lib/Alchemy/Phrasea/Authentication/Exception/RegistrationException.php
- lib/Alchemy/Phrasea/Authentication/ProvidersCollection.php
- lib/Alchemy/Phrasea/Authentication/RegistrationService.php
- lib/Alchemy/Phrasea/Controller/Api/V1.php
- lib/Alchemy/Phrasea/Controller/Root/Login.php
- lib/Alchemy/Phrasea/Core/Provider/AuthenticationManagerServiceProvider.php
- lib/Doctrine/Repositories/UsrAuthProviderRepository.php
- lib/classes/API/V1/adapter.php
- lib/classes/appbox.php
- lib/classes/databox.php
#1412 needs to be merged before this one.
> PHRAS-594 - Add account create and unlock routes

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineSuggestion.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineSuggestionTest.php
facets returned in API
"suggestions" returned in API (as flat facets)
> PHRAS-442 #time 5h

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
Fixes inconsistent rights returned by API
> PHRAS-571 - Use base ID instead of collection ID

- lib/classes/API/V1/adapter.php
> PHRAS-571 Use base ID instead of collection ID

- grammar/query.pp
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/BaseExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RecordidExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/resources/queries.csv
- added "recordid:xxx"
- added "base:yyy" (makes "Base" facets ok)
to query parser
> PHRAS-482 #time 4h

- lib/Alchemy/Phrasea/Controller/Prod/EditController.php
- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
- lib/Alchemy/Phrasea/ControllerProvider/Prod/Edit.php
- lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Xmlhttp.php
- templates/web/thesaurus/presets.html.twig
- www/skins/prod/jquery.edit.js
- fix: creation of presets
- fix: usage of presets
- fix: deletion of presets
- new: routes for presets
> PHRAS-556 #time 5h

- lib/classes/record/adapter.php
- tests/classes/record/adapterTest.php
Use of old PDO singleton.
Also fixup test suite to check behaviour of set_mime (only setter)
> PHRAS-372 Bad forward port

- lib/Alchemy/Phrasea/Controller/Api/V1.php
- lib/classes/API/V1/adapter.php
- new : api : delete records from story
> #PHRAS-602 #time 3h

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
- lib/classes/record/adapter.php
- tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
new : api to delete records from story
todo: doc
> #PHRAS-602 #time 6h

- lib/Alchemy/Phrasea/Authentication/RegistrationService.php
- lib/Alchemy/Phrasea/Controller/Admin/Users.php
- lib/classes/API/Webhook.php
- lib/classes/eventsmanager/eventAbstract.php
- lib/classes/eventsmanager/notify/feed.php
- lib/classes/task/period/apiwebhooks.php
Enable webhook callbacks for user registration events
> User webhooks

- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/AbstractTermNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/FieldEqualsExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RangeExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TermNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/AggregationHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/LimitedStructure.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Structure.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Concept.php
- lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
- lib/classes/databox.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/RawNodeTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TermNodeTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/Search/AggregationHelperTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/Search/QueryContextTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/LimitedStructureTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/StructureTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/Thesaurus/ConceptTest.php
We only allow querying on private fields where the user has edit right.
> Restrict search on visible private fields

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
fix "use_as_cover" in story api
> #PHRAS-603 #time 6h

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
fix: api quarantine/list now can return up to 1000 items
> #PHRAS-597 #time 15m

- lib/Alchemy/Phrasea/Model/Entities/ElasticsearchRecord.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/CoreHydrator.php
fix default "binary" thumbnails for stories
nb : must re-populate
> #PHRAS-606 #time 4h

- lib/classes/API/V1/adapter.php
api quarantine/list can return up to 1000 items
> #PHRAS-597 #time 5m

- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- templates/web/prod/index.html.twig
fix : advanced search can filter on status bits with same name on multiple databox
> #PHRAS-599 #time 4h

- www/skins/prod/Prod.css
- www/skins/prod/jquery.main-prod.js
> rollback captions tooltip to popover, update caption css

- lib/classes/API/V1/adapter.php
- Adds a collection key to the JSON data array to request specific collections upon account creation
> Create registration requests to collections from API route

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/AndExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/CollectionExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/DatabaseExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/ExceptExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/FieldEqualsExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/NullQueryNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/OrExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/PrefixNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RecordIdentifierExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TermNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php
add 'lenient' to prevent es errors when parsing invalid dates
cs
> #PHRAS-622 #time 3h

- lib/Alchemy/Phrasea/Account/AccountService.php
- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Core/Event/AccountDeletedEvent.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/AccountDeletedEventSubscriber.php
- lib/Alchemy/Phrasea/Core/PhraseaEvents.php
- lib/Alchemy/Phrasea/Core/Provider/AccountServiceProvider.php
- lib/Alchemy/Phrasea/Core/Provider/PhraseaEventServiceProvider.php
- lib/classes/API/OAuth2/Account.php
- lib/classes/API/OAuth2/Application.php
- lib/classes/User/Adapter.php
- lib/classes/task/period/apiwebhooks.php
- Raise account deleted event
- Add is_deleted property on API accounts and applications
> Delete account improvements

- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/LimitedStructure.php
- lib/classes/databox/field.php
- fix: facets number (admin/field) is now used by prod.
- add: query/es : removed useless & pack clauses on status masks -> shortest (fastest ?) query
> #PHRAS-668 #time 1d

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RangeExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
Date validation fixes the root cause of #1463
> Fix date validation, range query & equality operator

- lib/Alchemy/Phrasea/Out/Module/PDF.php
> #PHRAS-568 #time 5m

- composer.lock
> Bump alchemy/rest-bundle to handle FF content-type

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
a record of type "video" can be used (elected) as cover via "create story" api
> PHRAS-608 #time 10m

- lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- templates/web/prod/results/help.html.twig
query errors (bad syntax, bad field, ...) are displayed on the "no result page"
todo : i18n of messages
> PHRAS-672 #time 5h

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
"Foo IN Bar AND Baz" causes AST construction to fail.
> Fix freetext after IN query

- bin/developer
- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Authorization/AuthorizationChecker.php
- lib/Alchemy/Phrasea/Authorization/AuthorizationServiceProvider.php
- lib/Alchemy/Phrasea/Authorization/BaseVoter.php
- lib/Alchemy/Phrasea/Controller/Admin/PluginsController.php
- lib/Alchemy/Phrasea/Controller/BaseController.php
- lib/Alchemy/Phrasea/Controller/Prod/Basket.php
- lib/Alchemy/Phrasea/Controller/Prod/Root.php
- lib/Alchemy/Phrasea/Core/Provider/ORMServiceProvider.php
- lib/Alchemy/Phrasea/Core/Provider/PluginServiceProvider.php
- templates/web/admin/plugins/show.html.twig
- templates/web/prod/WorkZone/Basket.html.twig
- templates/web/prod/index.html.twig
> Add Security Voter

- lib/Alchemy/Phrasea/Controller/Admin/DataboxController.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/BulkOperation.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordQueuer.php
- lib/classes/databox.php
- templates/web/admin/databox/databox.html.twig
- tests/Alchemy/Tests/Phrasea/Controller/Admin/DataboxTest.php
fix : admin/base progress bar (indexation)
fix : reindex button
fix : indexation does not skip records between fetches
> PHRAS-716 #time 3d

- lib/Alchemy/Phrasea/TaskManager/Job/SubdefsJob.php
subdef creation raises the "to index" jeton
> PHRAS-737 #time 10m

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/TermIndexer.php
fix missing argument when indexing with thesaurus
> PHRAS-742 #time 10m

- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php
- lib/Alchemy/Phrasea/Core/Event/Thesaurus/ThesaurusEvents.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/IndexerSubscriber.php
> Handle thesaurus events & update index

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
array_values always returns a 0-indexed array.
fixes PHRAS-746
> array_filter keeps keys. Makes BC break in API.

- lib/classes/API/V1/adapter.php
- tests/classes/api/v1/api_v1_adapterTest.php
Bump API_VERSION to 1.5.0
PHRAS-748
> Bump API_VERSION to 1.5.0

- lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
- tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
Change Api version to 2.0.0
PHRAS-747
> Change Api version to 2.0.0

- lib/Alchemy/Phrasea/Core/Event/AclAccessPeriodChanged.php
- lib/classes/ACL.php
get the user of acl
removed useless code
> #PHRAS-741 #time 10m

- lib/Alchemy/Phrasea/Core/Event/CollectionLabelChanged.php
- lib/Alchemy/Phrasea/Core/Event/CollectionNameChanged.php
- lib/Alchemy/Phrasea/Core/PhraseaEvents.php
- lib/classes/collection.php
> #PHRAS-741 #time 15m

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/Flag.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/FlagStatement.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Exception/StructureException.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/CoreHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/FlagHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Flag.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/LimitedStructure.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Structure.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/FlagStatementTest.php
[PHRAS-731](https://phraseanet.atlassian.net/browse/PHRAS-731)
> Status query matcher and structure refactoring

- lib/Alchemy/Phrasea/TaskManager/Job/SubdefsJob.php
> PHRAS-737 #time 1h

- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
> PHRAS-749 #time 2h

- lib/Alchemy/Phrasea/Core/Provider/FtpServiceProvider.php
- lib/classes/ftpclient.php
- lib/classes/task/period/ftp.php
add proxy user/pwd to ftpclient object
add proxy user/pwd to ftp task interface
> #PHRAS-750 #time 3h

- lib/classes/task/period/ftp.php
> #PHRAS-750 #time 20m

- lib/classes/task/period/ftp.php
> #PHRAS-750 #time 10m

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Filter.php
> PHRAS-715 #time 6h

- lib/Alchemy/Phrasea/Notification/Deliverer.php
- lib/classes/task/period/ftp.php
fix : see http://stackoverflow.com/questions/6549819/symfony-mailer-swift-transportexception-between-message-sending
to be checked by MDiouf
> #PHRAS-760 #time 2h

- lib/Alchemy/Phrasea/Command/Command.php
> #PHRAS-761 #time 2h

- lib/classes/task/period/writemeta.php
fix: task writemeta, mwg checkbox is saved
> #PHRAS-763 #time 30m

- lib/Alchemy/Phrasea/Model/Repositories/UserRepository.php
fix : login and mail is now case insensitive in doctrine "find" methods.
> PHRAS-766 #time 30m

- templates/web/prod/preview/appears_in.html.twig
- www/include/jquery.p4.preview.js
story preview mode, "train" does not "bounce" anymore when selecting a thumbnail
> #PHRAS-344 #time 3h

- templates/web/prod/preview/appears_in.html.twig
- www/include/jquery.p4.preview.js
report de PHRAS-344 (story / preview / train : bounce)
> PHRAS-768 #time 5m

- lib/Alchemy/Phrasea/Notification/Deliverer.php
- tests/Alchemy/Tests/Phrasea/Notification/DelivererTest.php
report de PHRAS-760 (ftp task not ok in CLI)
> PHRAS-772 #time 15m

- lib/Alchemy/Phrasea/Core/Provider/FtpServiceProvider.php
- lib/Alchemy/Phrasea/TaskManager/Editor/FtpEditor.php
- lib/Alchemy/Phrasea/TaskManager/Job/FtpJob.php
- lib/classes/ftpclient.php
- templates/web/admin/task-manager/task-editor/ftp.html.twig
- tests/Alchemy/Tests/Phrasea/TaskManager/Editor/FtpEditorTest.php
report de PHRAS-750 (connect to ftp via a auth proxy)
> PHRAS-771 #time 2h

- lib/classes/caption/Field/Value.php
fix : field content mismatch between databoxes (due to metadata-id collision) is solved
> #PHRAS-794 #time 5m

- lib/classes/caption/Field/Value.php
fix : field content mismatch between databoxes (due to metadata-id collision) is solved
> #PHRAS-793 #time 3h

- templates/web/prod/index.html.twig
> Change Toolbar plugin buttons

- lib/classes/task/period/emptyColl.php
The xml of the task looks like this:
<?xml version="1.0" encoding="UTF-8"?><tasksettings><base_id>7</base_id></tasksettings>
> Changing bas_id with base_id

- lib/Alchemy/Phrasea/Controller/Thesaurus/Thesaurus.php
- templates/web/thesaurus/thesaurus.html.twig
fix : app thesaurus / searching is ok in ie11
> #PHRAS-493 #time 6h

- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php
- lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Thesaurus.php
- templates/web/thesaurus/thesaurus.html.twig
fix: app thesaurus, search is ok in ie11
> #PHRAS-797 time 10m

- lib/Alchemy/Phrasea/Authentication/Phrasea/FailureHandledNativeAuthentication.php
- lib/Alchemy/Phrasea/Authentication/Phrasea/NativeAuthentication.php
- lib/Alchemy/Phrasea/Authentication/Phrasea/PasswordAuthenticationInterface.php
> Remove static methods in interface which prevents extensions.

- lib/Alchemy/Phrasea/Feed/Aggregate.php
- lib/Alchemy/Phrasea/Model/Repositories/FeedRepository.php
> Filter feeds by id and user ACLs

- grammar/query.pp
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/EqualExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/MatchExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/RangeExpression.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/TimestampKey.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/resources/queries.csv
> Handle search with timestamps

- lib/Alchemy/Phrasea/Application/Api.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/ContentNegotiationSubscriber.php
- lib/Alchemy/Phrasea/Core/Provider/PhraseaEventServiceProvider.php
> Properly handle negotiation of custom formats.

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/RangeExpression.php
Post processor hook was not called
> Fix range expression with private fields

- CHANGELOG.md
- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/Alchemy/Phrasea/ControllerProvider/Prod/Tools.php
- lib/Alchemy/Phrasea/TaskManager/Job/EmptyCollectionJob.php
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/prod/Share/record.html.twig
- templates/web/prod/actions/Tools/index.html.twig
- templates/web/prod/toolbar.html.twig
- www/skins/prod/000000/prodcolor.css
- www/skins/prod/959595/prodcolor.css
- www/skins/prod/jquery.main-prod.js
Port of PHRAS-776 into v4
PHRAS-778
> Feature permalink activation/deactivation

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Command/Developer/TranslationDumper.php
- resources/locales/messages.en.xlf
- resources/locales/validators.en.xlf
- templates/web/admin/editusers.html.twig
- templates/web/prod/actions/Bridge/element_list.html.twig
- www/scripts/apps/admin/require.config.js
- www/scripts/apps/login/home/config.js
- www/scripts/common/geonames.js
> Reestablish geoname connection

- Gruntfile.js
- package.json
frontend dependencies update: bump grunt contrib deprecated dependencies
> PHRAS-803 - frontend dependencies update

- lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineResult.php
- resources/locales/messages.en.xlf
- resources/locales/validators.en.xlf
- www/skins/prod/jquery.main-prod.js
> Sort Facets and Give a Name

- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineOptionsTest.php
> Add check on Available collections before performing a search

- lib/Alchemy/Phrasea/Controller/Prod/Tools.php
- lib/classes/databox/subdef.php
> Fix users right before changing permalink attributes

- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/classes/databox/subdef.php
> User rights check before applying WS

- lib/Alchemy/Phrasea/Core/Configuration/RegistryManipulator.php
> Clear default Query

- lib/Alchemy/Phrasea/Command/BuildMissingSubdefs.php
- lib/classes/record/adapter.php
> Fixup build-missing-subdef command.

- resources/locales/messages.en.xlf
- resources/www/common/js/jquery.tooltip.js
- resources/www/prod/skins/ui-components/_buttons.scss
- resources/www/prod/skins/ui-components/_thumb-extractor.scss
- resources/www/prod/skins/ui-components/_upload.scss
- resources/www/vendors/jquery-test-paths/jquery.test-paths.js
- templates/web/admin/databox/databox.html.twig
- templates/web/admin/publications/list.html.twig
- templates/web/admin/subdefs.html.twig
- templates/web/admin/task-manager/task-editor/subdefs.html.twig
- templates/web/common/dialog_export.html.twig
- templates/web/prod/WorkZone/Browser/Browser.html.twig
- templates/web/prod/actions/Bridge/index.html.twig
- templates/web/prod/actions/Tools/confirm.html.twig
- templates/web/prod/actions/Tools/index.html.twig
- templates/web/prod/templates/upload.html.twig
- templates/web/report/listColumn.html.twig
Admin - allow input value change for sliders
fix misc css issues
update remaining jquery checked attr into prop
> PHRAS-450 - fix captured images dimension issue

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Core/Version.php
- lib/Alchemy/Phrasea/Model/Entities/ApiLog.php
- lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php
- lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20151209101524.php
- lib/classes/patch/400alpha4a.php
- tests/Alchemy/Tests/Phrasea/Functional/UserDeletionTest.php
PHRAS-811 Users that already logged via oauth could not be deleted
PHRAS-812 Logins should be available when a login was revoked
> User related bug fixes

- lib/Alchemy/Phrasea/Http/StaticFile/StaticMode.php
- lib/Alchemy/Phrasea/Model/Entities/ElasticsearchRecord.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
- lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
- lib/classes/media/subdef.php
- lib/classes/record/adapter.php
add : es "technical" fields (_index, _type, _version, ...) to es-record
fix: add etag to thumbnail on es answers, based on document _version
clean : obsolete methods calls changed, cs, ...
> #PHRAS-840 time 12h

- composer.lock
- resources/gulp/components/vendors/alchemy-embed.js
drop jQuery dependency in bundle
> Bump Embed Bundle

- lib/Alchemy/Phrasea/Controller/Admin/TaskManagerController.php
- lib/Alchemy/Phrasea/TaskManager/Log/AbstractLogFile.php
- lib/Alchemy/Phrasea/TaskManager/Log/LogFileInterface.php
- lib/Alchemy/Phrasea/TaskManager/Log/ManagerLogFile.php
- lib/Alchemy/Phrasea/TaskManager/Log/TaskLogFile.php
- templates/web/admin/task-manager/log.html.twig
- templates/web/admin/task-manager/log_scheduler.html.twig
- templates/web/admin/task-manager/log_task.html.twig
- tests/Alchemy/Tests/Phrasea/TaskManager/Log/LogFileTestCase.php
display of tasks logs in admin is ok.
if many logs (logrotate) display links
> Phras 846 tasks logs

- lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
> Try clear 'last' query.

- lib/Alchemy/Phrasea/Application/Api.php
> Lower priority of extended formats in API

- composer.json
- composer.lock
> Bump webmozart/json and justinrainbow/json-schema

- lib/Alchemy/Phrasea/Collection/Factory/DbalCollectionRepositoryFactory.php
- lib/Alchemy/Phrasea/Collection/Repository/CachedCollectionRepository.php
- lib/Alchemy/Phrasea/Collection/Repository/DbalCollectionRepository.php
This is mainly to facilitate debugging of registered keys
> Add cache key prefix in cached collection repository

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
> Check type of field before considering it a Date

- lib/classes/collection.php
- lib/classes/phrasea.php
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
> Unknown collection issue

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Application/ApplicationLoader.php
- lib/Alchemy/Phrasea/Application/Environment.php
- lib/Alchemy/Phrasea/Application/Root.php
- lib/Alchemy/Phrasea/Application/RouteLoader.php
- lib/Alchemy/Phrasea/ControllerProvider/ControllerProviderServiceProvider.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/DebuggerSubscriber.php
- lib/Alchemy/Phrasea/Core/Middleware/SetupMiddlewareProvider.php
- tests/Alchemy/Tests/Phrasea/Application/RouteLoaderTest.php
- tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/DebuggerSubscriberTest.php
- www/index.php
- Extract environment properties in Environment class
- Replaces initialization closure by ApplicationLoader class
- Extract classes for controller provider initialization and route loading
- Removes undesirable error handling/PHP settings modifications
> Application bootstrap refactor

- lib/Alchemy/Phrasea/Webhook/EventProcessorFactory.php
- lib/Alchemy/Phrasea/Webhook/Processor/CallableProcessorFactor.php
- lib/Alchemy/Phrasea/Webhook/Processor/FeedEntryProcessorFactory.php
- lib/Alchemy/Phrasea/Webhook/Processor/ProcessorFactory.php
- lib/Alchemy/Phrasea/Webhook/Processor/UserRegistrationProcessorFactory.php
Allows injection of processor factories in the webhook event processor factory
> Refactor event processor factory to make it extensible

- lib/Alchemy/Phrasea/Collection/Reference/ArrayCacheCollectionReferenceRepository.php
fix : "BaseFromColl" (dbox coll_id -> abox base_id) check for sbas_id
> #PHRAS-920 time 1h

- lib/Alchemy/Phrasea/Application/RouteLoader.php
> Fixup wrongly passed definition i/o providerKey

- lib/Alchemy/Phrasea/Controller/Admin/RootController.php
Databox/collection is rendered in controller and in template, which doubles the page load time unnecessarily.
> Deduplicate rendering of databox/collection tree

- lib/Alchemy/Phrasea/Core/Provider/WebhookServiceProvider.php
- lib/Alchemy/Phrasea/Model/Entities/WebhookEvent.php
- lib/Alchemy/Phrasea/TaskManager/Job/WebhookJob.php
Allows registering more event processor factories
> Configure event processor factory via DI

- lib/Alchemy/Phrasea/Command/Developer/IniReset.php
- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Controller/Root/SessionController.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/RegistrationSubscriber.php
- lib/Alchemy/Phrasea/Core/Provider/RepositoriesServiceProvider.php
- lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php
- lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php
- lib/classes/set/export.php
> Remove use of gettext shortcut method.

- lib/Alchemy/Phrasea/Core/Event/Subscriber/TrustedProxySubscriber.php
This should occurs very early in request.
PHRAS-929
> Increase setTrustedProxySubscriber priority.

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Model/Entities/WebhookEvent.php
- Removes restrictions on event types and names
- Registers service provider in application
> Fix bugs in webhook management

- lib/Alchemy/Phrasea/Core/Provider/ConfigurationTesterServiceProvider.php
- lib/Alchemy/Phrasea/Model/Entities/Session.php
- lib/Alchemy/Phrasea/Setup/DoctrineMigrations/SessionMigration.php
- lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20150519173347.php
- lib/Alchemy/Phrasea/Setup/Version/PreSchemaUpgrade/Upgrade39Sessions.php
- lib/Alchemy/Phrasea/Setup/Version/PreSchemaUpgrade/Upgrade39Users.php
- lib/classes/module/console/systemUpgrade.php
> Migration error fixes

- lib/Alchemy/Phrasea/Core/Profiler/TraceableCache.php
Checks whether lastCall is array before comparing it.
> Fixup invalid first compareCall

- lib/Alchemy/Phrasea/Controller/Prod/PropertyController.php
> reset should be called on a variable.

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Application/Api.php
- lib/Alchemy/Phrasea/Controller/Api/Oauth2.php
allow to display auth plugins on "authorize" page
> #PHRAS-944 time 3h

- lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- lib/classes/databox/subdef.php
- lib/classes/databox/subdefsStructure.php
- lib/classes/patch/370alpha6a.php
- lib/classes/record/exportElement.php
- templates/web/admin/subdefs.html.twig
- tests/Alchemy/Tests/Phrasea/Controller/Admin/SubdefsTest.php
- tests/classes/databox/subdefTest.php
> Add orderable flag

- resources/www/prod/js/jquery.Feedback.js
- resources/www/prod/js/jquery.main-prod.js
- resources/www/report/js/report.js
- templates/web/common/index_bootstrap.html.twig
- templates/web/prod/actions/delete_records_confirm.html.twig
> Group some PRs

- .travis.yml
- circle.yml
- resources/www/prod/skins/000000/skin-000000.scss
- resources/www/prod/skins/959595/skin-959595.scss
- resources/www/prod/skins/FFFFFF/skin-FFFFFF.scss
- resources/www/prod/skins/ui-components/_answers.scss
- resources/www/prod/skins/ui-components/_modal-edit.scss
- resources/www/prod/skins/ui-components/_workzone-proposals.scss
- templates/web/prod/actions/Tools/index.html.twig
> CI tweaks & fixes on white skin

- lib/Alchemy/Phrasea/Controller/Admin/UserController.php
> csv import users issue

- lib/Alchemy/Phrasea/Filesystem/FilesystemService.php
- tests/Alchemy/Tests/Phrasea/Filesystem/FilesystemServiceTest.php
Exported filenames have no extension.
PHRAS-967
> document filenames generation bug

- lib/classes/Bridge/Api.php
- tests/classes/Bridge/ApiTest.php
> Bridge_Api class should not depend on SQL time

- lib/Alchemy/Phrasea/Helper/User/Manage.php
Introduced by fad68369cad0adc45beb355cddd453f1b68c6a53 in PR #1690 PHRAS-962
> Twig uses users User_Query instance, not result iterable

- lib/Alchemy/Phrasea/Core/Provider/APIServiceProvider.php
- lib/classes/API/OAuth2/Adapter.php
> broken oauth2 authentication

- lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php
- lib/Alchemy/Phrasea/Notification/Mail/MailInfoNewOrder.php
- lib/Alchemy/Phrasea/Notification/Mail/MailInfoValidationRequest.php
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
> translation keys

- lib/Alchemy/Phrasea/Core/Version.php
- lib/Alchemy/Phrasea/Model/Entities/UserSetting.php
> Unsaved user preferences

- lib/Alchemy/Phrasea/TaskManager/Job/WriteMetadataJob.php
- lib/classes/databox/subdefsStructure.php
- lib/classes/module/console/systemUpgrade.php
> task write metadata

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineResult.php
> api fetch many records per databox at once

- composer.json
- lib/Alchemy/Phrasea/Media/Subdef/Image.php
- lib/classes/databox/subdef.php
- lib/classes/record/adapter.php
#PHRAS-975 time 5h
first commit
allow generation of png and tiff subdefs.
todo :
- add specific settings (transparency, depth, compression, ...) ?
- add tests
**nb** : Need change "ImageCodec" in Media-Alchemyst.
todo : new version for Media-Alchemyst ?
> png subdefs

- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/Alchemy/Phrasea/ControllerProvider/Prod/Tools.php
- lib/Alchemy/Phrasea/Core/Event/Record/RecordEvent.php
- lib/Alchemy/Phrasea/Core/Event/Record/RecordEvents.php
- lib/Alchemy/Phrasea/Record/RecordWasRotated.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/IndexerSubscriber.php
> Add RecordEvent when rotated

- lib/Alchemy/Phrasea/Controller/Api/SearchController.php
- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineResult.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineResultToRecordsConverter.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineResultTest.php
- tests/classes/PhraseanetAuthenticatedWebTestCase.php
> new search API

- lib/Alchemy/Phrasea/Controller/Api/LazaretController.php
- lib/Alchemy/Phrasea/Controller/Prod/LazaretController.php
- lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
- lib/Alchemy/Phrasea/Core/Provider/ManipulatorServiceProvider.php
- lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
#PHRAS-947 time 1d
first commit
new routes
DELETE /api/v2/quarantine/item/{{item_id}}/
POST /api/v2/quarantine/item/{{item_id}}/add/
> api routes to delete/force quarantine item

- lib/Alchemy/Phrasea/Controller/Api/SearchController.php
- Remove unnecessary fetching from database
- Remove redundant suggestions key in response (same as facets)
> Simplify V2 search controller

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Controller/Api/SearchController.php
- lib/Alchemy/Phrasea/Core/Event/RecordEdit.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
- lib/Alchemy/Phrasea/Core/Provider/PhraseaEventServiceProvider.php
- lib/Alchemy/Phrasea/Model/Entities/ElasticsearchRecord.php
- lib/Alchemy/Phrasea/Model/RecordInterface.php
- lib/Alchemy/Phrasea/Model/Serializer/ESRecordSerializer.php
- lib/Alchemy/Phrasea/Record/RecordUpdateSubscriber.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
- lib/classes/record/adapter.php
> search api v2 use timestamp

- lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- lib/Alchemy/Phrasea/Controller/DatafileController.php
- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/Alchemy/Phrasea/Databox/SubdefGroup.php
- lib/Alchemy/Phrasea/Media/MediaTypeFactory.php
- lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- lib/classes/databox.php
- lib/classes/databox/subdefsStructure.php
- lib/classes/p4field.php
- lib/classes/record/adapter.php
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/admin/subdefs.html.twig
> Subdef group refactoring

- circle.yml
- lib/conf.d/configuration.yml
- tests/Alchemy/Tests/Phrasea/TaskManager/TaskTest.php
> Fixes default embed-bundle configuration

- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/Alchemy/Phrasea/Media/SubdefSubstituer.php
> Subdef substitution rebuilds all sub-definitions

- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Filesystem/FilesystemService.php
- lib/Alchemy/Phrasea/Media/Subdef/Image.php
- lib/classes/databox/subdef.php
> backport png subdefs into 4.0

- lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
When hotfolder path terminates with a slash, invalid directories are created.
PHRAS-884
> Archive Task naming issue

- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
Should use hasser to check whether a group exists or not.
> SubdefGroup is not array accessible.

- lib/classes/set/export.php
backport fix to 3.8
PHRAS-1012
> export filenames with long filenames

- lib/Alchemy/Phrasea/Collection/CollectionHelper.php
- lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
- templates/web/admin/tree.html.twig
Only currently used in admin/tree.html.twig but could be used in collection rights.
> Added new Twig filter to sort a collection set.

- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- lib/Alchemy/Phrasea/Controller/RecordsRequest.php
PHRAS-1045 #time 4h
-fix : when a story is deleted with "Delete also content..." checked, the content and the story is deleted
> PHRAS-1045 Delete story and content

- templates/web/common/dialog_export.html.twig
#time 1h
-fix : added escaping to js context strings (translation contains a quote)
> PHRAS-1052 Download window is broken

- lib/Alchemy/Phrasea/Databox/DataboxBoundRepositoryFactory.php
- lib/Alchemy/Phrasea/Databox/DataboxBoundRepositoryProvider.php
- lib/Alchemy/Phrasea/Hydration/Hydrator.php
- lib/Alchemy/Phrasea/Hydration/IdentityMap.php
- lib/Alchemy/Phrasea/Hydration/ReflectionHydrator.php
- lib/Alchemy/Phrasea/Vocabulary/ControlProvider/ControlProviderInterface.php
- lib/classes/caption/Field/Value.php
- lib/classes/caption/field.php
- lib/classes/caption/record.php
- lib/classes/databox/descriptionStructure.php
- tests/Alchemy/Tests/Phrasea/Authentication/Provider/LinkedinTest.php
- tests/Alchemy/Tests/Phrasea/Databox/DataboxBoundRepositoryProviderTest.php
- tests/Alchemy/Tests/Phrasea/Hydration/IdentityMapTest.php
- tests/Alchemy/Tests/Phrasea/Hydration/ReflectionHydratorTest.php
also fix #1780. Found some Vocabulary Controller calls left.
> Batch load caption

- PULL_REQUEST_TEMPLATE.md
- Adds simple pull request template.
> Adds a Pull request template

- lib/Alchemy/Phrasea/Controller/Prod/EditController.php
- package.json
- resources/www/prod/skins/ui-components/_modal-edit.scss
- templates/web/prod/actions/Download/prepare.html.twig
- templates/web/prod/actions/Push.html.twig
- templates/web/prod/actions/edit_default.html.twig
- templates/web/prod/index.html.twig
Record Editor fix and refactoring
> Bump Phraseanet production client

- lib/Alchemy/Phrasea/Command/BuildSubdefs.php
- lib/classes/media/subdef.php
- lib/classes/record/adapter.php
PHRAS-1055
enhance "BuildSubdefs" command to allow filtering, partition, rebuild, cleaning, ...
> PHRAS-1055 better BuildSubdefs command

- lib/Alchemy/Phrasea/Command/BuildSubdefs.php
#time 15m
- PHRAS-1055: fix fatal error "getName()"
> PHRAS-1055 backport to 4.0

- lib/Alchemy/Phrasea/TaskManager/Job/WebhookJob.php
- Argument type errors in webhook job
> Doctrine iterator returns array not object

- lib/Alchemy/Phrasea/Controller/Api/LazaretController.php
- lib/Alchemy/Phrasea/Controller/Prod/LazaretController.php
- lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
- lib/Alchemy/Phrasea/Core/Provider/ManipulatorServiceProvider.php
- lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
> PHRAS-1065_backport-PHRAS-947

- templates/web/admin/search-engine/elastic-search.html.twig
#time 1h
- moved "index" buttons near "index name" field
> PHRAS-1061

- templates/web/account/access.html.twig
> PHRAS-1046 - fix cgu per database listing in account access

- lib/Alchemy/Phrasea/ControllerProvider/Prod/BasketProvider.php
- lib/Alchemy/Phrasea/ControllerProvider/Prod/Export.php
- PHRAS-1075: Add OAuth authentication on all export routes.
export_multi_export, export_mail, export_ftp & export_ftp_test are impacted.
> Add oauth authentication for export routes.

- lib/Alchemy/Phrasea/ControllerProvider/Prod/Download.php
- Oauth token based authentication on route to download record archives
> Add token based auth on download page

- lib/Alchemy/Phrasea/Controller/Api/SearchController.php
- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- lib/Alchemy/Phrasea/Databox/Subdef/CachedMediaSubdefDataRepository.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineInterface.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- lib/classes/caption/record.php
- lib/classes/databox/descriptionStructure.php
- lib/classes/record/preview.php
- tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
- tests/Alchemy/Tests/Phrasea/Controller/Prod/QueryTest.php
- tests/Alchemy/Tests/Phrasea/Controller/Prod/RecordsTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineOptionsTest.php
- tests/classes/PhraseanetAuthenticatedWebTestCase.php
- When all subdefs are requested, a special key is registered to list all available subdefs. This allows performing full request for each record.
> Add caching of all subdefs of a record

- lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/SessionManagerSubscriber.php
- #1813 Download via oauth is not possible
> Merge 4.0 back in master

- lib/Alchemy/Phrasea/Core/Event/Subscriber/CookiesDisablerSubscriber.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/SessionManagerSubscriber.php
- PHRAS-1086: Several calls should always have same result
Follows #1813 that does not completely solve the issue.
> OAuth authentication is not properly prioritized

- lib/Alchemy/Phrasea/Controller/DatafileController.php
- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
- lib/Alchemy/Phrasea/Databox/Subdef/MediaSubdefRepository.php
- lib/Alchemy/Phrasea/Databox/SubdefGroup.php
- lib/Alchemy/Phrasea/Media/MediaTypeFactory.php
- lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- lib/classes/databox/subdefsStructure.php
- lib/classes/media/subdef.php
- PHRAS-1024: Image rotate tooltip issue
> Image rotate issue

- resources/www/prod/js/jquery.WorkZone.js
- PHRAS-1076: Move listener definition on basket list refresh
> fix listener to be called when refreshing Basket Workzone

- lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
#time 10m
- PHRAS-1091: remove stories from ordered items
> PHRAS-1091_ORDER_ROUTE_STORIES

- resources/www/prod/js/jquery.WorkZone.js
- PHRAS-1076: Listener registration should be left at both places
> Restore register at initialization

- circle.yml
- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping.php
- upgrade the php-es lib to 2.x so ES can be upgraded to.
#time 1d
> PHRAS-1094_ES-LIB-UPGRADE

- resources/www/prod/js/jquery.WorkZone.js
> fix PHRAS-1076

- resources/www/prod/skins/ui-components/_answers.scss
- templates/web/prod/actions/edit_default.html.twig
- templates/web/prod/results/record.html.twig
> PHRAS-1082 - fix preview icon in record editor

- .travis.yml
- composer.json
> Tweak travis.yml

- composer.lock
- Security issues reported by Scrutinizer
Bump symfony/symfony
> Require latest version of roave/security-advisories.

- lib/Alchemy/Phrasea/Core/Provider/RepositoriesServiceProvider.php
- lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
- lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
- lib/classes/record/adapter.php
- Loading of children in record_adapter
- Add `findChildren()` & `findParents()` to `RecordRepository`
> Load children of many stories

- templates/web/account/access.html.twig
> PHRAS-1046 - fix CGU content disposition in account

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Core/Event/OrderDeliveryEvent.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/OrderSubscriber.php
- lib/Alchemy/Phrasea/Core/Provider/OrderServiceProvider.php
- lib/Alchemy/Phrasea/Core/Version.php
- lib/Alchemy/Phrasea/Model/Entities/Order.php
- lib/Alchemy/Phrasea/Model/Entities/WebhookEvent.php
- lib/Alchemy/Phrasea/Notification/Emitter.php
- lib/Alchemy/Phrasea/Notification/Mail/AbstractMail.php
- lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
- lib/Alchemy/Phrasea/Order/Controller/BaseOrderController.php
- lib/Alchemy/Phrasea/Order/OrderDelivery.php
- lib/Alchemy/Phrasea/Order/OrderElementView.php
- lib/Alchemy/Phrasea/Order/ValidationNotifier.php
- lib/Alchemy/Phrasea/Order/ValidationNotifier/MailNotifier.php
- lib/Alchemy/Phrasea/Order/ValidationNotifier/WebhookNotifier.php
- lib/Alchemy/Phrasea/Order/ValidationNotifierRegistry.php
- lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20160511160640.php
- lib/Alchemy/Phrasea/Webhook/EventProcessorFactory.php
- lib/Alchemy/Phrasea/Webhook/Processor/OrderNotificationProcessor.php
- lib/Alchemy/Phrasea/Webhook/Processor/OrderNotificationProcessorFactory.php
- lib/classes/patch/400alpha7a.php
- tests/Alchemy/Tests/Phrasea/Controller/Prod/OrderTest.php
- tests/classes/PhraseanetTestCase.php
- Dynamic selection of notification method for order events based on the method used to create the order (API vs Prod)
> Add webhook notifications for order events

- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineOptionsTest.php
- preview mode is ok when some collections are unchecked
#time 3h
> PHRAS-1101_THMB-TRAIN-IN-PREVIEW

- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineOptionsTest.php
- fix preview mode when some collections are unchecked (backport from master)
#time 30m
> PHRAS-1101_BACKPORT

- lib/classes/caption/Field/Value.php
- some elements of "train" don't display preview/caption when selected (due to code exception)
> PHRAS-1101_BACKPORT-4.0

- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Core/Provider/JsonSchemaServiceProvider.php
- lib/Alchemy/Phrasea/Helper/JsonBodyHelper.php
- Creating an order via the API triggers an error due to a bug in an upstream library.
> Fix JSON schema decode error

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Command/Task/TaskRun.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/OrderSubscriber.php
- lib/Alchemy/Phrasea/Core/Provider/OrderServiceProvider.php
- lib/Alchemy/Phrasea/Order/ValidationNotifier/WebhookNotifier.php
- lib/Alchemy/Phrasea/TaskManager/Job/WebhookJob.php
- Order event subscriber was not registered in application and did not initialize correctly
> Fix order notification subscriber and provider

- lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
- Allows admin accounts to access any order via the API
> Allow access to all orders via API to admins

- lib/Alchemy/Phrasea/Core/Event/Subscriber/OrderSubscriber.php
> Improve order create notification

- package.json
- templates/web/prod/tab_thesaurus.html.twig
- PHRAS-1106 - fix thesaurus search options
> PHRAS-1106 - fix thesaurus search options

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- Some translations
Currently translated at 100.0% (2296 of 2296 strings)
> Translations update 4.0

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
> Translations on master

- lib/classes/Bridge/Api/Youtube.php
- tests/Alchemy/Tests/Phrasea/Controller/Prod/OrderTest.php
- tests/Alchemy/Tests/Phrasea/Controller/Root/LoginTest.php
- tests/classes/PhraseanetTestCase.php
- Change default notification.deliverer to be no-op instead of throwing exception
> Fixup testsuite in 4.0

- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Filter.php
- during records indexation, thesaurus is searched strictly (no scoring)
- thesaurus search is compatible with ES 1.7 and ES 2.x
> Phras 1105 thesaurus notok es 2.3

- lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
- templates/web/prod/orders/order_box.html.twig
(button style and per-page parameter)
> PHRAS-1107 -  fix frontend issues for orders pagination

- resources/www/common/js/jquery.tooltip.js
- PHRAS-1113 - fix tooltip positionning for records previews
> PHRAS-1113 - fix tooltip positionning for records previews

- resources/www/common/js/jquery.tooltip.js
> PHRAS-1113 - fix tooltip positionning: handle dynamic size of thumbnails

- lib/Alchemy/Phrasea/Core/Event/Subscriber/OrderSubscriber.php
- lib/Alchemy/Phrasea/Model/Repositories/OrderRepository.php
- lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
- lib/Alchemy/Phrasea/TaskManager/Job/WebhookJob.php
- PHRAS-1107: Paginating orders was not working correctly
> PHRAS-1107 Fix order pagination in repository

- lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
- Offset was incorrectly calculated in order controller
> Fix page offsets

- lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
- lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
- lib/Alchemy/Phrasea/Order/OrderTransformer.php
- lib/Alchemy/Phrasea/Order/OrderView.php
- lib/Alchemy/Phrasea/Order/OrderViewBuilder.php
- lib/classes/databox.php
- lib/classes/record/exportElement.php
- lib/classes/set/export.php
- Archive URL is available in API responses for orders
> Add order download URL in API response

- lib/Alchemy/Phrasea/Order/Controller/BaseOrderController.php
- Incorrect use of `forAll` method closure
> Order validation issue

- lib/Alchemy/Phrasea/Core/Version.php
- lib/Alchemy/Phrasea/Model/Entities/FeedEntry.php
- lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20160520165600.php
- lib/classes/patch/400alpha8a.php
- PHRAS-1116: Enlarge FeedEntry length to 1024 chars
> Enlarge FeedEntry length to 1024 chars

- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- lib/classes/record/preview.php
- package.json
- resources/www/prod/skins/ui-components/_modal-preview.scss
- Bump Phraseanet Production Client
- PHRAS-851 - add databox name, collection name and logo to record title in preview
> PHRAS-851 - add missing informations in record preview

- resources/www/lightbox/js/jquery.validator.mobile.js
- PHRAS-1115 - fix lightbox mobile events handling
> PHRAS-1115 - fix lightbox mobile events handling (4.0)

- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- lib/classes/record/preview.php
- resources/www/prod/js/jquery.p4.preview.js
- resources/www/prod/skins/ui-components/_modal-preview.scss
- PHRAS-851 - add databox name, collection name and logo to record title in preview
> PHRAS-851 - add missing informations in record preview (4.0)

- templates/mobile/lightbox/basket_element.html.twig
- templates/mobile/lightbox/note_form.html.twig
- PHRAS-1115 - fix lightbox mobile events handling
> PHRAS-1115 - fix lightbox mobile events handling

- templates/web/prod/results/record.html.twig
- PHRAS-1078 - toggle collection name with mini logo
> PHRAS-1078 - toggle collection name with mini logo (4.0)

- resources/ansible/roles/nginx/templates/default.j2
- www/api_dev.php
- Access to profiler using api_dev.php in API routes
> Add dev entry point for API

- resources/ansible/roles/nginx/templates/default.j2
- Default configuration for nginx in Ansible template (redirect loop)
> Fix nginx configuration for api_dev.php

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/admin/collection/collection.html.twig
> Display unique collection IDs in collection admin

- lib/Alchemy/Phrasea/Controller/Root/DeveloperController.php
- PHRAS-570 Any authenticated user could access another user's application settings
> Restrict application settings access to application owner

- resources/www/common/js/jquery.tooltip.js
> Rollback PHRAS-1113 changes

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/classes/ACL.php
- PHRAS-572 List user databox rights in response of /me route in API
> PHRAS-572 List user rights by databox in /me route

- lib/Alchemy/Phrasea/Account/RestrictedStatusExtractor.php
- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/classes/ACL.php
- PHRAS-573: List available statuses and access rights in collection listing in /me route
> PHRAS-573 Add status rights in /me response

- templates/web/admin/collection/reorder.html.twig
- PHRAS-1121 - Admin: fix collection reordering
> PHRAS-1121 - Admin: fix collection reordering

- templates/web/common/technical_datas.html.twig
- PHRAS-870 - add physical size in technical informations
> PHRAS-870 - add physical size in technical informations

- templates/web/common/dialog_export.html.twig
- PHRAS-515 - fix export by email form submission
> PHRAS-515 - fix export by email form submission

- lib/classes/patch/390alpha13a.php
- lib/classes/patch/390alpha6a.php
> Fix upgrade from 3.8 to 4.0

- resources/www/prod/js/jquery.main-prod.js
- templates/web/prod/index.html.twig
- PHRAS-1080 - prod advanced search: fix document status selection
> PHRAS-1080 - prod advanced search: fix document status selection

- resources/www/prod/js/jquery.Edit.js
- PHRAS-1104 - edit record: fix empty value in multivalued fields
> PHRAS-1104 - edit record: fix empty value in multivalued fields

- lib/Alchemy/Phrasea/Out/Module/PDF.php
- on thumbnail grid (pdf), thumbnail title is now over the thumbnail image.
> PHRAS-1125_PDF-THUMBNAIL-TITLE

- lib/Alchemy/Phrasea/Out/Module/PDF.php
- see PHRAS-1125_PDF-THUMBNAIL-TITLE #1894
> PHRAS-1125_backport

- lib/Alchemy/Phrasea/Controller/Prod/DoDownloadController.php
- lib/classes/set/export.php
> Fix incorrect file names for filename containing dots

- lib/Alchemy/Phrasea/Core/MetaProvider/HttpStackMetaProvider.php
> Configure CORS for download path

- lib/Alchemy/Phrasea/Border/MetaFieldsBag.php
- lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
- lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
- add from quarantine is ok (did crash when a multivalue field was populated via xml file).
> PHRAS-1100_QUARANTINE-XML

- lib/Alchemy/Phrasea/Border/MetaFieldsBag.php
- lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
- lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
> PHRAS-1161_Backport-PHRAS_1100

- composer.json
- composer.lock
> PHRAS-1160_Backport-PHRAS_1159

- composer.json
- composer.lock
- fix : Error "wrong number of arguments" using a secondary encoding instance (subdef task) is fixed
> PHRAS-1159_Subdef-Task-Doctrine-Cache-err

- templates/web/prod/index.html.twig
- fix : js error in prod template when  not(app.debug)
> PHRAS-1162_js-err-prod

- lib/Alchemy/Phrasea/Controller/Prod/Edit.php
- lib/classes/record/adapter.php
> PHRAS-1166_Backport-PHRAS-1158-to-3.8

- lib/Alchemy/Phrasea/Collection/CollectionService.php
- lib/Alchemy/Phrasea/Controller/Prod/EditController.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
- lib/classes/record/adapter.php
- when a record moves to another collection, the stamp (logo) is now updated
> PHRAS-1158_STAMP-CHANGE-COLL

- lib/Alchemy/Phrasea/Collection/CollectionService.php
- lib/Alchemy/Phrasea/Controller/Prod/EditController.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
- lib/classes/record/adapter.php
> PHRAS-1164_Backport-PHRAS-1158-to-4.0

- lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php
- lib/classes/databox.php
- lib/classes/databox/field.php
- templates/web/admin/fields/templates.html.twig
- tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php
- tests/classes/databox/fieldTest.php
- www/scripts/apps/admin/fields/views/create.js
- www/scripts/apps/admin/fields/views/edit.js
- now the "multi" attribute on a field can be changed after creation
- field template is changed
> PHRAS-1177_change-multi-on-field

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Fractal/IncludeResolver.php
- lib/Alchemy/Phrasea/Search/StoryTransformer.php
- lib/Alchemy/Phrasea/Search/V1SearchCompositeResultTransformer.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- Story search responses no longer include the "records" property.
> Remove records property from story search results

- lib/Alchemy/Phrasea/Search/StoryTransformer.php
- lib/Alchemy/Phrasea/Search/StoryView.php
- Record count property for stories in API responses
> Add record count property to story responses

- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
- templates/web/prod/thesaurus.js.twig
- templates/web/thesaurus/thesaurus.html.twig
- prod / delete candidate is ok
- thesaurus / delete candidate is ok
- prod / delete candidate does not update records metadata
- prod / replace candidate is removed
> PHRAS-726_delete-candidate

- bower.json
- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- package.json
- resources/gulp/build.js
- resources/gulp/components/vendors/alchemy-embed.js
- resources/gulp/watch.js
- templates/web/common/thumbnail.html.twig
- templates/web/overview.html.twig
- Embed Medias are now loaded via pym.js 
- medias auto resizing in tooltips and preview
- stop or pause video when modals are closed or lose focus
> Pym.js integration for embed medias

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Search/RecordTransformer.php
- tests/bootstrap.sh
> Fix include resolution

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Search/StoryTransformer.php
> Include record caption in new story search type

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
> Fix incorrect include resolution for search type 2

- lib/Alchemy/Phrasea/Controller/Prod/Story.php
- lib/classes/caption/field.php
- story title is not set in a read-only field (it goes to the first non read-only "thumbtitle" field)
> #PHRAS-1187

- lib/Alchemy/Phrasea/Core/Event/RecordCreated.php
- lib/Alchemy/Phrasea/Core/Event/RecordEdit.php
- lib/Alchemy/Phrasea/Core/Event/StatusChanged.php
- lib/Alchemy/Phrasea/Core/Event/StoryCoverChanged.php
- lib/Alchemy/Phrasea/Core/PhraseaEvents.php
- lib/classes/record/adapter.php
- event STATUS_CHANGED
- event STORY_COVER_CHANGED
- event RECORD_CREATED
> #PHRAS-1184 time 2h

- lib/Alchemy/Phrasea/Border/Checker/Filename.php
- lib/Alchemy/Phrasea/Border/Checker/Sha256.php
- lib/Alchemy/Phrasea/Border/Checker/UUID.php
- lib/Doctrine/Entities/LazaretCheck.php
- lib/Doctrine/Entities/LazaretFile.php
- lib/Doctrine/Proxies/__CG__EntitiesLazaretFile.php
- lib/classes/record/adapter.php
- templates/web/prod/upload/lazaret.html.twig
- list of records related (conflict) to a file in quarantine is ok
- conflicting record indicates original filename an reason of conflict
> #PHRAS-1186 quarantine because filename conflict

- lib/classes/record/adapter.php
- templates/web/prod/feeds/entry_macro.html.twig
- templates/web/prod/results/answerabstract.html.twig
- templates/web/prod/results/answergrid.html.twig
- templates/web/prod/results/answerlist.html.twig
- templates/web/prod/results/record.html.twig
- templates/web/prod/upload/lazaret.html.twig
- new : thumbnails of conflicting records are rendered like in answer pages (with icons, roll-over, selection color)
> #PHRAS-1186 quarantine better thumbnails

- lib/classes/caption/Field/Value.php
- lib/classes/caption/record.php
- in prod/preview, terms with quotes are now "bounceable" (dashed underline, click to search)
> #PHRAS-1191 quotes in thesaurus terms

- composer.json
- composer.lock
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping.php
- see #1826  (update php-es lib)
> PHRAS-1168_Backport-PHRAS-1094-to-4.0

- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
- prod / thesaurus search is ok (language doesn't care)
> PHRAS-1190_prod-search-thesaurus

- lib/Alchemy/Phrasea/Collection/CollectionService.php
- lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php
- lib/Alchemy/Phrasea/Controller/Controller.php
- lib/Alchemy/Phrasea/Controller/LazyLocator.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Collection.php
- lib/Alchemy/Phrasea/Core/LazyLocator.php
- lib/classes/appbox.php
- templates/web/admin/collection/collection.html.twig
- It was not possible to remove an order master without adding a new one
> Allow removing order masters without adding a new one

- templates/web/admin/collection/collection.html.twig
> Remove autosubmit from order manager list

- lib/classes/patch/390alpha6a.php
> fix syntax error text_mail_receiver

- lib/Alchemy/Phrasea/Model/Repositories/TokenRepository.php
> Fix non unique validation tokens

- lib/Alchemy/Phrasea/Model/Repositories/TokenRepository.php
Reverts alchemy-fr/Phraseanet#1936
> Revert "Fix non unique validation tokens"

- lib/Alchemy/Phrasea/Controller/Prod/EditController.php
- lib/Alchemy/Phrasea/Core/Event/Record/RecordEvents.php
- lib/Alchemy/Phrasea/Core/Event/Record/StoryCoverChanged.php
- lib/Alchemy/Phrasea/Core/Event/Record/StoryCoverChangedEvent.php
- PHRAS-1216: Add the "STORY_COVER_CHANGED" event (port from 3.8)
> PHRAS-1216_story-cover-changed-event

- .gitignore
- Makefile
- composer.json
- resources/ansible/roles/app/tasks/main.yml
- resources/ansible/roles/app/templates/configuration.tpl
- resources/ansible/roles/mailcatcher/tasks/main.yml
- resources/ansible/roles/mariadb/tasks/main.yml
- resources/ansible/vars/all.yml
Fixes and adds the necessary Ansible roles to ensure the VM can be provisioned entirely via Vagrant and be operational without any manual operations
> Fix Vagrant provisionning

- .gitignore
- Makefile
- resources/ansible/roles/app/tasks/main.yml
> Split make targets and update provisioning accordingly

- .gitignore
- Makefile
- resources/ansible/roles/app/tasks/main.yml
- resources/ansible/roles/app/templates/configuration.tpl
- resources/ansible/roles/mailcatcher/tasks/main.yml
- resources/ansible/roles/mariadb/tasks/main.yml
- resources/ansible/vars/all.yml
- Provisioning now setups a functional instance
> Backport provisioning

- lib/Alchemy/Phrasea/Core/Database/DatabaseMaintenanceService.php
> PHRAS-1210 Remove invalid assignment

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- templates/web/prod/actions/Tools/index.html.twig
- PHRAS-1224 : Remove rotation subdef wording on 4.0
> Remove unwanted rotation wording

- resources/www/prod/skins/ui-components/_answers-tools.scss
- PHRAS-1196 Change caret color on phraseanet white skin
> Change caret color on phraseanet white skin

- Makefile
- resources/ansible/roles/app/tasks/main.yml
> Split build into smaller targets

- bin/setup
- lib/Alchemy/Phrasea/Command/Setup/ConfigurationEditor.php
- New command in bin/setup tool to read or write configuration values
> Add configuration editor command in setup

- Vagrantfile
- resources/ansible/roles/app/tasks/main.yml
- resources/ansible/roles/elasticsearch/tasks/main.yml
- PHRAS-1214 Access to app was not possible in debug mode with provisionned configuration
> Allow debugger access to Vagrant host IP addresses

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-1006 The API response for collections now includes the list of order masters
> PHRAS-1006 Add order manager in API collection description

- templates/web/admin/setup.html.twig
- PHRAS-1234 Change wording on setup template
> Change wording on setup template

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookUserEventSubscriber.php
- lib/Alchemy/Phrasea/Core/MetaProvider/DatabaseMetaProvider.php
- lib/Alchemy/Phrasea/Model/Manager/UserManager.php
- lib/Alchemy/Phrasea/Webhook/EventProcessorFactory.php
- lib/Alchemy/Phrasea/Webhook/Processor/UserDeletedProcessor.php
- lib/Alchemy/Phrasea/Webhook/Processor/UserDeletedProcessorFactory.php
- tests/Alchemy/Tests/Phrasea/Functional/UserDeletionTest.php
- tests/Alchemy/Tests/Phrasea/Model/Repositories/WebhookEventRepositoryTest.php
- PHRAS-1246: User deleted webhook was missing in 4.0
> PHRAS-1239 Add webhook for user deleted events

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- templates/web/prod/actions/Tools/index.html.twig
- PHRAS-1224 Rollback and change subdef rotation wording
> Rollback and change subdef rotation wording

- lib/Alchemy/Phrasea/Controller/Api/SearchController.php
- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- lib/Alchemy/Phrasea/Search/V1SearchTransformer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineResult.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineResultTest.php
- tests/classes/PhraseanetAuthenticatedWebTestCase.php
- PHRAS-842: query is logged in a "user" form, before parsing
> PHRAS-842_search-logged-as-es_4.0

- lib/Alchemy/Phrasea/Border/Checker/Filename.php
- lib/Alchemy/Phrasea/Border/Checker/Sha256.php
- lib/Alchemy/Phrasea/Border/Checker/UUID.php
- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- lib/Alchemy/Phrasea/Model/Entities/LazaretCheck.php
- lib/Alchemy/Phrasea/Model/Entities/LazaretFile.php
- lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
- lib/classes/caption/record.php
- lib/classes/media/Permalink/Adapter.php
- lib/classes/record/adapter.php
- lib/classes/record/preview.php
- lib/classes/set/export.php
- templates/web/common/macros.html.twig
- templates/web/prod/results/macro.html.twig
- templates/web/prod/results/record.html.twig
- templates/web/prod/results/records.html.twig
- templates/web/prod/upload/lazaret.html.twig
- PHRAS-1192: quarantine caused by name conflict is ok
- PHRAS-1205: extension on exported files
- PHRAS-1237: export of caption is ok (was failing with 404)
- codestyle
- quarantine thumbnails looks like result thb (zoom, caption, infos, ...) by using the same template
- some code about highlighting titles
> PHRAS-1192_quarantaine-by-filenames_4.0

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
- lib/classes/ACL.php
- lib/classes/record/adapter.php
- tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
- PHRAS-946: api route to delete record
verb DELETE ; /api/v1/records/{{databox_id}}/{{record_id}}
> PHRAS-946_delete-record-api

- resources/www/_shared/styles/main.scss
- PHRAS-1235 Change design to remove tooltip truncate
> Change design to remove tooltip truncate

- Vagrantfile
- resources/ansible/roles/php/tasks/pecl.yml
- resources/ansible/roles/server/tasks/main.yml
- resources/ansible/vars/all.yml
> Add some missing Phraseanet dependencies to provisioning

- resources/ansible/vars/all.yml
> Add MP4Box to provisioning

- templates/web/developers/application.html.twig
- PHRAS-1261: API application edit form behavior was broken due to missing JS bootstrap
> PHRAS-1261 Add account module bootstrap in API application settings

- lib/Alchemy/Phrasea/Model/Repositories/RegistrationRepository.php
- templates/web/account/access.html.twig
- PHRAS-1173 Hide cgu when insuffisent privilege.
> Hide cgu when insuffisent privilege

- lib/Alchemy/Phrasea/Setup/Requirements/PhpRequirements.php
- PHRAS-1266: Recommend more secure session cookie settings
> Session cookie recommandations

- lib/Alchemy/Phrasea/Core/Configuration/SessionHandlerFactory.php
- PHRAS-1236: It was not possible to configure other session types than file via php.ini
> Native session handler

- lib/Alchemy/Phrasea/Controller/Admin/TaskManagerController.php
- lib/Alchemy/Phrasea/TaskManager/Log/TaskLogFile.php
- templates/web/admin/task-manager/log_scheduler.html.twig
- templates/web/admin/task-manager/log_task.html.twig
- Improves version listing of task log files (now sorted by descending date)
> Improve task manager logs

- lib/Alchemy/Phrasea/Controller/PermalinkController.php
- PHRAS-1225: Trigger export event when a record subdef is downloaded via its permalink to ensure proper tracking of download stats
> PHRAS-1225 Log downloads triggered via permalinks

- lib/Alchemy/Phrasea/Command/SearchEngine/IndexPopulateCommand.php
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/TermIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/IndexerSubscriber.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Helper.php
- lib/Alchemy/Phrasea/TaskManager/Job/IndexerJob.php
- templates/web/thesaurus/new-term.html.twig
- If the thesaurus has been modified since it's last indexation, it will be re-indexed as soon a record is to be indexed.
- nb : after thesaurus modification, the databox MUST be manually re-indexed (which will reindex the thesaurus before)
- todo : remove useless dialog boxes from thesaurus app (... "this term was..."  "...add with/out reindexing ?..."). To be done in the future app using future routes.
> PHRAS-714_thesaurus_indexation

- lib/Alchemy/Phrasea/Command/BuildSubdefs.php
- option --garbage_collect renamed as --prune
- verbosity -v prints lines, no verbosity displays progress-bar
- options --mode, --all, --scheduled, --reverse, --show-sql
> PHRAS-1271_better-buildsubdefs

- lib/Alchemy/Phrasea/Command/SearchEngine/IndexPopulateCommand.php
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/TermIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/IndexerSubscriber.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Helper.php
- lib/Alchemy/Phrasea/TaskManager/Job/IndexerJob.php
- templates/web/thesaurus/new-term.html.twig
Reverts alchemy-fr/Phraseanet#1978
> Revert "PHRAS-714_thesaurus_indexation"

- lib/Alchemy/Phrasea/Command/SearchEngine/IndexPopulateCommand.php
- lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/TermIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/IndexerSubscriber.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Helper.php
- lib/Alchemy/Phrasea/TaskManager/Job/IndexerJob.php
- templates/web/thesaurus/new-term.html.twig
Reverts alchemy-fr/Phraseanet#1987
> Revert "Revert "PHRAS-714_thesaurus_indexation""

- bin/console
- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Command/CreateDataboxCommand.php
- lib/Alchemy/Phrasea/Command/Databox/CreateDataboxCommand.php
- lib/Alchemy/Phrasea/Command/Databox/MountDataboxCommand.php
- lib/Alchemy/Phrasea/Command/SearchEngine/IndexCreateCommand.php
- lib/Alchemy/Phrasea/Controller/Admin/DataboxesController.php
- lib/Alchemy/Phrasea/Controller/Controller.php
- lib/Alchemy/Phrasea/Core/Provider/DataboxServiceProvider.php
- lib/Alchemy/Phrasea/Databox/DataboxConnectionSettings.php
- lib/Alchemy/Phrasea/Databox/DataboxFactory.php
- lib/Alchemy/Phrasea/Databox/DataboxService.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContextFactory.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
- lib/classes/databox.php
- resources/ansible/roles/app/tasks/main.yml
- resources/ansible/roles/mariadb/tasks/main.yml
- resources/ansible/vars/all.yml
- tests/Alchemy/Tests/Phrasea/Controller/Admin/DataboxesTest.php
- Adds a new databox service to manipulate databoxes
> Extract databox service from admin databox controller

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Core/PhraseaExceptionHandler.php
- lib/Alchemy/Phrasea/Utilities/PassthroughTranslator.php
- PHRAS-1276: Error log is stored in logs subdirectory regardless of configured log path
> Fix exception log path

- resources/www/prod/js/jquery.main-prod.js
- resources/www/prod/skins/ui-components/_workzone.scss
- Align menu icons on prod view and fix misplaced webgalleries icon.
> Align menu icons on prod view

- lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
- lib/Alchemy/Phrasea/ControllerProvider/Prod/Order.php
- lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
- lib/Alchemy/Phrasea/Order/Controller/BaseOrderController.php
> PHRAS-1275 Fix order archive path

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php
- "concept_path" node in index structure was incorrectly generated
> Fix index creation errors with field linked concepts in thesaurus

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/ComplexFieldMapping.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/ComplexMapping.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/ComplexPropertiesMapping.php
- Specialized complex mapping type for property maps, mainly to improve readability
- Clean up mapping build process
> Add specialized complex mapping for property maps

- lib/Alchemy/Phrasea/Core/Event/RecordDocumentSubstituted.php
- lib/Alchemy/Phrasea/Core/PhraseaEvents.php
- lib/classes/record/adapter.php
- PHRAS-1277 : new event "RecordDocumentSubstituted"
> #PHRAS-1277_substitution-event_3.8

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/ComplexFieldMapping.php
- Invalid "fields" entries in string field mappings
> Fix invalid string mapping

- lib/Alchemy/Phrasea/Model/Entities/ElasticsearchRecord.php
- lib/Alchemy/Phrasea/Model/RecordInterface.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/CoreHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php
- lib/classes/record/adapter.php
- templates/web/common/technical_datas.html.twig
- PHRAS-1260: "technical data" template
- PHRAS-1260: methods getWidth(), getHeight(), getSize() to recordInterface; Add "width", "height" and "size" to ES
> Phras 1260 index width height

- lib/Alchemy/Phrasea/Command/BuildSubdefs.php
- PHRAS-1285: In cli "records:build-subdefs", using "--name=xxx" argument does not delete  all other subdefs anymore.
> fix: if using --name argument, some subdefs were deleted

- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
> Always add recordid as last sort option

- lib/Alchemy/Phrasea/Application.php
- lib/Alchemy/Phrasea/Controller/Admin/TaskManagerController.php
- lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- lib/Alchemy/Phrasea/Filesystem/FilesystemService.php
- lib/Alchemy/Phrasea/Media/SubdefSubstituer.php
- lib/classes/media/subdef.php
- PHRAS-757: Document substitution was broken
- PHRAS-1017: Document substitution was broken
- PHRAS-1126: Document substitution was broken
> Fix document substitution

- lib/Alchemy/Phrasea/Application.php
- PHRAS-1236: It was not possible to use session handlers other than "files"
> PHRAS-1236 Enable native session handlers

- lib/classes/eventsmanager/broker.php
- PHRAS-1286 Add missing notifications to the list
> Notifications are missing

- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
- PHRAS-830: (prod) Loading cterms was not possible if the already loaded list was empty (missing html tag). Not a cache problem.
- counting of thesaurus hits since the "thit" table is empty (and should be dropped...)
> PHRAS-830_CANDIDATES-CACHED

- resources/www/admin/styles/main.scss
- templates/web/admin/dashboard.html.twig
- Change blocker icon size on admin dashboard
> Change blocker icon size on admin dashboard

- composer.json
- PHRAS-1254: Adding fractal alchemy-fr fork to composer.json
> Adding fractal alchemy-fr fork to composer.json

- resources/www/admin/styles/main.scss
- templates/web/admin/fields/index.html.twig
- PHRAS-1220 Add warn message in admin (fields setup)
> Add warn message in admin

- lib/Alchemy/Phrasea/Command/Compile/Configuration.php
- lib/Alchemy/Phrasea/Core/Configuration/Configuration.php
> PHRAS-1289 Add group rights to compiled configuration

- templates/web/admin/collection/collection.html.twig
> Change order and wording for base ID in collection details

- lib/Alchemy/Phrasea/Command/BuildSubdefs.php
- option --min_record is now --min_record_id
- option --max_record is now --max_record_id
- PHRAS-1293: no more subdefs ignored when mode=scheduled
- options --maxrecs, --maxduration, --ttl
> PHRAS-1293_CLI-BUILD-SUBDEFS-RECORDS-IGNORED

- Makefile
- lib/Alchemy/Phrasea/Command/BuildSubdefs.php
- lib/Alchemy/Phrasea/Filesystem/FilesystemService.php
> Port PHRAS-1292 in master

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/StringFieldMapping.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- PHRAS-1300: search with the beginning of a word, ex. car finds car, carousel, caramel...
"car" (with quotes) only searches "car"
> PHRAS-1300_TRONCATURE_4.0

- lib/Alchemy/Phrasea/Application.php
> Fix session storage initialization

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/MappingBuilder.php
fix: files > 2Go can now be indexed  ('size' mapping is now type:long)
- PHRAS-1303: files > 2Go can now be indexed  ('size' mapping is now type:long)
> PHRAS-1303_BIG-FILES

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/StringFieldMapping.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContextFactory.php
- lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- templates/web/prod/index.html.twig
- tests/Alchemy/Tests/Phrasea/SearchEngine/Search/QueryContextTest.php
- PHRAS-1300 : add truncated search.
- prod : checkbox in advsearch
- api : add "truncation=1" as url parameter
> PHRAS-1300_TRONCATURE_FULL-4.0

- lib/Alchemy/Phrasea/Command/Plugin/AddPlugin.php
- lib/Alchemy/Phrasea/Plugin/Management/ComposerInstaller.php
> Improve error messages when plugin installation fails

- resources/ansible/playbook.yml
- resources/ansible/roles/nginx/templates/default.j2
- resources/ansible/roles/php/tasks/main.yml
- resources/ansible/roles/swftools/tasks/main.yml
- resources/ansible/vars/all.yml
- PHRAS-1257 Add compilation of swftools  and update php dependencies in provisionning
> Add compilation of swftools and update php dependencies

- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php
- tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php
- PHRAS-1300: fix tests
- code separation localize/truncation
- new test : truncation
> PHRAS-1300_TRONCATURE_FULL, fix tests

- grammar/query.pp
- tests/Alchemy/Tests/Phrasea/SearchEngine/resources/queries.csv
> Add missing spaces tokens in group declaration

- circle.yml
- PHRAS-1314: bump php version to 5.5.31
> PHRAS-1314_CIRCLECI-FAILS_4.0

- lib/classes/set/export.php
- lib/classes/unicode.php
- PHRAS-1205: export filenames are fixed (no more double extension, replace blank by '_', doubles are numbered with '#', ...)
> PHRAS_1205-DOUBLE-EXTENSIONS

- lib/classes/record/adapter.php
- PHRAS-1312: User rights were not fully enforced when loading stories containing records in collections that are not accessible to the current user
> PHRAS-1312 Fetch story children with user filter to enforce ACLs

- resources/ansible/roles/php/tasks/main.yml
- resources/ansible/roles/php/tasks/pecl.yml
- resources/ansible/vars/all.yml
> Fix vagrant provisioning

- lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
> PHRAS-510 Order by display index when retrieving story records

- .travis.yml
- circle.yml
- lib/Alchemy/Phrasea/Command/Setup/Install.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
- tests/Alchemy/Tests/Phrasea/Command/CheckConfigTest.php
- tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
- tests/bootstrap.sh
- PHRAS-1243 Add command line parameters for search engine settings in install command
- PHRAS-1244 Add interactive configuration steps for search engine settings in install command
> Add ElasticSearch settings to setup

- resources/ansible/roles/app/tasks/main.yml
- resources/ansible/roles/node/tasks/main.yml
- resources/ansible/vars/all.yml
> Improve application configuration playbook

- lib/Alchemy/Phrasea/Controller/SetupController.php
- resources/www/setup/styles/main.scss
- templates/web/setup/step2.html.twig
- tests/Alchemy/Tests/Phrasea/Controller/SetupTest.php
> Add an elastic step on web installer

- lib/classes/record/adapter.php
- PHRAS-1323: record->get_grouping_parents() crashed with no user authentified
> PHRAS-1323

- lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/BulkOperation.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/TitleHydrator.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- PHRAS-1327: ES crashed when indexing fields containing the NUL character.
> PHRAS-1327_ES_INDEX_NUL

- package.json
- PHRAS-1304: bump lib  "Phraseanet-production-client" to 0.20.0
> PHRAS-1304_AUTO-COMPLETION_MASTER_2

- lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-1344: fix missing extension on uploaded doc with api/record/add
> PHRAS-1344_API-RECORD-ADD-EXTENSION

- circle.yml
- package.json
- Bump lib Phraseanet-production-client to 0.19.24 (fixed jquery-ui dependency)
> PHRAS-1304_BUMP-PROD-LIB

- lib/Alchemy/Phrasea/Controller/AbstractDelivery.php
- PHRAS-1343: allow to specify a filename on permalink usage
> PHRAS-1343_DEFINE-FILENAME-AT-DONWNLOAD

- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- lib/classes/databox.php
- PHRAS-60: if a "\_TRASH\_" collection exists, "delete" action moves items to this coll.
Deleting a record already in "\_TRASH\_" collection deletes it for real.
> PHRAS-60_APPLICATIVE-TRASH

- lib/Alchemy/Phrasea/Controller/Root/Account.php
- PHRAS-1320: added event which sends email to admin when user asks for registration.
> PHRAS-1320_MAIL-INSCRIPT_3.8

- Vagrantfile
- resources/ansible/inventories/dev
- resources/ansible/roles/mariadb/tasks/main.yml
- resources/ansible/windows.sh
- resources/www/_shared/styles/main.scss
- resources/www/common/js/jquery.tooltip.js
- resources/www/lightbox/styles/main.scss
- resources/www/prod/js/record.editor.js
- templates/web/common/thumbnail.html.twig
- PHRAS-1280: PDF preview not rendered properly in editing mode. Fixed layout of preview
- PHRAS-1313: PDF preview is cropped in Lightbox . Fixed layout of preview in Lightbox and adjusted offset on tooltip view.
> Fix for PHRAS-1280 and PHRAS-1313

- bower.json
- composer.json
- Update version of alchemy-embed-medias to 0.3.4 in bower.json
> update version of alchemy-embed-medias to 0.3.4

- resources/www/prod/js/jquery.main-prod.js
- PHRAS-1367: Store keywords in sessionStorage when searching in prod
> Store keywords used in prod search bar in sessionStorage

- lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
- lib/Alchemy/Phrasea/Helper/Prod.php
- templates/web/admin/collection/reorder.html.twig
- templates/web/prod/index.html.twig
- PHRAS-1338 Order collections by name in prod search
> PHRAS-1338 Order collections by name in prod search

- lib/Alchemy/Phrasea/Controller/Admin/DashboardController.php
- lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php
- lib/Alchemy/Phrasea/ControllerProvider/Admin/Dashboard.php
- resources/locales/messages.ar.xlf
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.es.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- templates/web/admin/dashboard.html.twig
- tests/Alchemy/Tests/Phrasea/Controller/Admin/AdminDashboardTest.php
- PHRAS-1362: Add purge thumbnail and backup
user Daheda = user yannick-esokia
> PHRAS-1362_Purge-Thumbnails_4.0

- lib/classes/cache/databox.php
removing \n into SQL requests causing memcached content deletion issues.
> PHRAS-1359_remove_back_slash_n

- lib/classes/User/Query.php
- PHRAS-1386: guest users are now not displayed in list
> PHRAS-1386_Hide-guest-accounts-in-user-list_4.0

- lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
- lib/Alchemy/Phrasea/Helper/Prod.php
- templates/web/prod/index.html.twig
- PHRAS-1338 Add asc and desc options for alphabetic sort
> PHRAS-1338 Add asc and desc options for alphabetic sort

- resources/ansible/roles/mariadb/tasks/main.yml
- resources/ansible/windows-always.sh
- resources/ansible/windows.sh
- Update Vagrant provisionning. fix mariaDB vars names, fix windows.sh paths.
> Update Vagrant provisionning (4.0)

- templates/web/admin/collection/reorder.html.twig
- PHRAS-1371 Increase form width
> Increase form width

- composer.json
- composer.lock
- config/configuration.sample.yml
- lib/Alchemy/Phrasea/Core/MetaProvider/MediaUtilitiesMetaServiceProvider.php
- PHRAS-1377: add timeout to reader and writer, set in configuration file :
main / binaries / exiftool_timeout (default 60 sec)
nb : need alchemy/phpexiftool 0.7.0, run composer update
> PHRAS-1377_EXIFTOOLS-TIMEOUT-60

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/actions/edit_default.html.twig
- PHRAS-1280: Add text when preview window is empty in edit mode
> PHRAS-1280 - Add text when preview window is empty

- lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php
lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php
- PHRAS-1381_Applicative_trash_Reactivate_Permalink
> PHRAS-1381_Applicative_trash_Reactivate_Permalink

- lib/classes/module/console/fieldsRename.php
-  lib/classes/module/console/fieldsRename.php
- PHRAS-1349_bin_console_fields_rename
> PHRAS-1349_bin_console_fields_rename

- lib/Alchemy/Phrasea/Controller/Admin/SetupController.php
- lib/Alchemy/Phrasea/Controller/Admin/SetupController.php
- PHRAS-1390_Admin_setup_action_save
- Form initialisation with data
> PHRAS-1390_Admin_setup_action_save

- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php
- PHRAS-1353: fix fieldname when filtering on a business date field
- removed empty log message
> PHRAS-1353_BUSINESS-DATE-FIELD

- templates/web/admin/dashboard.html.twig
- templates/web/admin/dashboard.html.twig
- PHRAS-1383_Admin_dashboard_clean_thumbnails_cache
- Front implementation : changed position
> PHRAS-1383_Admin_dashboard_clean_thumbnails_cache

- resources/www/prod/skins/ui-components/_answers-tools.scss
- resources/www/prod/skins/ui-components/_answers.scss
- resources/www/prod/skins/ui-components/_answers-tools.scss
-  resources/www/prod/skins/ui-components/_answers.scss
- PHRAS-1370: Fixed layout of PROD to be able to scroll on side menu
> PHRAS-1370 PROD: Fixed bug on scroll-bar

- resources/www/common/js/jquery.tooltip.js
- resources/www/prod/js/jquery.main-prod.js
- resources/www/prod/styles/main.scss
-  resources/www/common/js/jquery.tooltip.js
- resources/www/prod/js/jquery.main-prod.js
- resources/www/prod/styles/main.scss
- PHRAS-1392: Modified layout of caption to adjust to screen height and add fix positioning to caption window
> Phras-1392 rollover graphic bug

- lib/Alchemy/Phrasea/Controller/Admin/SearchEngineController.php
- lib/Alchemy/Phrasea/Controller/Admin/SearchEngineController.php
- PHRAS-1378_Bin_console_add_max_result_window_parameter
- Bug Result window is too large
> PHRAS-1378_Bin_console_add_max_result_window_parameter

- templates/web/admin/users.html.twig
- templates/web/admin/users.html.twig
- PHRAS-1399: Admin - Refactor users's table to add sorting in asc and desc
> Phras-1399 admin-order user list

- templates/web/prod/index.html.twig
- PHRAS-1338 Add twig translator on configuration wordings
> Order collections by name in prod search

- resources/www/admin/styles/main.scss
- Add margin and align arrows on order collection buttons.
- Activate highlight on Search engine tab is now vertical aligned
- Add Italic and adjust left margin on every labels on setup form
> Update admin style

- lib/classes/set/export.php
- PHRAS-1350: set export timeout to 0 (no timeout)
> PHRAS-1350_EXPORT-TIMEOUT-100_4.0

- templates/mobile/api/auth/end_user_authorization.html.twig
- templates/web/api/auth/end_user_authorization.html.twig
- PHRAS-1366 Fix wrong function name to display app name on Oauth login.
> Fix wrong function name to display app name on Oauth login

- lib/Alchemy/Phrasea/Controller/Root/AccountController.php
- PHRAS-1320: added event which sends mail.
> PHRAS-1320_MAIL-INSCRIPT_4.0

- lib/Alchemy/Phrasea/Account/CollectionRequestMapper.php
- lib/Alchemy/Phrasea/Authentication/RegistrationService.php
- lib/Alchemy/Phrasea/Core/Configuration/RegistrationManager.php
- lib/Alchemy/Phrasea/Form/Login/PhraseaRegisterForm.php
- lib/Alchemy/Phrasea/Model/Repositories/RegistrationRepository.php
- lib/classes/collection.php
- templates/web/account/access.html.twig
- tests/Alchemy/Tests/Phrasea/Core/Configuration/RegistrationManagerTest.php
- PHRAS-1342: Refacto of registration, registrable databox are listed.
- new text strings
> PHRAS-1342_CANINSCRIPT

- lib/Alchemy/Phrasea/Core/Configuration/RegistrationManager.php
- resources/www/account/styles/_skin.scss
- templates/web/account/access.html.twig
- tests/Alchemy/Tests/Phrasea/Core/Configuration/RegistrationManagerTest.php
- PHRAS-1407 
- Replace wrong status : 'out-dated' expected 'out-time' given on Registration manager.
- Replace table style.
- Add odd/even style on access list
- Add toggle on database title box.
> Update access page design

- resources/www/account/styles/_skin.scss
- www/scripts/apps/login/home/common.js
- Remove unwanted html tags on register form collections multiselect
> Remove unwanted html tags on register form collections multiselect

- resources/www/prod/skins/000000/skin-000000.scss
- resources/www/prod/skins/959595/skin-959595.scss
- resources/www/prod/skins/FFFFFF/skin-FFFFFF.scss
- resources/www/prod/skins/skin-shared.scss
- resources/www/prod/skins/ui-components/_context-menu.scss
- resources/www/prod/skins/ui-components/_jquery-ui.scss
- resources/www/prod/skins/ui-components/_modal-push.scss
-PHRAS-879 - modify css styling for white theme
> PHRAS-879-Prod_skin_white

- resources/www/admin/styles/main.scss
- templates/web/admin/users.html.twig
- Changed position of modify and delete button
- PHRAS-1400: Add function to navigate user list by entering page number
> PHRAS-1400 page navigation

- lib/classes/User/Query.php
fix error 500 on push and validation list management
- fix error 500 on push and validation list management
- PHRAS-1409: error 500 on push and validation list management
- error 500 on push and validation list management
> PHRAS-1409_fix-push-list-management-error-500

- lib/Alchemy/Phrasea/Helper/Prod.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- templates/web/prod/index.html.twig
- advanced search : "sortable" fields are grouped by type (string, date, number) and alpha sorted
> PHRAS-1425_ADVSRCH-SORT-POPUP_4.0

- resources/www/prod/js/jquery.main-prod.js
- resources/www/prod/styles/main.scss
- templates/web/prod/index.html.twig
- PHRAS-1415: Add checkbox in advance search to enable or disable facets with single item
> PHRAS-1415 hide facet

- resources/www/prod/js/jquery.main-prod.js
- PHRAS-1415 - refactored PHRAS-1415 to handle facet view containing search item
> PHRAS-1415 hide facet function refactored

- resources/www/prod/skins/ui-components/_answers-tools.scss
- PHRAS-1309 - Fix size of icons in toolbar to override width:auto in IE10
> PHRAS-1309 - fix bug on toolbar in IE10

- resources/www/prod/skins/skin-shared.scss
- PHRAS-1370: Update width of scrollbar on browser using webkit
> PHRAS-1370 scrollbar update width on webkit

- templates/web/developers/applications.html.twig
- PHRAS-1414 - Update link to API documentation in My account/Developer
> PHRAS-1414 update link to api doc

- resources/www/common/js/jquery.tooltip.js
- PHRAS-1392: Apply fix positioning when clicking on thumbnail in "graphiste" mode
> PHRAS-1392 apply fix positioning graphiste mode

- resources/www/common/js/jquery.common.js
- templates/web/admin/editusers_timelimit.html.twig
- templates/web/admin/editusers_timelimit_sbas.html.twig
- PHRAS-1339: Apply localisation to datepicker
> PHRAS-1339 - localisation in datepicker

- resources/www/lightbox/styles/main.scss
- PHRAS-1384: refactor styling of image preview in lightbox/basket view
> PHRAS-1384 refactor presentation basket

- templates/web/common/menubar.html.twig
- templates/web/setup/step2.html.twig
- PHRAS-1433: update link to documentation version 4.0 in menubar and admin
> PHRAS-1433 update link in navigation bar

- resources/www/prod/js/jquery.main-prod.js
- resources/www/prod/skins/ui-components/_answers.scss
- PHRAS-732: refactor calculation and styling for grid display layout on PROD
> PHRAS-732 refactor calculation for grid display

- resources/www/common/js/jquery.tooltip.js
- PHRAS-1373: increase width of notice's popup when hovering or alt-clicking
> PHRAS-1373 refactor presentation of notice on hover

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/preview/basket_train.html.twig
- templates/web/prod/preview/feed_train.html.twig
- templates/web/prod/preview/reg_train.html.twig
- templates/web/prod/preview/result_train.html.twig
- PHRAS-1434: refactor layout containing action buttons and slideshow buttons
> PHRAS-1434 refactor location of action buttons

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/index.html.twig
- PHRAS-1436 - refactor layout of detail view
> PHRAS-1436 align layout detail view

- resources/www/lightbox/styles/main-ie6.scss
- resources/www/lightbox/styles/main.scss
- resources/www/prod/skins/ui-components/_diapo.scss
- PHRAS-1437: refactored thumbnail layout on lightbox and basket view in side bar
> PHRAS-1437 refactor thumbnail layout

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
> Refreshing translation files

- resources/www/prod/skins/skin-shared.scss
- PHRAS-1441: update width of webkit scrollbar from 10px to 8px
> PHRAS-1441 update width of webkit scrollbar

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/index.html.twig
- PHRAS-1415: add invisible buttons on preview object in detail view to allow slide show navigation
> PHRAS-1435 navigation on preview object

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- PHRAS-1396 PHRAS-1397 - update string with weblate command
> update locales weblate

- resources/www/prod/skins/skin-shared.scss
- PHRAS-1397: fix icon size on order detail view
> PHRAS-1397 fix icon size

- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- lib/classes/databox.php
- tests/Alchemy/Tests/Phrasea/Controller/Admin/DataboxTest.php
- tests/classes/databoxTest.php
- databox->get_label(lng) returns label if it is set, else viewname if it is set, else db_name
- PHRAS-1446: RecordController->getRecord() now contains "databox_label"
> PHRAS-1446_DATABOX-LABEL-IN-RECORD_4.0

- lib/Alchemy/Phrasea/Command/SearchEngine/IndexManipulateCommand.php
- bin/console searchengine:index:manipulate is renamed to searchengine:index
> PHRAS-1447_RENAME-CMD-s.i.m_4.0 to upstream/4.0

- lib/Alchemy/Phrasea/Controller/Prod/ExportController.php
- PHRAS-1426: Replaces redundancy separator
> PHRAS-1426_fix_export_email

- resources/www/prod/js/jquery.p4.preview.js
- PHRAS-1442: refactor title to use databox_label instead of databox_name
> PHRAS-1442 refactor title to use databox_label

- templates/web/prod/thesaurus.js.twig
- PHRAS-1445: filter candidates alphabetically
> PHRAS-1445 sort candidates in alphabetical order

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- templates/web/prod/orders/order_box.html.twig
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1448 - update source to english and clean .xlf files
> PHRAS-1448 clean strings of locale

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/prod/orders/order_box.html.twig
- PHRAS-1444: dump strings for translation using weblate
> PHRAS-1444 export locales bdc

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1450: make validated item clickable for preview. 
- Remove unnecessary codes and css classes
- Refactored shift-clicking function to allow selection from bottom-to-top and fix bug
> PHRAS-1450 item selectable after validation

- resources/www/prod/skins/skin-shared.scss
- PHRAS-1452: add max-width to preview layout in order view
> PHRAS-1452 optimise space

- resources/www/common/js/jquery.tooltip.js
- templates/web/prod/WorkZone/Browser/Basket.html.twig
- PHRAS-1453 - fix width for basket view when hovering and fix positioning when view is outside of screen
> PHRAS-1453 basket roll over

- lib/classes/User/Query.php
- fix error 500 on push and validation list management
- PHRAS-1409: error 500 on push and validation list management
- fix error 500 on push and validation list management
> PHRAS-1409_fix-push-list-management-error-500_master

- templates/web/prod/orders/order_item.html.twig
- PHRAS-1458: pass special characters in mailto parameters and refactor sendMail function
> PHRAS-1458 fix sendMail function in order view

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_box.html.twig
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1450: hide/disable button to send document based on document status
- trigger submit when filtering by week and month
- fix: opening new window when using mailto
> PHRAS-1450 disable buttons for validate item

- lib/Alchemy/Phrasea/Controller/Prod/BasketController.php
- PHRAS-1337: saving description of basket when creating one
> PHRAS-1337 fix saving description

- resources/www/prod/skins/skin-shared.scss
- resources/www/prod/skins/ui-components/_modal-preview.scss
- templates/web/prod/index.html.twig
- templates/web/prod/preview/basket_train.html.twig
- templates/web/prod/preview/caption.html.twig
- templates/web/prod/preview/feed_train.html.twig
- templates/web/prod/preview/reg_train.html.twig
- templates/web/prod/preview/result_train.html.twig
- templates/web/prod/preview/result_train_options.html.twig
- PHRAS-1434: update diaporama layout to optimise spaces and size of icons
> PHRAS-1434 update layout diaporama

- lib/Alchemy/Phrasea/Cache/WinCacheCache.php
- lib/Alchemy/Phrasea/TaskManager/LiveInformation.php
- resources/www/account/styles/_skin.scss
- resources/www/admin/styles/main.scss
- templates/web/account/access.html.twig
- PHRAS-1407 Update access page wording and fix JMS extract (translation dump)
> Update wording and fix JMS extract

- lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- templates/web/admin/subdefs.html.twig
- Data structure has changed, JS updated to get values
> Data structure has changed, JS updated to get values

- templates/web/admin/subdefs.html.twig
- Remove errors on subdef page.
> Remove errors on subdef page

- lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- lib/classes/databox/subdefsStructure.php
- PHRAS-1469, Fix travis build with updating patches
> Fix travis build with updating patches

- lib/Alchemy/Phrasea/Command/SearchEngine/IndexCreateCommand.php
- lib/Alchemy/Phrasea/Command/SearchEngine/IndexDropCommand.php
- lib/Alchemy/Phrasea/Command/SearchEngine/IndexPopulateCommand.php
- PHRAS-1449: Add comment
- Add comment for deprecated command
> Add comment for deprecated command

- resources/www/common/js/jquery.tooltip.js
- fix bug on positioning captions
> fix bug on positioning captions

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
- lib/classes/databox.php
- PHRAS-1439 : quick (dirty...) fix to force candidates refresh
> PHRAS-1439 thesaurus candidates bump 4.0

- templates/web/prod/orders/order_item.html.twig
- PHRAS-1471: Fix bug on firefox for jquery dialog
> PHRAS-1471 bug validation window firefox

- lib/Alchemy/Phrasea/Model/Repositories/OrderRepository.php
- lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
- templates/web/prod/orders/order_box.html.twig
- PHRAS-1474: fix pagination on order list
- fix bug starting date of current week
- refactored code in orderRepository to get total count of orders
- refactored code in order_box.html.twig
> PHRAS-1474 fix pagination order list

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
- lib/classes/databox.php
Reverts alchemy-fr/Phraseanet#2185
> Revert "PHRAS-1439 thesaurus candidates bump 4.0"

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1306: add functionality for creating basket from selected/validated/denied items in an order
> PHRAS-1306 create basket from order

- lib/Alchemy/Phrasea/Command/SearchEngine/IndexManipulateCommand.php
- PHRAS-1476: bin/console searchengine:index -d
- Add option force during drop command
> PHRAS 1476 - add force option to drop command

- templates/web/prod/tab_thesaurus.html.twig
- templates/web/prod/thesaurus.js.twig
- PHRAS-1464: refactor layout thesaurus tab to display scrollbar
> PHRAS-1464 missing scrollbar thesaurus tab

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
- lib/classes/databox.php
- PHRAS-1349: various pbs when manipulating candidates
(remake of PHRAS-1439_Thesaurus-Candidates-Bump_4.0 reverted due to bug)
> PHRAS-1439_Thesaurus-Candidates-Bump-2_4.0

- lib/Alchemy/Phrasea/Controller/Prod/ExportController.php
- PHRAS-1465: fix error for list of list of emails containing spaces and comma
> fix error for list of emails containing spaces and comma

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1479: display order id in order detail view section
> PHRAS-1479 add order id to order detail view

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1480: add text when document is already validated to preview
> PHRAS-1480 add text when document is already validated

- lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
- lib/classes/databox.php
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1481: add title to order usage paragraph
> PHRAS-1481 add title order usage

- lib/Alchemy/Phrasea/Model/Entities/Order.php
- lib/Alchemy/Phrasea/Model/Repositories/OrderRepository.php
- lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_box.html.twig
- PHRAS-1478: do not apply filter by default when viewing list of orders
> PHRAS-1478 refactor filter order list

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/prod/orders/order_box.html.twig
- PHRAS-1485: add column with order id in order list
> PHRAS-1485 add column with order id

- lib/classes/databox/field.php
- PHRAS-1295: attribut business ignored into database model
- Check if business field before set thumbtitle
> PHRAS-1295 attribut business ignored into model

- resources/www/prod/skins/ui-components/_workzone-thesaurus.scss
- templates/web/prod/tab_thesaurus.html.twig
- templates/web/prod/thesaurus.js.twig
- PHRAS-XXX: fix top margin after candidate validation.
- Fix styling and add button icon to cancel button
> PHRAS-1482 fix top margin after candidate validation

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-XXX: refactor code to add multiple selection
- display status of items in detail view
> PHRAS-1491 refactor for multiple selection

- lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
- lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Xmlhttp.php
- templates/web/prod/tab_thesaurus.html.twig
- templates/web/prod/thesaurus.js.twig
- PHRAS-1483: add search feature to candidate tab
- refactor searchTermJson() to handle search for thesaurus and candidate
> PHRAS-1483 add search to candidate tab

- templates/web/prod/thesaurus.js.twig
- PHRAS-1492: sort candidates aphabetically after accepting terms in Prod/Thesaurus
> PHRAS-1492 sort candidates alphabetically after accepting terms

- templates/web/thesaurus/load-thesaurus.html.twig
- PHRAS-1487: fix label on tab in Thesaurus
> PHRAS-1487 fix label thesaurus tab

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/common/index_bootstrap.html.twig
- templates/web/prod/preview/popularity.html.twig
- PHRAS-1475: rafactor code to add new google chart API for creating charts
> PHRAS-1475 refacto google chart

- lib/classes/record/preview.php
- templates/web/prod/preview/popularity.html.twig
- PHRAS-1486: new method to return record statistics
- todo : front render to replace obsolete google charts.
> PHRAS-1486_Refacto-Charts-Urls-to-client_4.0

- Vagrantfile
- PHRAS-1495: fix unknown "ip" command
> PHRAS-1495_MACOS-PROVISIONING-IP

- resources/www/prod/skins/ui-components/_workzone-thesaurus.scss
- PHRAS-1496: improve UX on thesaurus section in side menu
> PHRAS-1496 UX improvement thesaurus tabs

- templates/web/prod/actions/edit_default.html.twig
- PHRAS-1501: Fix dimension of preview in editing mode
> PHRAS-1501 fix dimension of preview in editing mode

- resources/www/prod/js/jquery.WorkZone.js
- PHRAS-1369: Desynchronization thumbnail / image of choice preview to the deletion of a media
-  Refresh the current selection after delete
> PHRAS-1369 detail view of a basket 

- resources/www/_shared/styles/jquery-ui/_shared.scss
- templates/web/common/dialog_export.html.twig
- Phras-1411 add a loading overlay when sending medias by email
> Phras-1411_add_loading_overlay

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1493: remplace description with intent of usage
- disable button for creating basket based on selection if no item is selected
> PHRAS-1493 put usage intent basket description

- templates/web/prod/thesaurus.js.twig
- PHRAS-1533: cancel accept candidate in prod
- Add button cancel to back normal mode
> PHRAS-1533 cancel accept candidate in prod

- package.json
- PHRAS-1537: update dependencies
> PHRAS-1537 update gulp-sass and bower

- package.json
- resources/www/admin/styles/main.scss
- templates/web/admin/users.html.twig
- PHRAS-1503: porting PHRAS-1400 to master
> PHRAS-1503 port PHRAS-1400

- package.json
- templates/web/admin/databox/databox.html.twig
- PHRAS-1504: porting PHRAS-392 to master
> PHRAS-1504 port PHRAS-392

- package.json
- resources/www/admin/styles/main.scss
- templates/web/admin/users.html.twig
- PHRAS-1505: porting PHRAS-1399 to master
> PHRAS-1505 port PHRAS-1399

- config/configuration.sample.yml
- lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
- lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
- lib/classes/set/export.php
- templates/web/common/dialog_export.html.twig
- PHRAS-424: ability to stamper or not an export document
- Add option delete stamp
> PHRAS-424 ability to stamper or not an export document

- lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
- lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- resources/www/prod/js/jquery.main-prod.js
- templates/web/prod/actions/delete_records_confirm.html.twig
- PHRAS-1354: define warning message when deleting a record based on type of deletion
> PHRAS-1354 define warning message based on type of deletion

- lib/Alchemy/Phrasea/Command/Plugin/AddPlugin.php
- lib/Alchemy/Phrasea/Command/Plugin/ListPlugin.php
- lib/Alchemy/Phrasea/Command/Plugin/RemovePlugin.php
- PHRAS-1546: add deprecated to plugins command
- add deprecated message to plugins command add/remove/list
> PHRAS-1546 add deprecated to plugins command

- templates/web/prod/orders/order_item.html.twig
- PHRAS-1490: add alert close overlay
> PHRAS-1490 add alert close overlay

- templates/web/prod/index.html.twig
- PHRAS-1542: saving truncation status to userSettings
> PHRAS-1542 save pref truncation

- templates/web/setup/step2.html.twig
- PHRAS-1297:  Links to the prerequisites
- Change link for prerequisites and configuration
> PHRAS-1297- Links to the prerequisites

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1549: add scrollbar to table in order details
> PHRAS-1549 add scrollbar table

- resources/www/common/js/jquery.tooltip.js
- PHRAS-1548: fix dimension of tooltip when hovering over a basket in the workzone
> PHRAS-1548 basket dimension

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1549: change style on validation button based on status and add scrollbar to item list
> PHRAS-1549_layout_with_scrollbar

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1551: improve UX order item
> PHRAS-1551 improve UX order item

- templates/web/prod/orders/order_item.html.twig
- PHRAS-1551: keep preview when cancelling a item for validation
> PHRAS-1551_improve_ux_order_item

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1551: refactored cancellation of items waiting for validation
> PHRAS-1551 improve UX order item and refactored cancellation

- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/orders/order_item.html.twig
- PHRAS-1552: fix bottom margin on order item page
> PHRAS-1552 fix bottom margin order item

- templates/web/common/dialog_export.html.twig
- PHRAS-1556: extend deactivation of the stamp 
-  Add possibiltity to stamp subdef indexed like document
> PHRAS-1556 extend deactivation of the stamp

- lib/Alchemy/Phrasea/Form/Configuration/GeneralFormType.php
- templates/web/login/index.html.twig
- PHRAS-1558: slideshow of the login page
- Remove Cooliris option in slideshow options
> PHRAS-1558 slideshow of the login page

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
> PHRAS-1319 dump locale

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
Reverts alchemy-fr/Phraseanet#2259
> Revert "PHRAS-1319 dump locale"

- circle.yml
- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
> PHRAS-1319 redump locale

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/prod/results/help.html.twig
- PHRAS-1319: add translation for search_tips placeholder
> PHRAS-1319 add translation search tips

- circle.yml
- lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php
- lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
- merge PHRAS-1559 and PHRAS-1560 - fixing order of collections
> PHRAS-1559 and PHRAS-1560 merge

- resources/www/_shared/styles/_main-menu.scss
- resources/www/admin/styles/_databases.scss
- resources/www/admin/styles/_tables.scss
- resources/www/admin/styles/main.scss
- templates/web/admin/collection/collection.html.twig
- templates/web/admin/dashboard.html.twig
- templates/web/admin/databox/cgus.html.twig
- templates/web/admin/publications/fiche.html.twig
- templates/web/admin/publications/list.html.twig
- templates/web/admin/setup.html.twig
- templates/web/admin/users.html.twig
- PHRAS-1555: refactor styling of admin screens
> PHRAS-1555 refacto admin

- templates/web/admin/fields/templates.html.twig
- PHRAS-1568: change color of save all button to blue
> PHRAS-1568 admin change button color

- templates/web/prod/upload/upload-flash.html.twig
- templates/web/prod/upload/upload.html.twig
- PHRAS-1301: save last used collection in upload dialog
> PHRAS-1301 store last collection

- lib/Alchemy/Phrasea/Controller/Admin/SearchEngineController.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
- resources/www/admin/styles/main.scss
- templates/web/admin/search-engine/elastic-search.html.twig
- templates/web/admin/search-engine/search-engine-settings.html.twig
- PHRAS-1578: add tab navigation and style elastic search content
> PHRAS-1578 admin search engine settings step 1

- templates/web/prod/WorkZone/Basket.html.twig
- templates/web/prod/WorkZone/Story.html.twig
- templates/web/prod/toolbar.html.twig
- PHRAS-1577: comment all buttons with bridge feature
> PHRAS-1577 hide bridge buttons

- templates/web/prod/actions/delete_records_confirm.html.twig
- PHRAS-1588: fix error in string
> PHRAS-1588 error in string

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- PHRAS-1589: dump locales for newly created string
> PHRAS-1589 dump locales

- templates/web/admin/editusers.html.twig
- PHRAS-1167: add max-height to main area - edituser - admin
> PHRAS-1167 fix height user detail admin

- lib/classes/databox/cgu.php
- PHRAS-1176: fix variable name - terms of use
> PHRAS-1176 fix variable name tou

- lib/Alchemy/Phrasea/Controller/Prod/ShareController.php
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- PHRAS-165: prod/share : propose multiple permalinks
> PHRAS-165 multiple share permalinks 4.0

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/prod/skins/skin-shared.scss
- templates/web/prod/Share/record.html.twig
- PHRAS-1595: add selection for sub definition
> PHRAS-1595 add selection sub def

- templates/web/common/menubar.html.twig
- PHRAS-1591: Add link to visualise gitlog
> PHRAS-1591 add link gitlog

- templates/web/prod/toolbar.html.twig
- PHRAS-1577: remove bridge button in toolbar
> PHRAS-1577 mask bridge

- templates/web/prod/preview/popularity.html.twig
- PHRAS-1574: remove zero values from pie chart
> PHRAS-1574 remove zero values google chart

- lib/classes/User/Query.php
- templates/web/prod/actions/Feedback/ListsMacros.html.twig
- templates/web/prod/actions/Feedback/list.html.twig
- PHRAS-1468: Push List manager : Filter search
- Fix filter by country, job, activity,enterprise
> PHRAS-1468 Push List manager filter search

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- resources/www/admin/styles/main.scss
- templates/web/admin/search-engine/general-aggregation.html.twig
- templates/web/admin/search-engine/search-engine-settings.html.twig
- PHRAS-1579: add layout for general aggregation
> PHRAS-1579 add layout general aggregation

- tests/Alchemy/Tests/Phrasea/Controller/Prod/ShareTest.php
> PHRAS-165_share-permalinks-unittests_4.0

- lib/Alchemy/Phrasea/ControllerProvider/Prod/Share.php
- PHRAS-1593: add firewall rules to route to match unit test
> PHRAS-1593_share-permalink-firewall_4.0

- .travis.yml
- PHRAS-1557: add zmq via pecl
> PHRAS-1557_Travis-zmq-bis_4.0

- templates/web/prod/Baskets/Reorder.html.twig
- PHRAS-179: More sorting options in the window order
- Add new filter by created/ updated date
> PHRAS-179-More sorting options in the window order

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- resources/locales/validators.de.xlf
- resources/locales/validators.en.xlf
- resources/locales/validators.fr.xlf
- resources/locales/validators.nl.xlf
- templates/web/prod/templates/push.html.twig
- PHRAS-1611: add string for feedback title
> PHRAS-1611 add string for feedback title

- resources/locales/messages.de.xlf
- resources/locales/messages.en.xlf
- resources/locales/messages.fr.xlf
- resources/locales/messages.nl.xlf
- templates/web/admin/search-engine/general-aggregation.html.twig
- PHRAS-1579: change string - document type
> PHRAS-1579 replace string

- lib/Alchemy/Phrasea/Controller/Admin/UserController.php
- PHRAS-1058 and PHRAS-1089: Flush all change on  user imported
> PHRAS-1089 and PHRAS-1058 Flush change on User imported

- resources/www/prod/skins/ui-components/_upload.scss
- templates/web/common/menubar.html.twig
- templates/web/prod/index.html.twig
- templates/web/prod/upload/upload-flash.html.twig
- templates/web/prod/upload/upload.html.twig
- PHRAS-1616: Add drag and drop feature + refactored layout for upload
> PHRAS-1616 add drag and drop feature and refactored layout

- lib/classes/User/Query.php
- templates/web/prod/actions/Feedback/list.html.twig
- PHRAS-1613: NOK on filter model in PUSH
- Fix users filter by model
> PHRAS-1613-NOK on filter model in PUSH

- lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- PHRAS-1336: aggregable technical fields are listed in one place, many fields hardcoded.
render is included in the symfony form.
> PHRAS-1336_setting-technical-aggregates_4.0

- .travis.yml
- PHRAS-1557: install zmb via pecl
> PHRAS-1557 travis zmq bis 4.0

- resources/www/common/js/jquery.tooltip.js
- resources/www/prod/skins/ui-components/_workzone-baskets.scss
- templates/web/prod/WorkZone/Macros.html.twig
- PHRAS-1372: Add notice for media on rollover in basket record
> PHRAS-1372 notice not available

- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
- resources/www/admin/styles/main.scss
- templates/web/admin/search-engine/elastic-search.html.twig
- templates/web/admin/search-engine/general-aggregation.html.twig
- templates/web/admin/search-engine/search-engine-settings.html.twig
- PHRAS-1621: PHRAS-1621_common_aggregats
> PHRAS-1621 common aggregats

- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
- lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
- templates/web/admin/search-engine/search-engine-settings.html.twig
- PHRAS-1621: add hidden field in symfony form to keep track of selected tab
> PHRAS-1621 add hidden field in symfony form to keep track of selected tab

- templates/web/prod/WorkZone/Macros.html.twig
- PHRAS-1622: Add fix positioning on notice in basket
> PHRAS-1622 add fix positioning notice

- resources/www/admin/styles/main.scss
- templates/web/admin/setup.html.twig
- templates/web/common/menubar.html.twig
- PHRAS-1571: include feature to add custom links in admin/setup
> PHRAS-1571 add custom link in admin

- lib/Alchemy/Phrasea/Command/Setup/Install.php
- lib/Alchemy/Phrasea/Controller/SetupController.php
- lib/Alchemy/Phrasea/Core/Configuration/StructureTemplate.php
- lib/Alchemy/Phrasea/Core/Provider/ConfigurationServiceProvider.php
- lib/Alchemy/Phrasea/Setup/Installer.php
- tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
- tests/Alchemy/Tests/Phrasea/Setup/InstallerTest.php
- PHRAS-1296: Install CLI/Graphic show all available  structures
- Get available template , add test
> PHRAS-1296 Install CLI/Graphic show all available  structures

- resources/www/prod/skins/ui-components/_context-menu.scss
- PHRAS-1614: revert outline style on dropdown - basket
> PHRAS-1614 revert outline dropdown
