templates/web/email-template.html.twig

#PHRAS-276 #time 45m
ajouter dans locales : "Ce lien est valable jusqu'au"
corriger dans locales/EN : "Pour gérer l'envoi d'email automatique, connectez-vous à %link%"

#PHRAS-276 #time 45m

---

lib/Alchemy/Phrasea/SearchEngine/Phrasea/PhraseaEngineQueryParser.php

#time 3h
could not find "echappées"  if stemming (fr) was checked because the qparser removed diacritics

fix #PHRAS-404

---

bin/console
lib/Alchemy/Phrasea/Command/SearchEngine/Debug/QuerySampleCommand.php
lib/Alchemy/Phrasea/Command/SearchEngine/MappingUpdateCommand.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php

- Index the full content of a record in a (private_)content_all field
- Handle all fields wide search as a special-case (drastically simplify
queries)
- QueryContext doesn't take all allowed fields anymore, but whether private
fields are allowed or not. Since private fields are namespaced, field level
restriction is not needed anymore.

Working cross-fields queries with multiple words (without operators)

---

grammar/query.pp
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/ContextAbleInterface.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Escaper.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
tests/Alchemy/Tests/Phrasea/SearchEngine/EscaperTest.php

Clicking on a facet value on the left pane now return the expected result count.
This commit implement a new "raw" matcher. It can be used like `r"some raw value"`. It operate on the the `.raw` multi-field and skips all analysis. Escaping `"` is supported by prepending a backslash `\"`. You can also escape the escaping character `\` by doubling it (`\\`).
Adds a new `ContextAbleInterface` to differenciate matcher supporting an optional context from those who can't.
Fixes an issue with `QueryContext::narrowToFields()` ignoring passed fields.

Strict facet matching

---

grammar/query.pp

Followup of #1347 
Fix mandatory escaping sequence in raw expressions (used in facets queries)

Strict facet matching (the return)

---

resources/vagrant/vms/phraseanet-php55-nginx/puphpet/puppet/manifest.pp

Since 3.8, index.php is no longer used for the API.

Use correct script for API location

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/classes/ACL.php

Adds accessible collection info to /me route in API.
The available collections are listed as follows:
```
collections: [{
databox_id: 1,
base_id: 1,
collection_id: 1,
rights: [
"actif"
]
}, {
databox_id: 1,
base_id: 2,
collection_id: 2,
rights: [
"actif"
]
}]
```

List collection rights in /me

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php

I use here SplObjectStorage::removeAllExcept() with an empty one since I didn't
found a simpler one step solution.

Empty indexer queues after flushing to index

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/AbstractTermNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TermNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryHelper.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/TextQueryHelper.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/RawNodeTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TermNodeTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php

Search with non numeric content will not hit number field (it breaks elasticsearch and is useless anyway)
- Rename QueryHelper::buildPrivateFieldQueries() to wrapPrivateFieldQuery().
- Signature changed too, the third parameter is dropped an QueryContext is replaced by an array of Field.
- Query builder closure is now passed an array of Field, not of index field names.
- Remove Field::toConceptPathIndexFieldArray() because method name was beyond understanding (and also because it wasn't needed anymore)
- Various AST node types have changed due to previous API changes
- Fix facets on non string fields (yeah, that was broken...)
- Fix raw query with "in" query (like those used in facets \o\)

Fix number field search

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Query.php

They lead to zero result instead of all results from elasticsearch.

Handle queries with invalid fields

---

lib/Alchemy/Phrasea/Out/Module/PDF.php

fix : the "print logo" (base) is back on pdf

#PHRAS-568 #time 3h

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php

fix: the field(s) selected in adv-search are applied to whole query.
nb : may return error message if query + filter is nonsense, ex:
Query="foo IN Title" + Filter="Keywords"

#PHRAS-230 #time 2h

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
lib/classes/databox/field.php
tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/FieldTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/StructureTest.php

- Single property for facet settings in Field, we can’t have a limit
with disabled faceting.
- Fixes bug when fields having incompatible limit but are still merged together.
- Use constants for special limit values (i.e. no limit)

Simpler facet handling in ES structure

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/AbstractTermNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryHelper.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TermNodeTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php

Concept queries on private fields where adding a « must » clause to
restrict match on certain collections only. Boolean queries do not
enforce one « should » clause match at least once a « must » clause is
added to it.
To make queries on private fields more robust & performants, these are
now wrapped in a filtered query with a collection filter.

Fix concept query builder & private field wrapping

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/SearchEngineInterface.php
templates/web/prod/index.html.twig
www/skins/prod/jquery.main-prod.js

fix: the default sort field/direction (defined as relevance/desc for es) is applied at startup & reset button.
add : default direction
todo in 4.0.1 : allow to change in config/admin ?

#PHRAS-669 #time 1d

---

lib/Alchemy/Phrasea/Command/BuildSubdefs.php

fix : console build-subdefs can build non existing subdefs, ex. after adding a new subdef name in admin.

#PHRAS-374 #time 10m

---

lib/Alchemy/Phrasea/Core/Provider/ManipulatorServiceProvider.php
lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
tests/Alchemy/Tests/Phrasea/Model/Manipulator/TokenManipulatorTest.php

When there are expired tokens in the database, the app crashes due to an undefined property error ($app in TokenManipulator) introduced a while ago.

Fix undefined property error

---

.travis.yml

ZeroMQ is not compatible with PHP7. Remove useless builds for PHP7 in `.travis.yml`

Remove PHP7

---

lib/Alchemy/Phrasea/Core/Configuration/AccessRestriction.php
lib/Alchemy/Phrasea/Core/Provider/ConfigurationServiceProvider.php
lib/classes/ACL.php
lib/classes/appbox.php
lib/classes/collection.php
tests/Alchemy/Tests/Phrasea/Core/Configuration/AccessRestrictionTest.php

Getting collection calls access_restriction which is not properly cached.
Remove use of cache in AccessRestriction and use instance memory cache instead.
Beware static keyword declares variable static for the class, not the instance

Avoid many calls to cache layer

---

lib/Alchemy/Phrasea/Core/Profiler/TraceableCache.php
templates-profiler/cache.html.twig

Aggregates repeated calls to reduce size of collected data. This prevents profiling issues when a page issues a lot of calls to the cache layer

Improve cache collector in heavy cache usage contexts

---

lib/Alchemy/Phrasea/Border/Manager.php
lib/Alchemy/Phrasea/Model/Entities/LazaretCheck.php
lib/classes/eventsmanager/notify/uploadquarantine.php

There are currently no ways to register 2 checkers of same type but applying them to a different set of collections/base. This remove the registering by checker type
PHRAS-957

Register checkers with similar type

---

.travis.yml

They are already run on CircleCI, so running them on Travis is redundant. This should also help reducing build times, and freeing up the queue faster for other builds.

Remove "install" tests from Travis suite

---

lib/Alchemy/Phrasea/Controller/Prod/Edit.php
lib/Alchemy/Phrasea/Core/PhraseaEvents.php
lib/Alchemy/Phrasea/SearchEngine/Phrasea/PhraseaEngine.php
lib/classes/media/subdef.php
lib/classes/record/adapter.php

#PHRAS-1008
-add : new event "StoryCoverChanged"
-fix : one "record edit" event when cover is changed (no more one event for both thumbnail and preview substitution)
-add : method to delete the cover of a story (goes back to "blue folder")
-add : "oldstatus" to StatusChanged event so client can detect what sb was modified.

Add story cover event

---

lib/Alchemy/Phrasea/TaskManager/Job/EmptyCollectionJob.php
tests/Alchemy/Tests/Phrasea/TaskManager/Job/EmptyCollectionJobTest.php

Could not refactor the job as there are static calls preventing mocks.

EmptyCollectionJob should accept bas_id setting.

---

lib/Alchemy/Phrasea/Core/Event/Subscriber/ContentNegotiationSubscriber.php

PHRAS-1060 #time 20m
-fix : no more error 406 when ie9 downloads css with header Accept=text/css

PHRAS-1060_CSS-IE9

---

lib/Alchemy/Phrasea/Command/BuildSubdefs.php
lib/classes/media/subdef.php
lib/classes/record/adapter.php

- no bug concerning --max_record
- add try/catch so the job don't stop on errors
PHRAS-1055 #time 5h
- add option --dry
- add verbose print (-v)
- add "ALL" for type and subdef arguments
- fix "substitute" options
- fix show sql with arguments
PHRAS-1055 #time 5h
- better error handling
- argument "databox" can be specified as id, dbname or viewname
- add option "--partition=n/N"
- argument "type" changed to option "--record_type=a,b,c" (can also be set as "--record_type=a,b --record_type=c")
- argument "subdefs" changed to option "--name=x,y,z" (can also be set as "--name=x,y --name=z")
- option "--with-substitution" changed to "--with_substituted"
- option "--substitution-only" changed to "--substituted-only"
PHRAS-1055 #time 2h
- change lone argument (databox) to option "--databox" …

PHRAS-1055 rebase on 4.0

---

lib/Alchemy/Phrasea/Model/Repositories/WebhookEventRepository.php
lib/Alchemy/Phrasea/TaskManager/Job/WebhookJob.php

- Deprecated `WebhookEventRepository::findUnprocessedEvents()`
- Prevents loading all unprocessed rows at once in the webhook job

Fix event processor memory usage

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping.php

- PHRAS-1072:  'ip' type to ES mapping builder so a 'ip' field can be created into ES logs
#time 15m

PHRAS-1072_Export-Logs-To-ES

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php

- PHRAS-1085: only take array_values when serializing element collection

Remove record ids in stories elements search API

---

lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php

- PHRAS-1091: Orders were created correctly but the API crashed when rendering the response due to the use of the order itself instead of the view

Fix 500 error response when creating an order via the API

---

lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php

- PHRAS-1091: Orders were created correctly but the API crashed when rendering the response due to the use of the order itself instead of the view

PHRAS-1091 Pass view instead of order to transformer

---

lib/Alchemy/Phrasea/Command/Compile/Configuration.php

- Fixes spelling error in compile configuration command

spelling error in Configuration.php

---

Vagrantfile

- It was no longer possible to spawn a new Vagrant VM (authentication errors due to hardcoded keys)

Let Vagrant generate its own private keys

---

lib/Alchemy/Phrasea/Core/Event/Subscriber/OrderSubscriber.php
lib/Alchemy/Phrasea/Order/ValidationNotifier/CompositeNotifier.php

- Order managers are not notified when orders are created via the API

Fix mail notification for order managers

---

lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php

- The access control condition for orders was negated, which prevented legitimate users from accessing their own orders

Fix access control condition

---

lib/Alchemy/Phrasea/Controller/Prod/PushController.php

- PHRAS-877: There are no authentication tokens on generated urls

URL in Push emails have no authentication tokens.

---

lib/Alchemy/Phrasea/Controller/PermalinkController.php
lib/classes/media/Permalink/Adapter.php

- PHRAS-1079: replace slashes in labels of permalinks by underscores

Slash in permalink labels

---

lib/Alchemy/Phrasea/Controller/Prod/DoDownloadController.php
lib/Alchemy/Phrasea/Databox/DataboxRepository.php
lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php

- Archives for orders were generated using a relative path which prevented them from being downloaded via the API

Fix archive path when downloading orders via API

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php
lib/conf.d/configuration.yml
resources/vagrant/config/phraseanet/configuration.yml

- Configuration key "api_require_ssl" can be set to false in "main" section of configuration.yml to disable the SSL requirement on the API auth routes. This setting should only be used for development purposes.

Add configuration option to disable SSL requirement on API

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Core/MetaProvider/HttpStackMetaProvider.php

- PHRAS-1180: It's now possible to enable CORS on custom paths via the "api_cors_paths" configuration node.

PHRAS-1180 Add configuration entry to enable CORS on custom paths

---

locale/ar_SA/LC_MESSAGES/phraseanet.po
locale/de_DE/LC_MESSAGES/phraseanet.po
locale/en_GB/LC_MESSAGES/phraseanet.po
locale/es_ES/LC_MESSAGES/phraseanet.po
locale/fr_FR/LC_MESSAGES/phraseanet.po
locale/nl_NL/LC_MESSAGES/phraseanet.po
locale/phraseanet.pot
templates/web/prod/actions/Tools/index.html.twig

- PHRAS-1224 : Remove rotation subdef wording on 3.8

Remove rotation subdef wording on 3.8

---

Makefile
resources/ansible/roles/elasticsearch/tasks/main.yml

- Gulp command path was incorrect in Makefile
- Installing ES plugins as an unprivileged user during Ansible provisioning triggered errors with Ansible 2

Fix provisioning errors

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Command/Setup/ConfigurationEditor.php
lib/conf.d/configuration.yml
resources/ansible/roles/app/tasks/main.yml

- API SSL requirement is now disabled by default in Vagrant VM
- API is enabled by default in Vagrant VM
- API SSL required is enabled in sample configuration files
- API is disabled in sample configuration files
- Default ElasticSearch index is created during provisioning

API settings provisioning

---

lib/classes/set/export.php

- PHRAS-1203 Backport duplicated extensions in filenames when exporting documents (triggered by API uploads with unsanitized filenames)

Backport extension fixes

---

Makefile

- PHRAS-1245 Some gitkeep files are deleted during provisioning

PHRAS-1245 Preserve gitkeep file

---

lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
lib/classes/record/adapter.php

- cache is now invalidated after editing records
- recordeditsuscriber can't run into recursion anymore
- PHRAS-1178: if a record is updated, every "parent" story is considered as updated too (editDateField(s) set)

PHRAS-1178_edit-story-and-records_4.0

---

lib/Alchemy/Phrasea/Media/MediaTypeFactory.php
lib/Alchemy/Phrasea/Media/Subdef/Subdef.php
lib/Alchemy/Phrasea/Media/Subdef/Unknown.php
lib/Alchemy/Phrasea/Media/Type/Unknown.php
lib/classes/databox/subdef.php

- PHRAS-1279: a "unknown"-type document can get subdefs substituted via API
-  added type "unknown" to subviews setup so an "unknown"-type document can have substituted subdefs

PHRAS-1279_SUBSTITUTE-UNKNOWN-TYPE

---

lib/Alchemy/Phrasea/Setup/DoctrineMigrations/OrderMigration.php
lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20160511160640.php
lib/classes/patch/390alpha1a.php

- PHRAS-1155 : The patch "OrderMigration" is fixed (the new column "Orders.notification_method" creation (2016...) is moved to an older patch (2013...) since this patch runs on 2016 orm object "Orders").

PHRAS-1155_UPDATE-3.8-4.0-FAILS

---

lib/Alchemy/Phrasea/TaskManager/Editor/SubdefsEditor.php
lib/Alchemy/Phrasea/TaskManager/TaskList.php

- default subdef task has a maxduration of 3600 sec (1h)
- parameters "maxmeg" and "maxduration" (if present) in xml task settings are passed to task:run as --max-memory and --max-duration

PHRAS-1284_MAX-DURATION-TASK-PARAMETER

---

lib/Alchemy/Phrasea/Controller/PermalinkController.php

- Download permalinks return a 500 response when there is no oauth_token param

Fix download permalink

---

resources/ansible/roles/elasticsearch/tasks/main.yml

- Remove plugin folder before elasticsearch setup

Remove plugin folder before elasticsearch setup

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
lib/classes/databox.php

- PHRAS-828: cterms are cleared before reindexation (admin button) or populate (cli) ; terms in "stock" are preserved.
nb.: rejected terms (red) are also purged so a term may pop-up again as candidate even if it had been rejected before.

PHRAS-828_CTERMS-NOT-PURGED

---

lib/classes/media/Permalink/Adapter.php

- PHRAS-1292: some invalid chars are now replaced by "_" in permalinks labels

PHRAS-1292_BAD-CHARS-IN-PERMALINKS

---

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
lib/Alchemy/Phrasea/Search/V1SearchTransformer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/StringFieldMapping.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineResultTest.php
tests/classes/PhraseanetAuthenticatedWebTestCase.php

- PHRAS-1300: search with the beginning of a word, ex. car finds car, carousel, caramel...
"car" (with quotes) only searches "car"
- The "searchengineresults" object now contains php query to ease debugging of es query (not double json encoding anymore)

PHRAS-1300_TRONCATURE_MASTER

---

lib/classes/set/export.php
lib/classes/unicode.php
tests/classes/media/subdefTest.php
tests/classes/unicodeTest.php

- PHRAS-1205: export filenames are fixed (no more double extension, replace blank by '_', doubles are numbered with '#', ...)
- faster unicode
- faster unicodeTests

PHRAS-1205_DOUBLE-EXTENSIONS_4.0_redo

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Escaper.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php

- PHRAS-1335: a facet containing a double quote (") generates a syntax error in query. Reason : A dquote inside the value after an "=" operator (ex. field:Keywords="intégrale "anthologie" ") generates syntax error parsing - even escaping internal dquotes as \" -
fix : facet filter query is changed to field:Keywords:r"intégrale \"anthologie\" ", using ":" operator on a raw value r"value".

PHRAS-1335_FACETS-ESCAPE-CHARS

---

grammar/query.pp
lib/Alchemy/Phrasea/Command/SearchEngine/Debug/QueryParseCommand.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/AbstractTermNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/EqualExpression.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/MatchExpression.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/RangeExpression.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/StringHelper.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php

- PHRAS-1340: fix query parser to better handle escaped dbl-quotes ("). Now " is a string delimiter, a real " must be escaped with anti-slash, especially in strict queries like Field:r"a value \\"including\\" quotes".
- better output of bin/console/searchengine:query:parse

PHRAS-1340_FACETS-TECH-FIELDS

---

lib/Alchemy/Phrasea/Command/Developer/RegenerateSqliteDb.php
lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Prod/LazaretController.php
lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
tests/Alchemy/Tests/Phrasea/Application/OverviewTest.php
tests/Alchemy/Tests/Phrasea/Controller/Prod/LazaretTest.php

- PHRAS-1347: fix missing ext. when a doc was substituted via api.
- calls to obsolete SubdefSubstituer::substitute() renamed (method NOT removed, may be used in plugins)

PHRAS-1347_API-SUBSTITUTE-EXTENSION

---

lib/classes/cache/databox.php

removing \n into SQL requests causing memcached content deletion issues.
- PHRAS-1359: memcache mysql table content deletion fix
- \n creates an issue while deleting memcached table content, causing issues into Phraseanet

PHRAS-1359_remove_back_slash_n

---

lib/Alchemy/Phrasea/Model/Entities/User.php

- PHRAS-1388: message "invalid geoname id" is not displayed anymore for empty fields

PHRAS-1388_Invalid-geonameId

---

lib/Alchemy/Phrasea/Form/Configuration/EmailFormType.php
templates/web/admin/setup.html.twig

-  lib/Alchemy/Phrasea/Form/Configuration/EmailFormType.php
-  templates/web/admin/setup.html.twig
- PHRAS-1341_Admin_setup_user_smtp_autofill_to_off
- Remove navigator autofill bug in SMTP user and SMTP password fields

PHRAS-1341_Admin_setup_user_smtp_autofill_to_off

---

lib/Alchemy/Phrasea/Helper/User/Edit.php

- lib/Alchemy/Phrasea/Helper/User/Edit.php
- PHRAS-1368_Admin_users_email_edit
- Email NULL if empty

PHRAS-1368_Admin_users_email_edit

---

templates/web/admin/databox/databox.html.twig

- PHRAS-392: show alert dialog and refresh page when enabling a collection similar to when disabling it

PHRAS-392 activate collection with feedback

---

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
lib/Alchemy/Phrasea/Databox/Subdef/SubdefPreset.php
lib/Alchemy/Phrasea/Databox/Subdef/SubdefPresetProvider.php
lib/Alchemy/Phrasea/Media/Subdef/Subdef.php
lib/classes/databox/subdef.php
lib/classes/databox/subdefsStructure.php
resources/www/admin/styles/main.scss
templates/web/admin/subdefs.html.twig
tests/Alchemy/Tests/Phrasea/Controller/Admin/SubdefsTest.php

- Add subdef pressets on subdef admin form.
- Subdefs are hardcoded and defined on SubdefController. TODO: create API route to manage subdef subsets values. 
- On subdef creation, presets values are deployed on subdef configuration.

PHRAS-1355 Add subdef pressets on subdef admin form

---

lib/Alchemy/Phrasea/Command/SearchEngine/IndexManipulateCommand.php
lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php

- PHRAS-1449: allow to specify a populate order/direction for "searchengine.index" cmd, see --help
todo : unit test of new methods

PHRAS-1449_Populate-Order-Option_4.0

---

templates/web/common/index_bootstrap.html.twig
templates/web/prod/preview/popularity.html.twig

- PHRAS-1498: fix issue with chart not loading on IE
- downgrade google chart API to fix flickering on hover

PHRAS-1498 chart not loading IE

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php

- PHRAS-1336: new searchengine settings :
allow to set the number of aggregate values displayed for base, collection and type
nb : 0 = don't aggregate ; N = limit to N values; -1 = no limit (all values)
todo : gui (menus) with
- "Not aggregated" (values = 0)
- 10; 20; 50; 100
- "All values" (value = -1)

PHRAS-1336_setting-technical-aggregates_4.0

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
lib/Alchemy/Phrasea/Search/V1SearchRecordsResultTransformer.php
tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
tests/Alchemy/Tests/Phrasea/Model/Manipulator/ApiLogManipulatorTest.php

- PHRAS-1688: revert deleted (obsolete) api route "records/search" because it is used by the Office plugin.

PHRAS-1688_rollback-record-search-api_4.0

---

Vagrantfile
lib/Alchemy/Phrasea/Command/SearchEngine/IndexManipulateCommand.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php
www/scripts/apps/admin/require.config.js

- PHRAS-1793: when indexing, the temporary alias is not named "phraseanetjy" anymore.
The alias name is "\<index\>\_T\<key\>" where \<key\> is a hex string, helping to distinguish from the index name "\<index\>_\<timestamp\>.\<microseconds\>"

PHRAS-1793_temp-index-phraseanetjy_4.0

---

resources/ansible/roles/elasticsearch/tasks/main.yml

- PHRAS-1817: change provisioning from oracle to openjdk

PHRAS-1817_java-provisioning_MASTER

---

resources/ansible/roles/elasticsearch/tasks/main.yml

- PHRAS-1823 for vagrant provisioning, switch to openjdk-7-jre repository, Oracle repo is not available

PHRAS-1823 postport 4.0 switch to openjdk-7-jre

---

lib/Alchemy/Phrasea/Command/Setup/Install.php

- PHRAS-1834: default-server-name = "phraseanet"

PHRAS-1834_missing-default-server-name_4.0

---

composer.json
composer.lock
config/configuration.sample.yml
lib/Alchemy/Phrasea/Authentication/Provider/Facebook.php
tests/Alchemy/Tests/Phrasea/Authentication/Provider/FacebookTest.php

- PHRAS-1752: Update facebook SDK
- Update code logic for connexion on phraseanet from facebook
- Add facebook/graph-sdk 5.6 in composer.json
- Remove facebook/php-sdk 3.2 in composer.json

PHRAS-1752 update facebook sdk

---

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
lib/Alchemy/Phrasea/Form/Configuration/ActionsFormType.php
lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php

- PHRAS-1828: Download link validity
- Set default value of download link validity to 24 (hours)
- Make download link validity editable from Admin > Setup

PHRAS-1828 Download link validity

---

Makefile

- PHRAS 1852 | Add --ignore-platform-reqs: ignore php, hhvm, lib-* and ext-* requirements and force the installation even if the local machine does not fulfill these. See also the platform config option.

PHRAS-1852 Ignore platform requirements on composer install

---

Vagrantfile
resources/ansible/roles/nginx/templates/default.j2
resources/ansible/roles/php/handlers/main.yml
resources/ansible/roles/php/tasks/configure.yml
resources/ansible/roles/php/tasks/main.yml
resources/ansible/roles/php/tasks/mod-php.yml
resources/ansible/roles/php/tasks/pecl.yml
resources/ansible/roles/php/tasks/php-cli.yml
resources/ansible/roles/php/tasks/php-fpm.yml
resources/ansible/roles/xdebug/tasks/main.yml
resources/ansible/vars/all.yml
resources/ansible/windows.sh

- Phpversion is now passed in args to vagrant up function.
- Now, run *phpversion='5.6' vagrant up* to run provisionning.

Phpversion is now passed in args to vagrant up function

---

Makefile

- Remove ignore-platform-reqs option on makefile composer setup. Rollback.

Rollback PHRAS-1852 - Remove ignore-platform-reqs option on makefile composer setup

---

lib/Alchemy/Phrasea/Border/File.php
lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php

- PHRAS-2031: Port to 4.1 - Add XmpMM:DocumentID source
- Add XmpMM:DocumentID source for value of 'UUID' of table 'record' of Databox

PHRAS-2031 Port to 4.1 - Add XmpMM:DocumentID source

---

lib/Alchemy/Phrasea/Application/ApiApplicationLoader.php
lib/Alchemy/Phrasea/Core/Event/ApiLoadEndEvent.php
lib/Alchemy/Phrasea/Core/Event/ApiLoadStartEvent.php

- Add missing events from 3.8
- PHRAS-1750: port missing 3.8 events to 4.1
- Add API LOAD START and API LOAD END event

Phras 1750 missing events from 3.8

---

grammar/query.pp
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/EqualExpression.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/GeolocationKey.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php

- PHRAS-2009_Geo-operator_MASTER add the 
> geolocation="lat lon distance"
query, running on the "location" technical field.
Since latitude, longitude and distance are separated by space(s) and may contain dots, the whole expression must be quoted. 
eg. : geolocation="47.21 0.99 1km"
distance units : see [https://www.elastic.co/guide/en/elasticsearch/reference/2.4/common-options.html#distance-units](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/common-options.html#distance-units)
todo: unit tests

PHRAS-2009_Geo-operator_MASTER

---

resources/ansible/roles/mariadb/tasks/main.yml

- Remove DB_alt from mariadb task.

Remove DB_alt from mariadb task

---

circle.yml

- PHRAS-2149: Circleci bum elasticsearch and node version as same 4.1 version

PHRAS-2149 Circleci bum elasticsearch and node version as same 4.1 version

---

Vagrantfile

- Provisionning was broken on second --provision attempt. fallocate command must be run one time. I'm choosing to disable swap before reactivation.

Turn off swap before instanciate it again on second provision

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Query.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php
lib/classes/databox.php

- PHRAS-1831: enforce strict search with [bracketted] query
- fix small issue with "clear candidates" function 
- th query on non-existing term (eg. " [vfshfvyervaze] ") now return 0 results instead of "all"

PHRAS-1831_wrong-results-th-query_4.0

---

lib/Alchemy/Phrasea/Filesystem/LazaretPathBooker.php

- PHRAS-2258: filter special characterin filename when created lazaretfile

PHRAS-2258 Quarantine - special characteres in filename of uploaded file, block actions, (add, substitute, delete).

---

lib/classes/record/adapter.php

- PHRAS-2268: now API / setmetadatas does trigger metadatas writting (raise jeton)

PHRAS- 2268 :API / setmetadatas does not trigger metadatas writting job on the file

---

lib/classes/record/adapter.php

- PHRAS-2271: port to 4.1 API / setmetadatas does not trigger metadatas writting job on the file
- update jeton when set metadatas

PHRAS-2271 Port to 4.1 - PHRAS-2268 API / setmetadatas does not trigger metadatas writting job on the file

---

templates/web/prod/results/record.html.twig

- PHRAS-2275: Backport to 4.0 - Stored XSS vulnerability in "Title" in answer grid

PHRAS-2275 Stored XSS vulnerability in "Title" in answer grid

---

lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
lib/classes/databox/status.php

- PHRAS-252: when the archive task was stopped because of overflow "max duration", all remaining files in the hotfolder were deleted.
nb : the exact reported bug  ("files go in error") was not reproduced.

PHRAS-252_archive-task-deletes-files_4.0

---

lib/Alchemy/Phrasea/Core/Version.php
lib/classes/patch/406b.php
lib/classes/record/adapter.php

- PHRAS-2317: wrong coll_id (destination collection) on table log_docs for "collection" actions (change collection)
Added a patch (4.0.6b) to fix old bad values.

PHRAS-2317_wrong-collid-logdoc_4.0

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php

Now we are strict when do a thesaurus search and when indexing record.
The following of PHRAS-1831
We are also strict with context of thesaurus term.
- Now we are strict when do a thesaurus search and when indexing record.
- A search with [orange] don't find record with thesaurus term "orange (city)" , "orange (fruit)" and 
"Orange (color)".
- A search with "Orange" (full text + thesaurus search ) find record with "orange (ville)" , "orange 
(fruit)" and "orange (color)".
- A search with "Orange City" find only record with "Orange (City)".
- PHRAS-2371 strict thesaurus search when indexing

PHRAS-2371 strict thesaurus search when indexing

---

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
resources/www/prod/js/jquery.main-prod.js
templates/web/prod/index.html.twig

- only the input text of query is saved/restored as "last query", everything else is lost (adv search settings, aggregates etc...)
todo : save / restore everything
- PHRAS-2322: 
- build jsonquery from adv-search and facets
- build equivalent fulltext query from jsonquery (backward compatible)
- save/restore only the input text for now (todo: save jsonquery, restore ux)
included some code from Filip so previous pr will be closed.

PHRAS-2322_return_aggregates_as_new_json_structure-BIS-4.0

---

resources/ansible/roles/app/tasks/main.yml

Cmd bin/console s:c:p is deprecated
- Cmd bin/console s:c:p is deprecated change in favor of new cmd
bin/console searchengine:index -c

PHRAS-2368 Change cmd elasticsearch create index

---

.circleci/config.yml

Disabled pear.php.net,  is down cause of security failure
- disabled because pear.php.net is down cause of security failure

PHRAS-2410 security failure in pear.php.net

---

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php

- PHRAS-2413: fix audio preset name

PHRAS-2413: fix audio preset name

---

resources/www/prod/js/jquery.main-prod.js

- PHRAS-2427: advsearch "date" zone is cleared ok
- PHRAS-2427: advsearch "fields" zone, click "add" does not send the query anymore

PHRAS-2427_advsearch-date-clear_4.0

---

lib/conf.d/data_templates/DublinCore.xml
lib/conf.d/data_templates/en-simple.xml
lib/conf.d/data_templates/fr-simple.xml

- PHRAS-2446: use pdf instead flexpaper for document's preview
- Change in database template

PHRAS-2446: Databases templates - 'flexpaper' to 'PDF' forChange setting of subdefs

---

lib/conf.d/data_templates/DublinCore.xml
lib/conf.d/data_templates/en-simple.xml
lib/conf.d/data_templates/fr-simple.xml

- PHRAS-2446: Databases templates - 'flexpaper' to 'PDF' for Change setting of subdefs
- backport in 4.0

PHRAS-2446: backport 4.0 Databases templates - 'flexpaper' to 'PDF' for Change setting of subdefs

---

package.json

- PHRAS-2464: last 4.1 version with search OK downgrade Phraseanet-production-client to 0.33.84

PHRAS-2464_downgrade_Phraseanet-production-client_to_0_33_84

---

package.json
yarn.lock

- PHRAS-2464: last 4.1 version with search OK downgrade Phraseanet-production-client to 0.33.84
- last 4.1 version with search OK downgrade Phraseanet-production-client to 0.33.84

PHRAS-2464 downgrade phraseanet production client to  0 33 84

---

templates/web/prod/index.html.twig

- PHRAS-2482: into advsearch/fields-zone, the "type" of fields is now always "string" so the json build is ok

PHRAS-2482_advsearch-date-fields_4.0

---

lib/Alchemy/Phrasea/Collection/CollectionService.php
lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php
lib/Alchemy/Phrasea/Controller/Admin/UserController.php

- PHRAS-2480: With SAML based authentication Order Managers are flushed when re-authenticate
- Allow model as order manager

PHRAS-2480:With SAML based authentication Order Managers are flushed when re-authenticate

---

.gitignore
Makefile
yarn.lock

- Run `yarn install` instead of `yarn upgrade` to rely on the `yarn.lock` file.
- Update yarn packages and lock them into `yarn.lock`
- git ignore `/Phrasea_datas` folder which is the default data location for the Docker stack.

PHRAS-2494 keep node_modules directory for performance

---

templates/web/admin/users.html.twig

- PHRAS-2153: Administration : No user search possible with the field "Company" and field "Country"
- 1/ Go to Phraseanet Administration
2/ Search for a user, using the "Company" field. Enter the first letters
Nothing happens, the whole list is being displayed. Search on a company is impossible.

PHRAS-2153 Administration : No user search possible with the field "Company" and field "Country"

---

.circleci/config.yml

- PHRAS-2532: adding phraseanet-docker hostnames to circleci machine hosts
- adding redis elasticsearch db rabbitmq to /etc/hosts on circleci machine

adding phraseanet-docker hostnames to circleci hosts

---

resources/gulp/components/vendors/alchemy-embed.js

- PHRAS-2552: Deploy alchemy-embed-medias from vendor 
Run   
> ./node_modules/.bin/gulp  build-alchemy-embed
- Don't use alchemy-embed-medias from npm-package

PHRAS-2552 embed-bundle-edit-workflow for deployment

---

templates/web/login/common/macros.html.twig

- PHRAS-2567: Registration Form / Term of use link is broken
- The term of use link is broken.

fix broken term of use link

---

package.json
yarn.lock

- PHRAS-2574: New search don't reset facets, use cross for remove it
- PHRAS-2613: Don't auto start video when openning video tool

PHRAS-2574 update phraseanet-production-client version to 0.34.15-d

---

bower.json
lib/Alchemy/Phrasea/Core/Version.php

- PHRAS-2535 - Back / Front - Unsubscription: It's now possible to request a validation by email to delete a Phraseanet user account.
- PHRAS-2480 - Back / Front - It's now possible to add a user model as order manager on a collection:All users with this model applied can manage orders on this collection. This features fixes an issue when users is provided by SAML and the orders manager is lost when user logs in.
- PHRAS-2474 - Back / front. - Searched terms are now found even if the searched terms are split in Business Field and regular Field.
- PHRAS-2462 - Front - Share media on LinkedIn as you can do on Facebook, Twitter.
- PHRAS-2417 - Front - Skin: grey and white, graphic enhancements.
- PHRAS-2067 - Front - Introducing thumbnail & preview generic images for Fonts
- PHRAS-2491 - …

PHRAS-2625 release version 4.0.9

---

lib/Alchemy/Phrasea/TaskManager/Job/WriteMetadataJob.php

- PHRAS-2652: do not push Fields "Phraseanet::no-source" to exiftool

PHRAS-2652 : fix Fields "Phraseanet::no-source" are pushed to exiftool

---

composer.json
composer.lock
config/configuration.sample.yml
lib/conf.d/configuration.yml

- embed-bundle@2.0.6
- PHRAS-2623 add videojs subtitle icons
- PHRAS-2621: Define a cover subdef for audio kind (file)

PRHAS-2621   update embed-bundle and configuration.yml

---

lib/Alchemy/Phrasea/Application.php

- PHRAS-1428: Phraseanet Binaries in configuration not used in some alchemy-fr libraries
- use  pdftotext_binary binary setting from the configuration.yml

PHRAS-1428 : Phraseanet Binaries in configuration not used in some alchemy-fr libraries

---

.circleci/config.yml

- error on phraseanet circleci " CircleCI was unable to run the job runner because we were unable to execute commands in build container".
- related to  https://discuss.circleci.com/t/circleci-was-unable-to-run-the-job-runner/31894/18

PHRAS-2711 : fix circleci unable to run the job runner

---

.circleci/config.yml

- PHRAS-2712: backport 2711
- do not use /sbin/init  on circleci

PHRAS-2712 : Port to 4.0 - CIRCLECI : All Phraseanet Build fails

---

lib/Alchemy/Phrasea/Application.php

- PHRAS-2704: port to 4.1 use configuration pdftotext binary

PHRAS-2704 : PORT To 4.1 - Phraseanet Binaries in configuration not used in some alchemy-fr libraries

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php

- PHRAS-2714: API leaves a copy of the file into the system temporary directory
- concerned route : /api/v1/embed/substitute/  and   /api/v1/records/add/

PHRAS-2714 : API leaves a copy of the file into the system temporary directory 4.0

---

lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
tests/Alchemy/Tests/Phrasea/Border/ManagerTest.php
tests/Alchemy/Tests/Phrasea/SearchEngine/RecordHelperTest.php

- PHRAS-2729: a date value like "Film de Jan De BONT (1997)" was exploded as ["","1997",""], now non-numeric parts are excluded

Phras 2729 datetime warnings 4.0

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php

- PHRAS-2714-: Port to 4.1 API leaves a copy of the file into the system temporary directory
- concerned route : /api/v1/embed/substitute/ and /api/v1/records/add/

PHRAS-2714 : Port to 4.1 API leaves a copy of the file into the system temporary directory 4.1

---

lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php

- PHRAS-2754: Permalink is not (re) activated when record is move from _TRASH_ collection

PHRAS-2754 : 4.0 reactivate permalink when record move from TRASH

---

lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php

- PHRAS-2754: 4.1 Permalink is not (re) activated when record is move from _TRASH_ collection

PHRAS-2754 : 4.1 reactivate permalink when record moved from TRASH

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/StringUtils.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php

- PHRAS-2748: fix : remove bad ascii chars (0...31 except tab; cr; lf) from cterms values
todo ? : also cleanup bad chars from prod/editing and api/editing ?

PHRAS-2748_bad-chars-cterms_4.1

---

lib/Alchemy/Phrasea/Cache/RedisCache.php
lib/Alchemy/Phrasea/Utilities/RedisSessionHandler.php

- PHRAS-2813: 4.0 redis function delete is deprecated

PHRAS-2813 : 4.0 redis function delete is deprecated

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php

- PHRAS-2802: changed truncation tokenizer to include punctuation

PHRAS-2802_truncation-with-dots_4.0

---

lib/classes/databox.php

- PHRAS-2834: When create a database from model, all fields have properties gui_editable gui_visible set to false
- gui_editable and gui_visible  default to true if not set

PHRAS-2834: When create a database from model, all fields have properties gui_editable gui_visible set to false

---

package.json
yarn.lock

- phraseanet-production-client@0.34.86-d
- PHRAS-2856: Define records order (sequence) in story GUI is NOK and the choice is not taken in account
- upgrade phraseanet-production-client

PHRAS-2856  Fix prod Basket and story : Set records order 

---

tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
tests/bootstrap.sh

- PHRAS-2814: to complete https://github.com/alchemy-fr/Phraseanet/pull/3222/commits : add options to bootstrap for tests

PHRAS-2814_missing-es-options-for-tests

---

lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php

- PHRAS-2877: User manipulator does not allow to set a null email
- User manipulator does not allow to set a null email

PHRAS-2877 User manipulator does not allow to set a null email

---

composer.json
composer.lock
lib/Alchemy/Phrasea/Setup/Requirements/BinariesRequirements.php
resources/ansible/roles/app/tasks/main.yml

- PHRAS-2750 : PHPExiftool to handle DJI XMP Tags, Bump exiftool version and switch to original exiftool/exiftool repo
- update alchemy/phpexiftool to 0.7.3 and use exiftool/exiftool

PHRAS-2750 : 4.0 PHPExiftool to handle DJI XMP Tags, Bump exiftool version and switch to original exiftool/exiftool repo

---

templates/web/prod/upload/lazaret.html.twig

- PHRAS-2894  Quarantine: allow to substitute without selecting target record, (when match only one record).

PHRAS-2894  Quarantine: allow to substitute without selecting target record, (when match only one record).

---

lib/classes/patch/410alpha17a.php

- PHRAS-2905:  4.1 Migration patch for "candidat terme", set zero when thesaurus branch is not define

PHRAS-2905 : 4.1 Migration patch for "candidat terme", set zero when thesaurus branch is not define

---

lib/classes/patch/4010.php

- PHRAS-2907: Backport To 4.0 - Migration patch for "candidat terme", set zero when thesaurus branch is not define

PHRAS-2907 : Backport To 4.0 - Migration patch for "candidat terme", set zero when thesaurus branch is not define

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Controller/Admin/SearchEngineController.php
lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
lib/Alchemy/Phrasea/Core/Version.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/LimitedStructure.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Structure.php
lib/classes/patch/410alpha21a.php
templates/web/admin/fields/templates.html.twig
templates/web/admin/search-engine/general-aggregation.html.twig
tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/StructureTest.php

OK to test
- PHRAS-2879: ~Save all facet settings in conf, order is preserved in admin/search-engine-settings.~ DONE
~todo : respect order of the admin form while saving.~ DONE
~todo : return facets into query results in this setting order.~ DONE
~todo : migration from dbox settings (field struct) to conf~ DONE
todo : remove field facet setting from admin ux ?
~todo : fix tests~ DONE
- facet rendered with /!\ means "new field, not yet configured" (= new dbox mounted ?). The sign will disappear as soon as the settings are saved.
- facet rendered with /?\ means "facet in config, but unknown in current dboxes/structures" (= a dbox was unmounted ?) - the setting is preserved just in case.
- facet with "#" is tech facet

PHRAS-2879-Define-facets-order-in-query-result

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php

- PHRAS-3003: fix (temporary ?) : text values are kept full in metadata table, but truncated to 32Ko by indexer.

PHRAS-3003_large-value-32ko-es_4.1

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php

es int type is always int32 (32 bits signed), so on php-64 we may receive overflow values if the last sb (#31) is set.
In mysql we use unsigned type, so the output value (as decimal string) may also overflow on php-32.
Since we use a php lib for es, - with php-int as underlying type - we have no way to use a binary-string notation from mysql to es.
The easy way here is to use a long (int64) in es, even if there is 32 status-bits in phraseanet
- PHRAS-3017

PHRAS-3017 Backport to 4.0 sb31 craches indexer

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php

- PHRAS-3015: set es:flags_bitfield as long (signed 64 bits)

PHRAS-3015_sb31-crashes-indexer_4.1

---

docker/phraseanet/entrypoint.sh
docker/phraseanet/root/usr/local/etc/php-fpm.d/zz-docker.conf

-  use stderr output instead of php fpm error log file

PHRAS-3025 : send Phraseanet log on stdout

---

lib/Alchemy/Phrasea/Core/Version.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/RecordListFetcherDelegate.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/ScheduledFetcherDelegate.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
lib/classes/patch/4012.php
lib/conf.d/bases_structure.xml

- PHRAS-3027: Backport To 4.0 - Populate - Slow query - due to LIMIT 508600, 200
- bump version 4.0.12

PHRAS-3027 : Backport To 4.0 - Populate - Slow query - due to LIMIT 508600, 200

---

.env

- Tag docker images to 4.0.12 in .env

PHRAS-3036 Tag docker image to 4.0.12 

---

.gitignore
config/filebeat.yml
config/logstash.conf
docker-compose.override.yml

use filebeat to get worker log from file and push it to ELK and to logstash stdout
- PHRAS-2524: put worker log to ELK
- add logstash container
- add filebeat container
- _docker-compose logs -f logstash_ to see task log message
- elasticsearch index prefixed by _logstash-_

PHRAS-2524 : put worker log to ELK

---

templates/web/prod/actions/Tools/videoEditor.html.twig

- PHRAS-3067 Prod - video tools - by default option "No Chapters Overlaps" need to be true

PHRAS-3067 Prod - video tools - by default option "No Chapters Overlaps" need to be true 

---

composer.lock

- PHRAS-2404 : remove unused phpexiftool/exiftool in composer.lock

PHRAS-2404 : remove unused phpexiftool/exiftool in composer.lock

---

lib/conf.d/data_templates/DublinCore.xml

- PHRAS-3120: change file path for audiovideowav and audiovideomp3

PHRAS-3120 fix storage file path for subview

---

Dockerfile

- PHRAS-3192: add inkscape apt package to Dokerfile for svg files
- add inkscape apt package to Dokerfile for svg files to fixe subview creation issues

PHRAS-3192 - add inkscape apt package to Dokerfile for svg files

---

templates/web/prod/upload/upload.html.twig

- PHRAS-3209 JS Error message during upload: "img.toDataURL is not a function" on 4.0.12
This js part is removed as it is deprecated

PHRAS-3209 JS Error message during upload: "img.toDataURL is not a function" on 4.0.12

---

composer.json

- PHRAS-3226: fix lower case composer dependencies
- Since composer 2.0 does not allow upper case caracters. we change composer.json

PHRAS-3226 4.0 lower case composer dependencies

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php

#time 1h
- PHRAS-3244: worker - admin - populate - populate again a databases after manual interruption is not possible

PHRAS-3244 : worker - admin - populate - populate again a databases after manual interruption is not possible

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php

- PHRAS-3265: Port to 4.1 - taken in account max_result_window when create elastisearch index

PHRAS-3265 Port to 4.1 - taken in account max_result_window when create elastisearch index

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/SubDefinitionHydrator.php
lib/classes/media/Permalink/Adapter.php
lib/conf.d/configuration.yml

The subdefintion's Permalinks are now injected in Elasticsearch index when the new option  "populate_permalinks" is set to "True".
This option is define in configuration.yml, "search-engine" section.
If property is missing the value is false.
With this feature, "api/v3/searchraw" can serve subdefinition's permalinks.
Warning, when populate_permalinks:true, duration and memory consumption during the Populate are increase, this factor is depending of  "databox's" structure.
- PHRAS-3279 : permalinks  in Elasticsearch index.

PHRAS-3279_api-v3-permalinks-to-es_4.1

---

lib/Alchemy/Phrasea/WorkerManager/Command/WorkerExecuteCommand.php

-  If rabbitMQ is not up, worker exit with code 1 
- PHRAS-3129 : Docker - Worker - if rabbitMQ is not up, worker need to exit with 1

PHRAS-3129 Docker - Worker - if rabbitMQ is not up, worker need to exit with 1

---

README.md
lib/Alchemy/Phrasea/Authentication/RecoveryService.php
lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
tests/Alchemy/Tests/Phrasea/Model/Manipulator/TokenManipulatorTest.php

- PHRAS-3350: Password renewal and creation - link send by email - token TTL - token table of applicationBox
- default renewal ttl to 72 hours

PHRAS-3350 Password renewal and creation - link send by email - token TTL - token table of applicationBox

---

.env
docker-compose.db.yml
docker-compose.mailhog.yml

- MariaDb and Mailhog container are moved in severals docker-compose file.
- You can compose your stack by dealing with COMPOSE_FILE env
eg :
For dev purpose 
```
COMPOSE_FILE=docker-compose.yml:docker-compose.db.yml:docker-compose.mailhog.yml:docker- 
compose.override.yml
```
For test
`COMPOSE_FILE=docker-compose.yml:docker-compose.db.yml:docker-compose.mailhog.yml`
Down your actual stack before using this pr.

PHRAS-3364 explode compose file

---

templates/web/prod/Thesaurus/droppedrecords.html.twig

- PHRAS-3406 : setting a mono-valued field with the "simple" ux is ok
- also tested ok with special chars : " bad_'_<_"_>_&_=_:_!_chars "

PHRAS-3406_classification-field-centric_MASTER

---

lib/classes/record/preview.php
templates/web/prod/preview/short_history.html.twig

- PHRAS-3460 : Prod - Detailed view - Timeline tab (History) - events sorting is wrong and some events do not appear

PHRAS-3460 Prod - Detailed view - Timeline tab (History) - events sorting is wrong and some events do not appear

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php

- PHRAS-3479: "trace" do not report usec anymore
bonus : the translation dumper run ok again (because php7 syntax is now avoided)

PHRAS-3479_trace-crash-on-usec0

---

docker-compose.yml

-  Docker Rabbitmq version is set  to rabbitmq:3.6.16-management

PHRAS-3484 set rabbitmq version

---

.gitignore

If the file `www / gitlog.txt` exist, it will be copied in FPM container and can be retrieved in
"About Phraseanet".
You need to generate this file with a Git log cmd, before build image
- PHRAS-3109

PHRAS-3109 gitlog in "About Phraseanet"

---

Dockerfile

- PHRAS-3526: Docker - builder - Bump composer version to 2.0 , git key format issue and set memory limit
- composer 2.1.6
- php memory_limit = 2048M

PHRAS-3526 Docker - builder container - Bump composer version to 2.0 and set memory limit

---

lib/Alchemy/Phrasea/Application/Helper/JsonBodyAware.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3SubdefsServiceController.php
lib/Alchemy/Phrasea/Helper/JsonBodyHelper.php
lib/Alchemy/Phrasea/Media/SubdefGenerator.php

- PHRAS-3564: wmark is applied (phr subdef setting)
Mapping from expected name (destination.subdefs/keys) to phr subdef name ("source") : Allows to ask for a subset of phr subdefs (see sample)
Default will map all phr subdefs.
sample request (json raw body):
```
{
"databoxId": 2,
"source": {
"url":"https://file-examples-com.github.io/uploads/2017/10/file_example_JPG_2500kB.jpg"
},
"destination": {
"subdefs": {
"thumbnail":  {
"source": "thumbnail"
},
"preview": {
"source": "preview"
},
"over": {
"source": "preview_mobile"
}
},
"url":"http://172.32.0.1:8082/api/v3/subdefs_service_callback/?oauth_token=xxxxxxx",
"payload": {
"text":"this is some text",
"int":555
},
"filename":"asset_555_"
}
}
```
output to subdefgenerator.txt :
```
2021-11-25T18:21:01 [818] : …
```

PHRAS-3564_subdef-service-api

---

lib/classes/media/subdef.php

- PHRAS-3519: remove delay to subdef->isStillAccessible() calling fs->exists().
because it's called by getsubdef(), any missing subdef will slow down phr by 10s. on every getsubdef() call.

PHRAS-3519_filesystem-atomic-move : remove delay

---

lib/Alchemy/Phrasea/Media/SubdefSubstituer.php
lib/classes/record/adapter.php

- PHRAS-3509: Prod - tools - document substitution - the generation message for sub-definition is published twice.

PHRAS-3509 Prod - tools - document substitution - the generation message for sub-definition is published twice.

---

lib/classes/patch/415PHRAS3604.php

- PHRAS-3616 : System:Updrade generates error in case a referenced databox doesn't exist
- fix patch 4.1.5 PHRAS-3604

PHRAS-3616 System:Updrade generates error in case a referenced databox doesn't exist

---

lib/classes/record/adapter.php

- PHRAS-3619: After record removal, we have an HTTP status 200 on the /records route of the API on the deleted record
- delete the correponding record_id  key in cache

PHRAS-3619 After record removal, we have an HTTP status 200 on the /records route of the API on the deleted record

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
lib/Alchemy/Phrasea/Controller/Prod/UploadController.php

- PHRAS-3637: API - Upload Url | Let's Encrypt ssl certificate verification fail. use the correct guzzle version

PHRAS-3637 : API - Upload Url | Let's Encrypt ssl certificate verification fail. use the correct guzzle version

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php

- PHRAS-3666: PROD - PRINT - PDF - Generated pdf cant be printed even if no password is defined

PHRAS-3666 PROD - PRINT - PDF - Generated pdf cant be printed even if no password is defined

---

lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php

- PHRAS-3663: empty baskets (for participants) were not visible in wz

PHRAS-3663: missing baskets in wz

---

lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php

- PHRAS-3686: Prod - caption : characters (#,!) into a clickable url link can lead to cut the link

PHRAS-3686 Prod - caption : characters (#,!) into a clickable url link can lead to cut the link

---

.circleci/config.yml

- PHRAS-3688: FIX Circle CI Image version deprecation
- FIX image building, caused by to Circle CI Image version deprecation

PHRAS-3688 Update image to Ubuntu 20.04

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Term.php

- PHRAS-3645: thesaurus indexation _before_ fetch record (prevents double-candidates)
- PHRAS-3645: <term (context)> parsing in php (fix first special char)

PHRAS-3645_candidates-special-chars

---

Dockerfile

- PHRAS-3698: fix docker imagemagick download link error
- update imagemagick download link that have changed

PHRAS-3698 fix docker imagemagick download link error

---

Dockerfile

- PHRAS-3698: fix docker imagemagick download error backport to 4.1.6 rc2
- update imagemagick download link that have changed

PHRAS-3698 fix docker imagemagick download error backport to 4.1.6 rc2

---

templates/web/prod/Thesaurus/droppedrecords.html.twig

- PHRAS-3612: Prod - thesaurus used for classement - Gui string html missmatch

PHRAS-3612 : Prod - thesaurus used for classement - Gui string html missmatch

---

composer.json
composer.lock

- Upgrade swiftmailer to v5.4.12
- PHRAS-3700: Issue when sending mail through Office 365 SMTP
- Upgrade swiftmailer to v5.4.12 for TLS 1.1 / 1.2 support

Phras 3700 upgrade swiftmailer to v5.4.12 1

---

Dockerfile

- PHRAS-3715: fix build image fails due to imagmagick version change
- ImageMagick build fails due to version changes

PHRAS-3715 Docker - fix build image - fix imagmagick version

---

.env
docker-compose.yml
docker/nginx/root/entrypoint.sh
docker/nginx/root/nginx.conf.sample

- PHRAS-3318: Fix K8S service name on proxy nginx usage
- sp saml need revers proxing. K8S need full service url when proxying

PHRAS-3318 sp saml - Fix K8S service name on proxy nginx usage

---

Dockerfile

git clone Imagemagick
- PHRAS-3715 : Fix build issue using git repo instead of curl for ImageMagick

PHRAS-3715 git clone Imagemagick

---

Dockerfile

Fix libheif version to v1.13.0-4.1.6-rc2
- PHRAS-3771 : Fix libheif version to v1.13.0-4.1.6-rc2

PHRAS-3771-fix-libheif-version-to-v1.13.0-4.1.6-rc2

---

Dockerfile
docker/phraseanet/php.ini.sample

- PHRAS-3780: fix opcache activation in fpm container
- enable opcache zend extension in php config

PHRAS-3780 enable opcache zend extension

---

Dockerfile

- PHRAS-3878: fix jq to latest working commit
- fix a build error due to libjq changes

PHRAS-3878 fix jq to latest working commit

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/search/geoSearch/searchGeoForm.js
lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
lib/classes/eventsmanager/notify/basketwip.php
lib/classes/eventsmanager/notify/validate.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/preview/title.html.twig

- PHRAS-3851: Untranslated terms : in Notifications, Detailed View, Map
- PHRAS-2642

PHRAS-3851 Untranslated terms : in Notifications, Detailed View, Map

---

lib/Alchemy/Phrasea/Helper/Prod.php
templates/web/prod/index.html.twig

- PHRAS-3884:advanced search sort field by label

PHRAS-3884 advanced search sort field by label

---

Dockerfile

- PHRAS-3910: fix redis php extension build into docker image
- fix error due to new redis extension release

PHRAS-3910 fix redis php extension build

---

lib/Alchemy/Phrasea/Application.php
lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
lib/Alchemy/Phrasea/Form/Configuration/EmailFormType.php
templates/web/prod/templates/push.html.twig

- PHRAS-3900: Check TLS version use for email SMTP sending - TLS 1.0 of 1.1 deprecation

PHRAS-3900 Check TLS version use for email SMTP sending - TLS 1.0 of 1.1 deprecation

---

.env
CHANGELOG.md

- PHRAS-3942 release 4.1.8-rc7
- Fix some typo .env file comment

PHRAS-3942 4.1.8-rc7 changelog and .env typo fix

---

lib/Alchemy/Phrasea/Command/Thesaurus/Translator/Action.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/GlobalConfiguration.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/Job.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/TranslateCommand.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/doc/configuration-sample.yml

- PHRAS-3940: declare actions (work on fields) inside job (work on records)
- PHRAS-3940: sb not changed after partial translation

PHRAS-3940 translator-group-jobs

---

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
lib/Alchemy/Phrasea/Core/Event/Record/RecordAutoSubtitleEvent.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/SubtitleSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
lib/classes/eventsmanager/broker.php
lib/classes/eventsmanager/notify/subtitle.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Tools/videoEditor.html.twig

- PHRAS-3668: subtitle notification
- language destination information ( filled or not )

PHRAS-3668 subtitle notification

---

.env
Dockerfile
docker-compose.override.yml
docker-compose.yml
docker/phraseanet/fpm/entrypoint.sh
docker/phraseanet/worker/entrypoint.sh

PHRAS-3980 cmd container

---

doc/feedback_report.md
doc/stamper.md

- PHRAS-3990: doc for feedback-report
- doc for stamper

PHRAS-3990_feedbackReport-stamper-doc

---

.env
docker-compose.altenatives.yml
lib/Alchemy/Phrasea/Core/Database/DatabaseMaintenanceService.php

- PHRAS-4010: Adding mysql8 as alternative datastore (beta)
- Allow to choose mysql8 as data store, for test purpose only
- Require a DB content migration by export/import database.

PHRAS-4010 Add mysql8 as alternative datastore

---

docker/phraseanet/setup/init-test-install.sh
lib/Alchemy/Phrasea/Command/Setup/Install.php

- PHRAS-4146 : bin/setup system:install - abort app installation if mysql db is not empty
- add force option -f  to force installation to continue even if table in DB already exist (override table)

PHRAS-4146 bin/setup system:install - abort app installation if mysql db is not empty

---

.env
CHANGELOG.md
lib/Alchemy/Phrasea/Core/Version.php

- **Phraseanet Migration Patch**:
- A migration script for the configuration file is available. Run the following command in the setup container with Docker if the environment variable `PHRASEANET_UPGRADE=1` is set:
```
bin/setup system:upgrade
```
- no change
- Installation process (bin/setup system:install) now aborts if the application and/or databox contain existing data. the option -f  also answer all questions for yes AND  force installation to continue even if DB table  already exist
* PHRAS-4146 bin/setup system:install - abort app installation if mysql db is not empty by @aynsix in https://github.com/alchemy-fr/Phraseanet/pull/4599
**Full Changelog**: https://github.com/alchemy-fr/Phraseanet/compare/4.1.17...4.1.18

PHRAS-4148 release 4.1.18 

---

doc/API_documentation/v3/_compiled.yaml
doc/API_documentation/v3/api.yaml
lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchController.php
lib/Alchemy/Phrasea/Search/RecordTransformer.php

- PHRAS-4151 add `include[]=results.records.stories` to searchV3 api

PHRAS-4151_stories-reference-in-api

---

.env
docker-compose.datastores.yml

- PHRAS-4153: Rabbitmq : Update rabbitmq to 4.1.0 to fix CVE-2025-32433

PHRAS-4153: Rabbitmq : Update rabbitmq to 4.1.0 to fix CVE-2025-32433 

---

docker-compose.datastores.yml

- PHRAS-4157: Add Elasticsearch ulimits configuration to docker-compose.datastores.yml for newer linux kernel

PHRAS-4157 Add Elasticsearch ulimits inside docker-compose.datastores.yml

---

.env
CHANGELOG.md
README.md
infra/helm/README.md
lib/Alchemy/Phrasea/Core/Version.php
stack.sh

PHRAS-4155 4.1.19 release WIP

---

.env
CHANGELOG.md
Dockerfile
lib/Alchemy/Phrasea/Core/Version.php

- Update debian apt repository
- Release 4.1.20
- PHRAS-4159: Update debian apt repository
- PHRAS-4160 Release 4.1.20

PHRAS-4159 Update apt repositories
