alchemy-fr/Phraseanet

tests/classes/PhraseanetAuthenticatedWebTestCase.php
=> PHRAS-1401_fix-test_4.0

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/skin-shared.scss, resources/www/prod/skins/ui-components/_workzone-proposals.scss
- PHRAS-1638: inverted facet
alt-click on a facet : facet filter is inverted, ex:
click -> people AND (keyword:portrait)
alt+click -> people EXCEPT (keyword:portrait)
=> PHRAS-1638_invert-facet_4.0

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/styles/main.scss, templates/web/prod/actions/delete_records_confirm.html.twig
- PHRAS-1643: Refactor layout of dialog
=> PHRAS-1643 fix layout dialog

templates/web/common/menubar.html.twig
- PHRAS-1652: fix bug on custom-link in help-menu
=> PHRAS-1652 nav bar link shortcut event

lib/Alchemy/Phrasea/Setup/Requirements/PhpRequirements.php
- Change old message session.cookie_secure
=> PHRAS-1657- Change message that prompts for session cookie secure

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/admin/setup.html.twig
- PHRAS-1650: Add missing text for translation
=> PHRAS-1650 add missing translation

templates/web/admin/setup.html.twig
- PHRAS-1651: fix quotes in links
=> PHRAS-1651 fix quotes in links

templates/web/common/menubar.html.twig
- PHRAS-1641: add spaces in menu trigger button
=> PHRAS-1641 space help menu

templates/web/common/index_bootstrap.html.twig
- PHRAS-1670: fix bug when exporting medias
=> PHRAS-1670 fix download assets

lib/classes/record/adapter.php
- PHRAS-1666: Publication reader after remove record
- Remove item into feed
=> PHRAS-1666- Fix publication reader after remove record

tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php, tests/Alchemy/Tests/Phrasea/Model/Manipulator/ApiLogManipulatorTest.php
- PHRAS-1674: removed tests on removed route "records/search"
=> PHRAS-1674_broken-test_4.0

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
- PHRAS-1656: add default custom-links in configuration file
=> PHRAS-1656 add default link store

templates/web/common/macros.html.twig, templates/web/prod/results/record.html.twig
- PHRAS-550: refactored caption code to make all links clickable in notice
=> PHRAS-550 clickable link notice

templates/web/prod/index.html.twig
- Add language selection on prod preferences. Design is ugly cause of preferences refacto in few days.
=> PHRAS-1673 - Add language switch on prod preferences

resources/www/admin/styles/main.scss, templates/web/admin/search-engine/elastic-search.html.twig, templates/web/admin/search-engine/search-engine-settings.html.twig
- PHRAS-1675: fix bug - drop index button not working
=> PHRAS-1675 drop index nok

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_workzone-proposals.scss
- PHRAS-1662: new feature to cumulate filters on facets
=> PHRAS-1662 aggregat facet

lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
- PHRAS-1676: fix bug - error when user does not have access to add record to collection
=> PHRAS-1676 missing collection upload

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, templates/web/prod/results/infos.html.twig
- PHRAS-1685: dump esquery to results-details/explain dialog (only if user is "super-admin")
=> PHRAS-1685_dump-esquery_4.0

lib/Alchemy/Phrasea/Controller/Admin/SetupController.php
- PHRAS-1691: conf/registry writing : remove "try to repair json" on customlinks
=> PHRAS-1691_test-testPostGlobals_4.0

resources/www/prod/js/jquery.main-prod.js
- PHRAS-1694: fix bug - advanced search filter on IE not working
=> PHRAS-1694 advanced search bug IE

resources/www/prod/js/jquery.main-prod.js
- PHRAS-1693: refactored code to keep last result when applying filters
=> PHRAS-1693 keep last filter

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_workzone-proposals.scss
- PHRAS-1701: reverse active facets on click
=> PHRAS-1701 reverse active facets

config/configuration.sample.yml, lib/Alchemy/Phrasea/Authentication/Phrasea/NativeAuthentication.php, lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php, lib/Alchemy/Phrasea/Core/Provider/AuthenticationManagerServiceProvider.php, lib/Alchemy/Phrasea/Form/Configuration/MainConfigurationFormType.php, lib/Alchemy/Phrasea/Form/Configuration/WebApplicationsFormType.php, lib/Alchemy/Phrasea/Model/Repositories/UserRepository.php, tests/Alchemy/Tests/Phrasea/Authentication/Phrasea/NativeAuthenticationTest.php
- PHRAS-1623: add preference for allowing user connection without email
- Add option email-optional-for-login
=> PHRAS-1623- Add preference for allowing user connection without email

lib/Alchemy/Phrasea/Authentication/Phrasea/NativeAuthentication.php, lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php, lib/Alchemy/Phrasea/Form/Configuration/CustomLinkFormType.php, lib/Alchemy/Phrasea/Form/Configuration/MainConfigurationFormType.php, lib/Alchemy/Phrasea/Model/Repositories/UserRepository.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/admin/custom_links.html.twig, templates/web/admin/setup.html.twig, templates/web/common/menubar.html.twig
- PHRAS-1700: refactored code to use symfony form collection for custom links
=> PHRAS-1700 configuration custom link with symfony

composer.lock
- PHRAS-1704: Complexe PDF subview generation
- Update PHPSwftools to 0.3.2 version, that introduce a fix on Complex PDF subview generation
=> PHRAS-1704 add new phpswftools 0.3.2 release to composer.lock

resources/www/prod/skins/skin-shared.scss
- PHRAS-1705: change color of exception facet
=> PHRAS-1705 fix facet design

resources/www/prod/js/jquery.main-prod.js
> 
- PHRAS-1701: toggle active facets with alt-click
=> PHRAS-1701 toggle facets

templates/web/thesaurus/thesaurus.html.twig
- PHRAS-511: Prevent submission of empty terms
=> PHRAS-511 thesaurus empty terms

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
- PHRAS-854: restore "exif" in result (fix wrong source for record from es data).
=> PHRAS-854_missing-video-duration

lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php, resources/www/prod/skins/ui-components/_diapo.scss, templates/web/common/technical_datas.html.twig, templates/web/prod/results/item.html.twig, templates/web/prod/results/record.html.twig
- PHRAS-854: add custom filter to format duration of video
=> PHRAS-854 conversion duration video

package.json, resources/www/common/js/components/common.js, templates/web/admin/editusers_timelimit.html.twig, templates/web/admin/editusers_timelimit_sbas.html.twig
port PHRAS-1339 to master
need to update Phraseanet-production-client as well
=> PHRAS-1516 Port PHRAS-1339

lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php, lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Xmlhttp.php, package.json, templates/web/prod/tab_thesaurus.html.twig
Porting of the following tickets:
PHRAS-1445
PHRAS-1464 
PHRAS-1482 
PHRAS-1483 
PHRAS-1492 
PHRAS-1496
need to update Phraseanet-production-client as well
=> PHRAS-1520 port to master

resources/www/lightbox/styles/main-ie6.scss, resources/www/lightbox/styles/main.scss, templates/web/prod/index.html.twig, templates/web/prod/preview/basket_train.html.twig, templates/web/prod/preview/caption.html.twig, templates/web/prod/preview/feed_train.html.twig, templates/web/prod/preview/reg_train.html.twig, templates/web/prod/preview/result_train.html.twig, templates/web/prod/preview/result_train_options.html.twig
- PHRAS-1525: Porting PHRAS-1434/1435/1436/1437/1457 to 4.1
=> PHRAS-1525 port phras 1434 1435 1436 1437 1457

lib/Alchemy/Phrasea/Controller/Prod/BasketController.php, package.json
- PHRAS-1522: port PHRAS-1337 to 4.1
=> PHRAS-1522 port PHRAS-1337

templates/web/prod/index.html.twig
- PHRAS-1529: hide facets containing single element from preference menu
=> PHRAS-1529 PORT PHRAS-1415

templates/web/prod/preview/tools.html.twig
- PHRAS-1526: fix event listener for button export / download
=> PHRAS-1526 fix event listener for button export / download

templates/web/developers/applications.html.twig
- PHRAS-1527: refactored link for documentation to 4.1
=> PHRAS-1527 PORT PHRAS-1414

templates/web/common/menubar.html.twig, templates/web/setup/step2.html.twig
- PHRAS-1528: refactor links of documentation to 4.0
=> PHRAS-1528 PORT PHRAS-1433

templates/web/thesaurus/load-thesaurus.html.twig
- PHRAS-1532: fix label tab thesaurus
=> PHRAS-1532 PORT PHRAS-1487

lib/Alchemy/Phrasea/Controller/SetupController.php, templates/web/setup/step2.html.twig
-  Show template name instead of key
=> PHRAS-1296-Install show all available documentary structures

lib/classes/record/preview.php, package.json, templates/web/common/index_bootstrap.html.twig, templates/web/prod/preview/popularity.html.twig
- PHRAS-1524: port PHRAS-1475 and PHRAS-1498
=> PHRAS-1524 port PHRAS-1475 and PHRAS-1498

bin/setup, lib/Alchemy/Phrasea/Command/Setup/FixAutoincrements.php
- PHRAS-1157: add bin/setup system:fix-autoincrements
wip do not merge
=> PHRAS-1157_mysql-autoincrement

bower.json, composer.json, composer.lock, resources/gulp/build.js, resources/gulp/components/vendors/alchemy-embed.js, resources/www/_shared/styles/main.scss, resources/www/common/js/components/tooltip.js, resources/www/lightbox/styles/main.scss, resources/www/prod/js/jquery.main-prod.js, templates/web/common/thumbnail.html.twig, templates/web/lightbox/sc_options_box.html.twig, templates/web/lightbox/validate.html.twig
- PHRAS-1512: Porting pdf JS to 4.1
=> PHRAS-1512 port pdfjs to 4.1

templates/web/admin/setup.html.twig
- PHRAS-1724: fix display of text containing single quote
=> PHRAS-1724 fix setup page

resources/ansible/roles/app/tasks/main.yml, resources/ansible/roles/mariadb/tasks/main.yml, resources/ansible/roles/nginx/templates/default.j2, resources/ansible/roles/php/handlers/main.yml, resources/ansible/roles/php/tasks/configure.yml, resources/ansible/roles/php/tasks/main.yml, resources/ansible/roles/php/tasks/mod-php.yml, resources/ansible/roles/php/tasks/pecl.yml, resources/ansible/roles/php/tasks/php-cli.yml, resources/ansible/roles/php/tasks/php-fpm.yml, resources/ansible/vars/all.yml
- PHRAS-1723, Fix some paths, variable namings.
=> PHRAS-1723 Fix some paths, variable namings

Makefile, package.json, resources/www/_shared/styles/_main-menu.scss, resources/www/admin/styles/_databases.scss, resources/www/admin/styles/_fields.scss, resources/www/admin/styles/_tables.scss, resources/www/admin/styles/main.scss, templates/web/admin/collection/collection.html.twig, templates/web/admin/dashboard.html.twig, templates/web/admin/databox/cgus.html.twig, templates/web/admin/fields/templates.html.twig, templates/web/admin/publications/fiche.html.twig, templates/web/admin/publications/list.html.twig, templates/web/admin/setup.html.twig, templates/web/admin/users.html.twig
- PORT PHRAS-1555/PHRAS-1568 to 4.1
=> PHRAS-1715 refactor admin

package.json, templates/web/prod/preview/popularity.html.twig
- PHRAS-1721: Porting PHRAS-1574
=> PHRAS-1721 Port PHRAS-1574

templates/web/admin/publications/wrapper.html.twig, templates/web/prod/orders/order_item.html.twig, templates/web/prod/preview/popularity.html.twig, templates/web/report/all_content.html.twig
- PHRAS-1725: refactored texts with single quotes
=> PHRAS-1725 clean string

resources/ansible/roles/app/templates/configuration.tpl, resources/ansible/roles/mariadb/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-1760: fix mismatch "database" (bad) -> "appbox_db" (good) variable in ansible scripts
=> PHRAS-1760_Provisionning-error_Master

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php, lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php, resources/ansible/roles/elasticsearch/tasks/main.yml, resources/ansible/vars/all.yml, templates/web/common/macros.html.twig, templates/web/prod/results/record.html.twig
- PHRAS-1539: restore highlight
Bump ES to 2.3.3
=> PHRAS-1539_highlight_4.0

resources/ansible/roles/app/templates/configuration.tpl, resources/ansible/roles/mariadb/tasks/main.yml
- PHRAS-XXX: fix mismatch "database" (bad) -> "appbox_db" (good) variable in ansible scripts
(Backport of PHRAS-1760)
=> PHRAS-1761_Provisionning-error_4.0

resources/www/prod/js/jquery.main-prod.js
- PHRAS-1763 - order facets with base, collections and types at the beginning
=> PHRAS-1763 order facets

resources/www/prod/js/jquery.main-prod.js
- PHRAS-1762: fix arrow navigation when on focus is on facet's treeview
=> Phras 1762 fix arrow keys navigation

resources/www/admin/styles/main.scss, templates/web/admin/editusers.html.twig
- PHRAS-1644: fixed layout of mask dialog
=> PHRAS-1644 mask dialog

resources/www/prod/skins/ui-components/_gui-misc.scss, templates/web/prod/results/infos.html.twig
- PHRAS-1697: add copy to clipboard feature and refactored layout
=> PHRAS-1697 copy clipboard explant

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, resources/www/prod/js/jquery.main-prod.js, resources/www/prod/styles/main.scss, templates/web/prod/actions/delete_records_confirm.html.twig
- PHRAS-1680: refacfored deletion dialog
=> PHRAS-1680 refactor deletion dialog

resources/www/prod/skins/skin-shared.scss
- PHRAS-1768: resize navigation area
=> PHRAS-1768 resize navigation area

templates/web/prod/upload/upload.html.twig
- PHRAS-1769: Fix status being displayed for selected collection
=> PHRAS-1769 status upload collection

templates/web/admin/task-manager/index.html.twig
- PHRAS-1764: refactored admin scheduler
=> PHRAS-1764 admin scheduler

lib/classes/record/preview.php
- PHRAS-1770: Add statistic for current day
=> PHRAS-1770 statistic current day

resources/www/prod/skins/skin-shared.scss
- PHRAS-1768: revert navigation area using percentage
=> PHRAS-1768 revert navigation area

lib/Alchemy/Phrasea/Command/Task/SchedulerRun.php, lib/Alchemy/Phrasea/Command/Task/TaskRun.php, lib/Alchemy/Phrasea/Command/TaskManagerCommand.php
- PHRAS-1772: tasks and taskmanager can be executed as cli even if taskmanager is disabled in conf.
=> PHRAS-1772_Task-Manager-Disabled_4.0

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- PHRAS-1774: output formatters to translate aggregate values
=> PHRAS-1774_Better-aggregates_4.0

resources/ansible/roles/php/tasks/pecl.yml
- PHRAS-1788 Fix zmq provisioning
=> Fix zmq provisioning

resources/www/prod/js/jquery.main-prod.js
Prod, store facet state, close or open, in session.
=> PHRAS-1789 prod store facet state in session

templates/web/prod/index.html.twig
- PHRAS-1712: Porting PHRAS-1542 to 4.1
=> PHRAS-1712 Porting PHRAS-1542 to 4.1

templates/web/prod/WorkZone/Basket.html.twig, templates/web/prod/WorkZone/Story.html.twig, templates/web/prod/toolbar.html.twig
- PHRAS-1727: Porting PHRAS-1577 to 4.1
=> PHRAS-1727 Port PHRAS-1577

.bowerrc, lib/Alchemy/Phrasea/Controller/Prod/ShareController.php, lib/Alchemy/Phrasea/ControllerProvider/Prod/Share.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/Share/record.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Prod/ShareTest.php
- PHRAS-1736: Porting PHRAS-165 and PHRAS-1593 to 4.1
=> PHRAS-1736 port PHRAS-165 and PHRAS-1593

resources/www/common/js/components/common.js
- PHRAS-1748: fix dropdown help-menu
=> PHRAS-1748: fix dropdown on help-menu

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/Alchemy/Phrasea/Databox/Subdef/SubdefPreset.php, lib/Alchemy/Phrasea/Databox/Subdef/SubdefPresetProvider.php, lib/Alchemy/Phrasea/Media/Subdef/Subdef.php, lib/classes/databox/subdef.php, lib/classes/databox/subdefsStructure.php, resources/www/admin/styles/main.scss, templates/web/admin/subdefs.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Admin/SubdefsTest.php
- Add presets selection on subdef admin page.
=> PHRAS-1719 Add presets selection on subdef admin page | Port to 4.1 PHRAS-1317

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/Alchemy/Phrasea/Databox/Subdef/SubdefPreset.php, lib/Alchemy/Phrasea/Databox/Subdef/SubdefPresetProvider.php, lib/Alchemy/Phrasea/Media/Subdef/Subdef.php, lib/classes/databox/subdef.php, lib/classes/databox/subdefsStructure.php, resources/www/admin/styles/main.scss, templates/web/admin/subdefs.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Admin/SubdefsTest.php
- Add presets selection on subdef admin page.
- Remove orderable checkboxes on subdefs groups. Add a orderable checkbox on each subdef.
=> PHRAS-1719 PHRAS-1766 Add subset presets on 4.1

lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php, lib/Alchemy/Phrasea/Controller/Prod/UploadController.php, lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php, lib/Alchemy/Phrasea/Helper/Prod.php, templates/web/prod/index.html.twig
- PHRAS-1726 PORT PHRAS-1559 and PHRAS-1560 to 4.1
=> PORT PHRAS-1559 and PHRAS-1560 to 4.1

templates/web/prod/upload/upload-flash.html.twig, templates/web/prod/upload/upload.html.twig
- PHRAS-1747: Porting PHRAs-1301/PHRAS-1676/PHRAS-1769 to 4.1
=> PHRAS-1747 port phras 1301

templates/web/common/menubar.html.twig
- PHRAS-1739: porting PHRAS-1641 to 4.1
=> PHRAS-1739 porting PHRAS-1641 to 4.1

templates/web/prod/upload/upload-flash.html.twig, templates/web/prod/upload/upload.html.twig
- PHRAS-1741: porting PHRAS-1616 to 4.1
=> PHRAS-1741 porting PHRAS-1616 to 4.1

templates/web/prod/Baskets/Reorder.html.twig, templates/web/prod/Story/Reorder.html.twig
- PHRAS-1778: porting PHRAS-179 to 4.1
=> PHRAS-1778 porting PHRAS-179 to 4.1

templates/web/thesaurus/thesaurus.html.twig
- PHRAS-1779: porting PHRAS-511 to 4.1
=> PHRAS-1779 porting PHRAS-511 to 4.1

lib/classes/record/preview.php
- PHRAS-1782 porting PHRAS-1770 to 4.1
=> PHRAS-1782 porting PHRAS-1770 to 4.1

templates/web/admin/task-manager/index.html.twig
- PHRAS-1783: porting PHRAS-1764 to 4.1
=> PHRAS-1783 porting PHRAS-1764 to 4.1

lib/Alchemy/Phrasea/Command/Setup/Install.php, lib/Alchemy/Phrasea/Controller/SetupController.php, lib/Alchemy/Phrasea/Core/Configuration/StructureTemplate.php, lib/Alchemy/Phrasea/Core/Provider/ConfigurationServiceProvider.php, lib/Alchemy/Phrasea/Setup/Installer.php, templates/web/setup/step2.html.twig
- PHRAS-1717: PORT 1296 - Install CLI/ Graphic mode show all available structure
- PORT-1296 add all functionality for showing all structures available
=> PHRAS-1717- PORT_1296_Show all available structure for install CLI/Graphic mode

resources/ansible/roles/php/tasks/main.yml
- PHRDPL-27 Fix typo on ansible php task.
=> PHRDPL-27 Fix typo on ansible php task

resources/ansible/roles/xdebug/tasks/main.yml, resources/ansible/roles/xdebug/templates/xdebug.ini.j2, resources/ansible/vars/all.yml
- PHRDPL-28 Export xdebug IDEKEY and port to an easy setting of debug configuration.
=> PHRDPL-28 Export xdebug IDEKEY and port to an easy setting of debug

Vagrantfile, resources/ansible/roles/elasticsearch/defaults/main.yml, resources/ansible/roles/elasticsearch/tasks/main.yml, resources/ansible/roles/php/tasks/main.yml, resources/ansible/roles/php/tasks/pecl.yml, resources/ansible/roles/rabbitmq/tasks/main.yml, resources/ansible/vars/all.yml
bump es to 2.3.3
WIP DO NOT MERGE
=> PHRAS-1765 bump es to 2.3.3

resources/ansible/playbook.yml, resources/ansible/roles/app/tasks/main.yml, resources/ansible/roles/elasticsearch/tasks/main.yml, resources/ansible/roles/mariadb/tasks/main.yml, resources/ansible/roles/php/tasks/main.yml, resources/ansible/roles/rabbitmq/tasks/main.yml, resources/ansible/roles/repositories/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-1790 Fix rabbitmq issue
- Export repository url on vars.yml
=> PHRAS-1790 Export repository url on vars, fix rabbitmq issue

resources/ansible/playbook.yml, resources/ansible/roles/ffmpeg/tasks/main.yml, resources/ansible/roles/node/tasks/main.yml, resources/ansible/roles/php/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-1794: fix node version
- PHRAS-1804: fix pecl-packages
- PHRAS-1800: add ffmpeg compilation and version as variable
- fix pecl-packages and node version as variable
=> PHRAS-1794 PHRAS-1800 and PHRAS-1804 : fix pecl-packages and node version

composer.json, composer.lock
- PHRAS-1805: fix PHPexiftool version and add execution
- PHRAS-1718: add Google recaptcha dependencies
=> PHRAS-1805 PHRAS-1718 fix composer dependencies

lib/Alchemy/Phrasea/Command/Developer/JsFixtures.php
- PHRAS-1816 Fix exception message.
=> PHRAS-1816 Fix exception message

lib/Alchemy/Phrasea/Core/Event/Subscriber/RegistrationSubscriber.php
- PHRAS-1818: PHRAS-1818_fix-undefined-method-named-get-job
=> PHRAS-1818 fix RegistrationSubscriber undefined method named get_job

resources/ansible/roles/mariadb/tasks/main.yml
- PHRAS-1823: give "grant" privilege to phraseanet user
=> PHRAS-1823_grant-phraseanet_MASTER

resources/ansible/roles/mariadb/tasks/main.yml
- PHRAS-1829: mariadb grant phraseanet user
=> PHRAS-1829 postport 4.0 grant phraseanet mariadb user

bin/setup, circle.yml, lib/Alchemy/Phrasea/Command/Databox/CreateDataboxCommand.php, lib/Alchemy/Phrasea/Command/Setup/Install.php, lib/Alchemy/Phrasea/Controller/SetupController.php, lib/Alchemy/Phrasea/Core/Configuration/StructureTemplate.php, lib/Alchemy/Phrasea/Core/Provider/ConfigurationServiceProvider.php, lib/Alchemy/Phrasea/Databox/DataboxService.php, lib/Alchemy/Phrasea/Setup/Installer.php, lib/classes/databox.php, tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php, tests/Alchemy/Tests/Phrasea/Setup/InstallerTest.php
- for cli databox:create and system:install, databox template name must bu fully specified (ex. "en-simple", NOT the short way "en")
- PHRAS-1776: fix creation of databox
- PHRAS-1717: databox templates are listed during cli databox:create and system:install.
the default value is "en-simple" or the first available template if "en-simple" was deleted.
- PHRAS-1776: for cli databox:create : if the db-user/pwd has grant to create a database it will do the job
=> Phras 1776 databox create 4.0

resources/ansible/roles/app/tasks/main.yml
- update vagrant provisioning  
- PHRAS-1801: Short description of bug and fix
-  PHRAS-1776 : use the new name for db template
=> vagrant provision: PHRAS-1801 fix populate cmd, PHRAS-1776

lib/Alchemy/Phrasea/Databox/DataboxService.php
=> PHRAS-1776_databox-create_4.0

bin/console, lib/Alchemy/Phrasea/Command/SearchEngine/IndexCreateCommand.php, lib/Alchemy/Phrasea/Command/SearchEngine/IndexDropCommand.php, lib/Alchemy/Phrasea/Command/SearchEngine/IndexManipulateCommand.php, lib/Alchemy/Phrasea/Command/SearchEngine/IndexPopulateCommand.php, lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
- PHRAS-1797 : porting command searchengine:index to 4.1
=> PHRAS-1797 porting searchengine:index to 4.1

www/scripts/apps/admin/fields/views/alert.js, www/scripts/apps/admin/fields/views/create.js, www/scripts/apps/admin/fields/views/dcField.js, www/scripts/apps/admin/fields/views/edit.js, www/scripts/apps/admin/fields/views/fieldError.js, www/scripts/apps/admin/fields/views/list.js, www/scripts/apps/admin/fields/views/listRow.js, www/scripts/apps/admin/fields/views/modal.js, www/scripts/apps/admin/fields/views/save.js, www/scripts/apps/admin/tasks-manager/views/scheduler.js, www/scripts/apps/admin/tasks-manager/views/task.js
- PHRAS-1847: refactored code to use newer version of backbone.js and underscore.js
=> PHRAS-1847 - refactored code for backbone.js and underscore.js

resources/ansible/playbook.yml, resources/ansible/roles/app/tasks/main.yml, resources/ansible/roles/yarn/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-1805 PHRAS-1839 Add yarn setup and make exiftool executable.
=> PHRAS-1805 PHRAS-1839 Add yarn setup and make exiftool executable

bin/setup, lib/Alchemy/Phrasea/Command/Setup/FixAutoincrements.php
- PHRAS-1722: porting mysql restart autoincrement to 4.1
=> PHRAS-1722-mysql-restart-autoincrement

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php, templates/web/prod/actions/Tools/index.html.twig
- PHRAS-1517: Don't display some data in tools/metadata
=> PHRAS-1517-tools-metadata-not-display-binary

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
- PHRAS-1865: Show binary bloc name in tools:metadata
=> PHRAS-1865 show binary bloc name tools/metadata

package-lock.json, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/results/help.html.twig, yarn.lock
- PHRAS-1854: Port PHRAS-1319 to 4.1
=> PHRAS-1854 port PHRAS-1319

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
- PHRAS-1862: allow null values for geonames-server
=> PHRAS-1862 postport PHRAS-1844

resources/ansible/vars/all.yml
- roolback zmq by Pecl stop using ondrej
=> roolback zmq by pecl stop using ondrej

resources/ansible/vars/all.yml
- nothing
- PHRAS-1880: fix yml syntaxe error
=> fix yml syntax error

lib/Alchemy/Phrasea/Controller/Admin/TaskManagerController.php, templates/web/admin/task-manager/index.html.twig, templates/web/admin/task-manager/templates.html.twig, www/scripts/apps/admin/tasks-manager/app.js
- PHRAS-1783: update backend code for PHRAS-1783
=> PHRAS-1783 update backend code for PHRAS-1783

lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php, templates/web/common/technical_datas.html.twig, templates/web/prod/results/item.html.twig, templates/web/prod/results/record.html.twig
- PHRAS-1871: PORT PHRAS-854 to 4.1
=> PHRAS-1871 - PORT PHRAS-854 to 4.1

composer.json, composer.lock, config/configuration.sample.yml, lib/Alchemy/Phrasea/Authentication/Provider/Facebook.php, tests/Alchemy/Tests/Phrasea/Authentication/Provider/FacebookTest.php
- PHRAS-1752 change "facebook/php-sdk": "~3.2.3" to "facebook/graph-sdk": "^5.6"
=> udpate facebook SDK to 5.6

templates/web/prod/index.html.twig
- Port PHRAS-1673 - language selection - to master PHRAS-1720.
=> Port PHRAS-1673 - language selection - to master PHRAS-1720

Vagrantfile
- PHRAS-1882 Add default value on phpversion argument and force user to pick one of the four Ondrej php version.
=> PHRAS-1882 Add default value on phpversion argument

lib/Alchemy/Phrasea/Controller/AbstractDelivery.php
- PHRAS-1858: Porting define filename at download by permalink
=> PHRAS-1858 port-to-4.1-define-filename-at-download

lib/classes/set/export.php
- PHRAS-1406: port 1350 to master - export time out
=> PHRAS-1406 port-1350-to-master

lib/Alchemy/Phrasea/Controller/Prod/RecordController.php, lib/classes/databox.php
- PHRAS-1863 : PORT PHRAS-60
- Add an applicative trash
=> PHRAS-1863 PORT PHRAS-60 Add applicative trash

Vagrantfile
- PHRAS-1882  Update Vagrantfile. phpversion argument fixed.
=> PHRAS-1882 Update Vagrantfile 

circle.yml, lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
- PHRAS-1884 Bump php to 7.0.24 on circle CI and elastic to 2.3.3.
=> PHRAS-1884 Bump php to 7.0.24 on circle CI and elastic to 2.3.3.

composer.lock, lib/Alchemy/Phrasea/Border/Checker/Colorspace.php
- PHRAS-1819: Lazaret checker colorspace add rgba
- Add support for rgba in colorspace checker
- Add allow bypass colorspace checker for document type files
- Updated Mediavorus version
=> PHRAS-1819: Lazaret checker colorspace add rgba

package-lock.json, resources/www/common/styles/main.scss, resources/www/lightbox/styles/main.scss, yarn.lock
- PHRAS-1894: fix index layout on lightbox
=> fix index layout on lightbox

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
- PHRAS-1862: PORT PHRAS-1862 to 4.1
=> PORT PHRAS-1862 to 4.1

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, templates/web/prod/results/infos.html.twig
- PHRAS-1873: dump esquery to results-details/explain dialog (only if user is "super-admin")
=> PHRAS-1873 PORT PHRAS-1685 dump esquery

lib/Alchemy/Phrasea/Command/Developer/RegenerateSqliteDb.php, lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/Controller/Prod/LazaretController.php, lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php, lib/Alchemy/Phrasea/Controller/Prod/UploadController.php, lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php, tests/Alchemy/Tests/Phrasea/Application/OverviewTest.php, tests/Alchemy/Tests/Phrasea/Controller/Prod/LazaretTest.php
- PHRAS-1856: fix missing ext. when a doc was substituted via api.
- calls to obsolete SubdefSubstituer::substitute() renamed (method NOT removed, may be used in plugins)
=> PHRAS-1856_PORT-PHRAS-1347

templates/web/prod/actions/Tools/index.html.twig
- PHRAS-1903: error on tools when multi record selection
=> PHRAS-1903 error-when-multi-record-selection

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, templates/web/prod/index.html.twig
- PHRAS-1904: sort facets via preferences
=> PHRAS-1904 sort facets via preferences

circle.yml, tests/Alchemy/Tests/Phrasea/Model/Manipulator/TokenManipulatorTest.php
- PHRAS-1910 Fix unit tests for 4.0.
=> PHRAS-1910 Fix unit tests for 4.0

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/index.html.twig
- PHRAS-1905: sort facets value alphabetically or by hits
=> PHRAS-1905 sort facets value alphabetically or by hits

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, package-lock.json, templates/web/prod/results/infos.html.twig, yarn.lock
- PHRAS-1781: port PHRAS-1697 to 4.1
=> PHRAS-1781 Port PHRAS-1697 to 4.1

lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php, package-lock.json, yarn.lock
- PHRAS-1899: Port PHRAS-1381 to 4.1 and update npm package
=> PHRAS_1899 Port PHRAS-1381 to 4.1

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php, resources/www/prod/js/jquery.main-prod.js, templates/web/prod/index.html.twig
- PHRAS-1914: Port PHRAS-1904 to 4.0
=> PHRAS-1914 port PHRAS-1904

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, resources/www/prod/js/jquery.main-prod.js, templates/web/prod/index.html.twig
- PHRAS-1915: Port PHRAS-1905 to 4.0
=> PHRAS-1915 port PHRAS-1905

lib/Alchemy/Phrasea/Helper/User/Edit.php, lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php
- PHRAS-1879: apply modification of template on user row from admin
=> PHRAS-1879 apply modification of template on user row from admin

lib/classes/databox/subdef.php
- PHRAS-1920 Add alias on deprecated function used on webgallery plugin
=> PHRAS-1920 Add alias on deprecated function used on webgallery plugin

lib/Alchemy/Phrasea/Helper/User/Manage.php, lib/classes/User/Query.php, templates/web/admin/users.html.twig
- PHRAS-1387: port to master PHRAS-1386
- Add "show special users" filter into admin user list
=> PHHRAS-1387 Admin-hide-guest-account-into-user-list

lib/Alchemy/Phrasea/Helper/User/Edit.php, lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php
- PHRAS-1921: PORT PHRAS-1879 to 4.1
=> PHRAS-1921 PORT PHRAS-1879 to 4.1

templates/web/common/thumbnail.html.twig, templates/web/prod/orders/order_item.html.twig
- PHRAS-1918: display record of type video in order list
=> PHRAS-1918 display record of type video in order list

circle.yml
- PHRAS-1919 Fix circle test with an node upgrade.
=> PHRAS-1919 Fix circle test with an node upgrade

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- PHRAS-1317 Update DPI default value on presets.
=> PHRAS-1317 Update DPI default value on presets

lib/classes/set/export.php, lib/classes/unicode.php, tests/classes/unicodeTest.php
- PHRAS-1316: Port 1205 to master , export/download double extension
=> PHRAS-1316 port-1205-double-extension-issue

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php, lib/Alchemy/Phrasea/ControllerProvider/Prod/Tools.php, templates/web/common/thumbnail.html.twig, templates/web/prod/actions/Tools/index.html.twig
- PHRAS-1898: save video chapters to meta field
=> PHRAS-1898 save video chapters to meta field

templates/web/common/index_bootstrap.html.twig
- PHRAS-1924: add jquery-ui library to resolve error when downloading assets
=> PHRAS-1924 fix error with jquery on download assets page

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/MetadataHelper.php, lib/classes/media/subdef.php, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
- PHRAS-1911: add route return list documentary fields
- refactor : added static function getTechnicalFieldsList()
- added tests
=> PHRAS-1911-add route return list documentary fields

package-lock.json, templates/web/prod/index.html.twig, yarn.lock
- PHRAS-1916: refactor layout of facet preferences
=> PHRAS-1916 refactor layout of facet preferences

lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
- PHRAS-398: add log info in the archive task
=> PHRAS-398 log-tache-d-archivage

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
- PHRAS-1317 update dpi subdefs values on 4.0.
=> PHRAS-1317 update dpi subdefs values on 4.0

lib/Alchemy/Phrasea/Controller/Prod/Records.php
- PHRAS-1730: add event "edit" on story(ies) when a record is deleted
=> PHRAS-1730_story-edit-event-on-record-delete_3.8

composer.lock, lib/Alchemy/Phrasea/Border/Checker/Colorspace.php
- PHRAS-1893 : Lazaret checker colorspace add rgba
- Add support for rgba in colorspace checker
- Add allow bypass colorspace checker for document type files
- Updated Mediavorus version
=> PHRAS-1893_POSTPORT_PHRAS-1819

lib/Alchemy/Phrasea/Command/Setup/XSendFileMappingGenerator.php, lib/Alchemy/Phrasea/Databox/DataboxPathExtractor.php
- PHRAS-1375 : config xsendfile ne fonctionne plus
=> PHRAS-1375 config xsendfile ne fonctionne plus

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/admin/users.html.twig
- PHRAS-1387: add checkbox text translation
=> PHRAS-1387 update translation

templates/web/common/index_bootstrap.html.twig, templates/web/common/indexfloat.html.twig
- PHRAS-1937 - fix preview permalink new
=> PHRAS-1937 - fix preview permalink new

package.json, yarn.lock
- PHRAS-1938: remove npm in package.json section "scripts" and use yarn instead
=> PHRAS-1938 package.json-scripts-section-remove-npm-use-yarn

lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/actions/Tools/videoEditor.html.twig
- PHRAS-1935: refactored layout and functionalities of video range extractor
=> PHRAS-1935 refacto prod video editor - video range editor

tests/Alchemy/Tests/Phrasea/Model/Manipulator/TokenManipulatorTest.php
- PHRAS-1828: Download link validity
- Fix tests
=> PHRAS-1828_download_link_validity

lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php, templates/web/prod/actions/Tools/videoEditor.html.twig
- PHRAS-1936: save overlapChapters in video editor in preferences
=> PHRAS-1936 save overlapChapters in video editor in preferences

templates/web/admin/user/import/file.html.twig
- PHRAS-1951: Short description of bug and fix
- fix user's cvs file import error on windows
=> PHRAS-1951 fix user cvs file import error on windows

templates/web/prod/preview/basket_train.html.twig, templates/web/prod/preview/feed_train.html.twig, templates/web/prod/preview/reg_train.html.twig, templates/web/prod/preview/result_train.html.twig, templates/web/prod/preview/result_train_options.html.twig
- PHRAS-1959: fix slideshow functionality in detail screen
=> PHRAS-1959 fix slideshow functionality in detail screen

lib/Alchemy/Phrasea/SearchEngine/Elastic/FieldMapping.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/MappingBuilder.php
- PHRAS-1809: Add a "location" field in records (type="geo_point"), populated with same values as "Longitude" and "Latitude" technical fields.
=> PHRAS-1809_Geoinfos-in-index_4.0

templates/web/common/thumbnail.html.twig
- PHRAS-1970 fix preview ratio when zooming in detail screen
=> PHRAS-1970 fix preview ratio when zooming in detail screen

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/MetadataHelper.php, lib/classes/media/subdef.php, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
- PHRAS-1925 : add route return list documentary fields
=> PHRAS-1925-add route return list documentary fields

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-1911 : fix fields structure
=> PHRAS-1911 fix fields structure

grammar/query.pp, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/NativeKey.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/NodeTypes.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php
- PHRAS-483: add index (not analysed) & search on fields "sha256" and "uuid"
e.g. : uuid:"4d006e01-bc38-4aac-9a5b-2c90ffe3a8a2"
e.g. : sha256:a7f3ec01c4c5efcadc639d494d432006f13b28b9a576afaee4d3b7508c4be074
=> PHRAS-483_SHA-UID_master

templates/web/admin/subdefs.html.twig
=> PHRAS-2007 Update wording keys

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
- PHRAS-1925: fix route me/structures
=> PHRAS-1925 : fix route me/structures

lib/Alchemy/Phrasea/Border/File.php
- PHRAS-2001: Add UUID source
-  Add XMP-xmpMM:DocumentID in the available UUID source
=> PHRAS-2001 add uuid source

resources/locales/messages.en.xlf
=> Fixed typo in translation

config/configuration.sample.yml, lib/Alchemy/Phrasea/Border/Checker/Colorspace.php, tests/Alchemy/Tests/Phrasea/Border/Checker/ColorspaceTest.php
- PHRAS-1819: add quarantine rule based on media type in configuration file
=> PHRAS-1819: add quarantine rule based on media type

lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php, templates/web/prod/actions/edit_default.html.twig
- PHRAS-2026: refactor suggested values on edit view
=> PHRAS-2026 refactor suggested values on edit view

resources/www/prod/js/record.editor.js, resources/www/prod/skins/ui-components/_modal-edit.scss, templates/web/prod/actions/edit_default.html.twig
- PHRAS-2022 move location of suggested values in edit view
=> PHRAS-2022 move suggested values

lib/Alchemy/Phrasea/TaskManager/Job/FtpJob.php
- PHRAS-1932: FTP export task : generates an error while sending files
- Add locator to FtpJob
=> PHRAS-1932 FTP export task

composer.lock
- PHRAS-1997: add indesign support
- Update mediavorus version to 0.4.7
=> PHRAS-1997-PORT-PHRAS-1991

lib/Alchemy/Phrasea/Controller/Admin/TaskManager.php
- PHRAS-1912: Fix build issue on packager 3.8
=> PHRAS-1912 build issue phraseanet packager

composer.lock
- PHRAS-1976: Use composite datasource
- update alchemy/mediavorus  from 0.4.7 to 0.4.8
=> PHRAS-1976 use composite datasource

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
- PHRAS-2032: Port to 4.1  PHRAS-1992
- Add route me/collections, return the actual result collections of route "me/" with name, logo, labels
=> PHRAS-2032 port to 4.1 api route me/collections

resources/www/lightbox/styles/main-mobile.scss, templates/mobile/common/thumbnail.html.twig, templates/mobile/lightbox/basket_element.html.twig, templates/mobile/lightbox/feed_element.html.twig
- PHRAS-2034: fix ui and dialog on lightbox mobile version
=> PHRAS-2034 fix ui and dialog lightbox mobile version

resources/www/lightbox/styles/main-mobile.scss, templates/mobile/common/thumbnail.html.twig, templates/mobile/lightbox/basket_element.html.twig, templates/mobile/lightbox/feed_element.html.twig
- PHRAS-2034 add scroll for webkit
=> PHRAS-2034 add scroll for webkit

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2025: regex for obtaining color values from text refactored
=> PHRAS-2025 facets color - refactored

resources/www/authentication/styles/main.scss
- PHRAS-2037: fix responsive ui of login page
=> PHRAS-2037 fix responsive ui of login page

lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2035: postport to 4.0 PHRAS-1999
- build preview for indesign file
=> PHRAS-2035 postport to 4.0 build preview for indesign file

lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-1999: Core / Build Preview for indesign document
- use embed preview to build indesign document subdef
=> PHRAS-1999 Core / Build Preview for indesign document

templates/web/prod/index.html.twig
- PHRAS-2040: memorizing enable and disable status of facets
=> PHRAS-2040 memorizing enable and disable status of facets

lib/Alchemy/Phrasea/Controller/Admin/RootController.php
- PHRAS-859: fix bug with special characters in status label
=> PHRAS-859 fix bug with special characters in status label

templates/web/login/common/macros.html.twig
- PHRAS-1163: fix translation of text on login page
=> PHRAS-1163 fix translation of text on login page

templates/web/thesaurus/thesaurus.html.twig
- PHRAS-1565: Fix focus on input field on thesaurus dialog
=> PHRAS-1565 Fix focus on input field on thesaurus dialog

lib/Alchemy/Phrasea/Status/XmlStatusStructureProvider.php
- PHRAS-1051 fix delete function for status icons
=> PHRAS-1051 fix delete function for status icons

templates/web/login/common/macros.html.twig
- PHRAS-2052: port PHRAS-1163 to 4.0
=> PHRAS-2052 port PHRAS-1163 to 4.0

lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php, resources/www/prod/skins/skin-shared.scss, resources/www/prod/skins/ui-components/_workzone-proposals.scss, templates/web/common/macros.html.twig
- PHRAS-2051: created twig filter to convert hex code to icons
=> PHRAS-2051 hex as icon 4.0

lib/classes/User/Query.php
- PHRAS-1753: User template list
- Template menu list user's template and FIX modele filter in Prod/ user list PHRAS-1613
=> PHRAS-1753 list user template and FIX modele filter

lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php, templates/web/common/macros.html.twig
- PHRAS-2053: port PHRAS 2051 to 4.1
=> PHRAS-2053 port PHRAS 2051 to 4.1

templates/web/common/menubar.html.twig
- PHRAS-1122: show display name in menu bar if exist
=> PHRAS-1122 Show display name in menu bar if exist

lib/Alchemy/Phrasea/Out/Module/PDF.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/actions/printer_default.html.twig
- PHRAS-1562: Export print: Wish to add a print mode Legend only
=> PHRAS-1562 add Export/ print caption

templates/web/admin/collection/reorder.html.twig, templates/web/prod/index.html.twig
- PHRAS-2057: Port to 4.1 - Admin / Ordre des collections : Altérer l'ordre des collections n'est pas pris en compte
=> PHRAS-2057 port to 4.1 admin/ordre des collections

templates/web/common/menubar.html.twig
- PHRAS-2054: port PHRAS-1122 to 4.0
=> PHRAS-2054 port PHRAS-1122 to 4.0

lib/Alchemy/Phrasea/Application/ApiApplicationLoader.php, templates/web/api/auth/end_user_authorization.html.twig
- PHRAS-2061:  authorize : Extend Phraseanet homepage login providers
=> PHRAS-2061 authorize : Extend Phraseanet homepage login providers

templates/web/admin/collection/collection.html.twig, templates/web/admin/collection/reorder.html.twig
-PHRAS-2064: fix reordering of collections from admin interface
=> PHRAS-2064 fix reordering of collections from admin interface

templates/web/admin/subdefs.html.twig
- PHRAS-2007 Update wordings key
=> PHRAS-2007 Update wordings key

resources/www/_shared/styles/_main-menu.scss, templates/web/common/menubar.html.twig
- PHRAS-2055: convert navigation menu to dropdown on small screen
=> PHRAS-2055 convert navigation menu to dropdown on small screen

lib/Alchemy/Phrasea/Application/ApiApplicationLoader.php, lib/Alchemy/Phrasea/Authentication/Provider/Facebook.php, lib/Alchemy/Phrasea/Authentication/Provider/Github.php, lib/Alchemy/Phrasea/Authentication/Provider/GooglePlus.php, lib/Alchemy/Phrasea/Authentication/Provider/Linkedin.php, lib/Alchemy/Phrasea/Authentication/Provider/ProviderInterface.php, lib/Alchemy/Phrasea/Authentication/Provider/Twitter.php, lib/Alchemy/Phrasea/Authentication/Provider/Viadeo.php, lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php, lib/Alchemy/Phrasea/ControllerProvider/Api/OAuth2.php, templates/web/api/auth/end_user_authorization.html.twig
- PHRAS-2061:Fix oauth authorize provider redirect
=> PHRAS-2061 fix oauth authorize redirect

resources/www/_shared/styles/_main-menu.scss, templates/web/common/menubar.html.twig
- PHRAS-2055: fix custom links on navigation bar
=> PHRAS-2055 fix custom links on navigation bar

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- PHRAS-1902: Port To 4.1 - PHRAS-1774 Better technical metadata/agregates
=> PHRAS-1902 port 1774 better agregate to 4.1

lib/Alchemy/Phrasea/Setup/Requirements/PhpRequirements.php
- change session.cookie_secure message, add HTTPS in message
=> PHRAS-2041 port to 4.1 session.cookie_secure message

lib/Alchemy/Phrasea/Controller/Admin/RootController.php, templates/web/admin/statusbit/edit.html.twig
- PHRAS-2050: PORT PHRAS-859 to 4.0
=> PHRAS-2050 PORT PHRAS-859 to 4.0

lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php
=> PHRAS-2061 update Oauth2Controller

lib/Alchemy/Phrasea/Authentication/Provider/Facebook.php, lib/Alchemy/Phrasea/Authentication/Provider/Github.php, lib/Alchemy/Phrasea/Authentication/Provider/GooglePlus.php, lib/Alchemy/Phrasea/Authentication/Provider/Linkedin.php, lib/Alchemy/Phrasea/Authentication/Provider/ProviderInterface.php, lib/Alchemy/Phrasea/Authentication/Provider/Twitter.php, lib/Alchemy/Phrasea/Authentication/Provider/Viadeo.php, lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php, lib/Alchemy/Phrasea/ControllerProvider/Api/OAuth2.php, templates/web/api/auth/end_user_authorization.html.twig
- PHRAS-2062: port to 4.1 PHRAS-2061 authorize : Extend Phraseanet homepage login providers
=> PHRAS-2062 port 2061 authorize with providers

lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
- PHRAS-2065: port to 4.1 PHRAS-1730 - deleting a record should "edit" stories it did belongs to
=> PHRAS-2065 port PHRAS-1730 to 4.1: dispatch record.edit event

lib/Alchemy/Phrasea/Controller/Admin/SetupController.php, lib/Alchemy/Phrasea/Form/Configuration/GeneralFormType.php, lib/Alchemy/Phrasea/Form/Configuration/PersonalisationLogoForm.php, resources/www/admin/styles/main.scss, templates/web/admin/personalisation_logo.html.twig, templates/web/admin/setup.html.twig
- PHRAS-2079: WIP Add personalisation logo section in admin/setup
=> PHRAS-2079 design personalisation logo

templates/web/admin/personalisation_logo.html.twig
- PHRAS-2079: refactor function to upload image file to server
=> PHRAS-2079 refactor function to upload image file to server

resources/www/_shared/styles/_main-menu.scss, templates/web/common/menubar.html.twig
- PHRAS-2091: update breakpoint to 1064 and refactor search bar
=> PHRAS-2091 update breakpoint

lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/Subdef/Image.php
- PHRAS-2000: generate pdf subdef
=> PHRAS-2000 generate pdf subdef

resources/www/_shared/styles/_main-menu.scss, resources/www/_shared/styles/_notification.scss, resources/www/common/js/components/common.js, templates/web/common/menubar.html.twig
-PHRAS-2093 refactor notification on mobile version
=> PHRAS-2093 refactor notification on mobile version

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_workzone-proposals.scss
- PHRAS-2073: Port PHRAS-2058 to 4.0
=> PHRAS-2073 port PHRAS-2058 to 4.0

config/configuration.sample.yml
- PHRAS-1998: update configuration.sample.yml file with geocoding-provider settings
=> PHRAS-1998 update configuration.sample.yml file with geocoding-provider settings

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/Subdef/Pdf.php, lib/Alchemy/Phrasea/Media/Subdef/Specification/PdfSpecification.php, lib/Alchemy/Phrasea/Media/Subdef/Subdef.php, lib/Alchemy/Phrasea/Media/SubdefGenerator.php, lib/classes/databox/subdef.php, tests/Alchemy/Tests/Phrasea/Media/Subdef/PdfTest.php, tests/Alchemy/Tests/Phrasea/Media/Subdef/Specification/PdfSpecificationTest.php, tests/classes/databox/subdefTest.php
- PHRAS-2094: PostPort to 4.0 Core - databox - define and generate PDF subdef for phraseanet type "Document" and "Image"
=> PHRAS-2094 generate subdef pdf

templates/web/prod/WorkZone/Basket.html.twig, templates/web/prod/WorkZone/Story.html.twig
- PHRAS-2103: refactor basket and story dropdown menu
=> PHRAS-2103 refactor basket and story dropdown menu

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/WorkZone/Basket.html.twig, templates/web/prod/WorkZone/Story.html.twig
-PHRAS-2103: rename placeholders for delete buttons
=> PHRAS-2103 rename placeholders for delete buttons

.travis.yml
- PHRAS-2016: fix travis build
=> PHRAS-2016_travis-circle-config-matrix_master

lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20180614113404.php
- PHRAS-2105: doctrine migration script for old guest account
=> PHRAS-2105 doctrine migration script for old guest account

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
- PHRAS-2106: Facets on "Camera Model" are NOK
=> PHRAS-2106 facets on camera model

lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2113: Port to 4.0 generate video subdef in specified path and copy it into correct path
=> PHRAS-2113 Port to 4.0 generate video subdef in specified path and copy it into correct path

lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2112: generate video subdef in specified path and copy it into correct path
- Find temporary directory in CONF registry > executables > ffmpeg-tmp-directory
=> PHRAS-2112 generate video subdef in temporary path first

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/classes/databox/subdefsStructure.php
- PHRAS-2115: admin - database -subwiew create, PDF option don't appear is media type dropdown
=> PHRAS-2115  admin - database -subwiew create, PDF option don't appear is media type dropdown

lib/Alchemy/Phrasea/Authentication/RegistrationService.php, lib/classes/collection.php, lib/classes/databox.php
- PHRAS-2096: Add a whitelist to filter autoregistration
(backport of PHRAS-2096)
=> PHRAS-2109_Autoregister-Whitelist_4.0

lib/Alchemy/Phrasea/Authentication/RegistrationService.php, lib/Alchemy/Phrasea/Core/Event/Subscriber/RegistrationSubscriber.php, lib/classes/collection.php, lib/classes/databox.php
- bug in registration email
- PHRAS-2096: Add a whitelist to filter autoregistration
=> PHRAS-2096_Autoregister-Whitelist_MASTER

lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2118: Use "tmp_files" storage for proxy generation in all cases (mean for all media type , image pdf etc... )
=> PHRAS-2118 use tmp_files storage for generating all mediatype

.travis.yml, Vagrantfile, resources/ansible/roles/nginx/templates/default.j2, resources/ansible/roles/php/tasks/main.yml, resources/ansible/roles/php/tasks/pecl.yml, resources/ansible/roles/xdebug/tasks/main.yml, resources/ansible/vars/all.yml, resources/ansible/windows.sh
- Add php version choice on 4.0 ansible provisionning.
=> Add php version choice on 4.0 ansible provisionning.

lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
- PHRAS-2119: Use tmp_files for tmp files during an upload
=> PHRAS-2119 use tmp_files on upload file

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/BulkOperation.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/MappingBuilder.php
- PHRAS-2126: es error message during indexation is now dumped (not always a string)
- PHRAS-2126: es file "size" is now type "long"
=> PHRAS-2126_Array-to-String-err-idx_4.1

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-2124: api substitute update subview when substitute is the "document"
=> PHRAS-2124 api substitute update subview when substitute is the "document"

Vagrantfile, resources/ansible/inventories/dev
- PHRAS-2134: Add inventories dev file on ansible.
- PHRAS-2135 Remove mount options on Vagrantfile.
=> PHRAS-2135 - PHRAS-2134 Add inventories dev file on ansible

lib/Alchemy/Phrasea/Command/Developer/RegenerateSqliteDb.php, lib/Alchemy/Phrasea/Core/Event/Listener/OAuthListener.php, lib/Alchemy/Phrasea/Core/Event/Subscriber/PhraseaInstallSubscriber.php, lib/Alchemy/Phrasea/Core/Version.php, lib/Alchemy/Phrasea/Model/Manipulator/ApiApplicationManipulator.php, lib/classes/API/OAuth2/Application/AdobeCCPlugin.php, lib/classes/patch/410alpha10a.php
- PHRAS-2086: add an "adobe_cc-plugin" api application
require system:upgrade to go to 4.1.0-alpha.10
must be enabled via "adobe_cc-enabled" in conf
=> PHRAS-2086_AdobeCC-AppToken_4.1

Vagrantfile, resources/ansible/inventories/GetIpAdresses.cmd
- PHRAS-2140 Check OS for SMB or NFS filesystem strategy. Now, we can install and make symlinks on SMB filesystem when OS is windows.
=> PHRAS-2140 Check OS for SMB or NFS folder strategy

lib/Alchemy/Phrasea/Command/Developer/RegenerateSqliteDb.php, lib/Alchemy/Phrasea/Core/Event/Listener/OAuthListener.php, lib/Alchemy/Phrasea/Core/Event/Subscriber/PhraseaInstallSubscriber.php, lib/Alchemy/Phrasea/Core/Version.php, lib/classes/API/OAuth2/Application/AdobeCCPlugin.php, lib/classes/patch/410alpha10a.php
- PHRAS-2086: Add app token For adobe cc Phraseanet plugin
- Fix PR 2662
=> PHRAS-2086 Add app token For adobe cc Phraseanet plugin

lib/Alchemy/Phrasea/Core/Version.php, lib/Alchemy/Phrasea/Setup/DoctrineMigrations/Version20180614113404.php, lib/classes/patch/410alpha11a.php
- PHRAS-1929: guest account patch doctrine migration
=> PHRAS-1929 guest account patch doctrine migration

lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
- PHRAS-2151: PostPot to 4.0 - Api / Order / Archive : zip archive is created at the application document root (www)
- use tmp/download directory
=> PHRAS-2151 PostPot to 4.0 - Api / Order / Archive : zip archive is created at the application document root (www)

lib/Alchemy/Phrasea/ControllerProvider/Root/Account.php, lib/Alchemy/Phrasea/ControllerProvider/Root/Developers.php
- PHRAS-2142: Creating API app need to be forbiden for guest account.
=> PHRAS-2142 Creating API app need to be forbiden for guest account

lib/Alchemy/Phrasea/Controller/Api/Result.php, lib/Alchemy/Phrasea/Core/Event/Listener/OAuthListener.php, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
- PHRAS-1993: API / API answer / the age of token define API version in answer
=> PHRAS-1993 API / API answer / the age of token define API version in answer

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php, lib/Alchemy/Phrasea/Form/Configuration/APIClientsFormType.php
- PHRAS-2088: admin- setup- checkbox for activate/desactivate plugin Adobe cc connection
=> PHRAS-2088 add checkbox authorize adobecc plugin in admin / setup

Makefile
- PHRAS-2159: change yarn cmd in Makefile
=>  PHRAS-2159 change yarn cmd in Makefile

lib/Alchemy/Phrasea/TaskManager/Job/FtpPullJob.php, lib/classes/ftpclient.php
- PHRAS-2092: admin / task-manager / ftp-pull task : generate errors and stops
=> PHRAS-2092 admin / task-manager / ftp-pull task : generate errors and stops

circle.yml, lib/Alchemy/Phrasea/Command/Developer/RegenerateSqliteDb.php, lib/Alchemy/Phrasea/Core/Event/Listener/OAuthListener.php, lib/Alchemy/Phrasea/Core/Event/Subscriber/PhraseaInstallSubscriber.php, lib/Alchemy/Phrasea/Core/Version.php, lib/classes/API/OAuth2/Application/AdobeCCPlugin.php, lib/classes/patch/403a.php
- PHRAS-2148: Postport PHRAS-2086 to 4.0 - Add app token For adobe cc Phraseanet plugin
- update version
=> PHRAS-2148 Postport to 4.0 - Add app token For adobe cc Phraseanet plugin

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf
- PHRAS-2155: Phraseanet Graphic installer are NOK
- remove line break on translation key 'Warning, this database is not empty'
=> PHRAS-2155 Phraseanet Graphic installer are NOK

lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
- Bump Phraseanet version to 2.0.0
=> bump api version to 2.0.0

lib/Alchemy/Phrasea/Controller/SetupController.php, templates/web/setup/step2.html.twig, templates/web/setup/wrapper.html.twig
- PHRAS-2155: Add SearchEngine step in graphic installer
- Change text "PHRASEANET" to "Phraseanet"
=> PHRAS-2155 graphic installer - add elastic step

lib/Alchemy/Phrasea/Controller/Api/Result.php, lib/Alchemy/Phrasea/Core/Event/Listener/OAuthListener.php, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiTestCase.php
- PHRAS-2160:  PostPort tp 4.0 - API / API answer / the age of token define API version in answer
=> PHRAS-2160 PostPort to 4.0 - API / API answer / the age of token define API version in answer

lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
- bump api version to 2.0.0 PHRAS-2163
=> Postport PHRAS-2163 bump api version to 2.0.0

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/classes/databox.php, lib/classes/databox/subdefsStructure.php, templates/web/admin/subdefs.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Admin/SubdefsTest.php
- PHRAS-2122: admin -bases - base - subviews setup create new subdef , path is empty
=> PHRAS-2122 admin -bases - base - subviews setup create new subdef , path is empty

lib/Alchemy/Phrasea/Controller/Root/AccountController.php
- PHRAS-2164: masquing some native Api application in user porfil -> Application tab
=> PHRAS-2164 User profil - application section , masquing of app created for adobe cc plugin

lib/Alchemy/Phrasea/Controller/Root/AccountController.php
- PHRAS-2166: PostPort to 4.0 - User profil - application section , masquing of app created for adobe cc plugin
=> PHRAS-2166 PostPort to 4.0 - User profil - application section , masquing of app created for adobe cc plugin

lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php, lib/Alchemy/Phrasea/Model/Repositories/UserRepository.php
- PHRAS-2172: the user application was updated (=created) after the check
- "find()" on user repo (type hinted) to allow code sniff, completion etc.
=> PHRAS-2172_parade-saml-err500_MASTER

lib/Alchemy/Phrasea/TaskManager/Job/SubdefsJob.php, lib/classes/Bridge/Account.php, lib/classes/Bridge/Element.php, lib/classes/base.php, lib/classes/databox/field.php, lib/classes/record/adapter.php
- PHRAS-2165: Sub_view task need to keep mysql connection Open like bin/console record:buildsubdef
- keep mysql connection alive
=> PHRAS-2165 keep mysql connection alive

lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2118:  rollback use just tmp_files storage for video
=> PHRAS-2118 rollback use just tmp_files storage for video

lib/Alchemy/Phrasea/TaskManager/Job/SubdefsJob.php, lib/classes/API/Webhook.php, lib/classes/Bridge/Account.php, lib/classes/Bridge/Element.php, lib/classes/base.php, lib/classes/databox/field.php, lib/classes/record/adapter.php
- PHRAS-2173: Postport To 4.0 - Sub_view task need to keep mysql connection Open like bin/console record:buildsubdef
- keep connection alive
=> PHRAS-2173 postport keep connection alive

lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php, lib/Alchemy/Phrasea/Model/Repositories/UserRepository.php
- PHRAS-2176: Postport to 4.0 - First saml auth on parade display err 500
=> PHRAS-2176 postport PHRAS-2172 : First saml auth display err 500

lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2179: Postport To 4.0 - Add subdef building duration in subdef task log
=> PHRAS-2179 Postport To 4.0 - Add subdef building duration in subdef task log

templates/web/prod/actions/Feedback/list.html.twig
=> renaming label Template to Models

lib/Alchemy/Phrasea/TaskManager/Notifier.php
- PHRAS-2180: change notifier timeout
=> PHRAS-2180 change notifier timeout

lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2179 : fix duration in log
- add file size
=> PHRAS-2179 task log add duration and file size

templates/web/prod/actions/Feedback/ListsMacros.html.twig, templates/web/prod/actions/Feedback/list.html.twig
- PHRAS-2187: fix page navigation
- Move "selected people" to top
=> PHRAS-2187 move selected people to top, fix page navigation

lib/classes/User/Query.php
- PHRAS-2185: List - Manager - advance mode - 500 error when select a criteria
- change field name in user query
=> PHRAS-2185 List - Manager - advance mode - 500 error when select a criteria

Vagrantfile, resources/ansible/roles/app/tasks/main.yml
- Add swap allocation on VM and async composer task.
=> Add swap allocation on VM and async composer task

.travis.yml
=> PHRAS-2209 disable travis

lib/Alchemy/Phrasea/Core/Configuration/Configuration.php
- PHRAS-2205: Change the configuration file content update methode : when saving from admin/setup
- change file content instead of recreate config file
=> PHRAS-2205 Change the configuration file content update methode : when saving from admin/setup

lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2175: fix size in task log
=> PHRAS-2175 fix size in task log

lib/Alchemy/Phrasea/Core/Configuration/Configuration.php
- PHRAS-2205: change default mod to 650
=> PHRAS-2205 Change default mod when change the configuration file content

lib/Alchemy/Phrasea/Core/Configuration/Configuration.php
- PHRAS-2205: POST PORT to 4.0 change file content instead of recreate config file
=> PHRAS-2205 postport to 4.0 : Change the configuration file content update methode : when saving from admin/setup

lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2179: fix task log size
=> PHRAS-2179 task log size

resources/www/admin/styles/main.scss, templates/web/admin/subdefs.html.twig, www/scripts/apps/admin/search-engine/views/es_config.js
- PHRAS-2212: Refacto design of user alert windows in admin
=> PHRAS-2212_refacto_admin_user_alerts

package-lock.json, templates/web/prod/actions/Feedback/list.html.twig, templates/web/prod/templates/push.html.twig
- PHRAS-2186: List manager - advance mode / add user fix
=> PHRAS-2186_list_manager_add_user

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf
- PHRAS-2191: generated new string translations
=> PHRAS-2191_string_translations generated

templates/web/prod/actions/Feedback/List-Share.html.twig, templates/web/prod/actions/Feedback/lists-all.html.twig
- PHRAS-2100: list manager modals UI refacto
=> PHRAS-2100_refactoring_list_manager modals UI

resources/www/_shared/styles/_main-menu.scss
- PHRAS-2217: fixing header (navbar) height and sidebar margin in admin
=> PHRAS-2217_admin_header_height_fix

bower.json, lib/Alchemy/Phrasea/Core/Version.php
- PHRAS-1792: bump version number on bower.json version.php.
Play bin/setup system:upgrade
=> Bump phraseanet version to 4.0.3

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/actions/Feedback/List-Share.html.twig, templates/web/prod/actions/Feedback/ListsMacros.html.twig, templates/web/prod/actions/Feedback/list.html.twig, templates/web/prod/actions/Feedback/lists-all.html.twig, templates/web/prod/actions/Push.html.twig, templates/web/prod/templates/push.html.twig
- PHRAS-2223: list manager corrections
=> PHRAS-2223_list_manager___corrections

lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
- PHRAS-2226: change log level to info in ArchiveJob
=> PHRAS-2226 Backport to 4.0 TASK - Rétablir le log de La tache d'archivage Reactivated the logs of the archive task

templates/web/prod/actions/Feedback/ListsMacros.html.twig, templates/web/prod/actions/Feedback/list.html.twig
- PHRAS-2222: Correction design on list manager advance mode window
=> PHRAS-2222_list_manager_advance_mode__corrections

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf
- PHRAS-2222: translation files update
=> PHRAS-2222_list_manager_advance_mode translations update

templates/web/prod/actions/Feedback/list.html.twig, templates/web/prod/actions/Push.html.twig
- PHRAS-2219: push window UI corrections
=> PHRAS-2219_push_window__corrections

templates/web/prod/templates/push.html.twig
- PHRAS-2220: feedback window UI corections
=> PHRAS-2220_feedback_window_UI__correction

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-2245 (backport of PHRAS-2124) : force subdefs re-creation after document substitute
=> PHRAS-2245_Backport-PHRAS-2124_4.0

lib/Alchemy/Phrasea/Core/Version.php, lib/classes/patch/410alpha12a.php, lib/conf.d/bases_structure.xml
- PHRAS-2171: extend "mime" columns (record, subdef) to 255 to allow long mimes & try to fix truncated mime.
=> PHRAS-2171_mime-truncated_MASTER

lib/Alchemy/Phrasea/Core/Version.php, lib/classes/patch/404a.php, lib/conf.d/bases_structure.xml
- PHRAS-2171: expand record.mime and subdef.mime to char(255), try to fix truncated mimes
=> PHRAS-2171_mime-truncated_4.0

lib/Alchemy/Phrasea/TaskManager/Job/FtpPullJob.php, lib/classes/ftpclient.php
- PHRAS-2250:  ftp-pull task generates errors and stops
=> PHRAS-2250 admin / task-manager / ftp-pull task : generate errors and stops

resources/www/permaview/styles/main.scss
- PHRAS-2237 4.0 fix Update demands design.
=> PHRAS-2237 | (4.0) fix demands design

resources/www/prod/skins/ui-components/_modal-advanced-search.scss, resources/www/prod/skins/ui-components/_search-form.scss
- PHRAS-2238: advanced search corrections fix
=> PHRAS-2238_advance_search_refacto__corrections fix

resources/www/prod/skins/ui-components/_search-form.scss
- PHRAS-2238: advance search text input color correction
=> PHRAS-2238_advance_search_refacto__corrections fix text input color

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/index.html.twig
- PHRAS-2238: advance search info text translation fix
=> PHRAS-2238_advance_search_refacto__info_text_correction

resources/www/prod/js/jquery.main-prod.js, templates/web/prod/index.html.twig
- PHRAS-2238: search query bug fix
=> PHRAS-2238_advance_search_refacto__search_query_correction

lib/Alchemy/Phrasea/Filesystem/LazaretPathBooker.php, templates/web/prod/results/record.html.twig, templates/web/prod/upload/lazaret.html.twig
- PHRAS-2230 : Prod IHM - Quarantine - Substitute action for asset is NOK
- PHRAS-2214 : Quarantine - special characteres in filename of uploaded file, block actions, (add, substitute, delete)
=> PHRAS-2230 quarantine action nok

resources/ansible/roles/app/tasks/main.yml
=> Symfony 4 installation - Disable frontend installation #2

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php, lib/Alchemy/Phrasea/Form/Configuration/APIClientsFormType.php
- PHRAS-2259: add checkbox in admin to activate adobe cc plugin
=> PHRAS-2259 admin- setup- checkbox for activate/desactivate plugin Adobe cc connection

templates/web/prod/results/record.html.twig, templates/web/prod/upload/lazaret.html.twig
- PHRAS-2257: Prod IHM - Quarantine - Substitute action for asset is NOK.
=> PHRAS-2257 Prod IHM - Quarantine - Substitute action for asset is NOK.

resources/www/prod/skins/ui-components/_modal-advanced-search.scss, resources/www/prod/skins/ui-components/_search-form.scss
- PHRAS-2238: advance search additional corrections
=> PHRAS-2238_advance_search_refacto___corrections_NEW fix

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_modal-advanced-search.scss, resources/www/prod/skins/ui-components/_search-form.scss, templates/web/prod/index.html.twig
- PHRAS-2238: advanced search new corrections UI and semantics
=> PHRAS-2238_advance_search_refacto__corrections_NEW

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2238: advanced search field select filter bug fix
=> PHRAS-2238_advance_search_refacto___corrections_NEW fix field select filter

lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
- PHRAS-2233: the magic file is now "special" and not moved after archiving (but deleted or re-created if needed)
=> PHRAS-2233_magic-file-in-error_4.0

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_modal-advanced-search.scss, templates/web/prod/index.html.twig
- PHRAS-2238: advance search corrections, scroll bar expand and responsive columns fix
=> PHRAS-2238_advance_search_refacto___corrections_NEW scroll bar and responsive

resources/www/prod/skins/ui-components/_modal-advanced-search.scss, templates/web/prod/index.html.twig
- PHRAS-2238: advance search - buttons width fix
=> PHRAS-2238_advance_search_refacto___corrections_NEW button width fix

resources/www/permaview/styles/main.scss
- PHRAS-2237 - Update table design to keep space when no entry in field.
=> PHRAS-2237 - Update table design to keep space when no entry in field

templates/web/prod/results/record.html.twig
- PHRAS-2264: fix encoding of title
=> PHRAS-2264_html-encode-title_MASTER

lib/Alchemy/Phrasea/Controller/Admin/DataboxesController.php
- PHRAS-1868: admin/databases/ mount database NOK
- clear cahce sbase param when mount
=> PHRAS-1868 admin/databases/ mount database NOK

lib/Alchemy/Phrasea/Controller/Prod/PropertyController.php, lib/Alchemy/Phrasea/ControllerProvider/Prod/Property.php
- PHRAS-2227: Action menu bar / Edit / Properties : Changing status for selected items don't appear in log_docs table
- add log when status change
=> PHRAS-2227 : Action menu bar / Edit / Properties : Changing status for selected items don't appear in log_docs table

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_workzone-proposals.scss
- PHRAS-440: adding "see more" button to the list of facets to limit the list view
=> PHRAS-440_prod_facets_show_more

resources/www/prod/skins/ui-components/_modal-advanced-search.scss, templates/web/prod/index.html.twig
- PHRAS-2238: reset button fix
=> PHRAS-2238_advance_search_buttons_additional_fix

lib/Alchemy/Phrasea/TaskManager/Job/WriteMetadataJob.php
- PHRAS-2211: Subdef generation : dpi values in subdef file mismatch dpi value in subdef setting
- rewrite dpi in file when metadatas
=> PHRAS-2211 Subdef generation : dpi values in subdef file mismatch dpi value in subdef setting

composer.lock
- PHRAS-2211 : Update phpexiftool dependency from 0.7.0 to 0.7.1.
=> PHRAS-2211 Update phpexiftool dependency from 0.7.0 to 0.7.1

.circleci/config.yml
Node.js is now version 10.12.0
=> PHRAS-2186

resources/ansible/roles/elasticsearch/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-1843 Add elasticsearch host setting in vars/all.yml file.
=> PHRAS-1843 Add elasticsearch host setting in vars/all.yml file

lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Query.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php, lib/classes/databox.php
- PHRAS-2261: Port to 4.1 - PROD / SEARCH / THESAURUS : not concerned assets in search result
=> PHRAS-2261 Port to 4.1 - PROD / SEARCH / THESAURUS : not concerned assets in search result

lib/Alchemy/Phrasea/Controller/Prod/PropertyController.php, lib/Alchemy/Phrasea/ControllerProvider/Prod/Property.php
- PHRAS-2274: Port to 4.1 - PHRAS-2227 Action menu bar / Edit / Properties : Changing status for selected items don't appear in log_docs table
=> PHRAS-2274 port to 4.1 PHRAS-2227 FIX changing status appear in log_docs table

lib/Alchemy/Phrasea/Controller/Admin/DataboxesController.php
- PHRAS-1864: Port to 4.1 - PHRAS-1868 admin - databases - mount database NOK
=> PHRAS-1864 port to 4.1 PHRAS-1868 database mount

resources/ansible/playbook.yml, resources/ansible/roles/app/tasks/main.yml
- commented some ansible roles (not yet implemented bin/...) to let provisioning run ok
=> PHRAS-2294_lighten-provisioning_S4

lib/Alchemy/Phrasea/Core/Version.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php, lib/classes/databox.php, lib/classes/databox/field.php, lib/classes/patch/405a.php, lib/conf.d/bases_structure.xml, lib/conf.d/data_templates/DublinCore.xml, lib/conf.d/data_templates/en-simple.xml, lib/conf.d/data_templates/fr-simple.xml, templates/web/admin/fields/templates.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
- Admin / database structure / Migrate all Text field to String
- Need system upgrade after merge
=> PHRAS-1690 field type migrate text to string type

lib/Alchemy/Phrasea/TaskManager/Job/WebhookJob.php
- PHRAS-2204: Port diff from 4.0 to master ; see : https://github.com/alchemy-fr/Phraseanet/commit/95bb3eedeb0f1867458e271fa0e6090d9673e41b
=> PHRAS-2204: Task Manager / Api webhook Task : error on event delivering

composer.json, composer.lock, lib/Alchemy/Phrasea/Application/ApiApplicationLoader.php, lib/Alchemy/Phrasea/Application/RouteLoader.php, lib/Alchemy/Phrasea/ControllerProvider/ControllerProviderServiceProvider.php, lib/Alchemy/Phrasea/Out/Module/Excel.php, lib/Alchemy/Phrasea/Report/Controller/ApiReportController.php, lib/Alchemy/Phrasea/Report/Controller/ProdReportController.php, lib/Alchemy/Phrasea/Report/ControllerProvider/ApiReportControllerProvider.php, lib/Alchemy/Phrasea/Report/ControllerProvider/ProdReportControllerProvider.php, lib/Alchemy/Phrasea/Report/Report.php, lib/Alchemy/Phrasea/Report/ReportConnections.php, lib/Alchemy/Phrasea/Report/ReportDownloads.php, lib/Alchemy/Phrasea/Report/ReportFactory.php, lib/Alchemy/Phrasea/Report/ReportRecords.php, lib/Alchemy/Phrasea/Report/ReportService.php
- PHRAS-2293: Backport PHRAS-2189_report-v2 _master
=> PHRAS-2293 backport 2189 to 4.0 report V2

lib/Alchemy/Phrasea/Controller/Prod/PushController.php, lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php, lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php, lib/classes/record/adapter.php, lib/classes/record/preview.php, templates/web/admin/connected-users.html.twig, templates/web/lightbox/index.html.twig, templates/web/prod/WorkZone/Macros.html.twig, templates/web/prod/upload/upload.html.twig
- PHRAS-2269: Check escaping in templates xss
=> PHRAS-2269 escaping templates xss

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, resources/www/common/js/jquery.common.js, templates/web/prod/results/infos.html.twig
- PHRAS-2298: extract concept_path queries from elastic search
=> PHRAS-2298_Extract_concept_path_from_elastic_query

lib/classes/module/console/systemUpgrade.php
- PHRAS-2144: execute autoincrement after system:upgrade
=> PHRAS-2144 execute autoincrement after system:upgrade

lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
- PHRAS-2300: Prod - Search thesaurus terms, search in all languages
=> PHRAS-2300 Prod - search terms in all languages

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/results/infos.html.twig
- PHRAS-2301: extract concept_path queries from elastic search port to 4.1
=> PHRAS-2301_thesaurus_concept_path_port_41

templates/web/prod/results/infos.html.twig
=> PHRAS-2301_thesaurus_concept_path_port_41 fix

templates/web/prod/WorkZone/Macros.html.twig
- PHRAS-2284: revert last modification for feedback unread icon
=> PHRAS-2284_refacto_basket_picto revert feedback unread

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- PHRAS-2303: fix field label in facet
=> PHRAS-2303: fix field label in facet

templates/web/admin/fields/templates.html.twig
- PHRAS-2303: fix field label in admin
=> PHRAS-2303 fix field label in admin

ab_master.sql, composer.json, db_master.sql
=> PHRAS-2200_configure_root_folder_and_databases

lib/Alchemy/Phrasea/Collection/Collection.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- PHRAS-2303: fix save/display collection name
=> PHRAS-2303 fix save/display collection name

resources/www/report/js/report.js, resources/www/report/styles/main.scss, templates/web/report/form_date_and_base.html.twig
- PHRAS-2315: refactoring of new report UI corrections
=> PHRAS-2315_report_refacto__corrections

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, lib/classes/databox/field.php
- PHRAS-1326: add "labels" array to facets returned by search
=> PHRAS-1326_intl-labels-in-facets_MASTER

resources/www/report/styles/main.scss
- PHRAS-2315: report corrections fix
=> PHRAS-2315_report_refacto__corrections fix

templates/web/report/report_layout_child.html.twig
- PHRAS-2315: fix type of record duplicates
=> PHRAS-2315_report_refacto type of record fix

config/packages/doctrine.yaml, config/routes.yaml, src/Command/Setup/ImportDatabases.php, src/Controller/DefaultController.php
=> NGINX_test_symfony4

resources/ansible/roles/nginx/templates/default.j2
- PHRAS-2338: fix-nginx-simple-conf_S4
todo later : restore dev/www differences
=> PHRAS-2338_fix-nginx-simple-conf_S4

resources/www/report/js/report.js, templates/web/report/report_layout_child.html.twig
- PHRAS: 2327: remove unselected collection from download
=> PHRAS-2327_report_refacto_41 base collections fix

resources/www/report/js/report.js, templates/web/report/form_date_and_base.html.twig, templates/web/report/report_layout_child.html.twig
- PHRAS-2342: fix collection and fields based on Base selection
=> PHRAS-2342_report_collections_fix

lib/Alchemy/Phrasea/Report/ControllerProvider/ApiReportControllerProvider.php, lib/Alchemy/Phrasea/Report/ControllerProvider/ProdReportControllerProvider.php, templates/web/report/report_layout_child.html.twig
- PHRAS-2342: change "GET" methods to "POST", because of the long url
=> PHRAS-2350_report_method_fix

lib/Alchemy/Phrasea/Core/Version.php, lib/classes/patch/410alpha13b.php, lib/classes/record/adapter.php
- PHRAS-2329: Port to master : log_doc error when move a record between collections 
- with a patch to fix old value
=> PHRAS-2329 Port to master : log_doc error when move a record between collections 

resources/www/prod/js/jquery.main-prod.js, resources/www/prod/skins/ui-components/_diapo.scss, resources/www/prod/skins/ui-components/_workzone-baskets.scss, templates/web/prod/results/record.html.twig
- PHRAS-2340: refactoring answer menu icons - corrections
=> Phras 2340 refactor menu icons 

lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus.php
- strict thesaurus search when indexing PHRAS-2372
=> PHRAS-2372 strict thesaurus search when indexing

lib/Alchemy/Phrasea/Core/Version.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php, lib/classes/databox.php, lib/classes/databox/field.php, lib/classes/patch/410alpha14a.php, lib/conf.d/bases_structure.xml, lib/conf.d/data_templates/DublinCore.xml, lib/conf.d/data_templates/en-simple.xml, lib/conf.d/data_templates/fr-simple.xml, templates/web/admin/fields/templates.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
- migrate field type text to string
=> PHRAS-2379 Port to 4.1 Migrate all field type text to string

.circleci/config.yml, .env.test, composer.json, composer.lock, package-lock.json, phpunit.xml.dist, tests/app/core/VersionTest.php, yarn.lock
- PHRAS-2373: fix test conf
- PHRAS-2373: add yarn lockfile
=> PHRAS-2373_set-tests-conf_S4

resources/ansible/roles/server/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-2368 - Add python packages on vagrant provisionning.
=> PHRAS-2368 - 4.0.7 - Add python packages on vagrant provisionning

.circleci/config.yml
- PHRAS-2392: 
- change cache key
- removed cache entries
=> PHRAS-2392_circleci-cache_S4

composer.lock, lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/Alchemy/Phrasea/Filesystem/FilesystemService.php, lib/Alchemy/Phrasea/Media/Subdef/Audio.php, lib/classes/databox/subdef.php
- PHRAS-2413: Backport To 4.0 - Extract audio as subdef from "video" in wave
=> PHRAS-2413 Backport To 4.0 - Extract audio as subdef from "video" in wave

lib/Alchemy/Phrasea/Report/ControllerProvider/ApiReportControllerProvider.php, lib/Alchemy/Phrasea/Report/ControllerProvider/ProdReportControllerProvider.php, templates/web/report/report_layout_child.html.twig
- PHRAS-2387: BackPort to 4.0 - Report : url is too long
- backport PHRAS-2350
=> PHRAS-2387: BackPort to 4.0 - Report : url is too long

resources/www/prod/js/jquery.main-prod.js, templates/web/prod/index.html.twig
- PHRAS-2420: adv search , "created on" and "updated on" fields on "date" menu
=> PHRAS-2420_advsearch-update-created-on_4.0

config/conf.d/bases_structure.xml.bkp, config/routes.yaml, config/services.yaml, src/Application/Helper/AclAware.php, src/Application/Helper/AclAwareService.php, src/Authentication/ACLProvider.php, src/Controller/Root/LoginController.php, src/Model/RecordInterface.php, src/Model/RecordReferenceInterface.php, src/Setup/Installer.php, src/Setup/PhpIniRequirement.php, src/Utils/ACL.php, src/Utils/NullableDateTime.php
=> PHRAS-2240_admin_part2

composer.lock, lib/Alchemy/Phrasea/Media/SubdefGenerator.php
- PHRAS-2436:PDF containing (XMP-xmp:PageImage) fails generating subview of image type
- just use XMP-xmp:PageImage embeded image for indesign file
=> PHRAS-2436: PDF containing (XMP-xmp:PageImage) fails generating subview of image type

Vagrantfile
- PHRAS-1802 Update default vagrant php version.
=> PHRAS-1802 | 4.0 | Update default vagrant php version

Vagrantfile
- PHRAS-1802 Update default vagrant php version.
=> PHRAS-1802 Update default vagrant php version

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/Controller/Prod/UploadController.php, lib/Alchemy/Phrasea/ControllerProvider/Prod/Upload.php, templates/web/prod/upload/upload.html.twig
- PHRAS-2452: in api record/add, pass a parameter "url" to a distant file (nb: the "file" parameter has precedence over "url")
- PHRAS-2452: in prod/upload, one can add a url to upload a distant file
=> PHRAS-2452_upload-via-url_4.0

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2467: adv-search sort is now ok
=> PHRAS-2467_sort-notok_4.0

lib/classes/patch/380alpha3a.php, lib/classes/patch/406a.php
- PHRAS-2468: fix : do not delete table log_colls
=> PHRAS-2468_dont-drop-logcolls_4.0

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
- PHRAS-2473: enhance, faster sql
=> PHRAS-2473 Populate some databox is very long ? bin/console

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
- PHRAS-2473: Populate time enhancement by sql query optimization.
On some databox, populate take a very long time.
=> PHRAS-2473 Populate improv, sql query optimization.

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2472: fixed js crash due to bug in "hideSingleValueFacet(...)"
=> PHRAS-2472_html-in-rollover_4.0

bower.json, lib/Alchemy/Phrasea/Core/Version.php
- PHRAS-2479: Release version 4.0.8
=>  PHRAS-2479: Release version 4.0.8

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2491: changed clickFolderMode to only "expand"
=> PHRAS-2491_facet-expand-launches-query_4.0

lib/classes/patch/380alpha3a.php, lib/classes/patch/410alpha13a.php
- PHRAS-2483: Port to 4.1 dont drop log_colls
=> PHRAS-2483: Port to 4.1 dont drop log_colls

resources/ansible/roles/php/tasks/mod-php.yml, resources/ansible/roles/php/tasks/php-cli.yml, resources/ansible/roles/php/tasks/php-fpm.yml
- PHRAS-2455 | Master | Resolve PHP warnings on setup, update provisionning
=> PHRAS-2455 Resolve PHP warnings on setup, update provisionning

resources/ansible/roles/php/tasks/mod-php.yml, resources/ansible/roles/php/tasks/php-cli.yml, resources/ansible/roles/php/tasks/php-fpm.yml
- PHRAS-2455 | 4.0 | Remove php warnings on dashboard.
=> PHRAS-2455 to 4.0 Remove php warnings on dashboard

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TermNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryHelper.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TermNodeTest.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php
- PHRAS-2474: es query : private-fields list now includes also public fields to allow cross-fields search
=> PHRAS-2474 search mix public business 4.0

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/Controller/Prod/UploadController.php, lib/Alchemy/Phrasea/ControllerProvider/Prod/Upload.php, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/prod/upload/upload.html.twig
- PHRAS-2465: Port To 4.1 - Add - upload assets, has records in Phraseanet, by URL
=> PHRAS-2465 Port To 4.1 - upload-via-url_4.0

lib/Alchemy/Phrasea/Collection/CollectionService.php, lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php, lib/Alchemy/Phrasea/Controller/Admin/UserController.php
- PHRAS-2499: Port to 4.1 - Add Model to "Order Managers" of collection
=> PHRAS-2499: Port to 4.1 - Add Model to "Order Managers" of collection

composer.json, composer.lock
- PHRAS-2505: remove mcrypt deprecations
=> PHRAS-2505 replace ircmaxell/random-lib with paragonie/random-lib for php7.1

composer.json, composer.lock
- PHRAS-2506: remove mcrypt deprecations
=> PHRAS-2506 replace ircmaxell/random-lib with paragonie/random-lib for php7.1

resources/ansible/roles/vagrant_local/tasks/docker-hosts-container.yml, resources/ansible/roles/vagrant_local/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-2533 Inject containers hostname on /etc/hosts file.
=> PHRAS-2533 Inject containers hostname on /etc/hosts file

resources/www/prod/styles/main.scss, templates/web/prod/index.html.twig
- PHRAS-2417: prod - skin grey and white - adv search, missing arrow for database and status
=> PHRAS-2417 prod - skin grey and white - adv search, missing arrow for database and status

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2510: Facet's values are truncated a the 15th character. the lay over informations are also truncated.
#time 1h
=> PHRAS-2510 PROD / Facets : facet's values are trucated at 15 characters

resources/ansible/roles/vagrant_local/tasks/docker-hosts-container.yml, resources/ansible/roles/vagrant_local/tasks/main.yml, resources/ansible/vars/all.yml
- PHRAS-2533 Add hosts on vagrant (4.0)
=> PHRAS-2533 Add hosts on vagrant (4.0)

resources/ansible/roles/vagrant_local/tasks/docker-hosts-container.yml, resources/ansible/vars/all.yml
- PHRAS-2533 Inject docker dependencies, typo fix.
=> PHRAS-2533 Inject docker dependencies, typo fix

resources/ansible/roles/vagrant_local/tasks/docker-hosts-container.yml, resources/ansible/vars/all.yml
=> PHRAS-2533 Typo fix

resources/ansible/roles/php/tasks/mod-php.yml
=> PHRAS-2533 | Fix typo

Vagrantfile, resources/ansible/playbook.yml
- PHRAS-2496 | Pre-build vagrant image for Phraseanet and implement it in Phraseanet vagrant file.
=> PHRAS-2496 | Pre-build vagrant image for Phraseanet

Vagrantfile, resources/ansible/playbook.yml
- PHRAS-2496 | 4.0 | Add old box name
=> PHRAS-2496 | 4.0 | Add old box name

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/QuotedTextNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/RawNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TermNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryHelper.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/QuotedTextNodeTest.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TermNodeTest.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php
#comment port to 4.1 Search issue when query mix data from Public and Private field
#time 2h
- PHRAS-2497: port to 4.1 fix Search issue when query mix data from Public and Private field
=> PHRAS-2497 Port TO 4.1 - Search issue when query mix data from Public and Private field 

config/configuration.sample.yml, lib/Alchemy/Phrasea/Controller/Root/AccountController.php, lib/conf.d/configuration.yml, templates/web/account/account.html.twig
#time 0.5h
- 4.1 delete account update config structure
=> PHRAS-1972: 4.1 delete account update config structure

.circleci/config.yml, AUTHORS, Dockerfile, Dockerfile-debug, Dockerfile-nginx, docker/nginx/etc/nginx/nginx.conf, docker/phraseanet-debug/entrypoint.sh, docker/phraseanet-debug/usr/bin/docker-get-host-ip, docker/phraseanet-debug/usr/bin/docker-xdebug-disable, docker/phraseanet-debug/usr/bin/docker-xdebug-enable, docker/phraseanet/etc/supervisor/conf.d/supervisor-phraseanet-scheduler.conf, docker/phraseanet/usr/local/etc/php-fpm.d/www.conf.default, docker/phraseanet/usr/local/etc/php-fpm.d/zz-docker.conf, docker/phraseanet/usr/local/etc/php/php.ini
- Build CircleCi Image
- PHRAS-2539 Build CircleCi Image
=> PHRAS-2539 circle ci image

.circleci/config.yml
PHRAS-2539 #comment remove workflow branch filtering
=> PHRAS-2539 remove workflow branch filtering

.circleci/config.yml
- Remove npm and replace by yarn
- PHRAS-2561 remove npm install add yarn Install
=> PHRAS-2561 #comment remove npm install add yarn Install

.circleci/config.yml
- Update yarn version 
- PHRAS-2561: Update yarn version
=> PHRAS-2561 #comment update yarn version

lib/Alchemy/Phrasea/Application.php
- PHRAS-2546 :  add monolog handler for app error
=> PHRAS-2546 : add monolog handler

composer.json, composer.lock, package.json, yarn.lock
- composer.json
- composer.lock
- package.json
- yarn.lock
- PHRAS-2552:  update composer.json + package.json to set new version of embed-bundle
embed_bundle:
video:
player: videojs
autoplay: false
coverSubdef: thumbnail
video_message_start: StartOfMessage
available-speeds:
- 1
- '1.5'
- 3
=> PHRAS-2552 Port to 4.1 - VideoJS - Embed bundle, Set the "reading head" position at a specified time.

composer.json, composer.lock, package.json, yarn.lock
-PHRAS-2552 update composer.json for embed-bundle 2.0.1
- Remove alchemy-embed-medias from package.json
=>  PHRAS-2552 embed_bundle_update_workflow

lib/Alchemy/Phrasea/TaskManager/Editor/SubdefsEditor.php, lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php, lib/Alchemy/Phrasea/TaskManager/Job/SubdefsJob.php, lib/Alchemy/Phrasea/TaskManager/Notifier.php, templates/web/admin/task-manager/task-editor/subdefs.html.twig
- PHRAS-2563: subdef task : if the "all" databox is checked, the task runs on every dbox (even the new ones)
- changed the task-manager notification timeout to 1s to be more responsive.
=> PHRAS-2563_subdef-task-alldb_4.1

Vagrantfile, resources/ansible/playbook.yml, resources/ansible/roles/elasticsearch/tasks/main.yml, resources/ansible/roles/mailcatcher/tasks/main.yml, resources/ansible/roles/mariadb/tasks/main.yml, resources/ansible/vars/all.yml
- Update Ubuntu default box build from trusty to xenial version.
=> PHRAS-2565 Vagrant Provisioning | Update Ubuntu default box build from trusty to xenial version

.circleci/config.yml
PHRAS-2566 #comment Test clear cache by rm node_modules
#time 1h
=> PHRAS-2566 Test clear cache rm node_modules

bower.json, composer.json, composer.lock
- Update composer.json : embed-bundle version to 1.0.0
- Update bower.json : alchemy-embed-medias version to 1.0.0
=> Doing PHRAS-1655 video js set the reading head position at a specified time - update composer.json

lib/Alchemy/Phrasea/Form/Login/PhraseaRegisterForm.php
- PHRAS-2531: changing declaration
=> PHRAS-2531 fix

lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
#time 1h
- PHRAS-2569: PHRAS-2569 :Backport to 4.0 - Archive Task Generate error when connection db lost
- backport the  ticket PHRAS-2399
=> PHRAS-2569 :Backport to 4.0 - Archive Task Generate error when connection db lost

lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
- PHRAS-2399: added reconnect everywhere
=> PHRAS-2399_arch-task-cnx-timeout_4.1

Vagrantfile
- 4.0 Update typo issue on Vagrantfile
=> 4.0 | Update typo issue on Vagrantfile

Vagrantfile, resources/ansible/playbook.yml
- 4.1 | Update playbook for phraseanet vagrant box workflow.
=> Update playbook for phraseanet vagrant box workflow

resources/ansible/playbook.yml
- Fix | Update playbook in case of phraseanet box usage.
=> 4.0 | Update playbook in case of phraseanet box usage

lib/Alchemy/Phrasea/Controller/PermalinkController.php, templates/web/overview.html.twig
#time 6h
- PHRAS-2564:Permalink on video file , add start parameter on url
- Add t parameter in permalink url  to start a video at t second
=> PHRAS-2564 :Permalink on video file , add start parameter on url

composer.json
- resolve composer warning 
- PHRAS-2576  typo fix mikey179/vfsstream
=> PHRAS-2576 #comment typo fix mikey179/vfsstream

.circleci/config.yml
=> CircleCI : building machine use Docker Llayer caching

resources/www/prod/js/jquery.main-prod.js, templates/web/prod/index.html.twig
- PHRAS-2537: Advanced search : translate the title
=> PHRAS-2537 prod advanced search title wording for advanced search windows remains advanced search 

bower.json, composer.json, composer.lock
- Composer.json version
- Bower.json version
=> PHRAS-1655 update composer.json to 1.0.1

Dockerfile, Dockerfile-nginx, README.md
Dockerfile optimised
- add warning on docker in README : Docker is still in work-in-progress
=> Dockerfile optimisation and add warning on WIP docker on README

Dockerfile
- The PHP code was not copied to the right location and cannot be serve by nginx
=> copy to the right location

Dockerfile
- PHRAS-2586: make the folder writable
=> make every writable folder writable

lib/conf.d/data_templates/DublinCore.xml
- Set type for all fields of this databox template 
- PHRAS-2534: Set type for all fields of this databox template
=> PHRAS-2534 Dublincore Databox template update.

Dockerfile, docker/phraseanet/boot.sh
PHRAS-2600 #comment fpm service doesn't use root account anymore
=> fpm service doesn't use root account anymore

.circleci/config.yml
- Update yarn install
- PHRAS-2561: Update yarn install
=> PHRAS-2561 Update yarn install

lib/conf.d/data_templates/en-simple.xml, lib/conf.d/data_templates/fr-simple.xml
PHRAS-2598 #comment add type string to fields, change to number lat and long for iptc's model
=> PHRAS-2598 #comment merge 

composer.json, composer.lock
- upgrade embed-bundle to 2.0.3 
- Fix audio player
- Clean configuration.yml :
- Rename variable enable-pdfjs into enable_pdfjs 
- Rename variable coverSubdef into cover_subdef
=> PHRAS-2592 composer.json : upgrade embed-bundle version

Dockerfile
- PHRDPL 34: change php version from 7.1 to 7.0 (in Docker only)
=> PHRDPL-34 #comment fix PHP version (from 7.1 to 7.0)

Dockerfile, docker/nginx/boot.sh, docker/nginx/nginx.conf.sample, docker/phraseanet/boot.sh, docker/phraseanet/php-fpm.conf.sample, docker/phraseanet/php.ini.sample
- PHP and Nginx can be configured via some environments vars
=> PHRDPL-32 #comment fpm/nginx configuration variabilisable

composer.json, composer.lock
- "alchemy/embed-bundle": "^2.0.4"
- PHRAS-2579:  Video player - chapter presentation: list mode
=> PHRAS-2579 update embed-bundle version on composer.json  

package.json, yarn.lock
- "phraseanet-production-client": "^0.34.16-d"
=> PHRAS-2376 Prod toolbar change icon update yarn.lock

Dockerfile
PHRDPL-32 #comment add gettext
=> PHRDPL-32 add gettext

docker/nginx/boot.sh, docker/nginx/nginx.conf.sample, docker/phraseanet/php.ini.sample
- PHRDPL-32 : max upload is configurable via env
=> fix max upload

Dockerfile, docker/phraseanet/auto-install.sh, docker/phraseanet/boot.sh
- PHRDPL-60: use the env vars for auto-installation
=> PHRDPL-60 #comment Check the INSTALL_* env vars for auto installation

lib/conf.d/configuration.yml
- PHRAS-2660 #comment add Rabbitmq conf in configuration.yml
=> PHRAS-2660 #comment add rabbitmq config

Dockerfile, README.md, docker/phraseanet/worker-boot.sh
- worker use the app user to run jobs
=> PHRDPL-61 #comment worker use the app user to run jobs

resources/www/permaview/styles/main.scss
- PHRAS-2618 Records: fix title and description display on overview
=> PHRAS-2618 Records: fix title and description display on overview

package.json, yarn.lock
- phraseanet-production-client@0.34.31-d
- PHRAS-2622
- PHRAS-2596
- PHRAS-2629
=> PHRAS-2622 update on stable version  phraseanet-production-client@0.34.31-d

templates/web/admin/users.html.twig
- PHRAS-2530 :Admin: user search by country and company fields
=> PHRAS-2530 Admin: user search by country and company fields

resources/www/admin/styles/main.scss
- PHRAS-2619 Admin Publication : Fix icon size
=> PHRAS-2619 Admin Publication : Fix icon size 

CHANGELOG.md
PHRAS-2401 #comment changelog for 4.0.9
=> PHRAS-2401 changelog for 4.0.9

CHANGELOG.md
PHRAS-2434 #comment update changelog.md in master
=> PHRAS-2434 #comment update changelog.md

Dockerfile, docker/nginx/boot.sh, docker/nginx/nginx.conf.sample, docker/phraseanet-debug/entrypoint.sh, docker/phraseanet-debug/usr/bin/docker-get-host-ip, docker/phraseanet-debug/usr/bin/docker-xdebug-disable, docker/phraseanet-debug/usr/bin/docker-xdebug-enable, docker/phraseanet/auto-install.sh, docker/phraseanet/boot.sh, docker/phraseanet/php-fpm.conf.sample, docker/phraseanet/php.ini.sample, docker/phraseanet/phraseanet-entrypoint.sh, docker/phraseanet/usr/local/etc/php-fpm.d/www.conf.default, docker/phraseanet/usr/local/etc/php-fpm.d/zz-docker.conf, docker/phraseanet/worker-boot.sh
- PHRAS-2632: Add Dockerfile  + container files
=> Phras 2632 backport dockerfile

composer.json, composer.lock, package.json, yarn.lock
- "alchemy/embed-bundle": "^2.0.5"
-  "phraseanet-production-client": "0.34.35-d"
-  update composer.json and package.lock on phraseanet
=> PHRAS-2623 Remove video-chapter-thumbail videojs and roll back on view 

package.json, yarn.lock
- upgrade phraseanet-production-client@0.34.41-d
- PHRAS-2544 change on grey and white skin
- PHRAS-2620 : add new icomoon
=> PHRAS-2544  upgrade phraseanet-production-client@0.34.41-d

templates/web/login/layout/base-layout.html.twig
- PHRAS-1310: Fix select language on login page
=> PHRAS-1310  Fix select language on login page 

lib/Alchemy/Phrasea/Media/SubdefSubstituer.php
- PHRAS-2405:  update record type and mimetype on sustitute
=> PHRAS-2405 : update record type and mimetype on sustitute

bin/setup, composer.json, composer.lock, lib/Alchemy/Phrasea/Command/Plugin/AbstractPluginCommand.php, lib/Alchemy/Phrasea/Command/Plugin/AddPlugin.php, lib/Alchemy/Phrasea/Command/Plugin/DownloadPlugin.php
- bin/setup plugins:add command detects if source is remote and switches on new plugins:download command
- new bin/setup plugins:download command downloads remote .zip file or clone git repo from remote source and to local
=> PHRAS-2507 Enhancing AddPlugin and adding DownloadPlugin command

lib/Alchemy/Phrasea/TaskManager/Job/WriteMetadataJob.php
- PHRAS-2654: fix do not push fields "Phraseanet::no-source" to exiftool
=> PHRAS-2654 : Port to 4.1 Fields "Phraseanet::no-source" are pushed to exiftool

templates/web/common/index_bootstrap.html.twig, templates/web/prod/WorkZone/Basket.html.twig, templates/web/prod/WorkZone/Macros.html.twig, templates/web/prod/index.html.twig, templates/web/prod/preview/popularity.html.twig
- phraseanet-production-client@0.34.52-d
- color of statistic block
- button on feedback
- advanced search: label color
-Border color of records
-Save Skin of User preference : phraseanet-production-client@0.34.52-d
=> PHRAS-2544  update fix on grey and white theme 

package.json, yarn.lock
- phraseanet-production-client@0.34.52-d
=> PHRAS-2544 #comment upgrade phraseanet-production-client to 0.34.52-d

package.json, yarn.lock
- phraseanet-production-client@0.34.53-d
=> PHRAS-2656 update package.json for the fix

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-2660: api stories enhancement
- add parameters "thumbnail_cover_source"  and "preview_cover_source"   for route 
/api/v1/stories 
/api/v1/stories/{databox_id}/{story_id}/addrecords 
/api/v1/stories/{databox_id}/{story_id}/setcover
=> PHRAS-2660 : api stories enhancement

Vagrantfile, resources/ansible/playbook-boxes.yml, resources/ansible/playbook.yml
- PHRAS-2496 | Update provisioning workflow, check if a box name is defined. A playbook for box usage is created.
=> PHRAS-2496 | Update provisioning workflow, check if a box name is defined. 

templates/web/common/index_bootstrap.html.twig, templates/web/prod/index.html.twig
=> PHRAS-2668  fix twig error

.circleci/config.yml
- PHRAS-2667: changed the name of the circle-ci cache
=> PHRAS_2667_CircleCI-cache_4.0

lib/Alchemy/Phrasea/Core/Version.php, lib/conf.d/bases_structure.xml
- PHRAS-2663: Add mysql index on table notification applicationbox
- simple index on column  usr_id , unread , created_on
=> PHRAS-2663 : 4.1 Add mysql index on table notification applicationbox

resources/gulp/components/vendors/alchemy-embed.js
- PHRAS-2672: simplify the deployment mode of embed-bundle
=> PHRAS-2672  simplify the deployment mode of embed-bundle 

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2681 Fix Facet display when switch from basket tab
=> PHRAS-2682 Fix Facet display when switch from basket tab

lib/classes/record/adapter.php
- PHRAS-2684: changed sql to use index (as reported by "explain")
=> PHRAS-2684_delete-record-slowsql_4.0

templates/web/prod/actions/Tools/videoEditor.html.twig
- PHRAS-2665: Prod-video tools - set image - Use preview ratio instead document ratio
=> PHRAS-2665 Fix video tool ratio

bower.json
PHRAS-2687 # comment Add "html5shiv": "^3.7.3" in bower.json
=> PHRAS-2687 error during make missing htmlshiv dep

composer.lock
- PHRAS-2672 | Update Embed bundle dependency from 1.0.1 to 1.0.3.
=> PHRAS-2672 | Update Embed bundle dependency from 1.0.1 to 1.0.3

bower.json
PHRAS-2697 #comment  error in embed version bundle version 1.0.2 not contains bower.json
=> Revert "PHRAS-2687 error during make missing htmlshiv dep"

composer.json
=> PHRAS-2672 Bump embed-bundle version

lib/Alchemy/Phrasea/Controller/Prod/RootController.php, lib/Alchemy/Phrasea/Controller/Prod/UploadController.php, lib/Alchemy/Phrasea/Controller/Root/AccountController.php, lib/Alchemy/Phrasea/Controller/Root/SessionController.php, lib/Alchemy/Phrasea/Helper/WorkZone.php, lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php, lib/classes/ACL.php, lib/classes/eventsmanager/notify/orderdeliver.php, lib/classes/eventsmanager/notify/validationdone.php, lib/classes/set/export.php
- PHRAS-2670 : backport to 4.0 fix notification slow sql and basket select
=> PHRAS-2670 : backport to 4.0 fix notification slow sql and basket select

resources/www/prod/js/jquery.Prod.js
- PHRAS-2699: Basket menu NOK when performe action like "browse" or "set order" (ordering item in basket)
=> PHRAS-2699 Basket menu NOK when performe action like "browse" or "set order" (ordering item in basket)

resources/www/prod/skins/ui-components/_search-form.scss
- PHRAS-2693: Collection Sort Sorter is not correctly presented by column but by lines / mini Logos create a view problem
=> PHRAS-2693 prod advanced search  : sort collections by column

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, resources/www/prod/js/jquery.main-prod.js
- PHRAS-2700: Prod workzone - Change type of numbering
=> PHRAS-2700  4.0 - Prod workzone - Change type of numbering

resources/www/prod/js/jquery.main-prod.js
- PHRAS-2644: Searching for stories after applying a document filtering choice gives no results
=> PHRAS-2644 Searching for stories after applying a document filtering choice gives no results

templates/web/common/preview.html.twig
- PHRAS-2671 Fix behaviour of preview display : use thumbnail if there is no preview
=> PHRAS-2671 Fix behaviour of preview display in audio file case

resources/www/lightbox/js/jquery.lightbox.ie6.js, resources/www/lightbox/js/jquery.lightbox.js
- PHRAS-2702: Backport to 4.0 - Lightbox / scroller thumbnail
=> PHRAS-2702 Backport to 4.0 - Lightbox /  Fix scroller thumbnail 

.circleci/config.yml, Dockerfile
- PHRDPL-75: Fix docker build
- update composer-installer checksum hash
=> PHRDPL-75 #comment composer-install : update checksum

lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
- PHRAS-1069: Dates seems not extracted from iptc
- format date from metadata to Y/m/d H:i:s
=> PHRAS-1069 : Dates seems not extracted from iptc

lib/Alchemy/Phrasea/TaskManager/Editor/SubdefsEditor.php, lib/Alchemy/Phrasea/TaskManager/Job/SubdefsJob.php, templates/web/admin/task-manager/task-editor/subdefs.html.twig
- PHRAS-2637 : BackPort to 4.0 - Subdef Task init : select all databases when property is not set
=> PHRAS-2637 : backport to 4.0 subdef Task default select all databases

Vagrantfile, resources/ansible/playbook-boxes.yml, resources/ansible/playbook.yml
- PHRAS-2496 | 4.0 | Add new playbook for boxes. Update provisioning workflow, check if a box name is defined.
=> PHRAS-2496 | 4.0 | Add new playbook for boxes. Update provisioning workflow.

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/BulkOperation.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/TitleHydrator.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
- PHRAS-2710: Port to 4.1 - ES indexer crashes if field contains NUL character
- port PHRAS-1327
=> PHRAS-2710 : Port to 4.1 - ES indexer crashes if field contains NUL character

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/FieldKey.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/Key.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/MetadataKey.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/NativeKey.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/RangeExpression.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/TimestampKey.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/FieldMapping.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/DateFieldMapping.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryHelper.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryVisitor.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/ValueChecker.php, lib/Alchemy/Phrasea/TaskManager/Job/WriteMetadataJob.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/RangeExpressionTest.php, tests/Alchemy/Tests/Phrasea/SearchEngine/resources/queries.csv
- PHRAS-2707: date with time on phraseanet
- port to 4.1 PHRAS-835
=> PHRAS-2707 : Port to 4.1 - ES - date format timestamp unix,  stocker/rechercher les dates phraseanet avec heure minutes secondes

lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
- PHRAS-2709:port to 4.1 Dates seems not extracted from iptc
=> PHRAS-2709 : port to 4.1 Dates seems not extracted from iptc

composer.json, composer.lock
- PHRAS-2715: Embed bundle, border issue on firefox.
- alchemy/embed-bundle : 1.0.4
=> PHRAS-2715 : 4.0 Embed bundle, border issue on firefox.

composer.json, composer.lock
- PHRAS-2715: Embed bundle, border issue on firefox
- alchemy/embed-bundle : 2.0.7
=> PHRAS-2715 : 4.1 Embed bundle, border issue on firefox

lib/Alchemy/Phrasea/Controller/Prod/RecordController.php, lib/Alchemy/Phrasea/Controller/RecordsRequest.php, lib/Alchemy/Phrasea/Model/Converter/BasketConverter.php, lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php, resources/www/prod/js/jquery.main-prod.js, templates/web/prod/actions/delete_records_confirm.html.twig, templates/web/prod/actions/delete_records_confirm_form.html.twig
- PHRAS-2691 : prod: delete records 3 by 3, running 5 // tasks
deletion can be cancelled, but the last "pack" (5*3=15) of records will be finished.
=> Phras 2691 delete 3by3 4.0

templates/web/prod/actions/delete_records_confirm.html.twig
- PHRAS-2732: tryout: try/catch jquery ui
=> PHRAS-2732_delete-3x3-stops_4.0

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-2726: setstatus api did change unspecified bits due to string offset error
=> PHRAS-2726_setstatus-api_4.1 : port of PHRAS-2716

lib/Alchemy/Phrasea/Controller/Prod/PushController.php, templates/web/admin/editusers.html.twig
- PHRAS-2723 : None information (name, last name etc...) is keep from the Push or a FeedBack user creation form
=> PHRAS-2723 : None information (name, last name etc...) is keep from the Push or a FeedBack user creation form

lib/Alchemy/Phrasea/Controller/Prod/PushController.php, templates/web/admin/editusers.html.twig
- PHRAS-2724: PORT To 4.1 - None information (name, last name etc...) is keep from the Push or a FeedBack user creation form
=> PHRAS-2724 : PORT To 4.1 - None information (name, last name etc...) is keep from the Push or a FeedBack user creation form

tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
- PHRAS-2727:4.0 Create a unit-test to detect bug described in PHRAS-2716
=> PHRAS-2727 : 4.0 Create a unit-test to detect bug described in PHRAS-2716 

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
- PHRAS-2716: setstatus api did change unspecified bits due to string offset error
=> PHRAS-2716_setstatus-api_4.0

tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
- PHRAS-2727: Create a unit-test to detect bug described in PHRAS-2716
=> PHRAS-2727 : Create a unit-test to detect bug described in PHRAS-2716

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
- phraseanet-production-client@0.34.57-d
- PHRAS-2688: Port to 4.1 - Prod workzone - Change type of numbering
=> PHRAS-2688 Port 41 of Prod workzone: Change type of numbering

templates/web/prod/WorkZone/Browser/Results.html.twig
- PHRAS-2705: fix basket browser windows nok
=> PHRAS-2705 : fix basket browser windows nok

lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php
PHRAS-2706: Prod - Basket browser windows - Received basket filter basket is
=> PHRAS-2706 Prod - Basket browser windows - Received basket filter basket

lib/Alchemy/Phrasea/Application.php, lib/Alchemy/Phrasea/Controller/Root/LoginController.php, lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
- PHRAS-2127 | 4.0 | Fix geonameid country and city.
=> PHRAS-2127 | 4.0 | Fix geonameid country and city

templates/web/prod/WorkZone/Browser/Browser.html.twig, templates/web/prod/WorkZone/Browser/Results.html.twig
- PHRAS-2282: Design of new basket windows Browser
- phraseanet-production-client@0.34.60-d for a first check
=> PHRAS-2282 Design of new basket windows Browser

lib/Alchemy/Phrasea/Application.php, lib/Alchemy/Phrasea/Controller/Root/LoginController.php, lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
- PHRAS-2127 | Add https in default geoname server url, remove url formatter in register controller.
=> PHRAS-2127 | Add https in default geoname server url

package.json, yarn.lock
- phraseanet-production-client@0.34.63-d
=> PHRAS-2282 upgrade phraseanet-production-client@0.34.63-d 

templates/web/prod/actions/delete_records_confirm.html.twig, templates/web/prod/actions/delete_records_confirm_form.html.twig
- PHRAS-2734 MoveToTrash3x3 : add counter
=> PHRAS-2734 MoveToTrash3x3 : add counter

package.json, yarn.lock
- phraseanet-production-client@0.34.72-d
- PHRAS-2686
=> PHRAS-2686 upgrade phraseanet-production-client

templates/web/prod/toolbar.html.twig
- PHRAS-2742: add block to extend the prod/actionbar (mainly to add js)
=> PHRAS-2742_enhance-plugin-skeleton_4.0

templates/web/prod/toolbar.html.twig
Reverts alchemy-fr/Phraseanet#3175
=> Revert "PHRAS-2742_enhance-plugin-skeleton_4.0"

lib/Alchemy/Phrasea/Controller/RecordsRequest.php
- PHRAS-2764: editing a single story is now properly detected
=> PHRAS-2764_edit-single-story_4.0

templates/web/prod/toolbar.html.twig
- PHRAS-2742_enhance-plugin-skeleton_4.0
add block to extend the prod/actionbar (mainly to add js)
add test for plugins with no template to insert
allow a plugin to add option(s) anywhere in the actionbar
- PHRAS-2765_plugin_menu_label_locale
fix menu labels / locale
=> PHRAS-2742 & PHRAS-2765 enhance for plugin skeleton_4.0

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, templates/web/prod/results/grid.html.twig, templates/web/prod/results/list.html.twig, templates/web/prod/results/record.html.twig, templates/web/prod/results/records.html.twig, templates/web/prod/toolbar.html.twig
- PHRAS-2775: allow a plugin to add option(s) to the thumbnail context menu
=> PHRAS-2775_context-menu-plugin_4.0

lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php, resources/www/prod/js/jquery.main-prod.js
- PHRAS-2758: date facets are now returned as the "string" version (not number)
- fix : select date facet now build a valid query
=> PHRAS-2758_facets-on-date_4.0

composer.lock
- PHRAS-2791 | 4.1 | Serve a permalink instead of direct url in case of specific subdef is selected.
=> PHRAS-2791 | 4.1 | Serve a permalink instead of direct url.

templates/web/prod/toolbar.html.twig
- PHRAS-2795: plugin wg did crash due to missing method method
=> PHRAS-2795_wg-500_4.0

templates/web/prod/upload/lazaret.html.twig
- PHRAS-2801: Quarantine files management is not working on firefox
=> PHRAS-2801 fix quarantine file managment on firefox 

lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
- PHRAS-2785 : Port to 4.1 - Facets on date are restitued in a wicked way
- phraseanet-production-client@0.34.74-d
=> PHRAS-2785 Port to 4.1 - Facets on date are restitued in a wicked way

templates/web/prod/actions/edit_default.html.twig
- PHRAS-2809:  hide field switch attribute gui_editable value
=> PHRAS-2809 Prod on editing window, hide field swith attribut "gui_editable" to false

lib/Alchemy/Phrasea/SearchEngine/Elastic/StringUtils.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
- PHRAS-2811: Backport PHRAS-2748 to 4.0 (bad chars in cterms)
- bad chars in cterms
=> PHRAS-2811 : backport PHRAS-2748 : 

resources/www/permaview/styles/main.scss
- PHRAS-2760 help menue NOK in /view
=> PHRAS-2760 help menue NOK in /view

package.json, yarn.lock
- phraseanet-production-client@0.34.76-d
- PHRAS-2792: Order manager : Applied choice not shown before order validation
=> PHRAS-2792  upgrade phraseanet-production-client@0.34.76-d

lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php, lib/Alchemy/Phrasea/Controller/Api/V1Controller.php, lib/Alchemy/Phrasea/Controller/Prod/EditController.php, lib/Alchemy/Phrasea/Core/Version.php, lib/Alchemy/Phrasea/Databox/Field/DbalDataboxFieldRepository.php, lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php, lib/classes/databox.php, lib/classes/databox/field.php, lib/conf.d/bases_structure.xml, templates/web/admin/fields/templates.html.twig, templates/web/common/macro_caption.html.twig, tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php, www/scripts/models/field.js, www/scripts/tests/specs/models.js
- PHRAS-2816: hide the field  on roll over and detailled view depending on "gui_editable" attribute
=> PHRAS-2816 Hidden fields is roll over and detailled view

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php, tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/StructureTest.php
- PHRAS-2815: the "generate cterms" setting is applied by db ;
how : the "global_structure" (fields merged) now also contains field settings by db
=> PHRAS-2815_generate-cterms-multi-db_4.1

templates/web/common/menubar.html.twig
-PHRAS-2760 HELP menu : close submenu on click a div out of this
=> PHRAS-2760 HELP menu : close submenu on click a div out of this

README.md
Embed README to have a more precise procedure explanation
=> Embed README

docker/phraseanet/auto-install.sh
Check the presence of INSTALL_ACCOUNT_EMAIL and INSTALL_ACCOUNT_PASSWORD env vars
=> autoinstall #comment check vars on auto-install

Dockerfile
- PHRAS-2817: add build tools on fpm images
=> PHRAS-2817 Update Dockerfile builds tools an 4.0

resources/www/common/styles/main.scss
- PHRAS-2823: Admin 404 error on iconmoon font
=> PHRAS-2823  fix icon of Fontawesome on admin page 

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Escaper.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php, tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/ValueCheckerTest.php
- phraseanet-production-client@0.34.77-d
- PHRAS-2805: Port to 4.1 - Prod : Facets search are case insensible
=> PHRAS-2805  Port to 41 of Facet-case-sensibility

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/StringFieldMapping.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php, lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContextFactory.php, lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php, tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php, tests/Alchemy/Tests/Phrasea/SearchEngine/Search/QueryContextTest.php
- PHRAS-2831 : copy elastic/truncation code from 4.0
nb: front code already exists
Includes port of PHRAS-2802 (truncation-with-dots)
=> PHRAS-2831_port-truncation_4.1

package.json, yarn.lock
- phraseanet-production-client@0.34.77-d
- PHRAS-2805 Port to 4.1 - Prod : Facets search are case insensible
=> PHRAS-2805  upgrade phraseanet-production-client

resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, templates/web/admin/fields/templates.html.twig
- PHRAS-2824 Admin add string for Gui_editable and Gui_visible in admin
=> PHRAS-2824 Admin add string for Gui_editable and Gui_visible in admin

grammar/query.pp
=> PHRAS-2830_space-in-query_4.1

README.md
Embed Readme to add deployment instruction
=>  #comment README instruction to deploy the phraseanet stack

.circleci/config.yml
- use branch name as Docker tag during circleci build
=> PHRDPL-81 #comment Use circle env vars CIRCLE_BRANCH

lib/conf.d/data_templates/DublinCore.xml, lib/conf.d/data_templates/en-simple.xml, lib/conf.d/data_templates/fr-simple.xml
- Change audio codec in database models from libaac to libmp3lame
=> PHRAS-2842 #comment change audio codec in databases models #time 15m

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php, templates/web/prod/results/grid.html.twig, templates/web/prod/results/list.html.twig, templates/web/prod/results/record.html.twig, templates/web/prod/results/records.html.twig, templates/web/prod/toolbar.html.twig
- PHRAS-2796: PORT to 4.1 actionbar enhancements (allow a plugin to add options or menus to toolbar)
=> PHRAS-2796 actionbar enhancements 4.1

package.json, resources/locales/messages.de.xlf, resources/locales/messages.en.xlf, resources/locales/messages.fr.xlf, resources/locales/messages.nl.xlf, resources/locales/validators.de.xlf, resources/locales/validators.en.xlf, resources/locales/validators.fr.xlf, resources/locales/validators.nl.xlf, resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss, resources/www/lightbox/styles/main-mobile.scss, templates/mobile/lightbox/basket_element.html.twig, templates/mobile/lightbox/sc_note.html.twig, templates/mobile/lightbox/validate.html.twig, templates/web/lightbox/basket_content_report.html.twig, yarn.lock
- phraseanet-production-client@0.34.80-d
- PHRAS-2829: Port to 4.1 - Lightbox - mobile - Users choice and Validation report can't be visualized on a smartphon
=> PHRAS-2829  Port 41 of Lightbox mobile: user choice and validation report

lib/Alchemy/Phrasea/Command/Setup/Install.php
- PHRAS-2814: Elasticsearch informations on setup command line options are missing on master version
- bin/setup system:install add options --es-host    --es-port  --es-index
=> PHRAS-2814 : Elasticsearch informations on setup command line options are missing on master version

templates/mobile/lightbox/sc_note.html.twig, templates/web/lightbox/basket_content_report.html.twig
PHRAS-2829 Port to 4.1 - Lightbox - mobile - Users choice and Validation report can't be visualized on a smartphone
=> PHRAS-2829 lightbox  hide list of users depending on right access

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php, lib/Alchemy/Phrasea/Media/Subdef/Video.php, tests/classes/databox/subdefTest.php
- PHRAS-1324 : libfaac abandonned
- use libmp3lame for default setting
=> PHRAS-1324 : libfaac abandonned

resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss, templates/mobile/common/menubar.html.twig, templates/mobile/lightbox/basket_element.html.twig, templates/mobile/lightbox/feed_element.html.twig, templates/mobile/lightbox/index.html.twig, templates/mobile/lightbox/validate.html.twig
PHRAS-2829 Lightbox mobile : sort basket list + add user info
=> PHRAS-2829 Lightbox mobile : sort basket list + add user info

.circleci/config.yml
=> circleci #comment circleci refactor build
