alchemy-fr/Phraseanet

.circleci/config.yml
.dockerignore
Dockerfile
build.sh

Dockerfile
.circleci
.dockerignore

PHRDLP-82 Backport to 4.0 opmimize dockerfile 4.0

---

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
lib/Alchemy/Phrasea/Media/Subdef/Video.php
tests/classes/databox/subdefTest.php

PHRAS-1324 #comment Reverts alchemy-fr/Phraseanet#3241 libfaac abandoned 4.1

Revert PHRAS-1324  libfaac abandoned 4.1

---

package.json
yarn.lock

-  phraseanet-common@0.4.5-d
- phraseanet-production-client@0.34.84-d
PHRAS-2375 define minimum size of document tips

PHRAS-2375  fix prod Roll over PDF 

---

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
lib/Alchemy/Phrasea/Media/Subdef/Video.php

- PHRAS-1324: add libfdk_aac and add presets 4.0

PHRAS-1324 : add libfdk_aac and add presets 4.0

---

lib/Alchemy/Phrasea/Border/Checker/AbstractChecker.php
lib/Alchemy/Phrasea/Border/Checker/Filename.php
lib/Alchemy/Phrasea/Border/Checker/Sha256.php
lib/Alchemy/Phrasea/Border/Checker/UUID.php
lib/Alchemy/Phrasea/Core/Provider/BorderManagerServiceProvider.php
lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
lib/classes/record/adapter.php

- PHRAS-2857: Backport to 4.0 - Exclude some collections from quarantine checkers sha256, UUID, filename (AKA exclude Trash)

PHRAS-2857 : Backport to 4.0 - Exclude some collections from quarantine checkers sha256, UUID, filename (AKA exclude Trash)

---

lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php

- PHRAS-2856: fix record order in story

PHRAS-2856 :fix record order in story 4.1

---

lib/Alchemy/Phrasea/Border/Checker/AbstractChecker.php
lib/Alchemy/Phrasea/Border/Checker/Filename.php
lib/Alchemy/Phrasea/Border/Checker/Sha256.php
lib/Alchemy/Phrasea/Border/Checker/UUID.php
lib/Alchemy/Phrasea/Core/Provider/BorderManagerServiceProvider.php
lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
lib/classes/record/adapter.php

- PHRAS-2840: Exclude collection on quarantaine treatment

PHRAS-2840 : Exclude collection from quarantine checker

---

resources/www/lightbox/styles/main-mobile.scss
templates/mobile/lightbox/basket_element.html.twig

- Fix audio  display
- PHRAS-2848: Lightbox mobile-Light design refacto 4.1

PHRAS-2848 Lightbox mobile-Light design refacto 4.1 - Fix audio  display

---

composer.json
composer.lock

- PHRAS-2821:  video portrait nok
- media-alchemyst/media-alchemyst 0.5.5

PHRAS-2821 : video portrait nok 4.1

---

composer.json
composer.lock

- PHRAS-2860: Backport to 4.0 - Generated Subdefs for video Portait are not correctly Oriented
- media-alchemyst/media-alchemyst 0.5.5

PHRAS-2860 : Backport to 4.0 - Generated Subdefs for video Portait are not correctly Oriented 4.0

---

tests/Alchemy/Tests/Phrasea/Command/Plugin/AddPluginTest.php
tests/Alchemy/Tests/Phrasea/Command/Plugin/DisablePluginTest.php
tests/Alchemy/Tests/Phrasea/Command/Plugin/EnablePluginTest.php
tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
tests/Alchemy/Tests/Phrasea/Controller/Prod/ExportTest.php
tests/Alchemy/Tests/Phrasea/Core/CLIProvider/PluginServiceProviderTest.php
tests/Alchemy/Tests/Phrasea/Core/Configuration/DisplaySettingServiceTest.php
tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/DebuggerSubscriberTest.php
tests/Alchemy/Tests/Phrasea/Core/Provider/AuthenticationManagerServiceProviderTest.php
tests/Alchemy/Tests/Phrasea/Core/Provider/BorderManagerServiceProviderTest.php
tests/Alchemy/Tests/Phrasea/Core/Provider/LocaleServiceProviderTest.php
tests/Alchemy/Tests/Phrasea/Plugin/Management/AutoloaderGeneratorTest.php
tests/Alchemy/Tests/Phrasea/Plugin/PluginManagerTest.php

- PHRAS-2859: fix : configuration.yml is not modified by unit-tests anymore

PHRAS-2859 #comment tests execution, corrupt conf 4.1

---

lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php

-PHRAS-2706 Prod - Basket browser windows - Received basket filter

PHRAS-2706 Prod - Basket browser windows - Received basket filter basket 

---

templates/web/prod/index.html.twig

- PHRAS-2861: Prod-Basket zone-Drop down menu-Preference

PHRAS-2861 Prod-Basket zone-Drop down menu-Preference

---

Dockerfile

- update composer hash
- PHRAS-2869 update composer hash

PHRAS-2869 update composer checksum

---

Dockerfile

PHRAS-2869 #comment update composer hash in 4.0

PHRAS-2869 Update composer hash in 4.0

---

tests/Alchemy/Tests/Phrasea/Controller/Api/ApiJsonTest.php
tests/Alchemy/Tests/Phrasea/Controller/Root/LoginTest.php
tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/SessionManagerSubscriberTest.php
tests/classes/media/Permalink/AdapterTest.php

PHRAS-2859_tests-do-corrupt-conf-bis_4.1

---

resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss
resources/www/lightbox/styles/main-mobile.scss
templates/mobile/common/thumbnail.html.twig
templates/mobile/lightbox/basket_element.html.twig

-PHRAS-2863-Lightbox mobile-PDF reading

PHRAS-2863  Lightbox mobile: Load PDF reader (videojs)

---

package.json
yarn.lock

phraseanet-production-client@0.34.89-d
- PHRAS-2870: Prod - Workzone - Detail view - Vertical video

PHRAS-2870  Fix Prod workzone video max-width 

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-2757: add translation to print basket feedback

PHRAS-2757 : add translation to print basket feedback

---

Dockerfile

Composer is installed from the official image

PHRAS-2867 Change the composer installation procedure

---

Dockerfile

MAJ Composer installation procedure

PHRAS-2867 #comment Change the composer installation procedure

---

package.json
templates/mobile/common/thumbnail.html.twig
templates/mobile/lightbox/basket_element.html.twig
yarn.lock

- PHRAS-2862: Lightbox mobile-Video size
phraseanet-production-client@0.34.102-d

PHRAS-2862 Fix lightbox mobile : video resize 

---

composer.json
composer.lock
lib/Alchemy/Phrasea/Setup/Requirements/BinariesRequirements.php
resources/ansible/roles/app/tasks/main.yml

- PHRAS-2750 : PHPExiftool to handle DJI XMP Tags, Bump exiftool version and switch to original exiftool/exiftool repo
- update phpexiftool to 0.7.3

PHRAS-2750 : 4.1 update phpexiftool to 0.7.3 in 4.1

---

templates/web/prod/User/Add.html.twig

- PHRAS-2866 Remove fields geoname

PHRAS-2866 Create User from push or feedback GUI, field label is  missing.

---

lib/Alchemy/Phrasea/Out/Module/PDF.php
lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/printer_default.html.twig

- PHRAS-2757: add format feedback only and fix pdf text

PHRAS-2757 : 4.1 add format feedback only and fix pdf text 

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/printer_default.html.twig

- PHRAS-2878: print pdf feedback report
- fix some pdf written and close the windows in production when launch the print

PHRAS-2878 : fix print pdf feedback report   Joindre

---

templates/web/common/preview.html.twig

- PHRAS-2671: Change behavior of preview display in audio file case

PHRAS-2671 : Change behavior of preview display in audio file case

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php

- PHRAS-2890: Don't print the field with attribute "Displayed in Graphical Interface" to false

PHRAS-2890 : 4.1 Don't print the field with attribute "Displayed in Graphical Interface" to false

---

package.json
templates/web/common/preview.html.twig
templates/web/prod/actions/edit_default.html.twig
yarn.lock

-  phraseanet-production-client@0.34.111-d
- PHRAS-2719: Fix multivalue fields selection

PHRAS-2719 Edit form : Unable to select a value in a multivalued field

---

package.json
yarn.lock

-phraseanet-production-client@0.34.113-d
- PHRAS-2875 update phraseanet-production-client

PHRAS-2875 workzone and basket refacto ( update phraseanet-production-client)

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/edit_default.html.twig
templates/web/prod/templates/push.html.twig
yarn.lock

- phraseanet-production-client@0.34.116-d
- PHRAS-2892 Push & Feedback fix string on input name

PHRAS-2892 Push & Feedback fix string on input name

---

templates/web/prod/actions/edit_default.html.twig

- PHRAS-2885 Prod - Add missing warning when try to edit record from different databases.

PHRAS-2885 Prod - Add missing warning when try to edit record from different databases.

---

package.json
yarn.lock

- phraseanet-production-client@0.34.119-d 
- PHRAS-2895 Prod - Edit windows - missing space betwen thumbnails

PHRAS-2895 Prod - Edit windows - missing space betwen thumbnails

---

templates/web/prod/upload/lazaret.html.twig

PHRAS-2899: backport 40 Quarantine: allow to substitute without selecting target record, (when match only one record).

PHRAS-2899 :backport 40 quarantine allow to substitute without selecting target record b

---

package.json
yarn.lock

-  phraseanet-production-client@0.34.121-d
-PHRAS-2891 Fix Facet tooltip

PHRAS-2891 Fix Facet tooltip

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-2898: Some string are missing or not take in account in Feedback printed report

PHRAS-2898 : 4.1  Some string are missing or not take in account in Feedback printed report

---

composer.lock

- PHRAS-2884: use embed-bundle 2.0.9 for cleaning chapter vtt source name

PHRAS-2884 : 4.1 use embed-bundle 2.0.9 for cleaning chapter vtt source name

---

lib/Alchemy/Phrasea/Core/Version.php
lib/classes/patch/410alpha20a.php
lib/classes/patch/410alpha21a.php

- PHRAS-2897: Mig patch for 3.8 and 4.0 to 4.1 change data format in geolocation technical fields

PHRAS-2897 : 4.1 Mig patch for 3.8 and 4.0 to 4.1 change data format in geolocation technical fields

---

package.json
yarn.lock

- phraseanet-production-client@0.34.126-d
- PHRAS-2909 Detailled views: Fix audio player

PHRAS-2909  Detailled views: Fix audio player

---

lib/Alchemy/Phrasea/Controller/Prod/FeedController.php
lib/Alchemy/Phrasea/Core/Event/Subscriber/FeedEntrySubscriber.php
lib/Alchemy/Phrasea/Core/Version.php
lib/Alchemy/Phrasea/Model/Entities/Token.php
lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
lib/Alchemy/Phrasea/Model/Repositories/TokenRepository.php
lib/classes/patch/4011.php

- PHRAS-2926: backport of 
- PHRAS-2901_tokens-add-index_4.1
- PHRAS-2913_create-tokens-faster_4.1
bump phraseanet to 4.0.11

PHRAS-2926_create-tokens-faster_4.0

---

bower.json

- PHRAS-2929: fix sinon version on bower dependencies
- fix sinon version on bower dependencies to 1.7.1

PHRAS-2929 fix sinon version on bower dependencies

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/lightbox/index.html.twig
yarn.lock

- "phraseanet-production-client": "0.34.129-d"
- PHRAS-2915 Fix sort basket order on lightbox desktop

PHRAS-2915 Lightbox (desktop version) Change sort order for basket and Feedback in landing page ( most recent in first)

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/index.html.twig
templates/web/prod/results/help.html.twig
yarn.lock

- phraseanet-production-client @0.34.132-d
- PHRAS 2825 Prod : Add a reset button to initialize searches filters

PHRAS 2825 Prod : Add a reset button to initialize searches filters

---

package.json
yarn.lock

- phraseanet-production-client : 0.34.133-d
- PHRAS-2923  Port 41 :Collection sort by column

PHRAS-2923  Port 41 :Collection sort by column 

---

lib/classes/eventsmanager/notify/order.php
package.json
yarn.lock

- phraseanet-production-client": "0.34.128-d"
- PHRAS-2910 Order manager : fix action from notification menu bar

PHRAS-2910 Order manager : Can't perform any action in order manager when coming from a notification in menu bar

---

package.json
yarn.lock

- phraseanet-production-client@0.34.135-d
- upgrade of phraseanet-production-client

PHRAS-2923 upgrade of phraseanet-production-client

---

lib/Alchemy/Phrasea/Controller/Root/AccountController.php
lib/Alchemy/Phrasea/Helper/User/Edit.php
templates/web/account/account.html.twig

- PHRAS-2912:  When updating a user informations the wrong field are populated
- Fix for job and activity field on update inside administration panel and on user account

PHRAS-2912-fix-for-job-and-activity-on-user-update

---

lib/Alchemy/Phrasea/Core/Version.php
lib/Alchemy/Phrasea/Model/Entities/Token.php
lib/classes/patch/410alpha21a.php
lib/classes/patch/410alpha22a.php

- PHRAS-2901: add indexes to table "Tokens"

PHRAS-2901_tokens-add-index_4.1

---

lib/Alchemy/Phrasea/Controller/Prod/FeedController.php
lib/Alchemy/Phrasea/Core/Event/Subscriber/FeedEntrySubscriber.php
lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
lib/Alchemy/Phrasea/Model/Repositories/TokenRepository.php

- PHRAS_2913 timeout during big publish

PHRAS-2913_create-tokens-faster-for-Publication-4.1 

---

templates/web/prod/results/help.html.twig

- PHRAS-2825 center the reset button

PHRAS-2825 Prod Search : No result : center the reset button

---

composer.lock

- PHRAS-2911: Gif preview have size set to zero in subdef table
- update alchemy/mediavorus to 0.4.10

PHRAS-2911 : 4.0  Gif preview have size set to zero in subdef table

---

composer.lock

- PHRAS-29911 :Gif preview have size set to zero in subdef table
- update alchemy/mediavorus to 0.4.10

PHRAS-2911 : 4.1 Gif preview have size set to zero in subdef table

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

PHRAS-2825 Add translation

---

templates/web/developers/application_form.html.twig
templates/web/developers/applications.html.twig

- PHRAS-2779 Account : Enable to delete an application in Developer tab

PHRAS-2779 Account : Enable to delete an application in Developer tab

---

lib/Alchemy/Phrasea/Model/Entities/WebhookEventPayload.php

- PHRAS-2934: added missing doctrine relation

PHRAS-2934_Bad-dctrine-mapping-webhookeventdelivery_4.1

---

lib/Alchemy/Phrasea/Command/Developer/JsFixtures.php

- PHRAS-2854: add a message to ask to remove plugins

PHRAS-2854 generate-js-fixtures adding a warn message when plugins are installed

---

bin/console
lib/Alchemy/Phrasea/Command/Databox/ListDataboxCommand.php

- PHRAS-1627 : bin/console databox:list

PHRAS-1627 : bin/console databox:list

---

bin/console
lib/Alchemy/Phrasea/Command/Collection/ListCollectionCommand.php

- PHRAS-1629:  bin/console collection:list

PHRAS-1629: bin/console collection:list

---

bin/console
lib/Alchemy/Phrasea/Command/User/UserListCommand.php

- PHRAS-1661:  bin/console user:list

PHRAS-1661 : bin/console user:list

---

bin/console
lib/Alchemy/Phrasea/Command/User/UserSetPasswordCommand.php

- PHRAS-1648: bin/console user:set-password

PHRAS-1648 : bin/console user:set-password

---

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.139-d 
- PHRAS-2933 Prod - alphabetic sort of facets is NOK but improve it

 PHRAS-2933 Fix facets order and move facets setting to workzone block

---

lib/Alchemy/Phrasea/Command/User/UserListCommand.php

- PHRAS-1661: add jsonformat to user:list
- bin/console user:list --jsonformat

PHRAS-1661 : add jsonformat to user:list

---

lib/Alchemy/Phrasea/Command/Databox/ListDataboxCommand.php

- PHRAS-1627: add jsonformat option to databox:list
- bin/console databox:list --jsonformat

PHRAS-1627 : add jsonformat option to databox:list

---

lib/Alchemy/Phrasea/Command/Collection/ListCollectionCommand.php

- PHRAS-1629: add jsonformat to collection:list
- bin/console collection:list --jsonformat

PHRAS-1629 : add jsonformat to collection:list

---

bin/console
lib/Alchemy/Phrasea/Command/User/UserCreateCommand.php
resources/locales/messages.fr.xlf

- PHRAS-1659:  bin/console user:create

PHRAS-1659: bin/console user:create

---

config/configuration.sample.yml
lib/conf.d/configuration.yml

- Change facets order section in conf.d/configuration.yml and configuration.sample.yml
- PHRAS-2942

PHRAS-2942 Facets default setting

---

docker/phraseanet/auto-install.sh

- PHRASE-2947 Use of the new syntax for setting facets, continuation of: setting the order of facets PHRAS-2879.

PHRAS-2947 Update auto-install.sh

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Core/MetaProvider/MediaUtilitiesMetaServiceProvider.php
lib/conf.d/configuration.yml

- PHRAS-2943: Set exiftool timeout, default is 60 secondes
- Port PHRAS-1377

PHRAS-2943 : 4.1 Set exiftool timeout, default is 60 secondes

---

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
templates/web/prod/actions/edit_default.html.twig

- PHRAS-2945: Prod - editing - set default value for "editing_top_box"

 Prod-editing : Fix default height/min-height for editing_top_box 

---

templates/web/common/menubar.html.twig

- PHRAS-2935 : Fix "About" popup on responsive

PHRAS-2935  Prod admin report in responsive About is always old design 

---

lib/classes/eventsmanager/broker.php

- PHRAS-2638 Remove eventsmanager_notify_bridgeuploadfail

PHRAS-2638 : Remove Bridge reference in /account

---

lib/Alchemy/Phrasea/Command/User/UserListCommand.php
lib/Alchemy/Phrasea/Model/Repositories/UserRepository.php

- PHRAS-2941: 4.1 bin/console user:list --model

PHRAS-2941 : 4.1 bin/console user:list --models

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/index.html.twig
yarn.lock

-     "phraseanet-production-client": "0.34.141-d"
- PHRAS-2950 Prod - facets - tooltips improvement, add the hits and string

PHRAS-2950 Prod - facets - tooltips improvement, add the hits and string

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/index.html.twig

- PHRAS-2954 Prod - user pref - port to 4.1 language selection

PHRAS-2954 Prod - user pref - port to 4.1 language selection

---

bin/console
lib/Alchemy/Phrasea/Command/Databox/MountDataboxCommand.php

- PHRAS-1626: bin/console databox:mount mount an existing databox

PHRAS-1626 : bin/console databox:mount mount an existing databox

---

bin/console
lib/Alchemy/Phrasea/Command/Databox/UnMountDataboxCommand.php

- PHRAS-1630: bin/console databox:unmount

PHRAS-1630 : bin/console databox:unmount

---

bin/console
lib/Alchemy/Phrasea/Command/Collection/PublishCollectionCommand.php

- PHRAS-1628: bin/console collection:publish

PHRAS-1628 : bin/console collection:publish

---

bin/console
lib/Alchemy/Phrasea/Command/Collection/UnPublishCollectionCommand.php

- PHRAS-1631:  bin/console collection:unpublish

PHRAS-1631 : bin/console collection:unpublish

---

lib/Alchemy/Phrasea/Command/User/UserListCommand.php

- PHRAS-1661: remove application list in bin/console user:list

PHRAS-1661: remove application list in bin/console user:list

---

lib/Alchemy/Phrasea/Command/User/UserApplicationsCommand.php

- PHRAS-1632: user:application , add client_secret on return

PHRAS-1632 : 4.1 user:application , add client_secret on return

---

package.json
yarn.lock

-  phraseanet-production-client@0.34.146-d
- PHRAS-2956 Account - developers - application - new, create a desktop application

PHRAS-2956 Account - developers - application - GUI create a desktop application

---

lib/Alchemy/Phrasea/Core/MetaProvider/DatabaseMetaProvider.php

- add cache to entity metadata for performance

PHRAS-2955 add doctrine metadata filesystem cache

---

docker/phraseanet/auto-install.sh

-  In redis config replace domain property by namespace
- PHRAS-2970

PHRAS-2970 Update redis domain property

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/Tooltip/Basket.html.twig
templates/web/prod/WorkZone/Basket.html.twig
templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-2961 Prod - Display ending date in feedback rollover and feedback deploy in workzone

PHRAS-2961 Prod - Display ending date in feedback rollover and feedback deploy in workzone

---

Dockerfile

- Added more file formats for unoconv
- PHRAS-2974

PHRAS-2974 more document formats for unoconv

---

lib/Alchemy/Phrasea/Core/Version.php
lib/conf.d/bases_structure.xml

- PHRAS-2964: change column char size

PHRAS-2964 : 4.0 change column char size

---

lib/Alchemy/Phrasea/Core/Version.php
lib/classes/patch/410alpha25a.php

- PHRAS-2976: Migration Patch, transform old facette style to new one.

PHRAS-2976 : Migration Patch, transform old facette style to new one.

---

lib/Alchemy/Phrasea/Helper/User/Edit.php

- PHRAS-2979: The content of a story is not displayed even for users with appropriate on the collection

PHRAS-2979 : 4.0 The content of a story is not displayed even for users with appropriate on the collection

---

lib/classes/phraseadate.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/Tooltip/Basket.html.twig
templates/web/prod/WorkZone/Basket.html.twig
templates/web/prod/preview/appears_in.html.twig
yarn.lock

phraseanet-production-client@0.34.151-d
- PHRAS-2978  Feedback basket - Change date format lib for translation and UI fix

PHRAS-2978  Feedback basket - Change date format lib for translation and UI fix

---

lib/Alchemy/Phrasea/Controller/Prod/PushController.php
lib/Alchemy/Phrasea/ControllerProvider/Prod/Push.php
lib/classes/phraseadate.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/Tooltip/Basket.html.twig
templates/web/prod/WorkZone/Basket.html.twig

- Feedback basket - Change date format lib for translation and UI fix

PHRAS-2978 Feedback basket - enable to edit validation deadline

---

bin/console
lib/Alchemy/Phrasea/Command/ApplyRightsCommand.php
lib/Alchemy/Phrasea/Helper/User/Edit.php
lib/classes/record/adapter.php

- PHRAS-2979 : The content of a story is not displayed even for users with appropriate on the collection

PHRAS-2979 : 4.1 The content of a story is not displayed even for users with appropriate on the collection

---

package.json
templates/web/prod/preview/appears_in.html.twig
yarn.lock

- phraseanet-production-client@0.34.153-d
- PHRAS-2989 Prod - Detailed view - link in basket, store etc ... requires a double click

PHRAS-2989 Prod - Detailed view - link in basket, store etc ... requires a double click

---

package.json
yarn.lock

- phraseanet-production-client@0.34.157-d 
- PHRAS-2978 Feedback basket - Fix on feedback count display

PHRAS-2978 Feedback basket - Fix on feedback count display

---

.dockerignore
Dockerfile

- PHRAS-2975: compile ffmpeg witth AAC in docker

PHRAS-2975 - add ffmpeg to docker image

---

lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php

PHRAS-2937_Remove libtheora from preset

---

package.json
templates/web/prod/WorkZone/Macros.html.twig
yarn.lock

phraseanet-production-client@ 0.34.160-d
- PHRAS-2998 Prod - workzone - basket tab - default sort is always by date

PHRAS-2998 Prod - workzone - basket tab - default sort is always by date

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php

- Truncate large value to 32k before insert into elasticsearch
- PHRAS-3003

PHRAS-3003 truncate large value to 32k

---

lib/Alchemy/Phrasea/Controller/Prod/QueryController.php

- PHRAS-2999 prod - answer grid -finish selection summary

PHRAS-2999 prod - answer grid - hide selection summary

---

templates/web/prod/Tooltip/Basket.html.twig
templates/web/prod/WorkZone/Basket.html.twig

- PHRAS-3005 Prod - workzone - error when expand feedback.

PHRAS-3005 Prod - workzone - error when expand feedback.

---

lib/classes/phraseadate.php

- PHRAS-2992 Prod Fix Date translation everywhere record history.

PHRAS-2992 Prod Fix Date translation everywhere record history.

---

lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/GpsPosition.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php

- PHRAS-3001: change es geo position data source
- fix : gps position indexed by es now comes from the metadata fields defined in conf; (fallback tech data).
supported formats in "latlng" type : 
**12.34 56.78** (lat=12.34, lon=56.78)
**-12.34 -56.78** (lat=-12.34, lon=-56.78)
**12.34 S 56.78 W** (lat=-12.34, lon=-56.78)
**12.34° 22.5' S 44** (lat=-12.715, lon=44)
**12.34° 22.5' 59" S 44** (lat=-12.7313888, lon=44)
etc...
**47°07'22.7"N 0°59'40.2"E** (The place)

PHRAS-3001_es-geopoint-sources_4.1

---

docker/phraseanet/auto-install.sh

- Fix for worker and scheduler conf in configuration.yml
- PHRAS-3020

Fix for worker and scheduler conf in configuration.yml

---

lib/Alchemy/Phrasea/Command/Setup/Install.php

- PHRAS-3018: reject install if not php64

PHRAS-3018_reject-php32_4.1

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/RecordListFetcherDelegate.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/ScheduledFetcherDelegate.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php

- PHRAS-3023: change fetcher query to paginate with record_id/count (not limit/count)

PHRAS-3023_slow-query-while-indexing_4.1

---

.env
docker-compose.override.yml
docker-compose.yml
docker/phraseanet/auto-install.sh
docker/phraseanet/entrypoint.sh

- Add volumes for www/custom and cache
- change owner of cache repository to app 
- Set title of instance on home on setup 
- PHRAS-3021
- PHRAS-3013

PHRAS-3021 add volumes www-custom and cache

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Command/Setup/Install.php
lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
lib/Alchemy/Phrasea/Controller/SetupController.php
lib/Alchemy/Phrasea/Media/SubdefGenerator.php
lib/Alchemy/Phrasea/Setup/Installer.php
lib/conf.d/configuration.yml
tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
tests/Alchemy/Tests/Phrasea/Setup/InstallerTest.php

- PHRAS-3019: More options for setup storage during install - set download lazaret

PHRAS-3019 4.1 More options for setup storage during install - set download lazaret

---

lib/conf.d/configuration.yml

- Removing section rabbitmq from configuration.yml , replacing by workers section
- PHRAS-3021

PHARS-3021 Remove rabbitmq from configuration.yml

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/edit_default.html.twig
yarn.lock

- phraseanet-production-client@0.34.171-d
- PHRAS-3014:Prod - Editing Confirm before  filling  field, latitude and longitude

PHRAS-3014:Prod - Editing Confirm before  filling  field, latitude and longitude

---

lib/Alchemy/Phrasea/Controller/RecordsRequest.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
resources/proxies/__CG__AlchemyPhraseaModelEntitiesWebhookEvent.php
templates/web/prod/actions/edit_default.html.twig
yarn.lock

-phraseanet-production-client@0.34.172-d
- PHRAS-3022 prod - editing - add button for select all records of story and desing fix

PHRAS-3022 prod - editing - add button for select all records of story and desing fix

---

package.json
resources/locales/messages.de.xlf
templates/web/prod/WorkZone/Macros.html.twig
templates/web/prod/WorkZone/Story.html.twig
templates/web/prod/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.177-d
- PHRAS-2669 : Prod set default color selection to vivid color

PHRAS-2669 Prod set default color selection to vivid color

---

templates/web/prod/Share/record.html.twig

-PHRAS-2991 Prod fix twitter sharing

PHRAS-2991 Prod - Sharing screen : Sharing to Twitter NOK

---

lib/Alchemy/Phrasea/Controller/Prod/PushController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Basket.html.twig
templates/web/prod/WorkZone/Browser/Results.html.twig

- PHRAS-2888 Find where some strings are called and remove it if unused

PHRAS-2888 remove unused strings 

---

package.json
yarn.lock

- phraseanet-production-client@0.34.178-d
-  Error on video tools due to missing or instable libraries of phraseanet-production-client

PHRAS-2669 upgrade phraseanet-production-client

---

lib/Alchemy/Phrasea/Controller/Prod/FeedController.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
yarn.lock

- phraseanet-production-client@0.34.179-d
- PHRAS-2963 prod - publication reader - suscribing to a feed - refacto design windows

PHRAS-2963 prod - publication reader - suscribing to a feed - refacto design windows

---

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php

- PHRAS-3033 Prod - 500 error when click on "Tools" (action bar) with a storie in selection.

PHRAS-3033 Prod - 500 error when click on "Tools" (action bar) with a story in selection.

---

package.json
yarn.lock

- phraseanet-production-client@0.34.181-d (this include the fix on PHRAS-2963 ..@0.34.179 )
- PHRAS-3035 Prod - videotools - change save message

PHRAS-3035 Prod - videotools - change save message

---

lib/Alchemy/Phrasea/Controller/Root/AccountController.php
lib/Alchemy/Phrasea/Controller/Root/LoginController.php
lib/Alchemy/Phrasea/Helper/User/Edit.php
lib/Alchemy/Phrasea/Helper/User/Manage.php

- PHRAS-3031: user account - remove space at end of email adress

PHRAS-3031: user account - remove space at end of email adress

---

package.json
yarn.lock

- phraseanet-production-client@0.34.182-d
- PHRAS-3037 Prod - Query with map - at reload the map box circle generate an error

PHRAS-3037 Prod - Query with map - at reload the map box circle generate an error 

---

templates/web/admin/connected-users.html.twig

- PHRAS-3041 Admin - connected user - roll over on user - user info - css is NOK

PHRAS-3041 Admin - connected user - roll over on user - user info - css is NOK 

---

templates/web/admin/editusers.html.twig

- PHRAS-3042 Admin - User edit - keep right pict always visible.

PHRAS-3042 Admin - User edit - keep right pict always visible.

---

lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php

- PHRAS-1071 : Prod / detailled view / basket link
- fix basket sql request

PHRAS-1071 : 4.1 Prod / detailled view / basket link

---

package.json
resources/www/lightbox/styles/main.scss
templates/web/lightbox/agreement_box.html.twig
templates/web/lightbox/validate.html.twig
templates/web/prod/WorkZone/Basket.html.twig
yarn.lock

- phraseanet-production-client@0.34.183-d
- PHRAS-2851 Lightbox - Feedback: Impossible to view the summary

PHRAS-2851 Lightbox - Feedback desktop: not possible to see the reviews summary

---

package.json
yarn.lock

- phraseanet-production-client@0.34.186-d 
- PHRAS-3043 Prod - After launch upload overlay in Prod - In editing, panels model, thesaurus, geonames, geoloc is NOK
Error was  due to " jquery-ui " and "blueimp-file-upload"

PHRAS-3043 Prod - After launch upload overlay in Prod - In editing, panels model, thesaurus, geonames, geoloc is NOK

---

package.json
templates/web/prod/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.189-d
- PHRAS-3044: Prod - Video editor - Design language fix and default title of chapter

PHRAS-3044: Prod - Video editor - Design language fix and default title of chapter

---

lib/Alchemy/Phrasea/Controller/Prod/SubdefsController.php
lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Tools/index.html.twig
templates/web/prod/actions/Tools/metadata.html.twig
yarn.lock

- phraseanet-production-client@0.34.192-d
- PHRAS-3047 front of - tools- metadatas tab - Add dropdown , fix design and refresh data.

PHRAS-3047 front of - tools- metadatas tab - Add dropdown , fix design and refresh data.

---

package.json
yarn.lock

- phraseanet-production-client@0.34.194-d
- PHRAS-3052 Prod - tools - Enable- Disable permalink Is NOK

PHRAS-3052 Prod - tools - Enable- Disable permalink Is NOK

---

lib/Alchemy/Phrasea/Controller/Prod/PushController.php

- PHRAS-3054 : Prod - Search for users in Pusch and Feedback is made on Login only, extend it to other fields

PHRAS-3054 : Prod - Search for users in Pusch and Feedback is made on Login only, extend it to other fields

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/databases.html.twig
templates/web/prod/WorkZone/Basket.html.twig
templates/web/prod/WorkZone/Story.html.twig
templates/web/prod/actions/Property/index.html.twig
templates/web/prod/index.html.twig
templates/web/report/report_layout_child.html.twig
yarn.lock

- phraseanet-production-client@0.34.195-d 
- PHRAS-3030 : Strings are Missing - translations are not possible in weblate - v4.1

PHRAS-3030 : Strings are Missing - translations are not possible in weblate - v4.1

---

templates/web/prod/templates/push.html.twig

-PHRAS-3056 Prod - Push and Feedback - searching user is NOK , javascirpt error

PHRAS-3056 Prod - Push and Feedback - searching user is NOK , javascirpt error

---

package.json
templates/web/prod/actions/Tools/videoEditor.html.twig
yarn.lock

- phraseanet-production-client@0.34.196-d
- PHRAS-3051 Prod - video tools - define a thumbnail for video don't update other static image like poster

PHRAS-3051 Prod - video tools - define a thumbnail for video don't update other static image like poster 

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Basket.html.twig

- PHRAS-3059 String is missing in weblate - Prod - Actions button

PHRAS-3059 String is missing in weblate - Prod - Actions button

---

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
templates/web/prod/actions/Tools/index.html.twig

- PHRAS-3066 Prod - Tools - 500 error when record selection containt more than one record

PHRAS-3066 Prod - Tools - 500 error when record selection contains more than one record

---

package.json
yarn.lock

-  phraseanet-production-client@0.34.197-d
- PHRAS-3062 Prod - Push feedback - The created user is not add to the current push or feedback

PHRAS-3062 Prod - Push feedback - The created user is not add to the current push or feedback

---

package.json
yarn.lock

- phraseanet-production-client@0.34.198-d
- PHRAS-3063 Prod - Reorder documents in basket: Design issues

PHRAS-3063 Prod - Reorder documents in basket: Design issues

---

templates/web/prod/Share/record.html.twig

- PHRAS-2157 Prod / Share : Iframe sizes are set to 0 for audio documents

PHRAS-2157 Prod / Share : Iframe sizes are set to 0 for audio documents

---

package.json
yarn.lock

- phraseanet-production-client@0.34.201-d
- PHRAS-3068 Prod - publication -editing - title and subtile is not update after modification

PHRAS-3068 Prod - publication -editing - title and subtile is not update after modification

---

package.json
templates/web/prod/results/item.html.twig
templates/web/prod/results/record.html.twig
yarn.lock

- phraseanet-production-client@0.34.202-d
-PHRAS-3070 Prod publication - gif are played and check behavior in 4.0

PHRAS-3070 Prod publication - gif are played and check behavior in 4.0

---

lib/Alchemy/Phrasea/Controller/Prod/FeedController.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Browser/Browser.html.twig
templates/web/prod/WorkZone/Browser/Results.html.twig
templates/web/prod/actions/publish/publish.html.twig
templates/web/prod/actions/publish/publish_edit.html.twig
templates/web/prod/results/entry.html.twig
templates/web/prod/results/feeds_entry.html.twig
yarn.lock

- phraseanet-production-client@0.34.204-d
- PHRAS-3072 Several Design fix on production client before 4.1.0 release

PHRAS-3072 Several Design fix on production client before 4.1.0 release

---

lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php

- PHRAS-3074: better regex, not 100% url strict but ok enough

PHRAS-3074_url-detection-4.1

---

lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Macros.html.twig
templates/web/prod/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.207-d
- PHRAS-3073 Prod - Basket Feedback - add type (image, video...) on each basket items

PHRAS-3073 Prod - Basket Feedback - add type (image, video...) on each basket items

---

lib/Alchemy/Phrasea/WorkerManager/Form/WorkerConfigurationType.php
lib/Alchemy/Phrasea/WorkerManager/Form/WorkerPullAssetsType.php
lib/Alchemy/Phrasea/WorkerManager/Form/WorkerSearchengineType.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-3082 dmin - design improvement - Invert sort on table "running job" , add icon to worker and search engine

PHRAS-3082 dmin - design improvement - Invert sort on table "running job" , add icon to worker and search engine

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
resources/www/admin/styles/main.scss
templates/web/admin/users.html.twig

- PHRAS-2685 Admin - User - Add drop down menu

PHRAS-2685 Admin - User - Add drop down menu

---

package.json
yarn.lock

- phraseanet-production-client@0.34.208-d
- PHRAS-3090   Don't auto start video when openning video tool

PHRAS-3090  Don't auto start video when openning video tool

---

resources/www/authentication/styles/main.scss

- PHRAS-3087 Login page - Design - Button is cut when login error occurs

PHRAS-3087 Login page - Design - Button is cut when login error occurs

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php

- PHRAS-3088 : fix mysql server gone away and dead lock on table worker
- if mysql server is gone away , reconnect it

PHRAS-3088 : fix mysql server gone away and dead lock on table worker

---

lib/Alchemy/Phrasea/Helper/User/Manage.php
lib/classes/User/Query.php
templates/web/admin/users.html.twig

- PHRAS-3091: Short feature description
- search user on like %...%

PHRAS-3091 : Back dev for add "content" operator when search users

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/index.html.twig
templates/web/admin/worker-manager/worker_configuration.html.twig
templates/web/prod/results/record.html.twig

- PHRAS-3101 Strings are missing in weblate - Admin - Worker

PHRAS-3101 Strings are missing in weblate - Admin - Worker

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Tools/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.212-d
- PHRAS-3105 Prod - tools - ask for re building subdef - Optim or Quick fix

PHRAS-3105 Prod - tools - ask for re building subdef - Optim or Quick fix

---

templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3086  workers : Jobs tab Refresh list on changing filters

PHRAS-3086  workers : Jobs tab Refresh list on changing filters 

---

package.json
templates/web/prod/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.213-d
- PHRAS-3108 Prod - User pref - Add icon arround thumbnail size slider

 PHRAS-3108 Prod - User pref - Add icon arround thumbnail size slider

---

docker/phraseanet/auto-install.sh

- PHRAS-3079: Fix redis setting issue

PHRAS-3079 #comment Fix redis setting issue

---

templates/web/prod/templates/upload.html.twig

- PHRAS-3111 Prod - Quarantine - Clean view quarantine warn

PHRAS-3111 Prod - Quarantine - Clean view quarantine warn

---

docker-compose.override.yml
docker-compose.yml
docker/phraseanet/entrypoint.sh

- PHRAS-3119 change volumes path in docker-compose and in override

PHRAS-3119 change volumes path in docker-compose and in override

---

lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookSubdefEventSubscriber.php

- PHRAS-2680: Webhook Privacy and Security

PHRAS-2680 : Webhook Privacy and Security

---

docker/phraseanet/entrypoint.sh

- PHRAS-3110 : Short description of bug and fix

PHRAS-3110 phraseanet entrypoint move chown

---

lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookSubdefEventSubscriber.php
tests/Alchemy/Tests/Phrasea/Model/Repositories/WebhookEventRepositoryTest.php

- PHRAS-2797:  remove unused webhook subdef_count

PHRAS-2797 : remove unused webhook subdef_count

---

lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php

- PHRAS-3107: Prod - Tools - rebuild subdef, fix issue when selection contents ZIP

PHRAS-3107 : Prod - Tools - rebuild subdef, fix issue when selection contents ZIP

---

package.json
templates/web/prod/WorkZone/Browser/Basket.html.twig
templates/web/prod/WorkZone/Browser/Results.html.twig
yarn.lock

- phraseanet-production-client@0.34.219-d
- PHRAS-3125 Prod - basket list - basket detail design is Nok

PHRAS-3125 Prod - basket list - basket detail design is Nok

---

package.json
templates/web/prod/index.html.twig
yarn.lock

- phraseanet-production-client@0.34.220-d
- PHRAS-2773: Prod : Add a message when downloading a large amount of file

PHRAS-2773: Prod : Add a message when dowloading a large amount of file

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- phraseanet-production-client@0.34.220-d
- PHRAS-2773: Prod : Add a message when downloading a large amount of file
- add string translation

PHRAS-2773: Prod : Add a message when downloading a large amount of file

---

Dockerfile

- Add nano into fpm and worker container
- PHRAS-3134 Add nano into fpm and worker container

PHRAS-3134 Add nano into fpm and worker container

---

.env
CHANGELOG.md
README.md
lib/Alchemy/Phrasea/Core/Version.php

PHRAS-2969 4.1.1 release

---

templates/web/common/menubar.html.twig

-  PHRAS-3137 : Help menue to doc 4.1

PHRAS-3137 : help menu to doc 4.1

---

lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Tools/videoEditor.html.twig
yarn.lock

- phraseanet-production-client@0.34.238-d
- PHRAS-3116  Prod - video-tools - Front for ask and edit subtitle or transcript generation

PHRAS-3116  Prod - video-tools - Front for ask and edit subtitle or transcript generation

---

lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php
lib/Alchemy/Phrasea/ControllerProvider/Thesaurus/Thesaurus.php

- PHRAS-3147 : Thesaurus GUI - launch a populate directly from GUI

PHRAS-3147 : Thesaurus GUI - launch a populate directly from GUI

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
lib/Alchemy/Phrasea/Controller/Prod/MoveCollectionController.php
lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
lib/Alchemy/Phrasea/TaskManager/Job/RecordMoverJob.php
lib/classes/record/adapter.php
tests/Alchemy/Tests/Phrasea/Application/OverviewTest.php

Removed "/setmetadatas" from route, the http verb "PATCH" on…"record" entity is ok
Cleanup : removed unused parm to recordadapter::move_to_collection()
unknown field now throws exception (no more erase all...)
set "base_id":x to change collection

PHRAS-3092 API V3 rename endpoint

---

README.md
docker/phraseanet/plugins/InstallCommand.php

- PHRAS-3144 change plugin delimiter

PHRAS-3144 change plugin delimiter

---

package.json
yarn.lock

- PHRAS-3151 upgrade phraseanet-production-client
- phraseanet-production-client@0.34.241-d

PHRAS-3151 upgrade phraseanet-production-client

---

package.json
templates/web/prod/actions/publish/publish.html.twig
yarn.lock

- phraseanet-production-client@0.34.248-d
- PHRAS-3163 Prod - Publication - Create publication - error in console when create

PHRAS-3163 Prod - Publication - Create publication - error in console when create

---

lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php

- PHRAS-3160 : Thesaurus - launch populate db - don't return elasticsearch detail in answer

PHRAS-3160 : Thesaurus - launch populate db - don't return elasticsearch detail in answer

---

lib/Alchemy/Phrasea/Application.php

- PHRAS-3159:  Lazaret (quarantine) storage file path is not taken in account

PHRAS-3159 : Lazaret (quarantine) storage file path is not taken in account 

---

package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
resources/www/lightbox/styles/main.scss
templates/web/common/dialog_export.html.twig
yarn.lock

- phraseanet-production-client@0.34.254-d
- PHRAS-3164 Lightbox : Remove key actions when modal is open

PHRAS-3164 Lightbox : Remove key actions when modal is open 

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php

- PHRAS-3171: Backport to 4.0 - Indexing - generate an error on a specific record pdf text extracted

PHRAS-3171 : Backport to 4.0 - Indexing - generate an error on a specific record pdf text extracted

---

package.json
yarn.lock

-phraseanet-production-client@0.34.255-d
- PHRAS-3169 Prod -video tools - Taken clip number from vtt when is present ideo subtitle with number

PHRAS-3169 Prod -video tools - Taken clip number from vtt when is present ideo subtitle with number

---

Dockerfile

- change xpdf in favor of poppler-utils
- PHRAS-3173

PHRAS-3173 change xpdf in favor of poppler-utils

---

package.json
yarn.lock

- phraseanet-production-client version": "0.34.256-d"
- PHRAS-3169 Prod video tools : Resize video on automatic subtitle tab

PHRAS-3169 Prod video tools : Resize video on automatic subtitle tab

---

templates/web/prod/actions/Tools/videoEditor.html.twig

- PHRAS-3177 prod - video tools - auto subtitling - add info about running autosubtitling request

PHRAS-3177 prod - video tools - auto subtitling - add info about running autosubtitling request

---

docker/phraseanet/entrypoint.sh

- new PHRASEANET_TRUSTED_PROXY env var

PHRAS-3178 PHRASEANET_TRUSTED_PROXY env var

---

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
lib/Alchemy/Phrasea/Core/Event/Record/RecordAutoSubtitleEvent.php
lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/SubtitleSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
templates/web/prod/actions/Tools/videoEditor.html.twig

- PHRAS-2504: subtitling
- add translate with ginger

PHRAS-2504 : subtitling - translate

---

Dockerfile

- Add UFRaw in Dockerfile to manipulate raw image formats
- PHRAS-3191: Add UFRaw in Dockerfile to manipulate raw image formats

Add UFRaw in Dockerfile to manipulate raw image formats

---

package.json
templates/web/prod/actions/Tools/videoEditor.html.twig
yarn.lock

- phraseanet-production-client@0.34.263-d
- PHRAS-3197 Prod- subtitlings screen - clean design

PHRAS-3197 Prod- subtitlings screen - clean design

---

package.json
yarn.lock

- phraseanet-production-client@0.34.265-d
- PHRAS-2145 Prod - refacto "move" record form collection overlay.

PHRAS-2145 Prod - refacto "move" record form collection overlay.

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
lib/conf.d/configuration.yml

- PHRAS-3193: SVG file is broken by exiftools
- do not write meta on svg file

PHRAS-3193 : SVG file is broken by exiftools

---

lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
package.json
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/publish/publish.html.twig
templates/web/prod/actions/publish/publish_edit.html.twig
yarn.lock

- phraseanet-production-client@0.34.267-d
- PHRAS-2541 Design-Prod/Publish window

PHRAS-2541 Design-Prod/Publish window

---

lib/Alchemy/Phrasea/WorkerManager/Worker/PopulateIndexWorker.php

- PHRAS-3204: worker sometime Populate is not acknowledge in WorkerRunnigJob table

PHRAS-3204 : worker sometime Populate is not acknowledge in WorkerRunnigJob table

---

lib/Alchemy/Phrasea/Model/Entities/WorkerRunningJob.php
lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
lib/Alchemy/Phrasea/WorkerManager/Provider/ControllerServiceProvider.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3202 : Admin - worker manager - job tab - mark a job line  "interrupted manually"
- add button in each line to make status as interrupt
- add filter for 'error' an 'interrupt manually'

PHRAS-3202 : Admin - worker manager - job tab - set a job finish manualy

---

lib/conf.d/configuration.yml
lib/conf.d/data_templates/DublinCore.xml
lib/conf.d/data_templates/en-simple.xml
lib/conf.d/data_templates/fr-simple.xml
lib/conf.d/data_templates/gs1.xml

Change default attribut for subviews in db model
- Change  size 
-  Flatten layers when build 
- PHRAS-3139

PHRAS-3139 default geolocalisation fields setting and default subview attributes

---

lib/Alchemy/Phrasea/Model/Entities/WorkerRunningJob.php
lib/Alchemy/Phrasea/WorkerManager/Worker/AssetsIngestWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/DeleteRecordWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/PopulateIndexWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3203 : Admin - worker manager - job tab - WorkerRunningJob add colon and store payload as Json
- add column payload in WorkerRunningJob table
- display payload message on admin

PHRAS-3203 : Admin - worker manager - job tab - WorkerRunningJob add colon and store payload as Json

---

Dockerfile

Add php-ldap extension to the docker-compose stack

Add php-ldap extension to the docker-compose stack

---

package.json
yarn.lock

- phraseanet-production-client@0.34.272-d
- PHRAS-3212 Port 4.1 - JS Error message during upload: "img.toDataURL is not a function"

PHRAS-3212 Port 4.1 - JS Error message during upload: "img.toDataURL is not a function"

---

API_documentation/v3/api.yaml
API_documentation/v3/responses.yaml
API_documentation/v3/schemas.yaml
lib/Alchemy/Phrasea/Controller/Api/Result.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3ResultHelpers.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchController.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3StoriesController.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
lib/Alchemy/Phrasea/Helper/JsonBodyHelper.php
lib/Alchemy/Phrasea/Search/StoryView.php
lib/Alchemy/Phrasea/Search/V3SearchResultTransformer.php
lib/Alchemy/Phrasea/Search/V3StoryTransformer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/classes/record/adapter.php

WIP DO NOT MERGE
- PHRAS-2443 api/v3/stories  number of returned records is  correct
- route GET:records
- route POST:records (can create a record without document)
- json can be passed in body OR in a multiparm parm named "body" (to allow upload of file along with json)

PHRAS-3174_api-v3-records_4.1

---

docker/phraseanet/entrypoint.sh

PHRAS-3220 chown datas in background

---

API_documentation/v3/api.yaml
API_documentation/v3/schemas.yaml

- doc : add facets structure
- doc : fix record/story differences

PHRAS-3174_api-v3-records_4.1 (doc only)

---

lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php

- PHRAS-3221: Prod - Admin about url to store.alchemy.fr switch scheme from https to http

PHRAS-3221 : Prod - Admin about url to store.alchemy.fr switch scheme from https to http

---

lib/Alchemy/Phrasea/SearchEngine/SearchEngineResult.php
tests/Alchemy/Tests/Phrasea/SearchEngine/SearchEngineResultTest.php

- PHRAS-3224: Prod - answer grid - page navigation have disappeared

PHRAS-3224 Prod - answer grid - page navigation have disappeared

---

lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php
templates/web/thesaurus/import-dialog.html.twig

- PHRAS-3227 : Unable to load a thesaurus file

PHRAS-3227 Unable to load a thesaurus file

---

lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
lib/Alchemy/Phrasea/WorkerManager/Provider/ControllerServiceProvider.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/worker-manager/worker_pull_assets.html.twig
templates/web/admin/worker-manager/worker_queue_monitor.html.twig

#time 6h
- PHRAS-3239 purge queue in admin

PHRAS-3239 worker - queue how to purge a queue in admin worker queue tab

---

templates/web/admin/worker-manager/worker_info.html.twig

#time 1h
- PHRAS-3244: display day in job duration if exist

PHRAS-3244 duration in day if needed

---

lib/Alchemy/Phrasea/Controller/Api/Result.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchController.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchRawController.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/SubDefinitionHydrator.php
lib/Alchemy/Phrasea/Utilities/Stopwatch.php

- Add a new endpoint for search , /searchraw
- Add timer in all api route 
- Add new endpoint /hello 
- PHRAS-2168: new search endpoint named searchraw, this endpoint return result fro elasticsearch index 
the elasticsearch index content now the permalink.

PHRAS-3174 api v3 records 4.1 search Raw WIP

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/geolocalisation/providers/markerGLCollection.js

#time : 2h
- PHRAS-3255: Prod - editing - set assets position with mapboxWebGL is NOK

PHRAS-3255 Prod - editing - set assets position with mapboxWebGL is NOK

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/geolocalisation/providers/mapbox.js

#time 3h
- PHRAS-3258 Prod - Query - editing and detailled view MapboxJS don't load map named Streets and Outdoor

PHRAS-3258 Prod - Query - editing and detailled view MapboxJS don't load map named Streets and Outdoor

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/geolocalisation/providers/mapbox.css
Phraseanet-production-client/src/components/geolocalisation/providers/mapbox.js
Phraseanet-production-client/src/components/geolocalisation/providers/markerGLCollection.js
Phraseanet-production-client/src/components/record/recordEditor/index.js

- PHRAS-3270: Prod - editing - MapboxGL - editing assets position form several record improvement

PHRAS-3270 Prod - editing - MapboxGL - editing assets position form several record improvement

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/geolocalisation/providers/markerGLCollection.js

- PHRAS-3270: fix geoloc in preview

PHRAS-3270 fix geoloc in preview

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php

- PHRAS-3265: taken account max_result_window

PHRAS-3265 taken account max_result_window

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/geolocalisation/providers/mapbox.js
Phraseanet-production-client/src/components/record/recordEditor/index.js
Phraseanet-production-client/src/components/record/recordEditor/plugins/preview.js
Phraseanet-production-client/src/components/record/recordPreview/index.js

- PHRAS-3281: Prod - editing - the preview tab is not working

PHRAS-3281 Prod - editing - the preview tab is not working

---

Phraseanet-production-client/dist/account.js
Phraseanet-production-client/dist/account.min.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/lightbox-mobile.js
Phraseanet-production-client/dist/lightbox-mobile.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/locale/index.js
Phraseanet-production-client/src/components/record/recordEditor/index.js
templates/web/prod/actions/edit_default.html.twig

- PHRAS-3211:  Prod - Editing- Date field - The editor's date picker is always displayed on the french language
- fix user input format

PHRAS-3211 Prod - Editing- Date field - The editor's date picker is always displayed on the french language

---

lib/Alchemy/Phrasea/Command/Upgrade/Step35.php
lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
lib/Alchemy/Phrasea/Controller/Prod/EditController.php
lib/Alchemy/Phrasea/Controller/Prod/StoryController.php
lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
lib/Alchemy/Phrasea/Core/Provider/PhraseanetServiceProvider.php
lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
lib/Alchemy/Phrasea/WorkerManager/Event/RecordEditInWorkerEvent.php
lib/Alchemy/Phrasea/WorkerManager/Event/RecordsWriteMetaEvent.php
lib/Alchemy/Phrasea/WorkerManager/Event/WorkerEvents.php
lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
lib/Alchemy/Phrasea/WorkerManager/Queue/MessageHandler.php
lib/Alchemy/Phrasea/WorkerManager/Queue/MessagePublisher.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/CreateRecordWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/RecordEditWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
lib/classes/caption/field.php
lib/classes/module/console/fieldsMerge.php
lib/classes/module/console/fieldsRename.php
lib/classes/record/adapter.php

- PHRAS-3274: Prod - editing - request is to long when editing a large amount of records

PHRAS- 3274 Prod - editing - request is to long when editing a large amount of records

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/preview/short_history.html.twig

- PHRAS-3275: Prod - detaille view - timeline tab - remove instance key from log entry for push validation etc

PHRAS-3275 Prod - detaille view - timeline tab - remove instance key from log entry for push validation etc

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordEditor/index.js
templates/web/prod/actions/edit_default.html.twig

- PHRAS-3211: add time control

PHRAS-3211 add time control

---

.circleci/config.yml

PHRAS-3295_circle-php7_MASTER

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
lib/Alchemy/Phrasea/PhraseanetService/Provider/PSExposeServiceProvider.php
templates/web/prod/WorkZone/ExposeEdit.html.twig

- PHRAS-3262: expose-plugin set user/group right on a publication

PHRAS-3262 expose-plugin set user/group right on a publication

---

lib/classes/record/adapter.php

- PHRAS-3300: faster sql (removed sub-select)

PHRAS-3300_slow-delete_MASTER

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
lib/Alchemy/Phrasea/PhraseanetService/Provider/PSExposeServiceProvider.php
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposePermission.html.twig

- PHRAS-3262: user right in tab

PHRAS-3262 user right in tab

---

lib/Alchemy/Phrasea/Command/SendValidationRemindersCommand.php
lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Root/LoginController.php
lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
lib/Alchemy/Phrasea/Form/Configuration/ActionsFormType.php
lib/Alchemy/Phrasea/Model/Repositories/ValidationParticipantRepository.php
lib/Alchemy/Phrasea/Notification/Mail/MailInfoValidationReminder.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ValidationReminderWorker.php
lib/classes/eventsmanager/notify/validationreminder.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
tests/classes/Doctrine/Repositories/ValidationParticipantRepositoryTest.php

- PHRAS-3277: Change validation-reminder-days: 2 for a percent of time before expiration
- "validation-reminder-time-left-percent"  conf used

PHRAS-3277 Change validation-reminder-days: 2 for a percent of time before expiration

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposeNew.html.twig
templates/web/prod/WorkZone/ExposeOauthLogin.html.twig
templates/web/prod/WorkZone/ExposePermission.html.twig
templates/web/prod/WorkZone/ExposePublicationAssets.html.twig
templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-3306: prod - expose - several fix

PHRAS-3306 prod - expose - several improvements

---

lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php

- PHRAS-3310: admin - worker manager - Tab "Job" - 500 Error when table "WorkerRunningJob" contain a huge number of lines

PHRAS-3310 admin - worker manager - Tab "Job" - 500 Error when table "WorkerRunningJob" contain a huge number of lines

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/phraseanet-service/expose.html.twig
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposeNew.html.twig

- PHRAS-3306: prod - expose - several fix

PHRAS-3306 prod - expose - several fix

---

templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3311: Admin - Worker manager - Tab Job - hide payload column

PHRAS-3311 Admin - Worker manager - Tab Job - hide payload column

---

lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposeNew.html.twig

- PHRAS-3315 : Prod - Expose uploader worker  - Use new upload method - PS-276 - Direct upload to Minio or S3

PHRAS-3315 Prod - Expose uploader worker  - Use new upload method - PS-276 - Direct upload to Minio or S3 

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/addToBasket.js
Phraseanet-production-client/src/components/ui/workzone/index.js

- PHRAS-3322: Prod - Add remove record into (current) Basket action is NOK
- PHRAS-3268 : Delete a record from a basket in detailled view is KO
- FIX selection in workzone

PHRAS-3322 Prod - Add remove record into (current) Basket action is NOK

---

templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-3323  Prod - Workzone - Basket menu - Remove "export" item

PHRAS-3323 Prod - Workzone - Basket menu - Remove "export" item

---

lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php

- PHRAS-3331:  Prod - Story - Ordering elements of a story is not working on a Docker environment

PHRAS-3331 Prod - Story - Ordering elements of a story is not working on a Docker environment

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPreview/index.js
templates/web/prod/preview/tools.html.twig

- PHRAS-3257 : Prod - detailled view - Unproper content display when clic on "also in basket/feedback"

PHRAS-3257 Prod - detailled view - Unproper content display when clic on "also in basket/feedback"

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPreview/index.js
lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
lib/classes/record/preview.php

- PHRAS-3338: Prod - Detailled view - title bar - add icon for basket or feedback, change place of record count (after the basket title)

PHRAS-3338 Prod - Detailled view - title bar - add icon for basket or feedback, change place of record count (after the basket title)

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf

PHRAS-3276 fix translation

---

docker/phraseanet/worker/entrypoint.sh

- PHRAS-3330: finish changes to add explode worker processes
- add some fixes

PHRAS-3336 test if PHRASEANET_EXPODE_WORKER is set fallback to default

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPreview/index.js
lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
lib/classes/record/preview.php
templates/web/prod/preview/appears_in.html.twig

- PHRAS-3340: Prod - Detailled view - title bar - some fix on story

PHRAS-3340 Prod - Detailled view - title bar - some fix on story

---

lib/Alchemy/Phrasea/Controller/Prod/BasketController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Reminder.html.twig

- PHRAS-3287 Prod - Workzone - feedback - send a reminder email 
- add token in link if exist in feedback creation
- some generation string

PHRAS-3287 Prod - Workzone - feedback - send a reminder email 

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPush/feedback.js
Phraseanet-production-client/src/components/ui/toolbar/index.js
lib/Alchemy/Phrasea/Controller/Prod/PushController.php
lib/Alchemy/Phrasea/Model/Entities/ValidationSession.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Basket.html.twig
templates/web/prod/actions/Push.html.twig
templates/web/prod/templates/push.html.twig

- PHRAS-3288: Prod - Workzone - Add more users in existing feedback

PHRAS-3288 Prod - Workzone - Add more users in existing feedback

---

Phraseanet-production-client/README.md
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/mobile/lightbox/basket_element.html.twig
templates/mobile/lightbox/feed.html.twig
templates/mobile/lightbox/feed_element.html.twig
templates/mobile/lightbox/index.html.twig
templates/mobile/lightbox/note_form.html.twig
templates/mobile/lightbox/validate.html.twig
templates/web/account/base.html.twig
templates/web/account/reset-email.html.twig
templates/web/admin/index.html.twig
templates/web/common/index_bootstrap.html.twig
templates/web/lightbox/IE6/feed.html.twig
templates/web/lightbox/IE6/validate.html.twig
templates/web/lightbox/feed.html.twig
templates/web/lightbox/index.html.twig
templates/web/lightbox/validate.html.twig
templates/web/login/layout/base-layout.html.twig
templates/web/overview.html.twig
templates/web/prod/index.html.twig
templates/web/prod/upload/upload-flash.html.twig
templates/web/report/all_content.html.twig
templates/web/setup/wrapper.html.twig
templates/web/thesaurus/accept.html.twig
templates/web/thesaurus/new-term.html.twig
templates/web/thesaurus/thesaurus.html.twig

- PHRAS-3353: Prod - Avoid purging the browser's local cache for JS - versioned file for commons.min.js production.mn.js
- add version number in file

PHRAS-3353 Prod - Avoid purging the browser's local cache for JS - versioned file for commons.min.js production.mn.js

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/baskets/index.js
lib/Alchemy/Phrasea/Controller/Prod/WorkzoneController.php
templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-3352: Prod- Workzone - keep sort (order) and filter define by the user - date or alpha

PHRAS-3352 Prod- Workzone - keep sort (order) and filter define by the user - date or alpha

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/search/advSearch/searchAdvancedForm.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3126 : prod - search bar - background blue coloration is missing when search filter is active.

PHRAS-3126 prod - search bar - background blue coloration is missing when search filter is active.

---

templates/web/prod/preview/popularity.html.twig

- PHRAS-3356: Prod - detailed view - related story - broken when no right to Access report

PHRAS-3356 Prod - detailed view - related story - broken when no right to Access report

---

.env

- PHRAS-3364 remove duplicate COMPOSE_FILE

PHRAS-3364 remove duplicate COMPOSE_FILE

---

docker-compose.yml

- PHRAS-3364 remove duplicate entry for db mailhog

PHRAS-3364 remove duplicate entry for db mailhog

---

docker-compose.yml

- PHRAS-3364 removing db service form depends_on for phraseanet and worker

PHRAS-3364 removing db service from depends_on for phraseanet and worker

---

lib/Alchemy/Phrasea/Out/Module/PDFCgu.php

- PHRAS-3080:  change cgu pdf filename

PHRAS-3080 change cgu pdf filename

---

Phraseanet-production-client/README.md
Phraseanet-production-client/config/config.js
Phraseanet-production-client/config/webpack/webpack.development.config.js
Phraseanet-production-client/config/webpack/webpack.production.minified.config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3374: Prod - upload overlay - rendering issue on Upload Overlays loading

PHRAS-3374 Prod - upload overlay - rendering issue on Upload Overlays loading

---

lib/classes/record/preview.php

- PHRAS-3378: Prod -Detailed view - Apply number formatting to result count " Result 1 900 / 902 723"

PHRAS-3378: Prod -Detailed view - Apply number formatting to result count " Result 1 900 / 902 723"

---

lib/Alchemy/Phrasea/Controller/Admin/DataboxController.php
lib/Alchemy/Phrasea/WorkerManager/Event/PopulateIndexEvent.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/databox/databox.html.twig

- PHRAS-3366: Admin - base base setting - Remove button "Re-index database now"

PHRAS-3366 Admin - Databox  setting -  Button "Re-index database now" send a populate 

---

lib/Alchemy/Phrasea/Setup/Requirements/BinariesRequirements.php
lib/Alchemy/Phrasea/Setup/Requirements/SystemRequirements.php

- PHRAS-3335: Admin - Dashboard - requirement - fix warning

PHRAS-3335 Admin - Dashboard - requirement - fix warning

---

.env
Dockerfile
docker-compose.yml
docker/phraseanet/entrypoint.sh
docker/phraseanet/worker/entrypoint.sh

- Adding NewRelic and Blackfire agent on Phraseanet and Worker container
see new env variables in `.env`
- PHRAS-3384

PHRAS-3384 add NewRelic and Blackfire agent on Phraseanet and worker container

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/preview/voting_notice.html.twig

- PHRAS-3388: generate translation for tab feedback result

PHRAS-3388 generate translation for tab feedback result

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/preview/voting_notice.html.twig

- PHRAS-3388: Prod - Baskets - Validation Basket - details view - add color and mailto on initiator

PHRAS-3388: Prod - Baskets - Validation Basket - details view - add color and mailto on initiator

---

templates/web/prod/preview/voting_notice.html.twig

- PHRAS-3388: Details view validation title clickable

PHRAS-3388 Details view validation title clickable

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/thesaurus/index.js

- PHRAS-3396: drop record on term is ok with ffox

PHRAS-3396_ffox-err-drop-record-on-term_MASTER

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/thesaurus/index.js
lib/Alchemy/Phrasea/Controller/Prod/ThesaurusController.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/Thesaurus/droppedrecords.html.twig

- PHRAS-3400: "operation" menu is ok on safari
- all js in twig is moved to prod-client (bump to v10)
- changed "poc/wip" message since now it writes meta

PHRAS-3400_safari-th-classification-bad-ops_MASTER

---

lib/classes/caption/Field/Value.php
lib/classes/record/adapter.php

- PHRAS-3397: adding/replacing values set_metadata() cannot create doubles in multi-v fields

PHRAS-3397_doubles-in-multi-values_MASTER

---

lib/Alchemy/Phrasea/Controller/Prod/PushController.php
templates/web/prod/actions/Push.html.twig

- PHRAS-3399: Prod - feedback - right issue

PHRAS-3399 Prod - feedback - right issue

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPush/feedback.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Push.html.twig
templates/web/prod/templates/push.html.twig

- PHRAS-3399: change initiator color badge
- invert button place

PHRAS-3399 fix initiator and button color

---

lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php

- PHRAS-3393: api v3 record metadata post/patch. Use the code that was moved to record adapter

PHRAS-3393_apiv3-patch-use-recordadapter_MASTER

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3391: Prod - Detailed view - feedback context - add confirmation when user try to delete a Record
- and change dialog window

PHRAS-3391 Prod - Detailed view - feedback context - add confirmation when user try to delete a Record

---

docker/phraseanet/entrypoint.sh
docker/phraseanet/worker/entrypoint.sh
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/GpsPosition.php

- PHRAS-3412 : invalid gps values are now ignored

PHRAS-3412_bad-gps-crash-indexation_MASTER

---

lib/Alchemy/Phrasea/Controller/Prod/ThesaurusController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/Thesaurus/droppedrecords.html.twig

- PHRAS-3411: Prod - String for Thesaurus as tx windows

PHRAS-3411 Prod - String for Thesaurus as tx windows

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposeNew.html.twig

- PHRAS-3420: Prod - expose - publication setting - layout selection - "Grid" Layout is missing

PHRAS-3420 Prod - expose - publication setting - layout selection - "Grid" Layout is missing

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php

- PHRAS-3421: Prod- expose - authentication for multi expose with password is NOK

PHRAS-3421 Prod- expose - authentication for multi expose with password is NOK

---

lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php

- PHRAS-3316: add retry on expose queue and fix purge

PHRAS-3316 add retry on expose queue and fix purge

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSAdminController.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php

- PHRAS-3422: Prod - Expose - Maintain hard link between Phraseanet records and Expose asset

PHRAS-3422 Prod - Expose - Maintain hard link between Phraseanet records and Expose asset

---

lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php

- PHRAS-3427: Worker - configuration - support the AMQPS SSL connection

PHRAS-3427 Worker - configuration - support the AMQPS SSL connection

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3391 
- PHRAS-3392 
- PHRAS-3426
- PHRAS-3420
- PHRAS-3417 
- PHRAS-3424

PHRAS-3416 phraseanet localization weblate

---

resources/locales/messages.fr.xlf

- Translation: Phraseanet/Phraseanet master message

PHRAS-3416 Translated using Weblate (French)

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposeNew.html.twig
templates/web/prod/WorkZone/Macros.html.twig
templates/web/prod/index.html.twig

- PHRAS-3316: add pub description, remove tree mode

PHRAS-3316 add pub description, remove tree mode

---

resources/locales/messages.fr.xlf

- Change string in french for expose

Translated using Weblate (French)

---

lib/Alchemy/Phrasea/WorkerManager/Worker/RecordEditWorker.php

- Add record edit payload to payload colon on table WorkerRunningJob
- PHRAS-3445

PHRAS-3445 Add record edit payload to DB

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPush/feedback.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3452: Prod - Push- Validation : Remove users is not possible

PHRAS-3452 Prod - Push- Validation : Remove users is not possible

---

lib/Alchemy/Phrasea/Controller/Prod/EditController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/edit_default.html.twig

- PHRAS-3032: Do not edit multi stories

PHRAS-3032 Do not edit multi stories

---

lib/Alchemy/Phrasea/WorkerManager/Queue/MessageHandler.php

- PHRAS-3454: Worker - write metadata « undefined index count »

PHRAS-3454 Worker - write metadata « undefined index count »

---

lib/Alchemy/Phrasea/WorkerManager/Worker/EditRecordWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/MainQueueWorker.php

- PHRAS-3445: some fix for edit worker

PHRAS-3445 some fix for edit worker

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/account.js
Phraseanet-production-client/dist/account.min.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/lazy-1.js
Phraseanet-production-client/dist/lazy-1.min.js
Phraseanet-production-client/dist/lazy-2.js
Phraseanet-production-client/dist/lazy-2.min.js
Phraseanet-production-client/dist/lazy-3.js
Phraseanet-production-client/dist/lazy-3.min.js
Phraseanet-production-client/dist/lightbox-mobile.js
Phraseanet-production-client/dist/lightbox-mobile.min.js
Phraseanet-production-client/dist/lightbox.js
Phraseanet-production-client/dist/lightbox.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/notify/index.js
Phraseanet-production-client/src/components/user/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3443: Prod - Maintenance message is not displayed to the end user

PHRAS-3443 :Prod - Maintenance message is not displayed to the end user

---

lib/Alchemy/Phrasea/Model/Entities/WorkerRunningJob.php
lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3447: exclusive lock for a worker to work on a subdef file

PHRAS-3447_file-lock-in-workers_4.1

---

lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php

- PHRAS-3469: faster sql/dql replace left joins by "inner join"+"union"

PHRAS-3469_slow-basket-select

---

lib/Alchemy/Phrasea/WorkerManager/Worker/PullAssetsWorker.php

- PHRAS-3438: fix uploader proxy

PHRAS-3438 fix uploader proxy

---

resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- Translation for 
PHRAS-3471
PHRAS-3466

Phras 3416 phraseanet localization weblate

---

lib/Alchemy/Phrasea/Border/Checker/Sha256.php
lib/Alchemy/Phrasea/Border/Checker/UUID.php
lib/Alchemy/Phrasea/Border/File.php
lib/Alchemy/Phrasea/Border/Manager.php
lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/classes/record/adapter.php

- PHRAS-3476: q-message "writemeta/document" is now sent after all synchronous exiftools.
added lot of traces, to be removed asap

PHRAS-3476_subdefs-corrupted

---

lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php

- PHRAS-3489 : align createtime and deadtime by using the same method (store in mysql converted to utc)

PHRAS-3489_order-from-parade-late-deadline

---

lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php

- PHRAS-3490: Admin - databases - collection setting- A duplication of value occurs when deleting suggested values

PHRAS-3490 Admin - databases - collection setting- A duplication of value occurs when deleting suggested values

---

lib/Alchemy/Phrasea/Setup/Installer.php

- PHRAS-3245: Install - scheduler - stop to create (default) tasks - subview and write metadata.

PHRAS-3245 : Install - scheduler - stop to create (default) tasks - subview and write metadata.

---

lib/Alchemy/Phrasea/Controller/Root/LoginController.php
lib/Alchemy/Phrasea/Helper/User/Manage.php

- PHRAS-3456: Admin - User registration - Send the email unlock account in first (Before renew password)

PHRAS-3456 Admin - User registration - Send the email unlock account in first (Before renew password)

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/databox/databox.html.twig
templates/web/admin/databox/details.html.twig

- PHRAS-3502: Admin - databases - database detail - add warn about document size return by GUI

PHRAS-3502 Admin - databases - database detail - add warn about document size return by GUI

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/index.js
lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/WorkZone/ExposeEdit.html.twig
templates/web/prod/WorkZone/ExposeNew.html.twig
templates/web/prod/WorkZone/ExposeOauthLogin.html.twig

- PHRAS-3507: Prod - Expose - Set null when user select "No parent publication"

PHRAS-3507 Prod - Expose - Set null when user select "No parent publication"

---

lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
lib/Alchemy/Phrasea/Model/Repositories/TokenRepository.php

- PHRAS-3348: gracefull delay of 30 days before removing expired validation token

PHRAS-3348 gracefull delay of 30 days before removing expired validation token

---

lib/Alchemy/Phrasea/Border/Manager.php
lib/Alchemy/Phrasea/Filesystem/FilesystemService.php
lib/Alchemy/Phrasea/Media/SubdefGenerator.php
lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
lib/classes/record/adapter.php

- PHRAS-3519: implement atomic (?) "tmp+move" method on uploaded file
add traces of document filesize

PHRAS-3519_upload-tmp-then-move

---

lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php

- PHRAS-3521: remove bad "assert"s

PHRAS-3521_export-by-email-not-stamped

---

templates/web/admin/collection/suggested_value.html.twig

- PHRAS-3490: fix null and undefined value

PHRAS-3490 : fix null and undefined value

---

lib/classes/recordutils/image.php

- PHRAS-3523: fix memory leak ; fix orientation of stamped images

PHRAS-3523_some-images-not-stamped

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3416 Phraseanet Translation weblate

---

composer.lock

- PHRAS-3514: bump embed-bundle 2.0.12

PHRAS-3514 bump embed-bundle 2.0.12

---

doc/development/external-lib/embend-bundle.md

- PHRAS-3532: Documentation - dev - init doc/developpement/external-lib repo - add dev workflow description for embed-bundle

PHRAS-3532 Documentation - dev - init doc/developpement/external-lib repo - add dev workflow description for embed-bundle

---

Dockerfile
composer.lock
lib/Alchemy/Phrasea/Border/MimeGuesserConfiguration.php

- PHRAS-2896:  Generate subdef for HEIC file - HEIF (High Efficiency Image Format)

PHRAS-2896 Generate subdef for HEIC file - HEIF (High Efficiency Image Format)

---

Dockerfile

- PHRAS-3543 update ca certificate
- PHRAS-3543 update ca certificate

PHRAS-3543 update ca certificate

---

composer.lock

- PHRAS-3514: bump embed-bundle for pdfjs

PHRAS-3514 bump embed-bundle for pdfjs

---

lib/Alchemy/Phrasea/Border/Checker/Sha256.php
lib/Alchemy/Phrasea/Border/Checker/UUID.php
lib/Alchemy/Phrasea/Border/File.php
lib/Alchemy/Phrasea/Border/Manager.php
lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
lib/Alchemy/Phrasea/Media/SubdefGenerator.php
lib/Alchemy/Phrasea/Metadata/PhraseanetMetadataSetter.php
lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
lib/classes/record/adapter.php

- PHRAS-3468: remove logs trace

PHRAS-3468 remove logs trace

---

docker/elasticsearch/Dockerfile
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/FieldToFieldMappingConverter.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/StringFieldMapping.php

- PHRAS-3583: fix sort on dates / num / business
- fix sort on multi-words strings / capitals / diacritics

PHRAS-3583_sort-on-dates

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Application/Helper/JsonBodyAware.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3SubdefsServiceController.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
lib/Alchemy/Phrasea/Filesystem/FilesystemService.php
lib/Alchemy/Phrasea/Media/SubdefGenerator.php

- PHRAS-3564 Graphic rendition service for PS, For TEST only Not for Production.

PHRAS-3564_subdef-service-api_v2

---

lib/Alchemy/Phrasea/Filesystem/PhraseanetFilesystem.php

- PHRAS-3519: faster return of fs->exists() if file exists

PHRAS-3519_filesystem-atomic-move : faster

---

lib/Alchemy/Phrasea/Helper/JsonBodyHelper.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-3555: missing translation

PHRAS-3555 missing translation

---

lib/classes/record/adapter.php

- PHRAS-3584 : clear record cache

PHRAS-3584 : clear record cache

---

lib/Alchemy/Phrasea/Model/Entities/ApiApplication.php
lib/classes/patch/415PHRAS3555.php

- PHRAS-3555: change column webhook_unactivate to webhook_active

PHRAS-3555 change column webhook_unactivate to webhook_active

---

lib/Alchemy/Phrasea/Core/Event/Record/CollectionChangedEvent.php

- PHRAS-3555: rename collection_id to base_id

PHRAS-3555 rename to base_id

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/account.js
Phraseanet-production-client/dist/account.min.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/src/components/account/index.js
lib/Alchemy/Phrasea/Command/User/UserApplicationsCommand.php
lib/Alchemy/Phrasea/Controller/Root/DeveloperController.php
lib/Alchemy/Phrasea/ControllerProvider/Root/Developers.php
lib/Alchemy/Phrasea/Model/Entities/ApiApplication.php
lib/Alchemy/Phrasea/Model/Manipulator/ApiApplicationManipulator.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/developers/application.html.twig
tests/Alchemy/Tests/Phrasea/WorkerManager/Worker/WebhookWorkerTest.php

- PHRAS-3598: taking account  webhook active and GUI

PHRAS-3598 taking account  webhook active

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
lib/Alchemy/Phrasea/Controller/Prod/StoryController.php
lib/Alchemy/Phrasea/Core/Event/RecordEdit.php
lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookRecordEventSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/CreateRecordWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/EditRecordWorker.php
lib/classes/record/adapter.php

- PHRAS-3555: add description in record.edit webhook

PHRAS-3555 add description in record.edit webhook

---

lib/Alchemy/Phrasea/Model/Entities/FeedItem.php
lib/classes/patch/415PHRAS3604.php
lib/classes/record/adapter.php
templates/web/prod/results/item.html.twig

- PHRAS-3604: do not display removed record in publication

PHRAS-3604 do not display removed record in publication

---

doc/API_documentation/v3/_compiled.yaml
doc/API_documentation/v3/api.yaml
doc/API_documentation/v3/record.yaml
doc/API_documentation/v3/search.yaml

- PHRAS-3607: fix mismatch record_id / story_id
- PHRAS-3607: add bases[]

PHRAS-3607 : apiv3 doc

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/Thesaurus/droppedrecords.html.twig

- PHRAS-3601: change translation string

PHRAS-3601 change translation string

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/Thesaurus/droppedrecords.html.twig

- PHRAS-3601: remove string on title

PHRAS-3601 remove string on title

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/ExistsExpression.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/KeyValue/MissingExpression.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php

- PHRAS-3417:change _empty_ special search value to _unset_

PHRAS-3417change _empty_ special search value to _unset_

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/search/index.js
Phraseanet-production-client/src/components/ui/workzone/facets/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/index.html.twig

- PHRAS-3609: color unset facets

PHRAS-3609 color unset facets

---

lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php

- PHRAS-3614: send heartbeat when set Q

PHRAS-3614 send heartbeat when set Q

---

.env
CHANGELOG.md

release version 4.1.5
- Update change log
- Bump docker image tag version

PHARS-3601 4.1.5 release

---

lib/classes/record/adapter.php

- PHRAS-3628: fix error 500 on api_v3 / records / POST with no file

PHRAS-3628 : 500 on API.create record

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Helper.php

- PHRAS-3285: Thesaurus - candidat panel - The Stock is not available

PHRAS-3285 Thesaurus - candidat panel - The Stock is not available

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/www/thesaurus/styles/main.scss
templates/web/thesaurus/export-text-dialog.html.twig
templates/web/thesaurus/import-dialog.html.twig
templates/web/thesaurus/properties.html.twig
templates/web/thesaurus/thesaurus.html.twig

- PHRAS-3229: Thesaurus GUI improvement - import - refresh candidat terms

PHRAS-3229 Thesaurus GUI improvement - import - refresh candidat terms

---

Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/print.js
lib/Alchemy/Phrasea/Controller/Prod/PrinterController.php
lib/Alchemy/Phrasea/Helper/Record/Printer.php
lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
lib/Alchemy/Phrasea/Out/Tool/PhraseaPDF.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/printer_default.html.twig
templates/web/prod/index.html.twig

- PHRAS-3633: Prod - Print records - add customisable "Title" and "Message" to generated PDF

PHRAS-3633 Prod - Print records - add customisable "Title" and "Message" to generated PDF

---

lib/Alchemy/Phrasea/Controller/Prod/PrinterController.php
lib/Alchemy/Phrasea/Helper/Record/Printer.php
lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/printer_default.html.twig

- PHRAS-3633:some print improvement

PHRAS-3633 : some print improvement

---

templates/web/prod/actions/printer_default.html.twig

- PHRAS-3633: invert box place
- default value 2 days

PHRAS-3633 : invert box place

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- localisation for Print PDF improvement

PHRAS-3633 localisation for Print PDF improvement

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3381 Missing translation for thesaurus as tx

---

templates/web/prod/actions/printer_default.html.twig

- PHRAS-3633: make in new line the input ttl

PHRAS-3633 : make in new line the input ttl

---

lib/Alchemy/Phrasea/Controller/MediaAccessorController.php
lib/Alchemy/Phrasea/Controller/Prod/PrinterController.php
lib/Alchemy/Phrasea/Helper/Record/Printer.php
lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/printer_default.html.twig

- PHRAS-3633: add option filename when download check

PHRAS-3633 : add option filename when download check

---

lib/Alchemy/Phrasea/Controller/Prod/PrinterController.php
lib/Alchemy/Phrasea/Helper/Record/Printer.php
lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
templates/web/prod/actions/printer_default.html.twig

- PHRAS-3633: title as the pdf filename

PHRAS-3633 : title as the pdf filename

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/notify/notifyLayout.js
lib/Alchemy/Phrasea/Controller/User/UserNotificationController.php
lib/Alchemy/Phrasea/ControllerProvider/User/Notifications.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
lib/classes/eventsmanager/broker.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/notifications_dialog.html.twig

- PHRAS-3631:  Prod : Notifications : Add a fonction to mark all notification as read

PHRAS-3631: Prod : Notifications : Add a fonction to mark all notification as read

---

lib/Alchemy/Phrasea/Controller/Api/V3/V3Controller.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php

- PHRAS-3642: API - Return subdefs with API /api/v3/databoxes/{databox_id}/subdefs/ and /api/v3/databoxes/subdefs/

PHRAS-3642 API - Return subdefs with API /api/v3/databoxes/{databox_id}/subdefs/ and /api/v3/databoxes/subdefs/

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/SubDefinitionHydrator.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/MetadataTagToFieldMappingConverter.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
lib/classes/media/subdef.php

- PHRAS-3215: add ThumbnailOrientation facet ; add strings
- Require a Drop Create Populate of elastic Index. 
- Activate facets  in  Admin/search engine setting  GUI or edit `facets` in  `search-engine` section in configuration.yml

PHRAS-3215 : add ThumbnailOrientation facet ; add strings

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/SubDefinitionHydrator.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/MetadataTagToFieldMappingConverter.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
lib/classes/media/subdef.php

Reverts alchemy-fr/Phraseanet#3973

 "PHRAS-3215 : Revert add ThumbnailOrientation facet ; add strings"

---

.env
CHANGELOG.md
lib/Alchemy/Phrasea/Core/Version.php

- PHRAS-3644: Release 4.1.6 and intermediate Release candidat

PHRAS-3644 Release 4.1.6 and intermediate Release candidat

---

lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchSettingsFormType.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/SubDefinitionHydrator.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/MetadataTagToFieldMappingConverter.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
lib/classes/media/subdef.php

- PHRAS-3215: add ThumbnailOrientation facet ; add strings
- Require a Drop Create Populate of elastic Index. 
- Activate facets  in  Admin/search engine setting  GUI or edit `facets` in  `search-engine` section in configuration.yml

PHRAS-3215 : merge add ThumbnailOrientation facet

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-3215: image orientation generate string

PHRAS-3215 image orientation generate string

---

resources/www/admin/styles/main.scss
templates/web/admin/users.html.twig

- PHRAS-3560: add space between button

PHRAS-3560 add space between button

---

docker-compose.datastores.yml
docker-compose.yml
lib/Alchemy/Phrasea/WorkerManager/Queue/MessagePublisher.php

- PHRAS-3653: Worker queue message : publish messages as persitent into rabbitmq queues

PHRAS-3653 Worker queue message : publish messages as persitent into rabbitmq queues

---

lib/Alchemy/Phrasea/Helper/User/Edit.php
lib/Alchemy/Phrasea/Helper/User/Manage.php
lib/Alchemy/Phrasea/Model/Manager/UserManager.php
lib/classes/User/Query.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
resources/www/admin/styles/main.scss
templates/web/admin/editusers.html.twig
templates/web/admin/users.html.twig

- PHRAS-3656: Admin - users list - adding search option to user 's creation, update and last connection date

PHRAS-3656 Admin - users list - adding search option to user 's creation, update and last connection date

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3656 localization Fix typo

PHRAS-3416 phraseanet localization

---

lib/Alchemy/Phrasea/Authentication/Phrasea/FailureManager.php
lib/Alchemy/Phrasea/Controller/Admin/UserController.php
lib/Alchemy/Phrasea/ControllerProvider/Admin/Users.php
lib/Alchemy/Phrasea/Helper/User/Manage.php
lib/Alchemy/Phrasea/Model/Repositories/ApiApplicationRepository.php
lib/Alchemy/Phrasea/Model/Repositories/ApiOauthCodeRepository.php
lib/classes/User/Query.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/editusers.html.twig
templates/web/admin/users.html.twig

- PHRAS-3223:  Admin - user details - Add tab for display AuthFailure table

PHRAS-3223 Admin - user details - display AuthFailure and Authprovider info 

---

resources/locales/messages.ar.xlf
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf

- PHRAS-3223 translation for auth failure display in admin GUI
- PHRAS-3560 translation for filter
- PHRAS-3659 fix string

PHRAS-3223 translation

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3602 Share Basket localization first iteration on french and english

PHRAS-3602 Share Basket  localization

---

.circleci/config.yml
resources/hudson/InstallDBs.yml

- PHRAS-3673: (after ssh tryout) change localhost to 127.0.0.1

PHRAS-3673_ci-fails-phr-install

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php

- PHRAS-3670: Prod - workzone - error 500 when try printing a feedback report

PHRAS-3670: Prod - workzone - error 500 when try printing a feedback report

---

.circleci/config.yml
lib/Alchemy/Phrasea/WorkerManager/Worker/WorkerInvoker.php
resources/hudson/InstallDBs.yml

- PHRAS-3675 heartbeat hot fix

PHRAS-3675 heartbeat hot fix

---

lib/Alchemy/Phrasea/ControllerProvider/Lightbox.php
lib/Alchemy/Phrasea/Model/Entities/BasketElement.php
lib/Alchemy/Phrasea/Model/Repositories/BasketElementRepository.php
lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
lib/classes/ACL.php
templates/web/lightbox/sc_container.html.twig
templates/web/lightbox/selector_box.html.twig
templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-3671: remove doctrine transaction
optim acl
prefetch records
gc_collect
- PHRAS-3677 : display "not-voted" votes in wz/baskets

PHRAS-3671_slow_share_basket_worker

---

lib/Alchemy/Phrasea/Model/Entities/ElasticsearchRecord.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchRecordHydrator.php
lib/classes/record/adapter.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/common/technical_datas.html.twig

- PHRAS-3674: Prod - Record Information - Add Databox name in information

PHRAS-3674 Prod - Record Information - Add Databox name in information

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/recordPreview/index.js
lib/Alchemy/Phrasea/Model/Entities/Basket.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3676: fix record position in detailed view

PHRAS-3676 : fix record position in detailed view

---

lib/Alchemy/Phrasea/WorkerManager/Command/WorkerExecuteCommand.php
lib/Alchemy/Phrasea/WorkerManager/Queue/MessageHandler.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ProcessPool.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WorkerInvoker.php

PHRAS-3675 fix hearbeat

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3602 Share basket translation

PHRAS-3416 phraseanet localization3

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/lightbox.js
Phraseanet-production-client/dist/lightbox.min.js
Phraseanet-production-client/src/components/lightbox/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss
templates/mobile/lightbox/basket_element.html.twig
templates/web/lightbox/agreement_box.html.twig
templates/web/lightbox/index.html.twig

- PHRAS-3678: lightbox fix short cut when vote

PHRAS-3678 lightbox fix short cut when vote/forbidden vote on session close

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/list/listManager.js
Phraseanet-production-client/src/components/record/pushOrShare/index.js
Phraseanet-production-client/src/components/record/pushOrShare/pushOrShare.js
Phraseanet-production-client/src/components/record/sharebasketModal.js
lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
lib/Alchemy/Phrasea/Model/Entities/BasketElement.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-3672: fix wording issue

PHRAS-3672 fix wording issue

---

templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-3684: add lines `<hr/>` to separate the 3 wz blocks

PHRAS-3684_wz-blocks-separation

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/pushOrShare/index.js
lib/Alchemy/Phrasea/Controller/Prod/StoryController.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/Story/Create.html.twig
templates/web/prod/WorkZone/Macros.html.twig
tests/Alchemy/Tests/Phrasea/Controller/Prod/StoryTest.php

- PHRAS-3685: Don't propose to set a name for a story

PHRAS-3685 Don't propose to set a name for a story

---

.circleci/config.yml
.env
lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php

- PHRAS-3691: Backport to 4.1.6-rc2 - fix CircleCI build - url link

PHRAS-3691 Backport to 4.1.6-rc2 - fix CircleCI build - url link

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3663 prod workzone filter localisation

PHRAS-3663 prod workzone filter localisation

---

lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndexer.php
lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/Term.php

- PHRAS-3693: candidate special char in rc2

PHRAS-3693 candidate special char in rc2

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
lib/conf.d/configuration.yml

PHRAS-3692 test git wk

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
lib/conf.d/configuration.yml

- PHRAS-3692: Add facet's default orders value to user settings
- Allow to set default facet orders to all newly created user or user that have never changed facet orders.

PHRAS-3692 Add facet's default orders value to user settings

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/pushOrShare/pushOrShare.js
lib/Alchemy/Phrasea/Core/Event/Subscriber/BasketSubscriber.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Push.html.twig
templates/web/prod/templates/push.html.twig

- PHRAS-3665: Prod : fix Validation reminder cannot be disabled

PHRAS-3665 Prod : fix Validation reminder cannot be disabled 

---

README.md
docker/phraseanet/entrypoint.sh

- PHRAS-3683: New dc() function in README
- PHRAS-3683: Support space in .env variables

PHRAS-3683 : Support space in .env variables

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/edit.js
Phraseanet-production-client/src/components/record/recordEditor/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/actions/edit_default.html.twig

- PHRAS-3679: Prod reload when editing multi-databox records

PHRAS-3679 Prod reload when editing multi-databox records

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/pushOrShare/pushOrShare.js
lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
lib/Alchemy/Phrasea/Controller/Prod/PushController.php
lib/Alchemy/Phrasea/Model/Entities/Basket.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/Basket.html.twig

- PHRAS-3695 : Prod - basket and feedback displayed informations improvement

PHRAS-3695 Prod - basket and feedback displayed informations improvement

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/videoEditor/videoSubtitleCapture.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3639: Prod - Video tools - Subtitle editing

PHRAS-3639 Prod - Video tools - Subtitle editing

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
lib/Alchemy/Phrasea/WorkerManager/Provider/ControllerServiceProvider.php
lib/Alchemy/Phrasea/WorkerManager/Worker/DeleteRecordWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/index.html.twig
templates/web/admin/worker-manager/worker_info.html.twig
templates/web/admin/worker-manager/worker_info_change_status.html.twig

- PHRAS-3525: Admin can change status to canceled for multiple job

PHRAS-3525 Admin can change status to canceled for multiple job

---

templates/web/admin/worker-manager/worker_info_change_status.html.twig

- PHRAS-3525: fix job count display

PHRAS-3525 fix job count display

---

lib/Alchemy/Phrasea/Model/Entities/Basket.php

- PHRAS-3701: Check why the user received a 500 error at first connection - see on docker context

PHRAS-3701 : Check why the user received a 500 error at first connection - see on docker context

---

lib/Alchemy/Phrasea/Out/Module/PDF.php
lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
lib/Alchemy/Phrasea/Out/Tool/PhraseaPDF.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/notifications_dialog.html.twig

- PHRAS-3699: fix missing translation

PHRAS-3699 fix missing translation

---

resources/locales/messages.de.xlf

- PHRAS-3699 several fix on German strings

PHRAS-3416  several fix on German strings 

---

lib/Alchemy/Phrasea/Out/Tool/PhraseaPDF.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/actions/Push.html.twig

- PHRAS-3699: missing translation

PHRAS-3699 missing translation

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3416 translation for PDF 

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
resources/locales/messages.de.xlf

- PHRAS-3706: Prod - 500 error when print a feedback report

PHRAS-3706 Prod - 500 error when print a feedback report

---

lib/Alchemy/Phrasea/Out/Module/PDFRecords.php

- PHRAS-3708: prod - printed PDF the Unexpressed user vote is missing

PHRAS-3708 prod - printed PDF the Unexpressed user vote is missing

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3416 phraseanet localization8

---

templates/web/lightbox/agreement_box.html.twig

- PHRAS-3709: lightbox - feedback - unexpressed vote don't appear

PHRAS-3709 lightbox - feedback - unexpressed vote don't appear

---

config/configuration.sample.yml
docker-compose.under-phrasea.yml
lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
lib/conf.d/configuration.yml

- add extra hosts to worker service
- add `verify_ssl` option in `workers.webhook` (default to `true`)

PHRAS-3704 add webhook client verify_ssl option

---

templates/web/admin/editusers.html.twig

- PHRAS-3711: Admin - Users - Modify multiple users rights

PHRAS-3711 Admin - Users - Modify multiple users rights

---

templates/web/admin/editusers.html.twig

- PHRAS-3711: Admin - Users - Modify multiple users rights rc2

PHRAS-3711 Admin - Users - Modify multiple users rights rc2

---

README.md
docker/phraseanet/setup/entrypoint.sh
infra/helm/README.md
infra/helm/all/templates/database.yml
infra/helm/all/templates/elasticsearch.yml
infra/helm/all/templates/gateway.yml
infra/helm/all/templates/phraseanet-setup.yml
infra/helm/all/templates/worker.yml
infra/helm/deploy-minikube.sh
infra/helm/myvalues.yaml

- PHRAS-3657: add helm job for phraseanet setup
- Allow an independent job to run phraseanet install, setup or upgrade

PHRAS-3657 Phraseanet Setup helm job

---

lib/Alchemy/Phrasea/Command/BuildSubdefs.php
lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3Controller.php
lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
lib/classes/databox/subdef.php
lib/classes/databox/subdefsStructure.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/subdefs.html.twig

- PHRAS-3712: admin - sudefinition - property to define building rules on subdefinition
- add atribute "tobuild" default value true

PHRAS-3712 admin - sudefinition - property to define building rules on subdefinition

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3725 "quit shared basket" missing string

PHRAS-3416 quit shared basket" missing string

---

lib/Alchemy/Phrasea/Collection/CollectionService.php
lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php
lib/Alchemy/Phrasea/Controller/Admin/DataboxController.php
lib/Alchemy/Phrasea/WorkerManager/Worker/MainQueueWorker.php
lib/classes/collection.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/databox/databox.html.twig
tests/Alchemy/Tests/Phrasea/Controller/Admin/AdminCollectionTest.php
tests/Alchemy/Tests/Phrasea/Controller/Admin/DataboxTest.php

- PHRAS-3235:Admin - Collection - Emptying a collection by deleteRecord worker

PHRAS-3235 Admin - Collection - Emptying a collection by deleteRecord worker

---

lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php
lib/Alchemy/Phrasea/PhraseanetService/Form/PSUploaderConfigurationType.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
resources/www/admin/styles/main.scss
templates/web/admin/phraseanet-service/uploader.html.twig

- PHRAS-3729: some change and string

PHRAS-3729 some change and string

---

lib/Alchemy/Phrasea/Controller/Admin/DataboxController.php
templates/web/admin/collection/create.html.twig

- PHRAS-3740: Admin -database - create collection - collection Right duplication drop down - display collection sorted by database

PHRAS-3740 Admin -database - create collection - collection Right duplication drop down - display collection sorted by database

---

lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
lib/Alchemy/Phrasea/Controller/RecordsRequest.php
templates/web/prod/actions/delete_records_confirm_form.html.twig

- PHRAS-3737: Prod - Delete story - Delete also attached record is NOK

PHRAS-3737 Prod - Delete story - Delete also attached record is NOK

---

.env
docker-compose.yml
docker/nginx/root/nginx.conf.sample
docker/phraseanet/root/usr/local/etc/maintenance.html
docker/phraseanet/setup/entrypoint.sh

- PHRAS-3734: add a sorry server to docker stack
- Allow to activate, disable or persit an unavailability message

PHRAS-3734 add maintenance mode to stack

---

Dockerfile

Reverts alchemy-fr/Phraseanet#4126

Revert "Add JQ php extension (required by incoming openid auth plugin)"

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3738: Admin - worker - job tab - add filter on databox_id (name),record_id

PHRAS-3738 Admin - worker - job tab - add filter on databox_id (name),record_id

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3743 Admin - databox, collection operation help 

---

Dockerfile
docker/phraseanet/setup/auto-install.sh

- PHRAS-3748: split dockerfile into multiple runs and fix elasticsearch
- run multiple lines executions into dockerfile for better debug

PHRAS-3748 split dockerfile into multiple runs and fix elasticsearch

---

CHANGELOG.md
README.md

PHRAS-3602 4.1.6 changelog

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php

- PHRAS-3750: fix filter on databox and record

PHRAS-3750 admin> job fix filter on databox and record

---

.env
docker-compose.tools.yml
docker/nginx/root/nginx.conf.sample
docker/phraseanet/saml-sp/root/bootstrap/entrypoint.sh

- PHRAS-3318: Fix phraseanet-saml-sp for kubernets use
- change container name and nginx configuration

PHRAS-3318 - Fix phraseanet-saml-sp for kubernets use

---

lib/Alchemy/Phrasea/Authentication/Authenticator.php
lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php
lib/Alchemy/Phrasea/ControllerProvider/Prod/Root.php
lib/Alchemy/Phrasea/Core/Version.php
lib/Alchemy/Phrasea/Model/Entities/User.php
lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
lib/Alchemy/Phrasea/Notification/Mail/MailRequestInactifAccount.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-3694: bin/maintenance clean:users finish

PHRAS-3694 bin/maintenance clean:users finish

---

lib/Alchemy/Phrasea/Controller/Admin/ConnectedUsersController.php
lib/Alchemy/Phrasea/Controller/Admin/DashboardController.php
lib/Alchemy/Phrasea/ControllerProvider/Admin/ConnectedUsers.php
lib/Alchemy/Phrasea/ControllerProvider/Admin/Dashboard.php
templates/web/admin/connected-users.html.twig
templates/web/admin/dashboard.html.twig

- PHRAS-3755: Admin - connected user - add button for Disconnecting a user by destroy session
- double click on a user list in connected user  **go to** user info

PHRAS-3755  Admin - connected user - add button for Disconnecting a user by destroy session

---

Dockerfile
lib/Alchemy/Phrasea/WorkerManager/Command/WorkerExecuteCommand.php

- PHRAS-3762: check worker connexion number on init

PHRAS-3762 check worker connexion number on init

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3750: job-info-some-improve

PHRAS-3750 PHRAS-3750-job-info-some-improve

---

Dockerfile
docker/phraseanet/worker/entrypoint.sh
docker/phraseanet/worker/logrotate/worker
lib/Alchemy/Phrasea/WorkerManager/Command/WorkerExecuteCommand.php
lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php

- PHRAS-3760: logs file - remove date from name of current log file - worker

PHRAS-3760 logs file - remove date from name of current log file - worker

---

lib/Alchemy/Phrasea/Controller/Api/OAuth2Controller.php
lib/classes/API/OAuth2/Adapter.php

- PHRAS-3765: allow oauth api clients to pass "custom" parameters in session

PHRAS-3765_oauth-parms-in-session

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3750: select field for time filter

PHRAS-3750 : select field for time filter

---

docker/phraseanet/worker/entrypoint.sh
docker/phraseanet/worker/logrotate/worker
lib/Alchemy/Phrasea/Command/TaskManagerCommand.php
lib/Alchemy/Phrasea/TaskManager/Log/TaskLogFile.php

- PHRAS-3760: task and scheduler log

PHRAS-3760: task and scheduler log

---

lib/Alchemy/Phrasea/Cache/Manager.php
lib/Alchemy/Phrasea/Command/Setup/ConfigurationEditor.php

- PHRAS-3772: bin/setup system:config 
- catch exception on redis connection, don't parse a file

PHRAS-3772 : bin/setup system:config 

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3750: real entry duration

PHRAS-3750 real entry duration

---

templates/web/admin/worker-manager/worker_info.html.twig

- PHRAS-3750:  fix job list order

PHRAS-3750 : fix job list order

---

bin/console
infra/tools/stack_migration/README.md
infra/tools/stack_migration/datastores_conf.sh
infra/tools/stack_migration/email_conf.sh
infra/tools/stack_migration/network_conf.sh
infra/tools/stack_migration/storage_conf.sh
lib/Alchemy/Phrasea/Command/Setup/ConfigurationEditor.php
lib/Alchemy/Phrasea/Core/Configuration/Configuration.php
lib/Alchemy/Phrasea/Core/Configuration/ConfigurationInterface.php
lib/Alchemy/Phrasea/Core/Configuration/HostConfiguration.php
lib/Alchemy/Phrasea/Core/Provider/ORMServiceProvider.php
lib/Alchemy/Phrasea/Core/Version/VersionRepository.php
lib/Alchemy/Phrasea/Setup/ConfigurationTester.php
lib/classes/base.php
tests/Alchemy/Tests/Phrasea/MockArrayConf.php

- PHRAS-3772 : bin/setup system:config add option

PHRAS-3772 bin/setup system:config add option

---

templates/web/prod/actions/Tools/index.html.twig

- PHRAS-3774: Prod - actions - fix design windows when more of one records is selected

PHRAS-3774 Prod - actions - fix design windows when more of one records is selected

---

lib/Alchemy/Phrasea/Controller/Admin/ConnectedUsersController.php
lib/Alchemy/Phrasea/WorkerManager/Command/WorkerExecuteCommand.php

PHRAS-3778 remove some logs

---

lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php

- PHRAS-3775: admin - worker - job tab - job line - manually ack a job is Broken

PHRAS-3775 admin - worker - job tab - job line - manually ack a job is Broken

---

composer.lock

- PHRAS-3778: update lib geonames-api-consumer to 0.1.3

PHRAS-3778 update lib geonames-api-consumer to 0.1.3

---

templates/web/prod/results/record.html.twig

- PHRAS-3781: remove preview symlink

PHRAS-3781 remove preview symlink

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Authentication/Provider/PsAuth.php
lib/Alchemy/Phrasea/Core/Version.php
lib/classes/patch/417RC2PHRAS2995.php
lib/conf.d/configuration.yml
resources/ansible/roles/app/templates/configuration.tpl
resources/vagrant/config/phraseanet/configuration.yml

- PHRAS-3789: patch to add missing options to conf
- PHRAS-3789: add auto-connect-idp-name option

PHRAS-3789_psauth-auto-select-idp

---

.env
docker-compose.yml

- removing depends_on in docker-compose for better usage when using managed service for datastores.
- fix typo in env

PHRAS-3788 Backport removing of depends_on , fix .env values

---

.env
docker-compose.yml

- docker-compose removing `depends_on` for some containers

PHRAS-3788 docker-compose removing depends_on

---

templates/web/prod/WorkZone/ExposePublicationAssets.html.twig

- PHRAS-3596: fix button position

PHRAS-3596 fix button position

---

.circleci/config.yml

- PHRAS-3792 including git log in builded images

PHRAS-3792 including git log in builded images

---

lib/Alchemy/Phrasea/Authentication/Authenticator.php
tests/Alchemy/Tests/Phrasea/Authentication/AuthenticatorTest.php

- PHRAS-3791: allow multiple calls to closeAccount()

PHRAS-3791_saml-logout-500

---

resources/www/common/styles/fonts/PhraseanetIcomoon/style.css

- PHRAS-3795 : Prod - fix 404 on GET icomoon.woff?z35ucj

PHRAS-3795 Prod - fix 404 on GET icomoon.woff?z35ucj

---

lib/Alchemy/Phrasea/Webhook/WebhookInvoker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php

- PHRAS-3778: export email logs

PHRAS-3778 export email logs

---

bin/console
lib/Alchemy/Phrasea/Model/Manipulator/WebhookEventDeliveryManipulator.php
lib/Alchemy/Phrasea/Model/Repositories/WebhookEventDeliveryRepository.php
lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php

- PHRAS-3598: Webhook - Emit improvement - Count and Log errors - stop to notify endpoint in error

PHRAS-3598 Webhook - Emit improvement - Count and Log errors - stop to notify endpoint in error

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/index.js
lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/WorkZone/ExposeList.html.twig
templates/web/prod/WorkZone/ExposePublicationAssets.html.twig

- PHRAS-3596: fix capabilities info

PHRAS-3596 fix capabilities info

---

docker/phraseanet/worker/entrypoint.sh

- PHRAS-3144: add plugin post install script on worker image
- Activating plugins into the worker container/pods

PHRAS-3144 add plugin post install script on worker image

---

lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php
lib/Alchemy/Phrasea/Helper/User/Manage.php
lib/Alchemy/Phrasea/Notification/Mail/MailRequestInactifAccount.php
lib/Alchemy/Phrasea/Notification/Mail/MailSuccessAccountInactifDelete.php
lib/classes/User/Query.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/users.html.twig

- PHRAS-3694: notif by email on delete inactif account, admin filter

PHRAS-3694 notif by email on delete inactif account, admin filter

---

lib/Alchemy/Phrasea/Controller/Root/LoginController.php
lib/Alchemy/Phrasea/Notification/Mail/MailRequestPasswordUpdate.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
tests/Alchemy/Tests/Phrasea/Controller/Root/LoginTest.php
tests/Alchemy/Tests/Phrasea/Notification/Mail/MailRequestPasswordUpdateTest.php

- PHRAS-3802: forgotten password change string

PHRAS-3802 forgotten password change string

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

Phras 3416 phraseanet localization8

---

lib/Alchemy/Phrasea/Command/MailTest.php
lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php
lib/Alchemy/Phrasea/Controller/Admin/DashboardController.php
lib/Alchemy/Phrasea/Model/Manager/UserManager.php
lib/Alchemy/Phrasea/Notification/Mail/AbstractMail.php
lib/Alchemy/Phrasea/Notification/Mail/MailCheck.php
lib/Alchemy/Phrasea/Notification/Mail/MailInterface.php
lib/Alchemy/Phrasea/Notification/Mail/MailRequestInactifAccount.php
lib/Alchemy/Phrasea/Notification/Mail/MailSuccessAccountInactifDelete.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/email-template.html.twig
tests/Alchemy/Tests/Phrasea/Command/MailTestTest.php
tests/Alchemy/Tests/Phrasea/Controller/Admin/AdminDashboardTest.php
tests/Alchemy/Tests/Phrasea/Notification/Mail/MailCheckTest.php

- PHRAS-3694: clean:user some fix
- add email deletion string
- more info on command help
- taken account locale on mail
- test clean table OK on ftpexport ,ftpExportElement ,record_right ,notification

PHRAS-3694 clean:user some fix

---

lib/Alchemy/Phrasea/Model/Manager/UserManager.php

- PHRAS-3694: clean ftpcredential an user list

PHRAS-3694: clean ftpcredential an user list

---

templates/web/prod/results/record.html.twig

- PHRAS-3808: Prod - video tools - Hiding "video tools" menu item when user doesn't have this right

PHRAS-3808 : Prod - video tools - Hiding "video tools" menu item when user doesn't have this right

---

lib/Alchemy/Phrasea/Controller/Prod/PushController.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
lib/classes/ACL.php

- PHRAS-3793: Shared basket - Update record_right when a share expire

PHRAS-3793 Shared basket - Update record_right when a share expire

---

docker/phraseanet/worker/entrypoint.sh

- PHRAS-3144:  add plugin post install and clean cache before run
- cache directory writing error fix

PHRAS-3144 add plugin post install clean cache

---

lib/Alchemy/Phrasea/Model/Manager/UserManager.php

- PHRAS-3694: fix clean usrlist

PHRAS-3694 fix clean usrlist

---

docker-compose.yml
lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Model/Entities/LazaretFile.php
lib/classes/eventsmanager/notify/uploadquarantine.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/upload/lazaret.html.twig

- PHRAS-2948: Lazaret ( quarantine ) - disabled a checker cause a 500 error
- fix on api , quarantine tab and notifications

PHRAS-2948 Lazaret ( quarantine ) - disabled a checker cause a 500 error

---

.env
docker-compose.datastores.yml

- PHRAS-3812: Rabbitmq define hostname
- to avoid random database name

PHRAS-3812 Rabbitmq define hostname

---

config/configuration.sample.yml
lib/Alchemy/Phrasea/Core/Version.php
lib/classes/patch/417RC5PHRAS3804.php
templates/web/common/axeptio.html.twig
templates/web/common/index_bootstrap.html.twig
templates/web/common/indexfloat.html.twig
templates/web/login/layout/base-layout.html.twig

- PHRAS-3804: add cookie consent axeptio

PHRAS-3804 add cookie consent axeptio

---

docker/phraseanet/setup/auto-install.sh
docker/phraseanet/setup/entrypoint.sh
lib/Alchemy/Phrasea/Command/Setup/ConfigurationEditor.php

- PHRAS-3798: bin/setup - system:config set - return sensitive credential on stdout
- use -q ou --quiet  option

PHRAS-3798 bin/setup - system:config set - return sensitive credential on stdout

---

lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php

- PHRAS-3694: clean:users Short description of bug and fix

PHRAS-3694 clean:users fix max relance = 0

---

lib/Alchemy/Phrasea/Webhook/EventProcessorFactory.php
lib/Alchemy/Phrasea/Webhook/Processor/SubdefEventProcessor.php

- PHRAS-3817: retrieve permalink if empty when sending webhook

PHRAS-3817 retrieve permalink if empty when sending webhook

---

templates/web/prod/WorkZone/Basket.html.twig
templates/web/prod/WorkZone/Story.html.twig

- PHRAS-3758: PROD : Baskets : Unable to start a feedback from Action menu in a basket I have Created until basket has been shared on version 4.1.6
- add share button

PHRAS-3758 PROD : Baskets : Unable to start a feedback from Action menu 

---

lib/classes/patch/416RC3PHRAS3602.php

- PHRAS-3814: Share basket fix migration patch

PHRAS-3814 Share basket fix migration patch

---

lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php

- PHRAS-3694 not send confirmation email if max relance 0

PHRAS-3694 not send confirmation email if max relance 0

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/lazy-1.js
Phraseanet-production-client/dist/lazy-1.min.js
Phraseanet-production-client/dist/lazy-2.js
Phraseanet-production-client/dist/lazy-2.min.js
Phraseanet-production-client/dist/lazy-3.js
Phraseanet-production-client/dist/lazy-3.min.js
Phraseanet-production-client/dist/lightbox.js
Phraseanet-production-client/dist/lightbox.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/videoEditor/index.js
Phraseanet-production-client/src/components/ui/index.js
Phraseanet-production-client/src/components/ui/toolbar/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3569: Prod - video tools - sometimes ERROR about record file type

PHRAS-3569 Prod - video tools - sometimes ERROR about record file type

---

docker/phraseanet/fpm/entrypoint.sh
docker/phraseanet/setup/entrypoint.sh
docker/phraseanet/worker/entrypoint.sh

- Only the `setup` container play `chown`

PHRAS-3821 chown re-organisation between setup and fpm and worker

---

bin/maintenance
lib/Alchemy/Phrasea/Command/Maintenance/CleanWebhookLogsCommand.php

- PHRAS-3819: clean webhook log

PHRAS-3819 clean webhook log

---

bin/maintenance

- PHRAS-3819: unused dependance

PHRAS-3819 unused dependance

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/search/geoSearch/searchGeoForm.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3273 Prod - mapbox user pref - map_zoom generate an error when is memorise by mapboxgl and read by mapboxJS

PHRAS-3273 Prod - mapbox user pref - map_zoom generate an error when is memorise by mapboxgl and read by mapboxJS

---

lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php

- PHRAS-3823:  add separator in subject report mail

PHRAS-3823 add separator in subject report mail

---

docker/phraseanet/fpm/entrypoint.sh
docker/phraseanet/worker/entrypoint.sh

- PHRAS-3821 delete cache content after plugin instal

PHRAS-3821 delete cache content after plugin install

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3823 localization

---

lib/Alchemy/Phrasea/Controller/Admin/UserController.php
templates/web/admin/editusers.html.twig
templates/web/admin/users.html.twig

- PHRAS-3827: Admin- users list - keep selection and page when validate or back in users edit

PHRAS-3827 Admin- users list - keep selection and page when validate or back in users edit

---

lib/Alchemy/Phrasea/Report/ReportConnections.php
lib/Alchemy/Phrasea/Report/ReportCountAssets.php
lib/Alchemy/Phrasea/Report/ReportDownloads.php
lib/Alchemy/Phrasea/Report/ReportRecords.php
lib/Alchemy/Phrasea/Report/ReportUsers.php

- PHRAS-3823: fix date max include, add destinataire email column

PHRAS- 3823 fix date max include, add destinataire email column

---

bin/report
lib/Alchemy/Phrasea/Command/Report/DownloadsCommand.php
lib/Alchemy/Phrasea/Report/ReportDownloads.php

- PHRAS-3823: downloads report command

PHRAS-3823 downloads report command

---

lib/Alchemy/Phrasea/Helper/Prod.php
templates/web/prod/index.html.twig

- PHRAS-473: Prod - advance search - display field label and other improvements

PHRAS-473 Prod - advance search - display field label and other improvements

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/search/advSearch/searchAdvancedForm.js
Phraseanet-production-client/src/components/search/index.js
lib/Alchemy/Phrasea/Helper/Prod.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
templates/web/prod/index.html.twig

- PHRAS-473: add field operator

PHRAS-473 add field operator

---

templates/web/prod/results/help.html.twig

- PHRAS-473: fix reset button color

PHRAS-473 fix reset button color

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-473 : localisation
- PHRAS-3764 : addd missing string
- PHRAS-3825: Localisation

PHRAS-3416 strings for search operator

---

bin/report
lib/Alchemy/Phrasea/Command/Report/DataboxContentCommand.php
lib/Alchemy/Phrasea/Report/ReportRecords.php

- PHRAS-3823: report databox content

PHRAS-3823 report databox content

---

docker/phraseanet/setup/entrypoint.sh

- PHRAS-3821 setup container run chown ftp and backup repository

PHRAS-3821 chown ftp

---

lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php
lib/Alchemy/Phrasea/Command/Report/DataboxContentCommand.php
lib/Alchemy/Phrasea/Command/Report/DownloadsCommand.php
lib/Alchemy/Phrasea/Report/ReportDownloads.php
lib/Alchemy/Phrasea/Report/ReportRecords.php

- PHRAS-3823: add column permalink and option in report command
- add option in bin/report databox:content  and bin/report downloads:all

PHRAS-3823 add column permalink and option in report command

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php
lib/Alchemy/Phrasea/Controller/Report/RootController.php
lib/Alchemy/Phrasea/Report/Controller/ProdReportController.php
lib/Alchemy/Phrasea/Report/Report.php
lib/Alchemy/Phrasea/Report/ReportRecords.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
resources/www/report/js/report.js
templates/web/report/report_layout_child.html.twig

- PHRAS-3823: add permalink in report GUI

PHRAS-3823 : add permalink in report GUI

---

lib/Alchemy/Phrasea/Report/Controller/ProdReportController.php
lib/Alchemy/Phrasea/Report/ReportDownloads.php
templates/web/report/report_layout_child.html.twig

- PHRAS-3832: report download  gui permalink, coll name, add field column

PHRAS-3832 report download  some improvement

---

lib/Alchemy/Phrasea/Controller/Admin/RootController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/statusbit.html.twig
templates/web/admin/statusbit/edit.html.twig

- PHRAS-3836: admin - status bits name - fix character encoding

PHRAS-3836 admin - status bits name - fix character encoding

---

.github/workflows/build.yml
.github/workflows/ci.yml

PHRAS-3826: fix tag name

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/prod/WorkZone/ExposePublicationAssets.html.twig

- PHRAS-3841: Prod - expose-client - get embed for asset in a publication

PHRAS-3841: Prod - expose-client - get embed for asset in a publication

---

.github/workflows/build.yml
templates/web/prod/WorkZone/ExposePublicationAssets.html.twig

- PHRAS-3841: fix generate iframe

PHRAS-3841 fix generate iframe

---

docker/phraseanet/php.ini.sample

- PHRAS-3843 change php-cli and fpm exposition config value
- for security impovement change php-cli and fpm exposition config value

PHRAS-3843 change in php-cli and fpm exposition config value

---

CHANGELOG.md
README.md

- PHRAS-3838 Change log and readme update

PHRAS-3838 Change log and readme update

---

.env
lib/Alchemy/Phrasea/Core/Version.php

PHRAS-3838 release version 4.1.7

---

templates/web/admin/fields/templates.html.twig

- PHRAS-3846: Admin - database - field detail

PHRAS-3846-Admin - database - field detail

---

bin/console
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/ConfigurationException.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/GlobalConfiguration.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/Job.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/TranslateCommand.php
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/doc/configuration-sample.yml
lib/Alchemy/Phrasea/Command/Thesaurus/Translator/doc/translator.md
lib/classes/record/adapter.php

- PHRAS-3805: translate field value(s) using thesaurus.

PHRAS-3805_translator

---

docker/nginx/root/entrypoint.sh
docker/nginx/root/etc/nginx/nginx.conf
docker/phraseanet/php.ini.sample

- PHRAS-3859:  increase security with headers
- increase security using Content-Security-Policy

PHRAS-3859 increase security with headers

---

.env
lib/Alchemy/Phrasea/Core/Version.php

- Release of 4.1.8-rc2 version

PHRAS-3862 release 4.1.8-rc2

---

.env
lib/Alchemy/Phrasea/Core/Version.php

* PHRAS-3862 release 4.1.8-rc2

PHRAS-3862 release 4.1.8-rc2 (#4326)

---

.env

- PHRAS-3859: fix gateway fastcgi https default value
- allow to set https scheme headers

PHRAS-3859 fix gateway fastcgi https default value

---

bin/console
lib/Alchemy/Phrasea/Command/User/UserEditCommand.php
lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php

- PHRAS-3860: bin/console user:edit

PHRAS-3860 bin/console user:edit

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/facets/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3855: Prod - Facettes : color facet is now showing html tags in place of the color image

PHRAS-3855 Prod - Facettes : color html tags

---

lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
templates/web/prod/actions/Tools/index.html.twig

- PHRAS-3874: Prod - tools - subdefinition tab - use subdefintion label

PHRAS-3874 Prod - tools - subdefinition tab - use subdefintion label

---

.env
CHANGELOG.md
lib/Alchemy/Phrasea/Core/Version.php

PHRAS-3875_release_4.1.8-rc3

---

docker/nginx/root/etc/nginx/nginx.conf

- PHRAS-3877: Fix csp for geonames, mapbox , prod

PHRAS-3877 Fix csp for geonames, mapbox , prod 

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

Phras 3416 phraseanet localization

---

.env
CHANGELOG.md
lib/Alchemy/Phrasea/Core/Version.php

PHRAS_3883 release 4.1.8-rc4

---

lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/worker-manager/worker_queue_monitor.html.twig

- PHRAS-3882: admin - workers - filter "consumed queue"

PHRAS-3882 admin - workers - filter "consumed queue"

---

docker/nginx/root/etc/nginx/nginx.conf
templates/web/common/analytics.html.twig

- PHRAS-3887: google analytics 4

PHRAS-3887 google analytics 4

---

docker/nginx/root/etc/nginx/nginx.conf

- adding policies for : 
-  matomo tracking (cloud only) 
-  newrelic monitoring

PHRAS-3891 CSP policies for matomo cloud  and newrelic

---

lib/Alchemy/Phrasea/Controller/Prod/ExportController.php
lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php
lib/classes/record/exportElement.php
lib/classes/set/export.php

- PHRAS-3252: Prod - Export - The captions are not being sent when doing an export by email

PHRAS-3252 Prod - Export - The captions are not being sent when doing an export by email

---

.github/workflows/build.yml

- PHRAS-3826: add mask password argument

PHRAS-3826 add mask password argument

---

templates/mobile/common/matomo_analytics.html.twig

- PHRAS-3914: Lightbox - mobile fix matomo url

PHRAS-3914 Lightbox - mobile fix matomo url

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3909 : Prod - Expose cli - load more publications - add pagination

PHRAS-3416 phraseanet-localization

---

lib/Alchemy/Phrasea/Media/Subdef/Image.php

- PHRAS-3061: Admin - subview definition - missmatch error between value set in form and slider limit

PHRAS-3061 Admin - subview definition - missmatch error between value set in form and slider limit

---

lib/Alchemy/Phrasea/Command/Maintenance/CleanLogDocsCommand.php
lib/Alchemy/Phrasea/Command/Maintenance/CleanLogSearchCommand.php
lib/Alchemy/Phrasea/Command/Maintenance/CleanLogViewCommand.php

- PHRAS-3894:  bin/maintenance clean: - Removing BETA prefix and Memory leak

PHRAS-3894 : bin/maintenance clean: - Removing BETA prefix and Memory leak

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/index.js
lib/Alchemy/Phrasea/PhraseanetService/Controller/PSAdminController.php
lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
lib/Alchemy/Phrasea/PhraseanetService/Form/PSExposeConfigurationType.php
lib/Alchemy/Phrasea/PhraseanetService/Form/PSExposeConnectionType.php
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
lib/Alchemy/Phrasea/WorkerManager/Event/ExposeUploadEvent.php
lib/Alchemy/Phrasea/WorkerManager/Subscriber/ExposeSubscriber.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/PullAssetsWorker.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf
templates/web/admin/phraseanet-service/expose.html.twig
templates/web/prod/WorkZone/Macros.html.twig

- PHRAS-3921: prod - expose-cli - became compatible with Phrasea V3 keycloak and fix

PHRAS-3921 prod - expose-cli - became compatible with Phrasea V3 keycloak and fix

---

Dockerfile

- Set Redis version for saml-sp container in Dockerfile

PHRAS-3929  Compose Set redis version For SAML container

---

composer.json
composer.lock

- PHRAS-3930 matomo media tracking
- update embed-bundle

PHRAS-3930 matomo media tracking

---

composer.json
composer.lock

* update embed-bundle version to 2.0.15

PHRAS-3930 master in PHRAS-3930

---

lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
templates/web/admin/phraseanet-service/expose.html.twig

- PHRAS-3921: expose cli oauth token uri compatibility
- PHRAS-3936 publication set asset title with title see in prod GUI, the thumbnail title depend of  connexion language

PHRAS-3921 expose-cli oauth token uri compatibility v2 v3 and asset title set 

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/lazy-1.js
Phraseanet-production-client/dist/lazy-1.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/record/videoEditor/index.js
Phraseanet-production-client/src/components/videoEditor/rangeCapture.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3933: prod - 403 "invalide search token" - after "video tools" openning
- fix videotools load twice, remove undefined video poster url

PHRAS-3933 prod - 403 "invalide search token" - after "video tools" openning

---

lib/Alchemy/Phrasea/Controller/Api/InstanceIdAware.php
lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3ResultHelpers.php
lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchController.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
lib/Alchemy/Phrasea/Search/RecordTransformer.php
lib/Alchemy/Phrasea/Search/StoryTransformer.php

- PHRAS-3931: add "resource_id" to record / story api v1/v3 ; formula defined into InstanceIdAware.php

PHRAS-3931_phraseanet_local_id_in_api

---

lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
lib/classes/eventsmanager/notify/basketwip.php
lib/classes/eventsmanager/notify/subtitle.php
resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf
resources/locales/messages.nl.xlf
resources/locales/validators.de.xlf
resources/locales/validators.en.xlf
resources/locales/validators.fr.xlf
resources/locales/validators.nl.xlf

- PHRAS-3668: fix incomplete translation

PHRAS-3668 fix incomplete translation

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- string for PHRAS-3966 admin - users list - filter user with api

PHRAS-3966 admin users filter translation

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3997 translation for new field option (beta features

PHRAS-3997 translation field content restriction option

---

.env
Dockerfile
docker-compose.yml
docker/phraseanet/worker/entrypoint.sh

- PHRAS-3980 removing blackfire

PHRAS-3980 custom worker

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-3978 "include guest user"  - "shared by"

PHRAS-3978 phraseanet translation 

---

Phraseanet-production-client/config/config.js
Phraseanet-production-client/dist/authenticate.js
Phraseanet-production-client/dist/authenticate.min.js
Phraseanet-production-client/dist/commons.js
Phraseanet-production-client/dist/commons.min.js
Phraseanet-production-client/dist/production.js
Phraseanet-production-client/dist/production.min.js
Phraseanet-production-client/src/components/ui/workzone/facets/index.js
lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php

- PHRAS-3975: Prod - Facets - Facets' values are truncated at the 20th character-extend

PHRAS-3975 : Prod - Facets - Facets' values are truncated at the 20th character-extend

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-4018 object_inspector_translate

PHRAS-4018_object_inspector_translate

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-3416 translation for 4.1.8-rc10 

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRAS-4041 MatomoMediaMetrics translation for json keys

PHRAS-4041 MatomoMediaMetrics translation for json keys

---

resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- change some string for Mark Job as "cancel"

PHRAS-3416 local for worker jobs

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

Translation for publication search in expose-cli

PHRAS-4069 translation for publication search

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

PHRA-3416 Translation for 4.1.8

---

.env
CHANGELOG.md

Release of 4.1.9 version

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- Translation of create subdefinition screen

PHRAS-3416 create subdefinition localisation

---

docker-compose.datastores.yml

- Bump rabbitMQ version to 3.8.34

PHRAS-4094 Bump rabbitMQ version to 3.8.34

---

resources/locales/messages.de.xlf
resources/locales/messages.en.xlf
resources/locales/messages.fr.xlf

- PHRAS-4124 missing translation for prod::download: delete-marking-stamp

PHRAS-3416 Phraseanet Translation

---

.env
CHANGELOG.md
lib/Alchemy/Phrasea/Core/Version.php

PHRAS-4142 Release of 4.1.17

---

.dockerignore
README.md
doc/infra/compose/stack_management.md
docker-compose.altenatives.yml
docker-compose.datastores.yml
docker-compose.limits.yml
docker-compose.override.yml
docker-compose.tools.yml
docker-compose.under-phrasea.yml
docker-compose.yml
stack_management.sh

- adding stack_management.sh script

PHRAS-4149 adding stack_management.sh script

---

stack.sh

- PHRAS-4149: Add kernel version in stack.sh

PHRAS-4149 Add kernel version
